objects/Attendance__c.object
<CustomObject>
    <description>Object to be used to record Challengers&apos; attendance during each phase of the programme, and authorised/unauthorised absences.</description>
    <fields>
        <fullName>Cluster__c</fullName>
        <formula>Contact__r.Assigned_Wave__r.Wave_Cluster__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Cluster</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF(NOT(ISBLANK(Contact__r.Assigned_Wave__c)),

IF( ISBLANK(Contact__r.Assigned_Wave__r.MM_confirmed_PCKO_starters__c), &quot;Not Started&quot;,&quot;Assigned&quot;)

,

IF(ISBLANK(Contact__r.Wave_started__c), &quot;Not Started&quot;, &quot;Left the programme&quot;)

)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Wave_Selection__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Wave Selection</label>
        <referenceTo>Wave_Selection__c</referenceTo>
        <relationshipLabel>Attendance</relationshipLabel>
        <relationshipName>Attendance</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Wave__c</fullName>
        <formula>IF(ISBLANK(Contact__r.Wave_started__c),


IF(ISBLANK( Contact__r.Assigned_Wave__r.Name ), Contact__r.Reserved_Wave__r.Name ,Contact__r.Assigned_Wave__r.Name)

,Contact__r.Wave_started__c)</formula>
        <label>Wave</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Wave_lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Wave lookup</label>
        <referenceTo>Wave__c</referenceTo>
        <relationshipLabel>Attendance</relationshipLabel>
        <relationshipName>Attendance</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Wave_number__c</fullName>
        <description>Displaying the wave number for waves in following formats:

Bradfield A 5 (1 digit number)
Bradfield A 12 (2 digit number)
Bradfield B 13a (2 digit number plus letter)</description>
        <formula>IF( 
(LEFT(RIGHT( Wave__c ,2),1)=&quot; &quot;), 
RIGHT(Wave__c,1), 
IF( 
ISNUMBER(RIGHT(Wave__c,2)), 
RIGHT(Wave__c,2), 
LEFT(RIGHT(Wave__c,3),2) 
))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Wave number</label>
        <type>Text</type>
    </fields>
    <label>Attendance</label>
    <nameField>
        <displayFormat>AR-{00000}</displayFormat>
        <label>Attendance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Cluster__c.object
<CustomObject>
    <label>Cluster</label>
    <nameField>
        <label>Cluster Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clusters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Wave__c.object
<CustomObject>
    <fields>
        <fullName>MM_confirmed_PCKO_starters__c</fullName>
        <inlineHelpText>Marketing Manager enters the date when they confirm that the number Mktg Number of YPs started Wave (entered by SC/AMM) is correct</inlineHelpText>
        <label>ASM confirmed PCKO starters</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Mktg_Number_of_YPs_started_Wave__c</fullName>
        <description>The number of YPs that marketing have calculated have got on the bus at PCKO</description>
        <inlineHelpText>The number of YPs that marketing have calculated have got on the bus at PCKO</inlineHelpText>
        <label>Sales Number of YPs started Wave at PCKO</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Wave_Cluster__c</fullName>
        <label>Cluster</label>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Waves</relationshipLabel>
        <relationshipName>Waves</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Wave_code__c</fullName>
        <description>Unique wave code</description>
        <inlineHelpText>Unique wave code</inlineHelpText>
        <label>Wave code</label>
        <length>25</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Wave_number__c</fullName>
        <label>Wave number</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Wave</label>
    <nameField>
        <label>Wave Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Waves</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Test_WaveTrigger.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class Test_WaveTrigger {

    static testMethod void myUnitTest() {
        RecordType rc=[Select id,Name From RecordType Where sObjectType='Contact' and Name Like '%YP20%' Order By Name  limit 1 ];
        List<Contact> cntList=new List<Contact>();
        List<Wave__c> waveList=new List<Wave__c>();
        List<Wave_Selection__c> WaveSelList=new List<Wave_Selection__c>();
        Cluster__c cluster1 = new Cluster__c (Name = 'Bloomsbury Cluster');
        insert cluster1;
        
        for(integer i=1;i<6;i++){
            Contact cnt=new Contact();
            cnt.Email='test@test.com'+i;
            cnt.LastName='cnt'+i;
            cntList.add(cnt);
            Wave__c wv=new Wave__c();
           
            wv.Name='Wave'+i;
            wv.Wave_number__c=String.valueOf(i);
            wv.Wave_code__c='Wave'+i;
            wv.Wave_Cluster__c=cluster1.ID;
            wv.MM_confirmed_PCKO_starters__c=System.today();
            waveList.add(wv);
        }
       
        insert cntList;
        insert waveList; 
        
        for(Contact c: cntList){
            for(Wave__c wave: waveList){
                Wave_Selection__c ws= new Wave_Selection__c();
                ws.Wave__c=wave.Id;
                ws.Young_Person__c=c.Id;
            
                if(wave.Name.contains('1')){
                    ws.Status__c='Waiting List';
                }
                //all contacts are assigned to Wave 2
                else if(wave.Name.contains('2')){
                    ws.Status__c='Assigned';
                }
                else{
                    ws.Status__c='Was reserved - now on waiting list';
                }
                WaveSellist.add(ws);
            }
        }
        System.debug('#####WaveSellist######'+WaveSellist);
        //insert WaveSellist;
        
        //Update Wave2
        waveList[1].MM_confirmed_PCKO_starters__c=System.Today();
        Update waveList[1];
        
     
       for(Wave_Selection__c ws: [Select Wave__r.Wave_Number__c,Status__c From Wave_Selection__c Where id in: WaveSellist Order By Name Asc]) {
            if(ws.Wave__r.Wave_Number__c < '2'){
                System.assertnotEquals(ws.Status__c,'Was on waiting list, now ineligible as has started another wave');
            }
            if(ws.Wave__r.Wave_Number__c > '2'){
                System.assertEquals(ws.Status__c,'Was on waiting list, now ineligible as has started another wave');
            }
        }
        
       
        for(Wave__c wave: WaveList){
            wave.MM_confirmed_PCKO_starters__c=System.today();
        }
        update waveList;
        
        for(Wave_Selection__c ws : [Select Wave__r.Mktg_Number_of_YPs_started_Wave__c,(Select id From Attendance__r) From Wave_Selection__c Where Wave__c in: waveList and Status__c='Assigned']){
            System.assert(ws.Attendance__r.Size()>0);
        }
        
        Map<Id,Wave__c> WaveMap = new Map<Id,Wave__c>();
        WaveMap.put(waveList[0].id,waveList[0]);
        List<Wave__c> WaveList2 = new List<Wave__c>();
        WaveList2.add(waveList[0]);
        WaveTriggerHandler wvtriger = new WaveTriggerHandler();
        wvtriger.onAfterUpdate(WaveMap,WaveMAp);
        wvtriger.Wave_AutoUpdateWaveSelectionStatus(WaveList2);
        wvtriger.Wave_CreateAttendanceRecordToWaveSelections(WaveList2);
    }
}