objects/Attendance__c.object
<CustomObject>
    <description>Object to be used to record Challengers&apos; attendance during each phase of the programme, and authorised/unauthorised absences.</description>
    <fields>
        <fullName>Cluster__c</fullName>
        <formula>Contact__r.Assigned_Wave__r.Wave_Cluster__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Cluster</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Attendance</relationshipLabel>
        <relationshipName>Attendance</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Hours_to_make_up_due_to_absences1__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Calculates the number of hours to be made up due to authorised absences.
Will show &quot;0&quot; if the YP has had too many authorised absences to graduate</inlineHelpText>
        <label>Hours to make up due to auth. absences</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RCA_1__c</fullName>
        <label>RCA 1</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Attended</fullName>
                </value>
                <value>
                    <fullName>Late - 1.5 to 3 hours</fullName>
                </value>
                <value>
                    <fullName>Late - more than 3 hours</fullName>
                </value>
                <value>
                    <fullName>Absence authorised</fullName>
                </value>
                <value>
                    <fullName>Absence unauthorised</fullName>
                </value>
                <value>
                    <fullName>Absent all day</fullName>
                </value>
                <value>
                    <fullName>Half day</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RCD_1__c</fullName>
        <label>RCD 1</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Attended</fullName>
                </value>
                <value>
                    <fullName>Late - 1.5 to 3 hours</fullName>
                </value>
                <value>
                    <fullName>Late - more than 3 hours</fullName>
                </value>
                <value>
                    <fullName>Absence authorised</fullName>
                </value>
                <value>
                    <fullName>Absence unauthorised</fullName>
                </value>
                <value>
                    <fullName>Absent all day</fullName>
                </value>
                <value>
                    <fullName>Half day</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <formula>IF(NOT(ISBLANK(Contact__r.Assigned_Wave__c)),

IF( ISBLANK(Contact__r.Assigned_Wave__r.MM_confirmed_PCKO_starters__c), &quot;Not Started&quot;,&quot;Assigned&quot;)

,

IF(ISBLANK(Contact__r.Wave_started__c), &quot;Not Started&quot;, &quot;Left the programme&quot;)

)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_hours_to_make_up_for_grad_C_O__c</fullName>
        <inlineHelpText>Total hours required by the Cabinet Office for YP graduation.
Made up of total number of hours due to authorised and unauthorised absences</inlineHelpText>
        <label>Total hours to make up for grad (C.O)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_hours_to_make_up_for_grad_TCN__c</fullName>
        <inlineHelpText>Total hours required by TCN for YP graduation.
Made up of total number of hours due to authorised, unauthorised absences and latenesses of over 1.5 hours</inlineHelpText>
        <label>Total hours to make up for grad (TCN)</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Wave_Selection__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Wave Selection</label>
        <referenceTo>Wave_Selection__c</referenceTo>
        <relationshipLabel>Attendance</relationshipLabel>
        <relationshipName>Attendance</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Wave__c</fullName>
        <formula>IF(ISBLANK(Contact__r.Wave_started__c),


IF(ISBLANK( Contact__r.Assigned_Wave__r.Name ), Contact__r.Reserved_Wave__r.Name ,Contact__r.Assigned_Wave__r.Name)

,Contact__r.Wave_started__c)</formula>
        <label>Wave</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Wave_number__c</fullName>
        <description>Displaying the wave number for waves in following formats:

Bradfield A 5 (1 digit number)
Bradfield A 12 (2 digit number)
Bradfield B 13a (2 digit number plus letter)</description>
        <formula>IF( 
(LEFT(RIGHT( Wave__c ,2),1)=&quot; &quot;), 
RIGHT(Wave__c,1), 
IF( 
ISNUMBER(RIGHT(Wave__c,2)), 
RIGHT(Wave__c,2), 
LEFT(RIGHT(Wave__c,3),2) 
))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Wave number</label>
        <type>Text</type>
    </fields>
    <label>Attendance</label>
    <nameField>
        <displayFormat>AR-{00000}</displayFormat>
        <label>Attendance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Cluster__c.object
<CustomObject>
    <label>Cluster</label>
    <nameField>
        <label>Cluster Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clusters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Incident__c.object
<CustomObject>
    <description>Object to be used to record health and behavioural issues, damage to property/equipment and details of those who quit the programme.</description>
    <fields>
        <fullName>Attendance__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Attendance</label>
        <referenceTo>Attendance__c</referenceTo>
        <relationshipLabel>Incidents</relationshipLabel>
        <relationshipName>Incidents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Cluster__c</fullName>
        <formula>Wave__r.Wave_Cluster__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Cluster</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Use the spyglass to look up the name of the young person.</inlineHelpText>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>YP2014, Summer staff, Young Person</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Incidents</relationshipLabel>
        <relationshipName>Incidents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Day_that_card_was_given__c</fullName>
        <inlineHelpText>For &apos;started but left&apos; YPs, this is the date that they quit the programme. If this is different from the day they actually went home, enter this information in the fields below.</inlineHelpText>
        <label>Day that action was taken/YP left</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PC 1</fullName>
                </value>
                <value>
                    <fullName>PC 2</fullName>
                </value>
                <value>
                    <fullName>PC 3</fullName>
                </value>
                <value>
                    <fullName>PC 4</fullName>
                </value>
                <value>
                    <fullName>PC 5</fullName>
                </value>
                <value>
                    <fullName>PC 6</fullName>
                </value>
                <value>
                    <fullName>TC 1</fullName>
                </value>
                <value>
                    <fullName>TC 2</fullName>
                </value>
                <value>
                    <fullName>TC 3</fullName>
                </value>
                <value>
                    <fullName>TC 4</fullName>
                </value>
                <value>
                    <fullName>TC 5</fullName>
                </value>
                <value>
                    <fullName>RCD 1</fullName>
                </value>
                <value>
                    <fullName>RCD 2</fullName>
                </value>
                <value>
                    <fullName>RCD 3</fullName>
                </value>
                <value>
                    <fullName>RCD 4</fullName>
                </value>
                <value>
                    <fullName>RCA 1</fullName>
                </value>
                <value>
                    <fullName>RCA 2</fullName>
                </value>
                <value>
                    <fullName>RCA 3</fullName>
                </value>
                <value>
                    <fullName>RCA 4</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Red_card_awarded__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Red card awarded</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Wave__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Wave</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Wave__c.RecordType.Name</field>
                <operation>equals</operation>
                <value>2016</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Wave__c</referenceTo>
        <relationshipLabel>Incidents</relationshipLabel>
        <relationshipName>Incidents</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Incident</label>
    <nameField>
        <displayFormat>I-{00000}</displayFormat>
        <label>Incident Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Incidents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Wave__c.object
<CustomObject>
    <fields>
        <fullName>Mktg_Number_of_YPs_started_Wave__c</fullName>
        <description>The number of YPs that marketing have calculated have got on the bus at PCKO</description>
        <inlineHelpText>The number of YPs that marketing have calculated have got on the bus at PCKO</inlineHelpText>
        <label>Sales Number of YPs started Wave at PCKO</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Wave_Cluster__c</fullName>
        <label>Cluster</label>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Waves</relationshipLabel>
        <relationshipName>Waves</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Wave_code__c</fullName>
        <description>Unique wave code</description>
        <inlineHelpText>Unique wave code</inlineHelpText>
        <label>Wave code</label>
        <length>25</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Wave_number__c</fullName>
        <label>Wave number</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Wave</label>
    <nameField>
        <label>Wave Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Waves</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Test_AttendanceTriggerHandler.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
public class Test_AttendanceTriggerHandler{
    static testMethod void myUnitTest() {
       	RecordType rc=[Select id,Name From RecordType Where sObjectType='Contact' and Name Like '%YP20%' Order By Name  limit 1 ];
        List<Wave__c> waveList=new List<Wave__c>();
        List<Wave_Selection__c> WaveSelList=new List<Wave_Selection__c>();
        Cluster__c cluster1 = new Cluster__c (Name = 'Bloomsbury Cluster');
        insert cluster1;
        
        Wave__c wv=new Wave__c();
        wv.Name='Wave Test';
        wv.Wave_number__c='1';
        wv.Wave_code__c='Wa45';
        wv.Wave_Cluster__c=cluster1.ID;
        wv.Mktg_Number_of_YPs_started_Wave__c=1;
        insert wv;
 
        Contact cnt=new Contact();
        cnt.Email='test@test.com';
        cnt.LastName='cnt';
        
        insert cnt;
       
        
      
        Wave_Selection__c ws= new Wave_Selection__c();
        ws.Wave__c=wv.Id;
        ws.Young_Person__c=cnt.Id;  
        ws.Status__c='Assigned';
        //insert ws;
        
        Wave_Selection__c ws2= new Wave_Selection__c();
        ws2.Wave__c=wv.Id;
        ws2.Young_Person__c=cnt.Id;  
        ws2.Status__c='Assigned';
        //insert ws2;
        
        Attendance__c att=new Attendance__c();
        att.Wave_Selection__c=ws.ID;
        att.Contact__c = cnt.id;
        insert att;
         System.debug('/////////////////////////////'+att);
         
        List<Incident__c> IncidentList=new List<Incident__c>();
        for(integer i=0;i<5;i++){
            Incident__c inc=new Incident__c();
            inc.Day_that_card_was_given__c='PC 1';
            inc.Attendance__c=att.Id;
            inc.Red_card_awarded__c=true;  
            inc.Wave__c= wv.Id;
            IncidentList.add(inc);
        }
        for(integer i=0;i<5;i++){
            Incident__c inc=new Incident__c();
            inc.Attendance__c=att.Id;
            inc.Wave__c= wv.Id;
            IncidentList.add(inc);
        }
        insert IncidentList;
        
        for(integer i=0;i<10;i++){
            if(IncidentList[i].Red_card_awarded__c!=true){
                IncidentList[i].Red_card_awarded__c=true;
                IncidentList[i].Day_that_card_was_given__c='PC 1';
            }   
        }
        update IncidentList;
        
       
        att.Hours_to_make_up_due_to_absences1__c=2;
        att.Wave_Selection__c=ws2.Id;
        update att;
        
        Attendance__c att2=att;
        att2.Id=null;
        att2.Total_hours_to_make_up_for_grad_C_O__c=0;
        att2.Total_hours_to_make_up_for_grad_TCN__c=0;
        insert att2;
        
        att.Hours_to_make_up_due_to_absences1__c=3;
        att.Total_hours_to_make_up_for_grad_TCN__c=1;
        att.RCA_1__c='Attended';
        att.RCD_1__c='Attended';
        update att;
        
        List<Attendance__c> AttList = new List<Attendance__c>();
        AttList.add(att);
        AttList.add(att2);
        Map<Id,Attendance__c> AttMap = new Map<Id,Attendance__c>();
        AttMap.put(att.id,att);
        AttMap.put(att2.id,att2);
        Set<Attendance__c> attSet = new Set<Attendance__c>();
        AttSet.add(att);
        AttSet.add(att2);
        //delete IncidentList;
        //delete att;
        //undelete att;
        
       AttendanceTriggerHandler attclass = new AttendanceTriggerHandler();
       attclass.onAfterInsert(AttList);
       attclass.onAfterUpdate(AttMap,AttMap);
       attclass.onAfterDelete(AttList);
       attclass.onAfterUndelete(AttList);
       attclass.calculateTotalHoursToMakeUpForGradCo(AttSet);
       attclass.calculateTotalHoursToMakeUpForGradTCN(AttSet);
       
    }

}