objects/Attendance__c.object
<CustomObject>
    <description>Object to be used to record Challengers&apos; attendance during each phase of the programme, and authorised/unauthorised absences.</description>
    <fields>
        <fullName>Max_Day_that_card_was_given_YP_left__c</fullName>
        <label>Day that the card was given/YP left</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Attendance</label>
    <nameField>
        <displayFormat>AR-{00000}</displayFormat>
        <label>Attendance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Incident__c.object
<CustomObject>
    <description>Object to be used to record health and behavioural issues, damage to property/equipment and details of those who quit the programme.</description>
    <fields>
        <fullName>Attendance__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Attendance</label>
        <referenceTo>Attendance__c</referenceTo>
        <relationshipLabel>Incidents</relationshipLabel>
        <relationshipName>Incidents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_left_the_programme__c</fullName>
        <inlineHelpText>This is the date that the YP left the programme.</inlineHelpText>
        <label>Date left the programme</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Day_as_a_number__c</fullName>
        <description>If a red card has been awarded, this field converts the day selected within the field &apos;Day that card was given/YP left&apos; into a number (ie PC1 = 1, PC2 = 2, ... , RCA4 = 19).</description>
        <formula>IF ( OR (Red_card_awarded__c = TRUE,  ISNULL( Date_left_the_programme__c ) = FALSE ), IF (  ISPICKVAL ( Day_that_card_was_given__c , &quot;PC 1&quot;), 1, IF (  ISPICKVAL (  Day_that_card_was_given__c , &quot;PC 2&quot;), 2, IF (  ISPICKVAL ( Day_that_card_was_given__c , &quot;PC 3&quot;), 3, IF (  ISPICKVAL ( Day_that_card_was_given__c , &quot;PC 4&quot;), 4, IF (  ISPICKVAL ( Day_that_card_was_given__c , &quot;PC 5&quot;), 5, IF (  ISPICKVAL ( Day_that_card_was_given__c , &quot;PC 6&quot;), 6, IF (  ISPICKVAL ( Day_that_card_was_given__c , &quot;TC 1&quot;), 6, IF (  ISPICKVAL ( Day_that_card_was_given__c , &quot;TC 2&quot;), 7, IF (  ISPICKVAL ( Day_that_card_was_given__c , &quot;TC 3&quot;), 8, IF (  ISPICKVAL ( Day_that_card_was_given__c , &quot;TC 4&quot;), 9, IF (  ISPICKVAL ( Day_that_card_was_given__c , &quot;TC 5&quot;), 10, IF (  ISPICKVAL ( Day_that_card_was_given__c , &quot;RCD 1&quot;), 11, IF (  ISPICKVAL ( Day_that_card_was_given__c , &quot;RCD 2&quot;), 12, IF (  ISPICKVAL ( Day_that_card_was_given__c , &quot;RCD 3&quot;), 13, IF (  ISPICKVAL ( Day_that_card_was_given__c , &quot;RCD 4&quot;), 14, IF (  ISPICKVAL ( Day_that_card_was_given__c , &quot;RCA 1&quot;), 15, IF (  ISPICKVAL ( Day_that_card_was_given__c , &quot;RCA 2&quot;), 16, IF (  ISPICKVAL ( Day_that_card_was_given__c , &quot;RCA 3&quot;), 17, IF (  ISPICKVAL ( Day_that_card_was_given__c , &quot;RCA 4&quot;), 18,0))))))))))))))))))), 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Day as a number</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Day_that_card_was_given__c</fullName>
        <inlineHelpText>For &apos;started but left&apos; YPs, this is the date that they quit the programme. If this is different from the day they actually went home, enter this information in the fields below.</inlineHelpText>
        <label>Day that action was taken/YP left</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>PC 1</fullName>
                </value>
                <value>
                    <fullName>PC 2</fullName>
                </value>
                <value>
                    <fullName>PC 3</fullName>
                </value>
                <value>
                    <fullName>PC 4</fullName>
                </value>
                <value>
                    <fullName>PC 5</fullName>
                </value>
                <value>
                    <fullName>PC 6</fullName>
                </value>
                <value>
                    <fullName>TC 1</fullName>
                </value>
                <value>
                    <fullName>TC 2</fullName>
                </value>
                <value>
                    <fullName>TC 3</fullName>
                </value>
                <value>
                    <fullName>TC 4</fullName>
                </value>
                <value>
                    <fullName>TC 5</fullName>
                </value>
                <value>
                    <fullName>RCD 1</fullName>
                </value>
                <value>
                    <fullName>RCD 2</fullName>
                </value>
                <value>
                    <fullName>RCD 3</fullName>
                </value>
                <value>
                    <fullName>RCD 4</fullName>
                </value>
                <value>
                    <fullName>RCA 1</fullName>
                </value>
                <value>
                    <fullName>RCA 2</fullName>
                </value>
                <value>
                    <fullName>RCA 3</fullName>
                </value>
                <value>
                    <fullName>RCA 4</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Red_card_awarded__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Red card awarded</label>
        <type>Checkbox</type>
    </fields>
    <label>Incident</label>
    <nameField>
        <displayFormat>I-{00000}</displayFormat>
        <label>Incident Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Incidents</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/IncidentTriggerHandler.cls
/***********************Description*******************************

	
	Incident Trigger Handler- Handler Class of IncidentTrigger
	CreatedBy: Ozlem Sabırlı 06/13/2013

**********************************************************************/
public with sharing class IncidentTriggerHandler {
	List<Id> AttIdList=new List<Id>();
	public void onAfterInsert(List<Incident__c> newList){
		for(Incident__c inc: newList){
			AttIdList.add(inc.Attendance__c);
		}
		if(AttIdList.Size()>0){
			CalculateMaxDayAsANumber(AttIdList);
		}
	}
	public void onAfterUpdate(Map<Id,Incident__c> oldMap,Map<Id,Incident__c> newMap){
		
		for(Incident__c inc: newMap.Values()){
			Incident__c newInc=newMap.get(inc.Id);
			Incident__c oldInc=oldMap.get(inc.Id);
		    if(newInc.Day_that_card_was_given__c != oldInc.Day_that_card_was_given__c || newInc.Date_left_the_programme__c != oldInc.Date_left_the_programme__c || newInc.Red_card_awarded__c != oldInc.Red_card_awarded__c || newInc.Attendance__c != oldInc.Attendance__c){
				AttIdList.add(newInc.Attendance__c);
			}
		}
		if(AttIdList.Size()>0){
			CalculateMaxDayAsANumber(AttIdList);
		}
	}
    public void onAfterDelete(List<Incident__c> oldList){
    	for(Incident__c oldInc: oldList){
    		AttIdList.add(oldInc.Attendance__c);
    	} 
    	if(AttIdList.Size()>0){
			CalculateMaxDayAsANumber(AttIdList);
		}
    }
     public void onAfterUndelete(List<Incident__c> newList){
    	for(Incident__c newInc: newList){
    		AttIdList.add(newInc.Attendance__c);
    	}
    	if(AttIdList.Size()>0){
			CalculateMaxDayAsANumber(AttIdList);
		}
    }
    public void CalculateMaxDayAsANumber(List<Id> AttIdList){
    	List<Attendance__c> AttLsist2Upd=new List<Attendance__c>();
    	for(Attendance__c att :[Select Id,Max_Day_that_card_was_given_YP_left__c,(Select Day_as_a_number__c From Incidents__r Order By Day_as_a_number__c  DESC limit 1) From Attendance__c a where a.Id in: AttIdList ]){
    		if(att.Incidents__r.Size()>0){
    			if(att.Max_Day_that_card_was_given_YP_left__c!=att.Incidents__r[0].Day_as_a_number__c){
		    		att.Max_Day_that_card_was_given_YP_left__c=att.Incidents__r[0].Day_as_a_number__c;
		    		AttLsist2Upd.add(att);
    			}
    		}
    	}
    	update AttLsist2Upd;
    }
}