objects/Attendance__c.object
<CustomObject>
    <description>Object to be used to record Challengers&apos; attendance during each phase of the programme, and authorised/unauthorised absences.</description>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Attendance</relationshipLabel>
        <relationshipName>Attendance</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Attendance</label>
    <nameField>
        <displayFormat>AR-{00000}</displayFormat>
        <label>Attendance Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attendance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Metric__c.object
<CustomObject>
    <description>Keeps the Contact and some detailed metrics</description>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Metrics</relationshipLabel>
        <relationshipName>Metrics</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Metric</label>
    <nameField>
        <displayFormat>M-{0000}</displayFormat>
        <label>Metric Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Metrics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TCSMetricAttendanceCreatorTriggerHandler.cls
public with sharing class TCSMetricAttendanceCreatorTriggerHandler {

	List<Metric__c> metrics = new List<Metric__c>(); 
	List<Attendance__c> attendances = new List<Attendance__c>(); 

	public void OnAfterUpdate(List<Contact> contacts){
	
		for(Contact con:contacts){
				
				if(con.Wave_started__c!=null && con.Metrics__r.size()==0){
					Metric__c metric = new Metric__c();
					metric.Contact__c = con.Id;
					metrics.add(metric);
				}
		}
		if(metrics.size()!=0){
			insert metrics;
		}
		
	}
	/*
	public void OnAfterInsert(List<Contact> contacts){
			
		for(Contact con:contacts){		
				Attendance__c attendance = new Attendance__c();
				attendance.Contact__c = con.Id;
				attendances.add(attendance);			
		}
		insert attendances;
		
	}
    */
	static testmethod void TCSMetricAttendanceCreatorTriggerHandler(){
			
	Account account = new Account(Name='testaccount');
    	
    	insert account;
    	            
        Contact con = new Contact(FirstName='testname',LastName='lasttest',AccountId=account.Id,Wave_started__c='test');
            
        insert con;
        
	}


}