objects/Booking__c.object
<CustomObject>
    <fields>
        <fullName>Booking_Timings__c</fullName>
        <description>Field pulled onto the Contract form</description>
        <inlineHelpText>Enter the timings of your booking/visit here e.g.4pm-6pm.  This will go onto the contract sheet.</inlineHelpText>
        <label>Timings of booking</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Booking_details__c</fullName>
        <description>Field pulled onto the Contract form</description>
        <inlineHelpText>Enter the details of your booking/visit here.  This will go onto the contract sheet.</inlineHelpText>
        <label>Booking details</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Cost__c</fullName>
        <label>Cost</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Cost_including_VAT__c</fullName>
        <label>Cost including VAT</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Details_of_weekend_1_booking__c</fullName>
        <inlineHelpText>Include which rooms and the timings</inlineHelpText>
        <label>Details of weekend 1 booking</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Details_of_weekend_2_booking__c</fullName>
        <inlineHelpText>Include which rooms and the timings</inlineHelpText>
        <label>Details of weekend 2 booking</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Details_of_weekend_3_booking__c</fullName>
        <inlineHelpText>Include which rooms and the timings</inlineHelpText>
        <label>Details of weekend 3 booking</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Details_of_weekend_4_booking__c</fullName>
        <description>Include which rooms and the timings</description>
        <label>Details of weekend 4 booking</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location_to_meet__c</fullName>
        <inlineHelpText>This should be a clear description of where Summer Staff go on the day.  If it&apos;s a new address then enter the address, if it&apos;s at the main address then enter &quot;Main address&quot;.  This information is not used for Young People</inlineHelpText>
        <label>Meeting point on the day</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Partner Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Bookings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Partner_or_Venue__c</fullName>
        <label>Usage</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>(1 AND 4) OR (3 AND 4) OR 2</booleanFilter>
            <filterItems>
                <field>$Source.Usage_TypeLOOK__c</field>
                <operation>equals</operation>
                <valueField>Partner_or_Venue__c.Usage_Type__c</valueField>
            </filterItems>
            <filterItems>
                <field>Partner_or_Venue__c.CreatedDate</field>
                <operation>lessThan</operation>
                <value>1/1/2014 12:00 AM</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Res Acc</value>
            </filterItems>
            <filterItems>
                <field>Partner_or_Venue__c.CreatedDate</field>
                <operation>greaterOrEqual</operation>
                <value>1/1/2014 12:00 AM</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Partner_or_Venue__c</referenceTo>
        <relationshipLabel>Bookings</relationshipLabel>
        <relationshipName>Bookings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Usage_Type__c</fullName>
        <formula>Partner_or_Venue__r.Usage_Type__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Usage Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Wave_Dates__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Wave Dates</label>
        <referenceTo>Wave_Dates__c</referenceTo>
        <relationshipName>Bookings</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Booking</label>
    <nameField>
        <label>Booking Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Partner_or_Venue__c.object
<CustomObject>
    <description>Type of services provided.
Junction, with lookups to Account, Cluster, Wave and Team</description>
    <fields>
        <fullName>Address_line_1__c</fullName>
        <formula>Account__r.Address_line_1__c</formula>
        <label>Address line 1</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_line_2__c</fullName>
        <formula>Account__r.Address_line_2__c</formula>
        <label>Address line 2</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Address_line_3__c</fullName>
        <formula>Account__r.Address_line_3__c</formula>
        <label>Address line 3</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <formula>Account__r.City__c</formula>
        <label>City</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postcode__c</fullName>
        <formula>Account__r.Postcode__c</formula>
        <label>Postcode</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cluster - Coach company</fullName>
                </value>
                <value>
                    <fullName>Cluster - Minibus company</fullName>
                </value>
                <value>
                    <fullName>Cluster - Residential accommodation</fullName>
                </value>
                <value>
                    <fullName>Cluster - Alternative residential accommodation</fullName>
                </value>
                <value>
                    <fullName>Cluster - Presentation day partner</fullName>
                </value>
                <value>
                    <fullName>Cluster - RCD Friday revue venue</fullName>
                </value>
                <value>
                    <fullName>Cluster - RCA meeting point 1 (Sat)</fullName>
                </value>
                <value>
                    <fullName>Cluster - RCA meeting point 1 (Sun)</fullName>
                </value>
                <value>
                    <fullName>Cluster - RCA meeting point 2 (Sat)</fullName>
                </value>
                <value>
                    <fullName>Cluster - RCA meeting point 2 (Sun)</fullName>
                </value>
                <value>
                    <fullName>Cluster - RCA meeting point 3 (Sat)</fullName>
                </value>
                <value>
                    <fullName>Cluster - RCA meeting point 3 (Sun)</fullName>
                </value>
                <value>
                    <fullName>Cluster - RCA meeting point 4 (Sat)</fullName>
                </value>
                <value>
                    <fullName>Cluster - RCA meeting point 4 (Sun)</fullName>
                </value>
                <value>
                    <fullName>Cluster - Graduation venue</fullName>
                </value>
                <value>
                    <fullName>Waves - PC KO venue</fullName>
                </value>
                <value>
                    <fullName>Waves - PC partner</fullName>
                </value>
                <value>
                    <fullName>Waves - PC Drop off venue</fullName>
                </value>
                <value>
                    <fullName>Waves - TC KO venue</fullName>
                </value>
                <value>
                    <fullName>Waves - Presentation day venue</fullName>
                </value>
                <value>
                    <fullName>Waves - TC venue</fullName>
                </value>
                <value>
                    <fullName>Waves - Showcase venue</fullName>
                </value>
                <value>
                    <fullName>Waves - RCD venue</fullName>
                </value>
                <value>
                    <fullName>Waves - Big Challenge partner</fullName>
                </value>
                <value>
                    <fullName>Team - Sports Venue</fullName>
                </value>
                <value>
                    <fullName>Team - TC partner name</fullName>
                </value>
                <value>
                    <fullName>Team - TC partner name 2</fullName>
                </value>
                <value>
                    <fullName>Team - RC CP</fullName>
                </value>
                <value>
                    <fullName>Team - Professional visit partner</fullName>
                </value>
                <value>
                    <fullName>Team - RCA partner challenge</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Usage_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Usage Type</label>
        <referenceTo>Usage_Type__c</referenceTo>
        <relationshipLabel>Usages</relationshipLabel>
        <relationshipName>Usages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>What_are_the_other_key_things_staff_need__c</fullName>
        <inlineHelpText>NB This Field appears on the contract sheet.

What are the other key things staff need to do to set up the venue? Is there anything key they should bring, e.g. CRBs?</inlineHelpText>
        <label>What are the other key things staff need</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <label>Usage</label>
    <nameField>
        <label>Usage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Usages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Role__c.object
<CustomObject>
    <description>Used in Staffing System.
Central holding place for seasonal staff role information.</description>
    <label>Role</label>
    <nameField>
        <label>Role Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Roles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Usage_Type__c.object
<CustomObject>
    <fields>
        <fullName>Plan__c</fullName>
        <label>Plan</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <label>Usage Type</label>
    <nameField>
        <label>Usage Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Usage Types</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Wave_Dates__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Usage_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Usage Type</label>
        <referenceTo>Usage_Type__c</referenceTo>
        <relationshipName>Wave_Dates</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Wave Components</label>
    <nameField>
        <displayFormat>Date-{0000}</displayFormat>
        <label>Wave Dates Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wave Components</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/ContractForm.cls
public with sharing class ContractForm {
    
        public Account account{get; set;}
        public List<Booking__c> usages{get; set;}
       // public boolean emptyUsage{get;set;}
        private String accountId;
        
        public ContractForm(ApexPages.StandardController stdController)
        {     
        	 // emptyUsage=false;
                usages=new List<Booking__c>();
                String[] usageNames=new String[]{};
                accountId=ApexPages.currentPage().getParameters().get('id');
                
                account=new Account();
            
            /*****find current year's Usage record type*/
            //Fiscal Year 2012 year runs 1 Nov 2012 - 31 Oct 2013
            //m/d/y
            	String currentYear = string.valueOf(system.now().year());
            	String fiscalYear = '';
            	if(system.today() < date.parse('1/11/'+currentYear)){
            		fiscalYear = string.valueOf(system.now().year());
            	}
            	else if ( system.today() == date.parse('1/11/'+currentYear) ||
            			(system.today() > date.parse('1/11/'+currentYear) && 
            			 system.today() <= date.parse('31/12/'+currentYear)) ){
        			 fiscalYear = string.valueOf(system.now().year()+1);	
    			 }
    			 /*else{
    			 	fiscalYear = string.valueOf(system.now().year());
    			 }*/
            	String tempQuery = 'SELECT id,Name FROM RecordType WHERE sObjectType=\'Partner_or_Venue__c\' AND Name LIKE \'%'+fiscalYear+'\'';
            	List<RecordType> ListCurrentYearRTs = Database.query(tempQuery);
            /*******************************/
                
                //get all Usages that related to the current Account record
                 account=[SELECT Name,
                /* Address_line_1__c,
                 Address_line_2__c,
                 Address_line_3__c,
                 City__c,
                 County_or_region__c,
                 Postcode__c,
	                BillingState, 
	                BillingCountry, 
	                BillingCity, 
	                BillingStreet, 
	                BillingPostalCode, 
	                Owner.Name, 
	                Owner.Phone, 
	                Owner.Country, 
	                Owner.City,
	                Owner.State,
	                Owner.Street,
	                Owner.PostalCode,
	                Owner.Email, 
	                Owner.UserRole.Name,
	                Owner.CompanyName,  
	                Main_Contact__r.Name, 
	                Main_Contact__r.Role__c, 
	                Main_Contact__r.Email, 
	                Main_Contact__r.MobilePhone,
	                Main_Contact__r.npe01__WorkPhone__c,*/
                    (SELECT Name,Id from Junctions__r where RecordTypeId IN :ListCurrentYearRTs) 
                    FROM Account WHERE id=:accountId];
                
                List<Partner_or_Venue__c> usagesByAccount=account.Junctions__r;
                        
                for(Partner_or_Venue__c p:usagesByAccount)
                {
                	usageNames.add(p.Id);
                }
                usages=[SELECT Partner_or_Venue__r.Name,
                        Wave_Dates__r.Start_Date__c,
                        Wave_Dates__r.End_Date__c,
                        //Location_to_meet__c, 
                        Booking_Timings__c,
                        Booking_details__c,
                        Details_of_weekend_1_booking__c,
                        Details_of_weekend_2_booking__c,
                        Details_of_weekend_3_booking__c,
                        Details_of_weekend_4_booking__c,
                        Cost__c,
                        Cost_including_VAT__c
                       // Partner_or_Venue__r.Usage_Type__r.Plan__c,
                        //Partner_or_Venue__r.What_are_the_other_key_things_staff_need__c,
                        //Partner_Contact__r.Name, 
                       // Partner_Contact__r.MobilePhone
                        FROM Booking__c WHERE Partner_or_Venue__c IN :usageNames ORDER BY Partner_or_Venue__r.Name];
                        
                      /*  if(usages.isEmpty())
                        emptyUsage=true;
                        emptyUsage=false;
                      */  
        } 
        
}