objects/Booking__c.object
<CustomObject>
    <fields>
        <fullName>Partner_or_Venue__c</fullName>
        <label>Usage</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>(1 AND 4) OR (3 AND 4) OR 2</booleanFilter>
            <filterItems>
                <field>$Source.Usage_TypeLOOK__c</field>
                <operation>equals</operation>
                <valueField>Partner_or_Venue__c.Usage_Type__c</valueField>
            </filterItems>
            <filterItems>
                <field>Partner_or_Venue__c.CreatedDate</field>
                <operation>lessThan</operation>
                <value>1/1/2014 12:00 AM</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Res Acc</value>
            </filterItems>
            <filterItems>
                <field>Partner_or_Venue__c.CreatedDate</field>
                <operation>greaterOrEqual</operation>
                <value>1/1/2014 12:00 AM</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Partner_or_Venue__c</referenceTo>
        <relationshipLabel>Bookings</relationshipLabel>
        <relationshipName>Bookings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Usage_Type__c</fullName>
        <formula>Partner_or_Venue__r.Usage_Type__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Usage Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Wave_Dates__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Wave Dates</label>
        <referenceTo>Wave_Dates__c</referenceTo>
        <relationshipName>Bookings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Wave__c</fullName>
        <label>Wave</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Wave__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>2014,2015,2016,2017</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Wave__c</referenceTo>
        <relationshipLabel>Bookings</relationshipLabel>
        <relationshipName>Bookings</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Wave_number__c</fullName>
        <formula>Wave__r.Wave_number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Wave number</label>
        <type>Text</type>
    </fields>
    <label>Booking</label>
    <nameField>
        <label>Booking Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Cluster__c.object
<CustomObject>
    <label>Cluster</label>
    <nameField>
        <label>Cluster Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clusters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Partner_or_Venue__c.object
<CustomObject>
    <description>Type of services provided.
Junction, with lookups to Account, Cluster, Wave and Team</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Usages</relationshipLabel>
        <relationshipName>Junctions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cluster</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Cluster__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>2013</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipName>Junctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Usage_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Usage Type</label>
        <referenceTo>Usage_Type__c</referenceTo>
        <relationshipLabel>Usages</relationshipLabel>
        <relationshipName>Usages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Wave__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Wave</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Wave__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>2013</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Wave__c</referenceTo>
        <relationshipLabel>Usages</relationshipLabel>
        <relationshipName>Junctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Usage</label>
    <nameField>
        <label>Usage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Usages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Transport_order__c.object
<CustomObject>
    <description>This object tracks the transport needed to carry YPs from one booking to another</description>
    <fields>
        <fullName>Cluster__c</fullName>
        <formula>From_Booking__r.Wave__r.Wave_Cluster__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Cluster</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_Optimised__c</fullName>
        <label>Date Optimised</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_of_Travel__c</fullName>
        <label>Date of Travel</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Earliest_departure_time__c</fullName>
        <label>Earliest departure time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>From_Booking__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>From Booking</label>
        <referenceTo>Booking__c</referenceTo>
        <relationshipName>Transport</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TMS_Status__c</fullName>
        <formula>IF(
AND(

 Date__c &gt;=TODAY()

,

OR( Status__c = &quot;Journey Ready&quot;,
Status__c = &quot;Approved (PM)&quot;)
)
,

&quot;Active&quot;,&quot;Inactive&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>TMS Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>To_Booking__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>To Booking</label>
        <referenceTo>Booking__c</referenceTo>
        <relationshipName>Transport1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Wave__c</fullName>
        <formula>IF(ISBLANK(From_Booking__r.Wave__r.Name), To_Booking__r.Wave__r.Name, From_Booking__r.Wave__r.Name)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Wave</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Wave_number__c</fullName>
        <description>Displaying the wave number for waves in following formats: 

Bradfield A 5 (1 digit number) 
Bradfield A 12 (2 digit number) 
Bradfield B 13a (2 digit number plus letter)</description>
        <formula>IF(
(LEFT(RIGHT( Wave__c ,2),1)=&quot; &quot;),
RIGHT(Wave__c,1),
IF(
ISNUMBER(RIGHT(Wave__c,2)),
RIGHT(Wave__c,2),
LEFT(RIGHT(Wave__c,3),2)
))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Wave number</label>
        <type>Text</type>
    </fields>
    <label>Transport order</label>
    <nameField>
        <displayFormat>{0000}{DD}{MM}</displayFormat>
        <label>Transport Order ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transport orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Usage_Type__c.object
<CustomObject>
    <fields>
        <fullName>Group_Event__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Should be ticked when it&apos;s a group event. Should be unticked when it&apos;s a team event.</inlineHelpText>
        <label>Group Event</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Plan__c</fullName>
        <label>Plan</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <label>Usage Type</label>
    <nameField>
        <label>Usage Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Usage Types</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Wave__c.object
<CustomObject>
    <fields>
        <fullName>MM_confirmed_PCKO_starters__c</fullName>
        <inlineHelpText>Marketing Manager enters the date when they confirm that the number Mktg Number of YPs started Wave (entered by SC/AMM) is correct</inlineHelpText>
        <label>ASM confirmed PCKO starters</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Wave_Cluster__c</fullName>
        <label>Cluster</label>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Waves</relationshipLabel>
        <relationshipName>Waves</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Wave_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Wave Template</label>
        <referenceTo>Wave_Template__c</referenceTo>
        <relationshipLabel>Waves</relationshipLabel>
        <relationshipName>Waves</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Wave_code__c</fullName>
        <description>Unique wave code</description>
        <inlineHelpText>Unique wave code</inlineHelpText>
        <label>Wave code</label>
        <length>25</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Wave_number__c</fullName>
        <label>Wave number</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <label>Wave</label>
    <nameField>
        <label>Wave Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Waves</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Wave_Dates__c.object
<CustomObject>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <label>Start Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Usage_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Usage Type</label>
        <referenceTo>Usage_Type__c</referenceTo>
        <relationshipName>Wave_Dates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Wave_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Wave Template</label>
        <referenceTo>Wave_Template__c</referenceTo>
        <relationshipName>Wave_Dates</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Wave Components</label>
    <nameField>
        <displayFormat>Date-{0000}</displayFormat>
        <label>Wave Dates Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wave Components</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Wave_Template__c.object
<CustomObject>
    <label>Wave Template</label>
    <nameField>
        <label>Wave Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Wave Template</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/AccountTriggerHandlerTest.cls
/************************************************************************
Developer : Dreamwares (Amol)
Date : 18-12-2014
Description : Test class for AccountTriggerHandler.
************************************************************************/

@isTest
public class AccountTriggerHandlerTest
{

    /*******************************************************************
    Method Name : testInactiveTranspOrder
    Description : used to test inactive Transport order condition.
    ********************************************************************/
    
    Static TestMethod void testInactiveTranspOrder()
    {
        //create test data
        createInactiveTestData();
        
        //update Account of FROM Address
        Account acc = [SELECT Id,Name,BillingPostalCode FROM Account WHERE Name = 'Test FromAccount' LIMIT 1];
        acc.BillingPostalCode = '7896';
        update acc;
        
        //update Account of To Address
        acc =  [SELECT Id,Name,BillingPostalCode FROM Account WHERE Name = 'Test Account' LIMIT 1];
        acc.BillingPostalCode = '4569';
        update acc;
    }
    
    /*******************************************************************
    Method Name : testActiveTranspOrder
    Description : used to test active Transport order condition.
    ********************************************************************/
    
    Static TestMethod void testActiveTranspOrder()
    {
        //create test data
        createActiveTestData();
        
        //update Account address of From Address
        Account acc = [SELECT Id,Name,BillingPostalCode FROM Account WHERE Name = 'TestActive FromAccount' LIMIT 1];
        acc.BillingPostalCode = '7896';
        try
        {
          update acc;
        }
        catch(Exception e)
        {
            system.debug('ERROR : ' + e.getMessage());
        }
        
        //update Account of To Address
        acc =  [SELECT Id,Name,BillingPostalCode FROM Account WHERE Name = 'TestActive Account' LIMIT 1];
        acc.BillingPostalCode = '4569';
        try
        {
          update acc;
        }
        catch(Exception e)
        {
            system.debug('ERROR : ' + e.getMessage());
        }
    }
    
    /*******************************************************************
    Method Name : createInactiveTestData
    Description : used to test active Transport order condition.
    ********************************************************************/
    
    Static void createInactiveTestData()
    {
        //create Account for To Address
        Account testToAccount = new Account();
        testToAccount.Name = 'Test Account';
        testToAccount.BillingCity = 'Test City';
        testToAccount.BillingCountry = 'Test Country';
        testToAccount.BillingPostalCode = '1245';
        testToAccount.BillingState = 'Test State';
        testToAccount.BillingStreet = 'Test Street';
        insert testToAccount;
        
        //get record type of Usage
        Schema.DescribeSObjectResult cfrSchema = Schema.SObjectType.Partner_or_Venue__c; 
        Map<String,Schema.RecordTypeInfo> UsageRecordTypeInfo = cfrSchema.getRecordTypeInfosByName();
        Id UsageRecId = UsageRecordTypeInfo.get('PC Return Venue 2015').getRecordTypeId();
        
        //create Usage Type
        Usage_Type__c testUsageType = new Usage_Type__c();
        testUsageType.Group_Event__c = true;
        testUsageType.Name = 'PC Return Venue 2015';
        testUsageType.Plan__c = 'Test Plan';
        insert testUsageType;
        
        //Create Usage for To Address
        Partner_or_Venue__c testToUsage = new Partner_or_Venue__c();
        testToUsage.Account__c = testToAccount.Id;
        testToUsage.Name = 'Test Usage';
        testToUsage.RecordTypeId = UsageRecId;
        testToUsage.Usage_Type__c = testUsageType.Id;
        insert testToUsage;
        
        //create cluster record
        Cluster__c cluster1 = new Cluster__c (Name = 'Bloomsbury Cluster');
        insert cluster1;
        
        //create wave template
        Wave_Template__c wvt = new Wave_Template__c();
        wvt.Name = 'Wave Template';
        insert wvt;
        
        //create wave record
        Wave__c wv=new Wave__c();
        wv.Name='Wave';
        wv.Wave_number__c= '12';
        wv.Wave_code__c='Wave';
        wv.Wave_Cluster__c=cluster1.ID;
        wv.Wave_Template__c = wvt.Id;
        wv.MM_confirmed_PCKO_starters__c=System.today();
        insert wv; 
        
        //create wave date record
        Wave_Dates__c WD = new Wave_Dates__c();
        WD.Start_Date__c = system.today();
        WD.End_Date__c = system.today() + 10;
        WD.Usage_Type__c = testUsageType.Id;
        WD.Wave_Template__c = wvt.Id;
        insert WD;
        
        //Create Account for From Address
        Account testFromAccount = new Account();
        testFromAccount.Name = 'Test FromAccount';
        testFromAccount.BillingCity = 'Test FromCity';
        testFromAccount.BillingCountry = 'Test FromCountry';
        testFromAccount.BillingPostalCode = '12345';
        testFromAccount.BillingState = 'Test FromState';
        testFromAccount.BillingStreet = 'Test FromStreet';
        insert testFromAccount;
        
        //Create usage for From Address
        Partner_or_Venue__c testFromUsage = new Partner_or_Venue__c();
        testFromUsage.Account__c = testFromAccount.Id;
        testFromUsage.Name = 'Test Usage';
        testFromUsage.RecordTypeId = UsageRecId;
        testFromUsage.Usage_Type__c = testUsageType.Id;
        insert testFromUsage;
        
        Test.startTest();
        //create booking record for To Address
        Booking__c testToBooking = new Booking__c();
        testToBooking.Name = 'Test Booking';
        testToBooking.Partner_or_Venue__c = testToUsage.Id;
        testToBooking.Wave__c = wv.Id;
        insert testToBooking;
        
        //create booking record for From Address
        Booking__c testFromBooking = new Booking__c();
        testFromBooking.Name = 'Test Booking';
        testFromBooking.Partner_or_Venue__c = testFromUsage.Id;
        testFromBooking.Wave__c = wv.Id;
        insert testFromBooking;
        
        //create inactive transport order record
        Transport_order__c testOrder = new Transport_order__c();
        testOrder.From_Booking__c = testFromBooking.Id;
        testOrder.To_Booking__c = testToBooking.Id;
        testOrder.Earliest_departure_time__c = system.today() + 10;
        insert testOrder;
        
        //check TMS Status of transport order
        Transport_order__c order = new Transport_order__c();
        order = [SELECT Id,TMS_Status__c FROM Transport_order__c WHERE Id = :testOrder.Id];
        System.assertEquals(order.TMS_Status__c,'Inactive');
        Test.stopTest();
    }
    
    Static void createActiveTestData()
    {
        //create Account for To Address
        Account testToAccount = new Account();
        testToAccount.Name = 'TestActive Account';
        testToAccount.BillingCity = 'Test City';
        testToAccount.BillingCountry = 'Test Country';
        testToAccount.BillingPostalCode = '1245';
        testToAccount.BillingState = 'Test State';
        testToAccount.BillingStreet = 'Test Street';
        insert testToAccount;
        
        //get record type for Usage
        Schema.DescribeSObjectResult cfrSchema = Schema.SObjectType.Partner_or_Venue__c; 
        Map<String,Schema.RecordTypeInfo> UsageRecordTypeInfo = cfrSchema.getRecordTypeInfosByName();
        Id UsageRecId = UsageRecordTypeInfo.get('PC Return Venue 2015').getRecordTypeId();
        
        //create usage type record
        Usage_Type__c testUsageType = new Usage_Type__c();
        testUsageType.Group_Event__c = true;
        testUsageType.Name = 'PC Return Venue 2015';
        testUsageType.Plan__c = 'TestActive Plan';
        insert testUsageType;
        
        //create usage record for To Address
        Partner_or_Venue__c testToUsage = new Partner_or_Venue__c();
        testToUsage.Account__c = testToAccount.Id;
        testToUsage.Name = 'TestActive Usage';
        testToUsage.RecordTypeId = UsageRecId;
        testToUsage.Usage_Type__c = testUsageType.Id;
        insert testToUsage;
        
        //create cluster record
        Cluster__c cluster1 = new Cluster__c (Name = 'Bloomsbury ClusterTest');
        insert cluster1;
        
        //create wave template
        Wave_Template__c wvt = new Wave_Template__c();
        wvt.Name = 'TestWave Template';
        insert wvt;
        
        //create wave record
        Wave__c wv=new Wave__c();
        wv.Name='TestWave';
        wv.Wave_number__c= '13';
        wv.Wave_code__c='Wave';
        wv.Wave_Cluster__c=cluster1.ID;
        wv.Wave_Template__c = wvt.Id;
        wv.MM_confirmed_PCKO_starters__c=System.today();
        insert wv; 
        
        //create wave date record
        Wave_Dates__c WD = new Wave_Dates__c();
        WD.Start_Date__c = system.today();
        WD.End_Date__c = system.today() + 5;
        WD.Usage_Type__c = testUsageType.Id;
        WD.Wave_Template__c = wvt.Id;
        insert WD;
        
        //Create Account record for From Address
        Account testFromAccount = new Account();
        testFromAccount.Name = 'TestActive FromAccount';
        testFromAccount.BillingCity = 'Test FromCity';
        testFromAccount.BillingCountry = 'Test FromCountry';
        testFromAccount.BillingPostalCode = '12345';
        testFromAccount.BillingState = 'Test FromState';
        testFromAccount.BillingStreet = 'Test FromStreet';
        insert testFromAccount;
        
        //create usage record for From Address
        Partner_or_Venue__c testFromUsage = new Partner_or_Venue__c();
        testFromUsage.Account__c = testFromAccount.Id;
        testFromUsage.Name = 'TestActive Usage';
        testFromUsage.RecordTypeId = UsageRecId;
        testFromUsage.Usage_Type__c = testUsageType.Id;
        insert testFromUsage;
        
        Test.startTest();
        
        //create booking record for To Address
        Booking__c testToBooking = new Booking__c();
        testToBooking.Name = 'TestActive Booking';
        testToBooking.Partner_or_Venue__c = testToUsage.Id;
        testToBooking.Wave__c = wv.Id;
        insert testToBooking;
        
        //create booking record for From Address
        Booking__c testFromBooking = new Booking__c();
        testFromBooking.Name = 'TestActive Booking';
        testFromBooking.Partner_or_Venue__c = testFromUsage.Id;
        testFromBooking.Wave__c = wv.Id;
        insert testFromBooking;
        
        //create Active Transport Order record
        Transport_order__c testOrder = new Transport_order__c();
        testOrder.From_Booking__c = testFromBooking.Id;
        testOrder.To_Booking__c = testToBooking.Id;
        testOrder.Date_of_Travel__c = system.today() + 5;
        testOrder.Date_Optimised__c = system.today();
        testOrder.Earliest_departure_time__c = system.today() + 4;
        insert testOrder;
        
        //check TMS Status of transport order
        Transport_order__c order = new Transport_order__c();
        order = [SELECT Id,TMS_Status__c FROM Transport_order__c WHERE Id = :testOrder.Id];
        System.assertEquals(order.TMS_Status__c,'Active');
        Test.stopTest();
    }
    
     /*******************************************************************
    Method Name : testActiveTranspOrderAllowAdressChange
    Description : used to test active Transport order condition.
    Created By  : [Dreamwares]Amol Kulthe
    ********************************************************************/
    
    Static TestMethod void testActiveTranspOrderAllowAdressChange()
    {
        // create test data
        createActiveTestData();              
        
        Account acc = [SELECT Id, Name, BillingPostalCode, Override_TMS_validation__c  
                       FROM Account 
                       WHERE Name = 'TestActive FromAccount' 
                       LIMIT 1];
        acc.Override_TMS_validation__c = true;
        acc.BillingPostalCode = '7896';  
        update acc;      
        
        //Check Changes are made
        acc = [SELECT Id, Name, BillingPostalCode, Override_TMS_validation__c  
               FROM Account 
               WHERE Name = 'TestActive FromAccount' 
               LIMIT 1];           
        System.assertEquals(acc.BillingPostalCode,'7896');
        System.assertEquals(acc.Override_TMS_validation__c,false);

        acc = [SELECT Id, Name, BillingPostalCode, Override_TMS_validation__c  
               FROM Account 
               WHERE Name = 'TestActive FromAccount' 
               LIMIT 1];
        acc.BillingPostalCode = '345123';       
        try
        {
          update acc;
        }
        catch(Exception e)
        {
            system.debug('ERROR : ' + e.getMessage());
        }       
        
        acc = [SELECT Id, Name, BillingPostalCode, Override_TMS_validation__c  
               FROM Account 
               WHERE Name = 'TestActive FromAccount' 
               LIMIT 1];
        System.assertEquals(acc.Override_TMS_validation__c,false);             
        System.assertEquals(acc.BillingPostalCode,'7896');

    }
}