objects/Booking__c.object
<CustomObject>
    <fields>
        <fullName>Partner_or_Venue__c</fullName>
        <label>Usage</label>
        <lookupFilter>
            <active>false</active>
            <booleanFilter>(1 AND 4) OR (3 AND 4) OR 2</booleanFilter>
            <filterItems>
                <field>$Source.Usage_TypeLOOK__c</field>
                <operation>equals</operation>
                <valueField>Partner_or_Venue__c.Usage_Type__c</valueField>
            </filterItems>
            <filterItems>
                <field>Partner_or_Venue__c.CreatedDate</field>
                <operation>lessThan</operation>
                <value>1/1/2014 12:00 AM</value>
            </filterItems>
            <filterItems>
                <field>$Source.RecordTypeId</field>
                <operation>equals</operation>
                <value>Res Acc</value>
            </filterItems>
            <filterItems>
                <field>Partner_or_Venue__c.CreatedDate</field>
                <operation>greaterOrEqual</operation>
                <value>1/1/2014 12:00 AM</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Partner_or_Venue__c</referenceTo>
        <relationshipLabel>Bookings</relationshipLabel>
        <relationshipName>Bookings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Usage_Type__c</fullName>
        <formula>Partner_or_Venue__r.Usage_Type__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Usage Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Wave__c</fullName>
        <label>Wave</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Wave__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>2014,2015,2016,2017</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Wave__c</referenceTo>
        <relationshipLabel>Bookings</relationshipLabel>
        <relationshipName>Bookings</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Booking</label>
    <nameField>
        <label>Booking Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Partner_or_Venue__c.object
<CustomObject>
    <description>Type of services provided.
Junction, with lookups to Account, Cluster, Wave and Team</description>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Usages</relationshipLabel>
        <relationshipName>Junctions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cluster</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Cluster__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>2013</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipName>Junctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cluster - Coach company</fullName>
                </value>
                <value>
                    <fullName>Cluster - Minibus company</fullName>
                </value>
                <value>
                    <fullName>Cluster - Residential accommodation</fullName>
                </value>
                <value>
                    <fullName>Cluster - Alternative residential accommodation</fullName>
                </value>
                <value>
                    <fullName>Cluster - Presentation day partner</fullName>
                </value>
                <value>
                    <fullName>Cluster - RCD Friday revue venue</fullName>
                </value>
                <value>
                    <fullName>Cluster - RCA meeting point 1 (Sat)</fullName>
                </value>
                <value>
                    <fullName>Cluster - RCA meeting point 1 (Sun)</fullName>
                </value>
                <value>
                    <fullName>Cluster - RCA meeting point 2 (Sat)</fullName>
                </value>
                <value>
                    <fullName>Cluster - RCA meeting point 2 (Sun)</fullName>
                </value>
                <value>
                    <fullName>Cluster - RCA meeting point 3 (Sat)</fullName>
                </value>
                <value>
                    <fullName>Cluster - RCA meeting point 3 (Sun)</fullName>
                </value>
                <value>
                    <fullName>Cluster - RCA meeting point 4 (Sat)</fullName>
                </value>
                <value>
                    <fullName>Cluster - RCA meeting point 4 (Sun)</fullName>
                </value>
                <value>
                    <fullName>Cluster - Graduation venue</fullName>
                </value>
                <value>
                    <fullName>Waves - PC KO venue</fullName>
                </value>
                <value>
                    <fullName>Waves - PC partner</fullName>
                </value>
                <value>
                    <fullName>Waves - PC Drop off venue</fullName>
                </value>
                <value>
                    <fullName>Waves - TC KO venue</fullName>
                </value>
                <value>
                    <fullName>Waves - Presentation day venue</fullName>
                </value>
                <value>
                    <fullName>Waves - TC venue</fullName>
                </value>
                <value>
                    <fullName>Waves - Showcase venue</fullName>
                </value>
                <value>
                    <fullName>Waves - RCD venue</fullName>
                </value>
                <value>
                    <fullName>Waves - Big Challenge partner</fullName>
                </value>
                <value>
                    <fullName>Team - Sports Venue</fullName>
                </value>
                <value>
                    <fullName>Team - TC partner name</fullName>
                </value>
                <value>
                    <fullName>Team - TC partner name 2</fullName>
                </value>
                <value>
                    <fullName>Team - RC CP</fullName>
                </value>
                <value>
                    <fullName>Team - Professional visit partner</fullName>
                </value>
                <value>
                    <fullName>Team - RCA partner challenge</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Usage_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Usage Type</label>
        <referenceTo>Usage_Type__c</referenceTo>
        <relationshipLabel>Usages</relationshipLabel>
        <relationshipName>Usages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Wave__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Wave</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Wave__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>2013</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Wave__c</referenceTo>
        <relationshipLabel>Usages</relationshipLabel>
        <relationshipName>Junctions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>What_are_the_other_key_things_staff_need__c</fullName>
        <inlineHelpText>NB This Field appears on the contract sheet.

What are the other key things staff need to do to set up the venue? Is there anything key they should bring, e.g. CRBs?</inlineHelpText>
        <label>What are the other key things staff need</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <label>Usage</label>
    <nameField>
        <label>Usage Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Usages</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Team__c.object
<CustomObject>
    <fields>
        <fullName>Cluster__c</fullName>
        <formula>Wave__r.Wave_Cluster__r.Name</formula>
        <label>Cluster</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Wave__c</fullName>
        <label>Wave</label>
        <referenceTo>Wave__c</referenceTo>
        <relationshipLabel>Teams</relationshipLabel>
        <relationshipName>Teams</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Usage_Type__c.object
<CustomObject>
    <fields>
        <fullName>Group_Event__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Should be ticked when it&apos;s a group event. Should be unticked when it&apos;s a team event.</inlineHelpText>
        <label>Group Event</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Plan__c</fullName>
        <label>Plan</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <label>Usage Type</label>
    <nameField>
        <label>Usage Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Usage Types</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Wave__c.object
<CustomObject>
    <fields>
        <fullName>Wave_Cluster__c</fullName>
        <label>Cluster</label>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Waves</relationshipLabel>
        <relationshipName>Waves</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Wave_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Wave Template</label>
        <referenceTo>Wave_Template__c</referenceTo>
        <relationshipLabel>Waves</relationshipLabel>
        <relationshipName>Waves</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Wave_code__c</fullName>
        <description>Unique wave code</description>
        <inlineHelpText>Unique wave code</inlineHelpText>
        <label>Wave code</label>
        <length>25</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Wave</label>
    <nameField>
        <label>Wave Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Waves</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Wave_Dates__c.object
<CustomObject>
    <fields>
        <fullName>Usage_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Usage Type</label>
        <referenceTo>Usage_Type__c</referenceTo>
        <relationshipName>Wave_Dates</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Wave_Template__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Wave Template</label>
        <referenceTo>Wave_Template__c</referenceTo>
        <relationshipName>Wave_Dates</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Wave Components</label>
    <nameField>
        <displayFormat>Date-{0000}</displayFormat>
        <label>Wave Dates Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wave Components</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/Test_ContractForm.cls
@isTest
private class Test_ContractForm {
    
    static testMethod void ContractFormTest(){
         System.debug('#####');
        // *** BEGIN: data insert 
        /*UserRole rol=new UserRole(Name='Testrol');
        insert rol;
          */
           
        Contact TestCon=new Contact(
            FirstName='Test1', LastName='ConName1',Email='test1@gmail.com',Phone='123456',MobilePhone='05051234567'//,Role__c=rol.id
        );
        insert TestCon;
        
        Profile p = [select id from profile where name='Standard User'];
        
        RecordType recT=[Select id from RecordType where SobjectType ='Partner_or_Venue__c' AND Name='Professional Visit 2013'];
        
        
        User own=new User(LastName='Owner1',Phone='112345',Country='Test Country',City='Test',State='Test',Street='Test',PostalCode='Test',Email='test1@test.com',alias = 'standt', 
            emailencodingkey='UTF-8', 
            languagelocalekey='en_US', 
            localesidkey='en_US', 
            profileid = p.Id,
            timezonesidkey='America/Los_Angeles', 
            username='testuser3@testorg.com');
           // own.UserRoleId=rol.Id;
        
       insert own;
        
        Account TestAcc = new Account(
                                    Name='Test Name' ,
                                    BillingState='Test State', 
                                    BillingCountry='Test Country', 
                                    BillingCity='Test City', 
                                    BillingStreet='Test Street', 
                                    BillingPostalCode='Test PostalCode', 
                                    Main_Contact__c=TestCon.Id                   
                                    );
        TestAcc.OwnerId=own.Id;
        insert TestAcc;
        
        Cluster__c cl=new Cluster__c(Name='Test Cluster');
        insert cl;
        
        Usage_Type__c usgType=new Usage_Type__c(Name='Professional Visit 2013');
        usgType.Plan__c='Test Plan';
        usgType.Group_Event__c=false;
        insert usgType;
        
        Partner_or_Venue__c testUsg=New Partner_or_Venue__c(Name='Test Usage');
        testUsg.RecordTypeId=recT.Id;
        testUsg.Account__c=TestAcc.Id;
        testUsg.Usage_Type__c=usgType.Id;
        testUsg.What_are_the_other_key_things_staff_need__c='Key Things';
        insert testUsg; 
        
         
        Wave_Template__c wt=new Wave_Template__c(Name='Test Template');
        insert wt;
        
        recordtype rt = [select id,name from recordtype where sobjecttype='Wave__c' and name = '2014' limit 1];
        Wave__c wa=new Wave__c(Name='test Wave');
        wa.Wave_Template__c=wt.Id;
        wa.Wave_Cluster__c=cl.Id;
        wa.Wave_code__c='xx';
        wa.Recordtypeid = rt.id;
        insert wa;
     
       
        Team__c team=new Team__c(Name='Test Team Name'); 
        team.Wave__c=wa.Id;
        insert team;
        
        
        Wave_Dates__c dt=new Wave_Dates__c();
        dt.Start_Date__c=System.today();
        dt.Usage_Type__c=usgType.Id;
        dt.Wave_Template__c=wt.Id;
        insert dt;     
        
        Wave_Dates__c WD=[SELECT Id,
                               Usage_Type__c, 
                               Wave_Template__c
                               FROM Wave_Dates__c where id=:dt.id ];
                               
        
        Booking__c b= new Booking__c();
        b.Wave__c=wa.Id;
        b.Wave_Dates__c= dt.Id;
        b.Partner_or_Venue__c=testUsg.Id;  
        b.Location_to_meet__c='Test';
        b.Partner_Contact__c=TestCon.Id;
        insert b;
       
        Test.startTest();
         
        ApexPages.StandardController stdController=new ApexPages.StandardController (TestAcc);
         PageReference DummyPage=new PageReference('/confirmation?id='+TestAcc.Id);
             Test.setCurrentPage(DummyPage);
        ContractForm cf=new ContractForm(stdController);
        
        Test.stopTest();
    
    }

}