objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>Allow_registration_on_website__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Checked box allows registration on TCS website</description>
        <inlineHelpText>Check box to allow users to register for this event on the TCS website</inlineHelpText>
        <label>Allow registration on website?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Challenger_Action__c</fullName>
        <description>Whether Challenger RSVP is necessary</description>
        <inlineHelpText>Whether Challenger RSVP is necessary</inlineHelpText>
        <label>Challenger Action</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Just turn up</fullName>
                </value>
                <value>
                    <fullName>Please let us know you are coming</fullName>
                </value>
                <value>
                    <fullName>Don&apos;t sign up yet - we will provide more information soon!</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Cluster the event relates to</description>
        <inlineHelpText>The cluster the event relates to</inlineHelpText>
        <label>Cluster</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Cluster__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>2012,2013,2014, 2015, 2016</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Campaigns</relationshipLabel>
        <relationshipName>Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Summary_description__c</fullName>
        <inlineHelpText>Provide a short summary description of the event</inlineHelpText>
        <label>Summary description</label>
        <type>TextArea</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Cluster__c.object
<CustomObject>
    <fields>
        <fullName>Zone__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Zone the cluster is part of</description>
        <inlineHelpText>The zone this cluster is part of</inlineHelpText>
        <label>Zone</label>
        <referenceTo>Zone__c</referenceTo>
        <relationshipLabel>Clusters</relationshipLabel>
        <relationshipName>Clusters</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Cluster</label>
    <nameField>
        <label>Cluster Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clusters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Metric__c.object
<CustomObject>
    <description>Keeps the Contact and some detailed metrics</description>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Metrics</relationshipLabel>
        <relationshipName>Metrics</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Metric</label>
    <nameField>
        <displayFormat>M-{0000}</displayFormat>
        <label>Metric Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Metrics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Region__c.object
<CustomObject>
    <description>TCN Region (geographical area)</description>
    <fields>
        <fullName>Region_code__c</fullName>
        <description>Unique code for the region</description>
        <inlineHelpText>Unique code for the region</inlineHelpText>
        <label>Region code</label>
        <length>1</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Regions</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Zone__c.object
<CustomObject>
    <description>TCN Zone (geographical area)</description>
    <fields>
        <fullName>Region__c</fullName>
        <description>Region the zone is part of</description>
        <inlineHelpText>The region this zones is part of</inlineHelpText>
        <label>Region</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Zones</relationshipLabel>
        <relationshipName>Zones</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Zone_code__c</fullName>
        <description>Zone&apos;s unique code</description>
        <inlineHelpText>Zone&apos;s unique code</inlineHelpText>
        <label>Zone code</label>
        <length>1</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Zone</label>
    <nameField>
        <label>Zone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Test_SummaryViewController.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class Test_SummaryViewController {

    static testMethod void myUnitTest() {
    	Region__c region = new Region__c(Name='TestRegion4Metric',Region_Code__c='b');
    	insert region;
    	
    	Zone__c zone = new Zone__c(Name='TestZone4Metric',Region__c=region.id, Zone_Code__c='b');
    	insert zone;
    	
    	
    	
    	RecordType r = [SELECT Id FROM RecordType WHERE SObjectType='Cluster__c' AND Name='2012'];
        Cluster__c cluster = new Cluster__c(Name='TestCluster4Metric',Zone__c=zone.id, RecordTypeId = r.Id);
        insert cluster;
        
        Contact contact = new Contact();
        contact.FirstName = 'Test Contact for Metric';
        contact.LastName = 'Test Contact for Metric';
        contact.Ethnicity__c = 'White';
        contact.Religion__c = 'Muslim';
        contact.Gender__c = 'Female';
        contact.Cluster__c = cluster.id;
        insert contact;
        
         Contact contact2 = new Contact();
        contact2.FirstName = 'Test Contact for Metric';
        contact2.LastName = 'Test Contact for Metric';
        contact2.Ethnicity__c = 'Black';
        contact2.Religion__c = 'Hindu';
        contact2.Gender__c = 'Male';
        contact2.Cluster__c = cluster.id;
        insert contact2;
        
       // RecordType rt = [SELECT Id FROM RecordType WHERE SObjectType='Contact' AND (Name='YP' OR Name='Grad2011') LIMIT 1];
			
		Metric__c metric = new Metric__c(Contact__c = contact.Id);
		insert metric;
			
		RecordType rtr = [SELECT Id FROM RecordType WHERE SObjectType='Campaign' AND Name='Action Team Meeting'];
		Campaign cam = new Campaign(Name='testcampaign', Summary_description__c='testsummarydescription', Description='testdescription', Cluster__c = cluster.Id,
										RecordTypeId = rtr.Id,Allow_registration_on_website__c = true,Challenger_Action__c = 'Please let us know you are coming');
		insert cam;
			
		CampaignMember campmem = new CampaignMember(CampaignId = cam.Id, ContactId = contact.Id, status = 'Attended');
		insert campmem;
		CampaignMember campmem2 = new CampaignMember(CampaignId = cam.Id, ContactId = contact2.Id, status = 'Attended');
		insert campmem2;
		
		SummaryViewController Customcontroller;
		PageReference DummyPage;
        
        
        Test.startTest();
        DummyPage=new PageReference('/SummaryView?id=&Name=');
		Test.setCurrentPage(DummyPage);
		Customcontroller = new SummaryViewController();
		Customcontroller.FetchMetrics();
		
		 DummyPage=new PageReference('/SummaryView?id='+zone.id+'&Name=Zone');
		 Test.setCurrentPage(DummyPage);
		 Customcontroller = new SummaryViewController();
		
		 
		 DummyPage=new PageReference('/SummaryView?id='+cluster.id+'&Name=Cluster');
		 Test.setCurrentPage(DummyPage);
		 Customcontroller = new SummaryViewController();
		 
		 SummaryMetricController smc = new SummaryMetricController();
		 smc.getMetrics();
		 smc.getSummaryMetircList();
		 
		 ApexPages.StandardController stdController=new ApexPages.StandardController(contact);
		 PageReference DumPage=new PageReference('/IndividualMetric?id='+contact.Id);
         Test.setCurrentPage(DumPage);
		 IndividulMetricController imc = new IndividulMetricController(stdController);
		 Test.stopTest();
		 
        
    }
}