objects/Cluster__c.object
<CustomObject>
    <fields>
        <fullName>Cluster_location_boroughs_areas__c</fullName>
        <description>Boroughs/areas covered by cluster</description>
        <inlineHelpText>The boroughs/areas covered by the cluster</inlineHelpText>
        <label>Cluster location</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Acocks Green</fullName>
                </value>
                <value>
                    <fullName>Aston</fullName>
                </value>
                <value>
                    <fullName>Barking &amp; Dagenham</fullName>
                </value>
                <value>
                    <fullName>Barnet</fullName>
                </value>
                <value>
                    <fullName>Bartley Green</fullName>
                </value>
                <value>
                    <fullName>Bexley</fullName>
                </value>
                <value>
                    <fullName>Billesley</fullName>
                </value>
                <value>
                    <fullName>Birmingham</fullName>
                </value>
                <value>
                    <fullName>Blackburn</fullName>
                </value>
                <value>
                    <fullName>Blackburn with Darwen</fullName>
                </value>
                <value>
                    <fullName>Blackpool</fullName>
                </value>
                <value>
                    <fullName>Bordesley Green</fullName>
                </value>
                <value>
                    <fullName>Bournville</fullName>
                </value>
                <value>
                    <fullName>Bracknell Forest</fullName>
                </value>
                <value>
                    <fullName>Bradford</fullName>
                </value>
                <value>
                    <fullName>Brandwood</fullName>
                </value>
                <value>
                    <fullName>Brent</fullName>
                </value>
                <value>
                    <fullName>Bromley</fullName>
                </value>
                <value>
                    <fullName>Burnley</fullName>
                </value>
                <value>
                    <fullName>Bury</fullName>
                </value>
                <value>
                    <fullName>Camden</fullName>
                </value>
                <value>
                    <fullName>Central Manchester</fullName>
                </value>
                <value>
                    <fullName>Chiltern</fullName>
                </value>
                <value>
                    <fullName>Chorley</fullName>
                </value>
                <value>
                    <fullName>City of London</fullName>
                </value>
                <value>
                    <fullName>CNE Birmingham</fullName>
                </value>
                <value>
                    <fullName>CNW Birmingham</fullName>
                </value>
                <value>
                    <fullName>Coventry</fullName>
                </value>
                <value>
                    <fullName>Croydon</fullName>
                </value>
                <value>
                    <fullName>CSE Birmingham</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Zone__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Zone the cluster is part of</description>
        <inlineHelpText>The zone this cluster is part of</inlineHelpText>
        <label>Zone</label>
        <referenceTo>Zone__c</referenceTo>
        <relationshipLabel>Clusters</relationshipLabel>
        <relationshipName>Clusters</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Cluster</label>
    <nameField>
        <label>Cluster Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clusters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Metric__c.object
<CustomObject>
    <description>Keeps the Contact and some detailed metrics</description>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                    <default>true</default>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Metrics</relationshipLabel>
        <relationshipName>Metrics</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Involved__c</fullName>
        <formula>IF(Big_Challenge_Day_Event_Attended__c +  CAT_Meetings_Attended__c +  YB_Meetings_Attended__c +  Local_Events_Attended__c +  Skill_Workshop_Attended__c +  Marketing_Ambassador_Events_Attended1__c +  Media_Ambassador_Events_Attended__c +  Staffing_Ambassador__c +  PC_Meetings_Attended__c +  Total_AM_SAM_Attendances__c +  Total_SignPosting_Oppty_Meetings_Attend__c &gt;= 1, &apos;Yes&apos;, &apos;No&apos; )</formula>
        <label>Involved</label>
        <type>Text</type>
    </fields>
    <label>Metric</label>
    <nameField>
        <displayFormat>M-{0000}</displayFormat>
        <label>Metric Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Metrics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Survey__c.object
<CustomObject>
    <description>Hold Survey data</description>
    <fields>
        <fullName>Cluster__c</fullName>
        <formula>IF( ISBLANK( Wave__c  ), Cluster_Wave_Not_Entered__c,Cluster_Wave_Entered__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Cluster</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Desire_to_remain_involved_0_10__c</fullName>
        <inlineHelpText>Survey Question: Would you want to get involved in a day like this again? (10 = yes definitely! 0 = no thanks)</inlineHelpText>
        <label>Desire to remain involved (0-10)</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Event_rating_0_10__c</fullName>
        <inlineHelpText>Survey Question: On a scale of 0 to 10 please rate the day</inlineHelpText>
        <label>Event rating (0-10)</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Wave_Summary__c</fullName>
        <label>Wave Summary</label>
        <referenceTo>Wave_Summary__c</referenceTo>
        <relationshipLabel>Surveys</relationshipLabel>
        <relationshipName>Surveys</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Zone__c</fullName>
        <formula>IF( ISBLANK( Wave__c),  Zone_Wave_Not_Entered__c ,Zone_Wave_Entered__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Zone</label>
        <type>Text</type>
    </fields>
    <label>Survey</label>
    <nameField>
        <displayFormat>S-{YYYY}{MM}{00000}</displayFormat>
        <label>Survey Reference No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <recordTypes>
        <fullName>YP</fullName>
        <active>true</active>
        <label>YP</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Wave_Summary__c.object
<CustomObject>
    <description>Summarised Survey results for field.</description>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cluster</label>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Survey Summaries</relationshipLabel>
        <relationshipName>Survey_Summaries</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Zone__c</fullName>
        <label>Zone</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Survey Summary</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Zone__c.object
<CustomObject>
    <description>TCN Zone (geographical area)</description>
    <label>Zone</label>
    <nameField>
        <label>Zone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ClusterController.cls
public class ClusterController {
        
        public String title {get; set;}
        public String clusterid {get; set;}
        public List<Cluster__c> borough {get; set;}
        public List<Metric__c> involvedReports {get; set;}
        public List<Metric__c> activeReports {get; set;}
        public List<Survey__c> wantToRemains {get; set;} 
        public List<Survey__c> eventRatings {get; set;} 
        public Integer noInvolvedReports {get; set;}
        public Integer noActiveReports {get; set;}
        public Decimal percentageOfRemainings {get; set;}
		public Decimal averageRating {get; set;}
		public List<String> borvalues {get; set;}
		public String backid {get; set;}
        public Zone__c zonename {get; set;}
        
        public ClusterController(){
        	
        		clusterid = ApexPages.currentPage().getParameters().get('id');
        		percentageOfRemainings = 0; 
        		averageRating = 0;
        		getBorough();
        		getInvolvedReports();
        		getRatios();
        }       
                
        public List<Cluster__c> getBorough(){
                  
                Cluster__c cluster = new Cluster__c();
                borough = [SELECT Name,Cluster_location_boroughs_areas__c FROM Cluster__c WHERE Id =: clusterid];
        		cluster = [SELECT Name, Zone__c FROM Cluster__c WHERE Id =: clusterid];
                title = cluster.Name;
                backid = cluster.Zone__c;
                zonename = [SELECT Name FROM Zone__c WHERE Id =: backid];
                borvalues=new list<string>();
                for(Integer b=0; b<borough.size(); b++){
                	if(borough[b].Cluster_location_boroughs_areas__c!=null){
	                	for(string s:borough[b].Cluster_location_boroughs_areas__c.split(';'))
			        	{
			        			borvalues.add(EncodingUtil.UrlEncode(s,'UTF-8'));
				        }
                	}
                }
                borvalues.sort();

        return borough;
        }

		public List<Metric__c> getInvolvedReports(){
        
        		involvedReports = [SELECT Involved__c FROM Metric__c WHERE Involved__c = 'Yes' AND Contact__r.Cluster__c =: clusterid];
        		activeReports = [SELECT Active__c FROM Metric__c WHERE Active__c = 'Yes' AND Contact__r.Cluster__c =: clusterid];

        		noInvolvedReports = involvedReports.size();
        		noActiveReports = activeReports.size();
        
       return activeReports;
        }
		
		public List<Survey__c> getRatios(){
        
        	List<Survey__c> remains = new List<Survey__c>();
        	Decimal totalRatings=0;

        		List<RecordType> r = [SELECT Id FROM RecordType WHERE SObjectType='Survey__c' AND Name='TCS event YP'];
        	
        		wantToRemains = [SELECT Desire_to_remain_involved_0_10__c, Event_rating_0_10__c FROM Survey__c WHERE Wave_Summary__r.Cluster__c =: clusterid AND RecordTypeId =: r];
        		
        	if(wantToRemains.size()!=0){
        		for(Integer i=0; i<wantToRemains.size(); i++)
        		{
        			if(wantToRemains[i].Desire_to_remain_involved_0_10__c != null && 
        			   wantToRemains[i].Desire_to_remain_involved_0_10__c>=7){
        					remains.add(wantToRemains[i]);
        				}
    				if(wantToRemains[i].Event_rating_0_10__c != null){
    					totalRatings += wantToRemains[i].Event_rating_0_10__c;
    				}
        		
        		}
        		Decimal a = remains.size();
        		Decimal b = wantToRemains.size();
        		percentageOfRemainings = ((a/b)*100).setScale(1);
        		averageRating = (totalRatings/Decimal.valueOf(wantToRemains.size())).setScale(1);
        	}
        	        		
        	/*	eventRatings = [SELECT Event_rating_0_10__c FROM Survey__c WHERE Wave_Summary__r.Cluster__c =: clusterid AND RecordTypeId =: r];
        		
        	if(eventRatings.size()!=0){
        		for(Integer i=0; i<eventRatings.size(); i++){
        			totalRatings += eventRatings[i].Event_rating_0_10__c;
        		}
        		averageRating = (totalRatings/Decimal.valueOf(eventRatings.size())).setScale(1);
        	}
        	*/	
        return wantToRemains;
        }
}