objects/Cluster__c.object
<CustomObject>
    <fields>
        <fullName>Cluster_code__c</fullName>
        <description>TCN&apos;s unique cluster code</description>
        <inlineHelpText>TCN&apos;s unique cluster code</inlineHelpText>
        <label>Cluster code</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Zone__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Zone the cluster is part of</description>
        <inlineHelpText>The zone this cluster is part of</inlineHelpText>
        <label>Zone</label>
        <referenceTo>Zone__c</referenceTo>
        <relationshipLabel>Clusters</relationshipLabel>
        <relationshipName>Clusters</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Cluster</label>
    <nameField>
        <label>Cluster Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clusters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Region__c.object
<CustomObject>
    <description>TCN Region (geographical area)</description>
    <fields>
        <fullName>Region_code__c</fullName>
        <description>Unique code for the region</description>
        <inlineHelpText>Unique code for the region</inlineHelpText>
        <label>Region code</label>
        <length>1</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Regions</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Wave__c.object
<CustomObject>
    <fields>
        <fullName>PCKO_Mktg_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup relationship to the Marketing person running the PC KO</description>
        <label>Sales KO Lead</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Waves5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <description>Region the wave is in</description>
        <formula>Wave_Cluster__r.Zone__r.Region__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Region the wave is in</inlineHelpText>
        <label>Region</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Support_APM_3__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The wave staffing fields are currently being updated. If you have questions or concerns regarding these fields, please contact innovation.support@the-challenge.org</inlineHelpText>
        <label>Support APM 3</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Waves5Usr</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Support_APM_4__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The wave staffing fields are currently being updated. If you have questions or concerns regarding these fields, please contact innovation.support@the-challenge.org</inlineHelpText>
        <label>Support APM 4</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Waves5Utp</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Support_APM_5__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Formally labelled &quot;Support APM 5&quot;. Updates Geographic Sharing Rules.</description>
        <inlineHelpText>The wave staffing fields are currently being updated. If you have questions or concerns regarding these fields, please contact innovation.support@the-challenge.org</inlineHelpText>
        <label>Programme Administrator 1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Waves5Uud</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Support_APM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The wave staffing fields are currently being updated. If you have questions or concerns regarding these fields, please contact innovation.support@the-challenge.org</inlineHelpText>
        <label>Support APM 1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Waves7</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Wave_APM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the APM for this wave</description>
        <inlineHelpText>The wave staffing fields are currently being updated. If you have questions or concerns regarding these fields, please contact innovation.support@the-challenge.org</inlineHelpText>
        <label>Wave APM</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Waves1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Wave_Cluster__c</fullName>
        <label>Cluster</label>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Waves</relationshipLabel>
        <relationshipName>Waves</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Wave_code__c</fullName>
        <description>Unique wave code</description>
        <inlineHelpText>Unique wave code</inlineHelpText>
        <label>Wave code</label>
        <length>25</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Zone__c</fullName>
        <description>Zone the wave is in</description>
        <formula>Wave_Cluster__r.Zone__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Zone the wave is in</inlineHelpText>
        <label>Zone</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>support_APM_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The wave staffing fields are currently being updated. If you have questions or concerns regarding these fields, please contact innovation.support@the-challenge.org</inlineHelpText>
        <label>Support APM 2</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Waves8</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Wave</label>
    <nameField>
        <label>Wave Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Waves</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Zone__c.object
<CustomObject>
    <description>TCN Zone (geographical area)</description>
    <fields>
        <fullName>Region__c</fullName>
        <description>Region the zone is part of</description>
        <inlineHelpText>The region this zones is part of</inlineHelpText>
        <label>Region</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Zones</relationshipLabel>
        <relationshipName>Zones</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Zone_code__c</fullName>
        <description>Zone&apos;s unique code</description>
        <inlineHelpText>Zone&apos;s unique code</inlineHelpText>
        <label>Zone code</label>
        <length>1</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Zone</label>
    <nameField>
        <label>Zone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TestUpdateWaveLeadGroups.cls
@istest
public class TestUpdateWaveLeadGroups{
    static testMethod void checkWaveLeads(){        
        Region__c Reg = new Region__c();
    	Reg.Name = 'London Region';
   		Reg.Region_code__c = 'L';
    	insert reg;
    
  	 	Zone__c Zon = new Zone__c();
  	 	Zon.Name = 'London Zone';
   		Zon.Region__c= Reg.Id;
        Zon.Zone_code__c= 'L';
   		insert Zon;
	    
        Cluster__c Clus = new Cluster__c();
        Clus.Name = 'BHARN';
        Clus.Cluster_code__c = 'L';
        Clus.Zone__c = Zon.Id;
        insert Clus;
        
        Group Gprog = new Group();
        Gprog.Name = 'Sharing Rules Prog London Zone';
        Insert Gprog;
        
        Group Gsales = new Group();
        Gsales.Name = 'Sharing Rules Sales London Zone';
        Insert Gsales;
        

        Wave__c wav = new Wave__c();
        Wav.Name = 'Summer wave 1';
        Wav.Wave_Cluster__c = Clus.id;
        Wav.Wave_code__c = 'W';
        Wav.PCKO_Mktg_Lead__c = '005C00000075H7L';
        Wav.Wave_APM__c = '005C0000003Ye0w';
        Wav.Support_APM__c = '005C00000075H7L';
        Wav.support_APM_2__c = '005C00000084trz';
        Wav.support_APM_3__c = '005C0000004bwe4';
        Wav.support_APM_4__c = '00580000001nuzY';
        Wav.support_APM_5__c = '005C00000044VE5';      
        insert Wav;
        
        Test.startTest();
        List<Id> IDS = new List<Id>();
        IDS.add(wav.Id);
        UpdateWaveLeadGroups LEADS = new UpdateWaveLeadGroups();
        UpdateWaveLeadGroups.waveleads(IDS);
        Test.stopTest();
        
        List<ID> Us = new list<ID>();  
        Us.add('005C00000075H7L');
        Us.add('005C0000003Ye0w');
        Us.add('005C00000084trz');
        Us.add('005C0000004bwe4');
        Us.add('00580000001nuzY');
        Us.add('005C00000044VE5');
        List<GroupMember> Mem = [SELECT ID,Group.Name, UserOrGroupId from GroupMember WHERE UserOrGroupId IN: Us AND Group.Name like '%London Zone%'];
        system.debug(Mem);
        system.debug(Mem.Size());
        System.assert(Mem.Size()==7);
        
    }

    
}