objects/Cluster__c.object
<CustomObject>
    <label>Cluster</label>
    <nameField>
        <label>Cluster Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clusters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Metric__c.object
<CustomObject>
    <description>Keeps the Contact and some detailed metrics</description>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                    <default>true</default>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Metrics</relationshipLabel>
        <relationshipName>Metrics</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Involved__c</fullName>
        <formula>IF(Big_Challenge_Day_Event_Attended__c +  CAT_Meetings_Attended__c +  YB_Meetings_Attended__c +  Local_Events_Attended__c +  Skill_Workshop_Attended__c +  Marketing_Ambassador_Events_Attended1__c +  Media_Ambassador_Events_Attended__c +  Staffing_Ambassador__c +  PC_Meetings_Attended__c +  Total_AM_SAM_Attendances__c +  Total_SignPosting_Oppty_Meetings_Attend__c &gt;= 1, &apos;Yes&apos;, &apos;No&apos; )</formula>
        <label>Involved</label>
        <type>Text</type>
    </fields>
    <label>Metric</label>
    <nameField>
        <displayFormat>M-{0000}</displayFormat>
        <label>Metric Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Metrics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Survey__c.object
<CustomObject>
    <description>Hold Survey data</description>
    <fields>
        <fullName>Borough_Areas__c</fullName>
        <label>Borough/Areas</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Barking &amp; Dagenham</fullName>
                </value>
                <value>
                    <fullName>Barnet</fullName>
                </value>
                <value>
                    <fullName>Bexley</fullName>
                </value>
                <value>
                    <fullName>Birmingham</fullName>
                </value>
                <value>
                    <fullName>Blackburn</fullName>
                </value>
                <value>
                    <fullName>Brent</fullName>
                </value>
                <value>
                    <fullName>Bromley</fullName>
                </value>
                <value>
                    <fullName>Burnley</fullName>
                </value>
                <value>
                    <fullName>Bury</fullName>
                </value>
                <value>
                    <fullName>Camden</fullName>
                </value>
                <value>
                    <fullName>City of London</fullName>
                </value>
                <value>
                    <fullName>Coventry</fullName>
                </value>
                <value>
                    <fullName>Croydon</fullName>
                </value>
                <value>
                    <fullName>Dudley</fullName>
                </value>
                <value>
                    <fullName>Ealing</fullName>
                </value>
                <value>
                    <fullName>Enfield</fullName>
                </value>
                <value>
                    <fullName>Greenwich</fullName>
                </value>
                <value>
                    <fullName>Hackney</fullName>
                </value>
                <value>
                    <fullName>Hammersmith &amp; Fulham</fullName>
                </value>
                <value>
                    <fullName>Haringey</fullName>
                </value>
                <value>
                    <fullName>Harrow</fullName>
                </value>
                <value>
                    <fullName>Havering</fullName>
                </value>
                <value>
                    <fullName>Hillingdon</fullName>
                </value>
                <value>
                    <fullName>Hounslow</fullName>
                </value>
                <value>
                    <fullName>Islington</fullName>
                </value>
                <value>
                    <fullName>Kensington &amp; Chelsea</fullName>
                </value>
                <value>
                    <fullName>Kingston</fullName>
                </value>
                <value>
                    <fullName>Lambeth</fullName>
                </value>
                <value>
                    <fullName>Lewisham</fullName>
                </value>
                <value>
                    <fullName>Manchester</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Cluster__c</fullName>
        <formula>IF( ISBLANK( Wave__c  ), Cluster_Wave_Not_Entered__c,Cluster_Wave_Entered__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Cluster</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Desire_to_remain_involved_0_10__c</fullName>
        <inlineHelpText>Survey Question: Would you want to get involved in a day like this again? (10 = yes definitely! 0 = no thanks)</inlineHelpText>
        <label>Desire to remain involved (0-10)</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Event_rating_0_10__c</fullName>
        <inlineHelpText>Survey Question: On a scale of 0 to 10 please rate the day</inlineHelpText>
        <label>Event rating (0-10)</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Wave_Summary__c</fullName>
        <label>Wave Summary</label>
        <referenceTo>Wave_Summary__c</referenceTo>
        <relationshipLabel>Surveys</relationshipLabel>
        <relationshipName>Surveys</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Survey</label>
    <nameField>
        <displayFormat>S-{YYYY}{MM}{00000}</displayFormat>
        <label>Survey Reference No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <recordTypes>
        <fullName>YP</fullName>
        <active>true</active>
        <label>YP</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Wave_Summary__c.object
<CustomObject>
    <description>Summarised Survey results for field.</description>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cluster</label>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Survey Summaries</relationshipLabel>
        <relationshipName>Survey_Summaries</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Survey Summary</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/BoroughController.cls
public class BoroughController {

        public String title {get; set;}
        public String boroughname {get; set;}
        public String boroughnamedecoded {get; set;}
        public String clusterid {get; set;}
        public List<Cluster__c> borough {get; set;}
        public List<Metric__c> involvedReports {get; set;}
        public List<Metric__c> activeReports {get; set;}
        public List<Survey__c> wantToRemains {get; set;} 
        public List<Survey__c> eventRatings {get; set;} 
        public Integer noInvolvedReports {get; set;}
        public Integer noActiveReports {get; set;}
        public Decimal percentageOfRemainings {get; set;}
        public Decimal averageRating {get; set;}
        public Cluster__c clustername{get; set;}
        
        public BoroughController(){
            
                boroughname =Encodingutil.urlEncode(ApexPages.currentPage().getparameters().get('Name'),'UTF-8');
                boroughnamedecoded = Encodingutil.urlDecode(boroughname,'UTF-8');
                clusterid = ApexPages.currentPage().getParameters().get('id');
                percentageOfRemainings = 0;
                averageRating = 0;
                getInvolvedReports();
                getRatios();
                clustername = [SELECT Name FROM Cluster__c WHERE Id =: clusterid];
        }       
                

        public List<Metric__c> getInvolvedReports(){

                involvedReports = [SELECT Involved__c FROM Metric__c WHERE Involved__c = 'Yes' AND Contact__r.Cluster__c =: clusterid AND Contact__r.Borough_area__c INCLUDES(:boroughnamedecoded)];
                activeReports = [SELECT Active__c FROM Metric__c WHERE Active__c = 'Yes' AND Contact__r.Cluster__c =: clusterid AND Contact__r.Borough_area__c INCLUDES(:boroughnamedecoded)];

                noInvolvedReports = involvedReports.size();
                noActiveReports = activeReports.size();
        
       return activeReports;
        }
        
        public List<Survey__c> getRatios(){
        
            List<Survey__c> remains = new List<Survey__c>();
            Decimal totalRatings=0;
            
            
                List<RecordType> r = [SELECT Id FROM RecordType WHERE SObjectType='Survey__c' AND Name='TCS event YP'];
                
                wantToRemains = [SELECT Desire_to_remain_involved_0_10__c, Event_rating_0_10__c FROM Survey__c WHERE Wave_Summary__r.Cluster__c =:clusterid AND Borough_Areas__c INCLUDES(:boroughnamedecoded) AND RecordTypeId =: r];
                
            if(wantToRemains.size()!=0){
                
                for(Integer i=0; i<wantToRemains.size(); i++)
                {
                        if(wantToRemains[i].Desire_to_remain_involved_0_10__c != null && 
                           wantToRemains[i].Desire_to_remain_involved_0_10__c>=7){
                                remains.add(wantToRemains[i]);
                        }
                        if(wantToRemains[i].Event_rating_0_10__c != null){
                        totalRatings += wantToRemains[i].Event_rating_0_10__c;
                        }
                }
                
                Decimal a = remains.size();
                Decimal b = wantToRemains.size();
                percentageOfRemainings = ((a/b)*100).setScale(1);
                averageRating = (totalRatings/Decimal.valueOf(wantToRemains.size())).setScale(1);
            }
              /*  eventRatings = [SELECT Event_rating_0_10__c FROM Survey__c WHERE Wave_Summary__r.Cluster__c =:clusterid AND Borough_Areas__c INCLUDES(:boroughnamedecoded) AND RecordTypeId =: r];
                
            if(eventRatings.size()!=0){
                for(Integer i=0; i<eventRatings.size(); i++){
                    totalRatings += eventRatings[i].Event_rating_0_10__c;
                }
                averageRating = (totalRatings/Decimal.valueOf(eventRatings.size())).setScale(1);
            }*/
                
        return wantToRemains;
        }
}