objects/Cluster__c.object
<CustomObject>
    <label>Cluster</label>
    <nameField>
        <label>Cluster Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clusters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Inclusion_Details__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Inclusion Details</relationshipLabel>
        <relationshipName>Inclusion_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>MASI_Source__c</fullName>
        <label>MASI Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Paper</fullName>
                </value>
                <value>
                    <fullName>Website</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OBS_P3_form_status__c</fullName>
        <label>OBS MASI form status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Started but not completed</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Season__c</fullName>
        <formula>Contact__r.NCS_Application_Primary_Season__c</formula>
        <label>Season</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Support_Level__c</fullName>
        <label>Support Level</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1 - no extra support</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>2 - medical conditions</fullName>
                </value>
                <value>
                    <fullName>3a - extra mentor support for learning difficulties</fullName>
                </value>
                <value>
                    <fullName>3b - extra mentor support for challenging behaviour or mental health conditions</fullName>
                </value>
                <value>
                    <fullName>4a – Extra APL support for YPs with restricted mobility, language barrier or learning difficulties</fullName>
                </value>
                <value>
                    <fullName>4b - extra APL support for challenging behaviour or mental health conditions</fullName>
                </value>
                <value>
                    <fullName>5.05 - support worker required, can share with another YP</fullName>
                </value>
                <value>
                    <fullName>5.1 - full-time support worker required</fullName>
                </value>
                <value>
                    <fullName>5.2 - requires 2 full time support workers</fullName>
                </value>
                <value>
                    <fullName>6 - case-by-case, potential non-accept</fullName>
                </value>
                <value>
                    <fullName>5b - personal coach required</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Which_wave_PIE_attending__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is a lookup field to the wave object so that Sales can identify which wave&apos;s Parent Information Evening (PIE) the Young Person is attending from the Inclusion Object</description>
        <label>Which wave PIE attending?</label>
        <referenceTo>Wave__c</referenceTo>
        <relationshipLabel>Inclusion Details</relationshipLabel>
        <relationshipName>Inclusion_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Inclusion Detail</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Inclusion Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inclusion Details</pluralLabel>
    <recordTypes>
        <fullName>Archived</fullName>
        <active>true</active>
        <description>Archived Inclusion Detail Information</description>
        <label>Archived</label>
    </recordTypes>
    <recordTypes>
        <fullName>Current</fullName>
        <active>true</active>
        <label>Current</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/NCS_Application__c.object
<CustomObject>
    <fields>
        <fullName>Active_season__c</fullName>
        <description>Pulls through the value of Active Season from the Season object</description>
        <formula>TEXT( Season__r.Active_season__c )</formula>
        <inlineHelpText>Pulls through the value of Active Season from the Season object</inlineHelpText>
        <label>Active season</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Assigned_wave__c</fullName>
        <formula>YoungPerson__r.Assigned_Wave__r.Name</formula>
        <label>Assigned wave</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_Email__c</fullName>
        <inlineHelpText>Updated via a workflow before sending out Telesales emails</inlineHelpText>
        <label>PG Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Season__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Season</label>
        <referenceTo>Season__c</referenceTo>
        <relationshipLabel>NCS Applications</relationshipLabel>
        <relationshipName>NCS_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Wave__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Wave</label>
        <referenceTo>Wave__c</referenceTo>
        <relationshipLabel>NCS Applications</relationshipLabel>
        <relationshipName>NCS_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>X18_Status__c</fullName>
        <label>18+ Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>18+ for entire season</fullName>
                </value>
                <value>
                    <fullName>Turns 18+ During Season</fullName>
                </value>
                <value>
                    <fullName>DOB OK</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>YoungPerson__c</fullName>
        <label>Young Person</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>NCS Applications</relationshipLabel>
        <relationshipName>NCS_Applications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>NCS Application</label>
    <nameField>
        <displayFormat>NCSA{000000}</displayFormat>
        <label>NCS Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NCS Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Season__c.object
<CustomObject>
    <description>NCS season</description>
    <fields>
        <fullName>Active_season__c</fullName>
        <label>Active season</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Oldest_Date_of_Birth_Possible_First_Wave__c</fullName>
        <label>Oldest Date of Birth Possible:FirstWave</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Oldest_date_of_birth__c</fullName>
        <label>Oldest date of birth</label>
        <type>Date</type>
    </fields>
    <label>Season</label>
    <nameField>
        <label>Season Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Seasons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Wave__c.object
<CustomObject>
    <fields>
        <fullName>Max_Number_of_SL5_allowed__c</fullName>
        <label>Max Number of SL5 allowed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Max_Number_of_SL_4a_allowed__c</fullName>
        <label>Max Number of SL 4a allowed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Max_Number_of_SL_4b_allowed__c</fullName>
        <label>Max Number of SL 4b allowed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Oldest_date_of_birth_possible__c</fullName>
        <description>Oldest DOB of YP to be able to go on this wave.</description>
        <label>Oldest date of birth possible</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Season__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Which season the wave is part of.  A look up to the Season object</description>
        <label>Season</label>
        <referenceTo>Season__c</referenceTo>
        <relationshipLabel>Waves</relationshipLabel>
        <relationshipName>Waves</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Wave_Cluster__c</fullName>
        <label>Cluster</label>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Waves</relationshipLabel>
        <relationshipName>Waves</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Wave_code__c</fullName>
        <description>Unique wave code</description>
        <inlineHelpText>Unique wave code</inlineHelpText>
        <label>Wave code</label>
        <length>25</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Wave</label>
    <nameField>
        <label>Wave Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Waves</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Test_updateSupportLevelAndHTR.cls
/*
@ Name : Test_updateSupportLevelAndHTR (Test Class)
@ Description : Unit testing of 'updateSupportLevelAndHTR' and 'updateSupportLevelOnContact'
@ Developer : Shaikh Saquib
@ Date : 27-Oct-2014
*/
@isTest
public class Test_updateSupportLevelAndHTR
{
    static testmethod void test_Method()
    {
                
        // Create new Account record
        Account testAccount = new Account(Name = 'TestAccount');
        insert testAccount;
        
        // Create new Season record
        Season__c testSeason1 = new Season__c(Name = 'TestSeason1',
                                              Active_Season__c = '1',
                                              Oldest_date_of_birth__c = Date.valueOf('2014-10-30'),
                                              Oldest_Date_of_Birth_Possible_First_Wave__c = Date.valueOf('2014-10-15'));
        insert testSeason1; 

        Recordtype YPRecType = [SELECT id, Name, SobjectType 
                                FROM Recordtype 
                                WHERE 
                                    SObjectType = 'Contact' 
                                AND 
                                    Name = 'Young Person'] ;
        
        // Create Contact record
        Contact testContact = new Contact(Account = testAccount,
                                          LastName = 'TestContact',
                                          BirthDate = Date.valueOf('2014-10-28'),
                                          Email = 'testContact@test.com',
                                          Gender__c = 'Male',
                                          Parent_Email__c = 'testContact@test.com',
                                          RecordTypeId = YPRecType.Id
                                          );
        insert testContact;
        
        // List of NCS Application
        List<NCS_Application__c> listNCSApplication = new List<NCS_Application__c>();
        
        //List<Contact> listContact = new List<Contact>();
                                                    
        
        
       /* for(integer count=0; count < 1; count++)
        {
            listContact.add( new Contact(Account = testAccount,
                                          LastName = 'TestContact ' + (count + 1),
                                          BirthDate = Date.valueOf('2014-10-28'),
                                          Email = 'testContact@test.com',
                                          Gender__c = 'Male',
                                          Parent_Email__c = 'testContact@test.com',
                                          RecordTypeId = YPRecType.Id
                                          ));
        }
        
        insert listContact;*/
        
        // Check new Contact record is inserted successfully
        Contact chkContact = [SELECT Name,RecordType.Name, RecordTypeId, 
                              (SELECT Id FROM Inclusion_Details__r
                              WHERE Recordtype.Name = 'Current' LIMIT 1)
                              FROM Contact 
                              WHERE Id = :testContact.Id];          
        
        // Create NCS Application records and add to listNCSApplication for Insertion
        for(integer count = 0; count < 1; count++)
        {              
            listNCSApplication.add(new NCS_Application__c(YoungPerson__c = chkContact.Id));                
        }
      
        
        if(!listNCSApplication.isEmpty())
        {
            insert listNCSApplication; 
        }
        
        // Fetch all NCS Application records inserted
        listNCSApplication = [SELECT Season__c, YoungPerson__c, X18_Status__c 
                              FROM NCS_Application__c 
                             ];
                   
        
        // Create new Cluster record
        Cluster__c testCluster = new Cluster__c(Name = 'testCluster');
        insert testCluster;
        System.debug('testCluster ::: ' + testCluster);
        
        // Create new Wave record
        Wave__c testWave = new Wave__c(Name = 'testWave',
                                      Wave_code__c = 'xyz',                                          
                                      Oldest_date_of_birth_possible__c = Date.valueOf('2014-10-25'),
                                      Wave_Cluster__c = testCluster.Id);
        insert testWave;
        System.debug('testWave ::: ' + testWave);
        
        Inclusion_Details__c inclusionDetailCurrentRecord = [SELECT Id, OBS_P3_form_status__c
                                                            FROM Inclusion_Details__c
                                                            WHERE 
                                                                Id = :chkContact.Inclusion_Details__r[0].Id
                                                            AND
                                                                Recordtype.Name = 'Current'];            
        
        // list Wave Selection records
        List<Wave_Selection__c> listWaveSelection = new List<Wave_Selection__c>();           
        
        
        // Create NCS Application records and add to listNCSApplication for Insertion
        for(integer count = 0; count < 1; count++)
        {
            listWaveSelection.add(new Wave_Selection__c(Young_Person__c = chkContact.Id,
                                                       Wave__c = testWave.Id,
                                                       Inclusion_Detail__c = inclusionDetailCurrentRecord.Id,
                                                       Status__c = 'Assigned',
                                                       NCS_Application__c = listNCSApplication[count].Id));
        } 

        Test.startTest(); 

        if(!listWaveSelection.isEmpty())
        {
            insert listWaveSelection;       
            
            inclusionDetailCurrentRecord.OBS_P3_form_status__c  = 'Started but not completed';
            inclusionDetailCurrentRecord.MASI_Source__c = 'Other';
            update inclusionDetailCurrentRecord;
           
            inclusionDetailCurrentRecord.OBS_P3_form_status__c  = 'Completed';
            //inclusionDetailCurrentRecord.Support_Level__c = '4b - extra APL support for challenging behaviour or mental health conditions';
            update inclusionDetailCurrentRecord;                                     
            
            Recordtype inclusionDetailArchivedType = [SELECT id, Name, SobjectType 
                                                      FROM Recordtype 
                                                      WHERE SObjectType = 'Inclusion_Details__c' 
                                                      AND Name = 'Archived'] ;
            System.assertEquals('Archived', inclusionDetailArchivedType.Name);
            
            // Create new Inclusion Detail Record
            Inclusion_Details__c inclusionDetailRecord = new Inclusion_Details__c(Contact__c = testContact.Id,
                                                                                  RecordtypeId = inclusionDetailArchivedType.Id);
            insert inclusionDetailRecord;     
            
            Recordtype inclusionDetailCurrentType = [SELECT id, Name, SobjectType 
                                      FROM Recordtype 
                                      WHERE SObjectType = 'Inclusion_Details__c' 
                                      AND Name = 'Current'] ;
            
            List<Inclusion_Details__c> listInclusionDetail = new List<Inclusion_Details__c>();              
            
            for(integer count =0; count < 1; count++)
            {
                listWaveSelection[count].Inclusion_Detail__c = chkContact.Inclusion_Details__r[0].Id;
            }
            
            update listWaveSelection;                

        }   
        
        chkContact.BirthDate = Date.valueOf('2014-10-25');
        update chkContact;
        
        System.debug('testContact ::: ' + chkContact);
        
        Test.stopTest(); 
        
        // Get the related list of NCS Application and Wave Selection
       /* chkContact = [SELECT RecordTypeId, RecordType.Name,
                      (SELECT Id FROM NCS_Applications__r),
                      (SELECT Id FROM Wave_Selections__r)
                      FROM Contact
                      WHERE 
                        Id = :testContact.Id];
        
        System.assertEquals('Young Person', chkContact.RecordType.Name); 
        
        // Fetch all NCS Application records inserted
        listWaveSelection = [SELECT X18__c, Wave__c FROM Wave_Selection__c WHERE Id IN :listWaveSelection];
        System.debug('chk listWaveSelection ::: ' + listWaveSelection);
        
        // Check new Wave Selection record is inserted successfully
        for(Wave_Selection__c waveSelctionRecord : listWaveSelection)
        {
            System.assertEquals(testWave.Id, waveSelctionRecord.Wave__c);
        }
           
        // Check new NCS Application record is inserted successfully
        listNCSApplication = [SELECT Season__c, X18_Status__c, YoungPerson__c FROM NCS_Application__c WHERE Season__c = :testSeason1.Id ];
        
        for(NCS_Application__c ncsAppRecord : listNCSApplication)
        {
            System.assertEquals('Turns 18+ During Season', ncsAppRecord.X18_Status__c);
        }*/
    }
    
    static testmethod void test_Method2()
    {
                  
        // Create new Account record
        Account testAccount = new Account(Name = 'TestAccount');
        insert testAccount;
        
        // Create new Season record
        Season__c testSeason1 = new Season__c(Name = 'TestSeason1',
                                              Active_Season__c = '1',
                                              Oldest_date_of_birth__c = Date.valueOf('2014-10-30'),
                                              Oldest_Date_of_Birth_Possible_First_Wave__c = Date.valueOf('2014-10-15'));
        insert testSeason1; 

        Recordtype YPRecType = [SELECT id, Name, SobjectType 
                                FROM Recordtype 
                                WHERE 
                                    SObjectType = 'Contact' 
                                AND 
                                    Name = 'Young Person'] ;
        
        // Create Contact record
        Contact testContact = new Contact(Account = testAccount,
                                          LastName = 'TestContact',
                                          BirthDate = Date.valueOf('2014-10-28'),
                                          Email = 'testContact@test.com',
                                          Gender__c = 'Male',
                                          Parent_Email__c = 'testContact@test.com',
                                          RecordTypeId = YPRecType.Id
                                          );
        insert testContact;
        
        // List of NCS Application
        List<NCS_Application__c> listNCSApplication = new List<NCS_Application__c>();
        
        //List<Contact> listContact = new List<Contact>();
                                                    
        
        
       /* for(integer count=0; count < 1; count++)
        {
            listContact.add( new Contact(Account = testAccount,
                                          LastName = 'TestContact ' + (count + 1),
                                          BirthDate = Date.valueOf('2014-10-28'),
                                          Email = 'testContact@test.com',
                                          Gender__c = 'Male',
                                          Parent_Email__c = 'testContact@test.com',
                                          RecordTypeId = YPRecType.Id
                                          ));
        }
        
        insert listContact;*/
    
        Recordtype inclusionDetailArchivedType = [SELECT id, Name, SobjectType 
                                                  FROM Recordtype 
                                                  WHERE SObjectType = 'Inclusion_Details__c' 
                                                  AND Name = 'Archived'] ;  
    
        Recordtype inclusionDetailCurrentType = [SELECT id, Name, SobjectType 
                                                  FROM Recordtype 
                                                  WHERE SObjectType = 'Inclusion_Details__c' 
                                                  AND Name = 'Current'] ;        
        
        // Check new Contact record is inserted successfully
        Contact chkContact = [SELECT Name,RecordType.Name, RecordTypeId, 
                              (SELECT Id FROM Inclusion_Details__r
                              WHERE Recordtype.Name = 'Current' LIMIT 1)
                              FROM Contact 
                              WHERE Id = :testContact.Id];          
          
    
        // Create NCS Application records and add to listNCSApplication for Insertion
        for(integer count = 0; count < 1; count++)
        {              
            listNCSApplication.add(new NCS_Application__c(YoungPerson__c = chkContact.Id));                
        }
      
        
        if(!listNCSApplication.isEmpty())
        {
            insert listNCSApplication; 
        }
        
        // Fetch all NCS Application records inserted
        listNCSApplication = [SELECT Season__c, YoungPerson__c, X18_Status__c 
                              FROM NCS_Application__c 
                             ];
                   
        
        // Create new Cluster record
        Cluster__c testCluster = new Cluster__c(Name = 'testCluster');
        insert testCluster;
        System.debug('testCluster ::: ' + testCluster);
        
        // Create new Wave record
        Wave__c testWave = new Wave__c(Name = 'testWave',
                                      Wave_code__c = 'xyz',                                          
                                      Oldest_date_of_birth_possible__c = Date.valueOf('2014-10-25'),
                                      Wave_Cluster__c = testCluster.Id);
        insert testWave;
        System.debug('testWave ::: ' + testWave);
        
        Inclusion_Details__c inclusionDetailCurrentRecord = [SELECT Id, OBS_P3_form_status__c
                                                            FROM Inclusion_Details__c
                                                            WHERE 
                                                                Id = :chkContact.Inclusion_Details__r[0].Id
                                                            AND
                                                                Recordtype.Name = 'Current'];            
        
        // list Wave Selection records
        List<Wave_Selection__c> listWaveSelection = new List<Wave_Selection__c>();           
        
        
        // Create NCS Application records and add to listNCSApplication for Insertion
        for(integer count = 0; count < 1; count++)
        {
            listWaveSelection.add(new Wave_Selection__c(Young_Person__c = chkContact.Id,
                                                       Wave__c = testWave.Id,
                                                       Inclusion_Detail__c = inclusionDetailCurrentRecord.Id,
                                                       Status__c = 'Assigned',
                                                       NCS_Application__c = listNCSApplication[count].Id));
        }  

        Test.startTest();

        if(!listWaveSelection.isEmpty())
        {
            insert listWaveSelection;       
           
            inclusionDetailCurrentRecord.RecordTypeId = inclusionDetailArchivedType.Id;                
            update inclusionDetailCurrentRecord;   
            System.assertEquals('Archived', inclusionDetailArchivedType.Name);                
            
            // Create new Inclusion Detail Record
            Inclusion_Details__c inclusionDetailRecord = new Inclusion_Details__c(Contact__c = testContact.Id,
                                                                                  OBS_P3_form_status__c  = 'Completed',
                                                                                  RecordtypeId = inclusionDetailCurrentType.Id,
                                                                                  MASI_Source__c = 'Other');
            insert inclusionDetailRecord;                                  
            
            for(integer count =0; count < 1; count++)
            {
                listWaveSelection[count].Inclusion_Detail__c = chkContact.Inclusion_Details__r[0].Id;
            }
            
            update listWaveSelection;  
            
            delete inclusionDetailRecord;
            
            inclusionDetailCurrentRecord.RecordTypeId = inclusionDetailCurrentType.Id;                
            update inclusionDetailCurrentRecord;  

        }   
        
        chkContact.BirthDate = Date.valueOf('2014-10-25');
        update chkContact;
        
        System.debug('testContact ::: ' + chkContact);
        Test.stopTest(); 
        
        
        // Get the related list of NCS Application and Wave Selection
       /* chkContact = [SELECT RecordTypeId, RecordType.Name,
                      (SELECT Id FROM NCS_Applications__r),
                      (SELECT Id FROM Wave_Selections__r)
                      FROM Contact
                      WHERE 
                        Id = :testContact.Id];
        
        System.assertEquals('Young Person', chkContact.RecordType.Name); 
        
        // Fetch all NCS Application records inserted
        listWaveSelection = [SELECT X18__c, Wave__c FROM Wave_Selection__c WHERE Id IN :listWaveSelection];
        System.debug('chk listWaveSelection ::: ' + listWaveSelection);
        
        // Check new Wave Selection record is inserted successfully
        for(Wave_Selection__c waveSelctionRecord : listWaveSelection)
        {
            System.assertEquals(testWave.Id, waveSelctionRecord.Wave__c);
        }
           
        // Check new NCS Application record is inserted successfully
        listNCSApplication = [SELECT Season__c, X18_Status__c, YoungPerson__c FROM NCS_Application__c WHERE Season__c = :testSeason1.Id ];
        
        for(NCS_Application__c ncsAppRecord : listNCSApplication)
        {
            System.assertEquals('Turns 18+ During Season', ncsAppRecord.X18_Status__c);
        }        */    
    }   
    
    static testmethod void testSupportLevelValidation1() {
        
        // Create new Account record
        Account testAccount = new Account(Name = 'TestAccount');
        insert testAccount;
        
        // Create new Season record
        Season__c testSeason1 = new Season__c(Name = 'TestSeason1',
                                              Active_Season__c = '1',
                                              Oldest_date_of_birth__c = Date.valueOf('2014-10-30'),
                                              Oldest_Date_of_Birth_Possible_First_Wave__c = Date.valueOf('2014-10-15'));
        insert testSeason1; 
        
        // Create new Cluster record
        Cluster__c testCluster = new Cluster__c(Name = 'testCluster');
        insert testCluster;
        System.debug('testCluster ::: ' + testCluster);
        
        // Create new Wave record
        Wave__c testWave = new Wave__c(Name = 'testWave',
                                      Wave_code__c = 'xyz',   
                                      Max_Number_of_SL_4a_allowed__c = 1,
                                      Oldest_date_of_birth_possible__c = Date.valueOf('2014-10-25'),
                                      Wave_Cluster__c = testCluster.Id);
        insert testWave;
        System.debug('testWave ::: ' + testWave);       
        
        Recordtype recTypeYP = [SELECT id, Name, SobjectType 
                                FROM Recordtype 
                                WHERE 
                                    SObjectType = 'Contact' 
                                AND 
                                    Name = 'Young Person'];
        
        // Create Contact record
        Contact testContact = new Contact(Account = testAccount,
                                          Assigned_Wave__c = testWave.Id,
                                          LastName = 'TestContact',
                                          BirthDate = Date.valueOf('2014-10-28'),
                                          Email = 'testContact@test.com',
                                          Gender__c = 'Male',
                                          Parent_Email__c = 'testContact@test.com',
                                          RecordTypeId = recTypeYP.Id
                                          );
        insert testContact; 
        Contact recContact = [SELECT Id FROM Contact LIMIT 1];
        
        Test.startTest();
        
        NCS_Application__c recNCSApp = [SELECT Id FROM NCS_Application__c LIMIT 1];
        System.assertNotEquals(null, recNCSApp);
        
        Inclusion_Details__c recIncDetail = [SELECT Id, Support_Level__c, Recordtype.Name 
                                            FROM Inclusion_Details__c 
                                            WHERE Contact__c = :recContact.Id
                                            LIMIT 1];
        
        /*Recordtype recTypeIncDetail = [SELECT id, Name, SobjectType 
                                        FROM Recordtype 
                                        WHERE 
                                            SObjectType = 'Inclusion_Details__c' 
                                        AND 
                                            Name = 'Current'] ;
        System.assertEquals(recTypeIncDetail.Name, recIncDetail.Recordtype.Name);*/ 
        
        // list Wave Selection records
        Wave_Selection__c recWaveSelection = new Wave_Selection__c(Young_Person__c = recContact.Id,
                                                                   Wave__c = testWave.Id,
                                                                   Inclusion_Detail__c = recIncDetail.Id,
                                                                   Status__c = 'Assigned',
                                                                   NCS_Application__c = recNCSApp.Id,
                                                                   Access_category_filter__c = '4a – Extra APL support for YPs with restricted mobility, language barrier or learning difficulties'); 
        insert recWaveSelection;    
        
        recIncDetail.Support_Level__c = '4a – Extra APL support for YPs with restricted mobility, language barrier or learning difficulties';
        
        try {
            update recIncDetail;
        }catch(System.DmlException  e) {
             for (Integer i = 0; i < e.getNumDml(); i++) {
                // Process exception here               
                System.debug('e.getDmlMessage(' + i + ') ::: ' + e.getDmlMessage(i)); 
            }                   
            //System.assertEquals('Prevents more than given amount of SL4as being assigned/reserved to a Wave', e.getDmlMessage());
        }
        
        Test.stopTest();        
    }   
    
    static testmethod void testSupportLevelValidation2() {
    
        
        // Create new Account record
        Account testAccount = new Account(Name = 'TestAccount');
        insert testAccount;
        
        // Create new Season record
        Season__c testSeason1 = new Season__c(Name = 'TestSeason1',
                                              Active_Season__c = '1',
                                              Oldest_date_of_birth__c = Date.valueOf('2014-10-30'),
                                              Oldest_Date_of_Birth_Possible_First_Wave__c = Date.valueOf('2014-10-15'));
        insert testSeason1; 
        
        // Create new Cluster record
        Cluster__c testCluster = new Cluster__c(Name = 'testCluster');
        insert testCluster;
        System.debug('testCluster ::: ' + testCluster);
        
        // Create new Wave record
        Wave__c testWave = new Wave__c(Name = 'testWave',
                                      Wave_code__c = 'xyz',   
                                      Max_Number_of_SL_4b_allowed__c = 1,
                                      Oldest_date_of_birth_possible__c = Date.valueOf('2014-10-25'),
                                      Wave_Cluster__c = testCluster.Id);
        insert testWave;
        System.debug('testWave ::: ' + testWave);       
        
        Recordtype recTypeYP = [SELECT id, Name, SobjectType 
                                FROM Recordtype 
                                WHERE 
                                    SObjectType = 'Contact' 
                                AND 
                                    Name = 'Young Person'];
        
        // Create Contact record
        Contact testContact = new Contact(Account = testAccount,
                                          Reserved_Wave__c = testWave.Id,
                                          LastName = 'TestContact',
                                          BirthDate = Date.valueOf('2014-10-28'),
                                          Email = 'testContact@test.com',
                                          Gender__c = 'Male',
                                          Parent_Email__c = 'testContact@test.com',
                                          RecordTypeId = recTypeYP.Id
                                          );
        insert testContact; 
        Contact recContact = [SELECT Id FROM Contact LIMIT 1];
        
        Test.startTest();
        
        NCS_Application__c recNCSApp = [SELECT Id FROM NCS_Application__c LIMIT 1];
        System.assertNotEquals(null, recNCSApp);
        
        Inclusion_Details__c recIncDetail = [SELECT Id, Support_Level__c, Recordtype.Name 
                                            FROM Inclusion_Details__c 
                                            WHERE Contact__c = :recContact.Id
                                            LIMIT 1];
        
        /*Recordtype recTypeIncDetail = [SELECT id, Name, SobjectType 
                                        FROM Recordtype 
                                        WHERE 
                                            SObjectType = 'Inclusion_Details__c' 
                                        AND 
                                            Name = 'Current'] ;
        System.assertEquals(recTypeIncDetail.Name, recIncDetail.Recordtype.Name);*/ 
        
        // list Wave Selection records
        Wave_Selection__c recWaveSelection = new Wave_Selection__c(Young_Person__c = recContact.Id,
                                                                   Wave__c = testWave.Id,
                                                                   Inclusion_Detail__c = recIncDetail.Id,
                                                                   Status__c = 'Reserved',
                                                                   NCS_Application__c = recNCSApp.Id,
                                                                   Access_category_filter__c = '4b - extra APL support for challenging behaviour or mental health conditions'); 
        insert recWaveSelection;    
        
        recIncDetail.Support_Level__c = '4b - extra APL support for challenging behaviour or mental health conditions';
        
        try {
            update recIncDetail;
        }catch(System.DmlException  e) {
             for (Integer i = 0; i < e.getNumDml(); i++) {
                // Process exception here               
                System.debug('e.getDmlMessage(' + i + ') ::: ' + e.getDmlMessage(i)); 
            }                   
            //System.assertEquals('Prevents more than given amount of SL4as being assigned/reserved to a Wave', e.getDmlMessage());
        }
        
        Test.stopTest();
    }   

    static testmethod void testSupportLevelValidation3() {
    
        
        // Create new Account record
        Account testAccount = new Account(Name = 'TestAccount');
        insert testAccount;
        
        // Create new Season record
        Season__c testSeason1 = new Season__c(Name = 'TestSeason1',
                                              Active_Season__c = '1',
                                              Oldest_date_of_birth__c = Date.valueOf('2014-10-30'),
                                              Oldest_Date_of_Birth_Possible_First_Wave__c = Date.valueOf('2014-10-15'));
        insert testSeason1; 
        
        // Create new Cluster record
        Cluster__c testCluster = new Cluster__c(Name = 'testCluster');
        insert testCluster;
        System.debug('testCluster ::: ' + testCluster);
        
        // Create new Wave record
        Wave__c testWave = new Wave__c(Name = 'testWave',
                                      Wave_code__c = 'xyz',   
                                      Max_Number_of_SL5_allowed__c = 1,
                                      Oldest_date_of_birth_possible__c = Date.valueOf('2014-10-25'),
                                      Wave_Cluster__c = testCluster.Id);
        insert testWave;
        System.debug('testWave ::: ' + testWave);       
        
        Recordtype recTypeYP = [SELECT id, Name, SobjectType 
                                FROM Recordtype 
                                WHERE 
                                    SObjectType = 'Contact' 
                                AND 
                                    Name = 'Young Person'];
        
        // Create Contact record
        Contact testContact = new Contact(Account = testAccount,
                                          Reserved_Wave__c = testWave.Id,
                                          LastName = 'TestContact',
                                          BirthDate = Date.valueOf('2014-10-28'),
                                          Email = 'testContact@test.com',
                                          Gender__c = 'Male',
                                          Parent_Email__c = 'testContact@test.com',
                                          RecordTypeId = recTypeYP.Id
                                          );
        insert testContact; 
        
        Contact recContact = [SELECT Id FROM Contact LIMIT 1];
        
        Test.startTest();
        
        NCS_Application__c recNCSApp = [SELECT Id FROM NCS_Application__c LIMIT 1];
        System.assertNotEquals(null, recNCSApp);
        
        Inclusion_Details__c recIncDetail = [SELECT Id, Support_Level__c, Recordtype.Name 
                                            FROM Inclusion_Details__c 
                                            WHERE Contact__c = :recContact.Id
                                            LIMIT 1];
        
        /*Recordtype recTypeIncDetail = [SELECT id, Name, SobjectType 
                                        FROM Recordtype 
                                        WHERE 
                                            SObjectType = 'Inclusion_Details__c' 
                                        AND 
                                            Name = 'Current'] ;
        System.assertEquals(recTypeIncDetail.Name, recIncDetail.Recordtype.Name);*/ 
        
        // list Wave Selection records
        Wave_Selection__c recWaveSelection = new Wave_Selection__c(Young_Person__c = recContact.Id,
                                                                   Wave__c = testWave.Id,
                                                                   Inclusion_Detail__c = recIncDetail.Id,
                                                                   Status__c = 'Reserved',
                                                                   NCS_Application__c = recNCSApp.Id,
                                                                   Access_category_filter__c = '5.1 - full-time support worker required'); 
        insert recWaveSelection;        
        
        recIncDetail.Support_Level__c = '5.1 - full-time support worker required';
        
        try {
            update recIncDetail;
        }catch(System.DmlException  e) {
             for (Integer i = 0; i < e.getNumDml(); i++) {
                // Process exception here               
                System.debug('e.getDmlMessage(' + i + ') ::: ' + e.getDmlMessage(i)); 
            }                   
            //System.assertEquals('Prevents more than given amount of SL4as being assigned/reserved to a Wave', e.getDmlMessage());
        }
        
        Test.stopTest();
    }
}