objects/Cluster__c.object
<CustomObject>
    <label>Cluster</label>
    <nameField>
        <label>Cluster Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clusters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Inclusion_Details__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Inclusion Details</relationshipLabel>
        <relationshipName>Inclusion_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>MASI_Source__c</fullName>
        <label>MASI Source</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>Paper</fullName>
                </value>
                <value>
                    <fullName>Website</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>OBS_P3_form_status__c</fullName>
        <label>OBS MASI form status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Started but not completed</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Season__c</fullName>
        <formula>Contact__r.NCS_Application_Primary_Season__c</formula>
        <label>Season</label>
        <type>Text</type>
    </fields>
    <label>Inclusion Detail</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Inclusion Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inclusion Details</pluralLabel>
    <recordTypes>
        <fullName>Archived</fullName>
        <active>true</active>
        <description>Archived Inclusion Detail Information</description>
        <label>Archived</label>
    </recordTypes>
    <recordTypes>
        <fullName>Current</fullName>
        <active>true</active>
        <label>Current</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/NCS_Application__c.object
<CustomObject>
    <fields>
        <fullName>Active_season__c</fullName>
        <description>Pulls through the value of Active Season from the Season object</description>
        <formula>TEXT( Season__r.Active_season__c )</formula>
        <inlineHelpText>Pulls through the value of Active Season from the Season object</inlineHelpText>
        <label>Active season</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_of_Birth_Approval__c</fullName>
        <label>Date of Birth Approval?</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Parent_Email__c</fullName>
        <inlineHelpText>Updated via a workflow before sending out Telesales emails</inlineHelpText>
        <label>PG Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Season__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Season</label>
        <referenceTo>Season__c</referenceTo>
        <relationshipLabel>NCS Applications</relationshipLabel>
        <relationshipName>NCS_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Wave__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Wave</label>
        <referenceTo>Wave__c</referenceTo>
        <relationshipLabel>NCS Applications</relationshipLabel>
        <relationshipName>NCS_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>YoungPerson__c</fullName>
        <label>Young Person</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>NCS Applications</relationshipLabel>
        <relationshipName>NCS_Applications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>NCS Application</label>
    <nameField>
        <displayFormat>NCSA{000000}</displayFormat>
        <label>NCS Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NCS Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Season__c.object
<CustomObject>
    <description>NCS season</description>
    <fields>
        <fullName>Active_season__c</fullName>
        <label>Active season</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Oldest_Date_of_Birth_Possible_First_Wave__c</fullName>
        <label>Oldest Date of Birth Possible:FirstWave</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Oldest_date_of_birth__c</fullName>
        <label>Oldest date of birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Youngest_date_of_birth__c</fullName>
        <label>Youngest date of birth</label>
        <type>Date</type>
    </fields>
    <label>Season</label>
    <nameField>
        <label>Season Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Seasons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Wave__c.object
<CustomObject>
    <fields>
        <fullName>Oldest_date_of_birth_possible__c</fullName>
        <description>Oldest DOB of YP to be able to go on this wave.</description>
        <label>Oldest date of birth possible</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Season__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Which season the wave is part of.  A look up to the Season object</description>
        <label>Season</label>
        <referenceTo>Season__c</referenceTo>
        <relationshipLabel>Waves</relationshipLabel>
        <relationshipName>Waves</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Wave_Cluster__c</fullName>
        <label>Cluster</label>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Waves</relationshipLabel>
        <relationshipName>Waves</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Wave_code__c</fullName>
        <description>Unique wave code</description>
        <inlineHelpText>Unique wave code</inlineHelpText>
        <label>Wave code</label>
        <length>25</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Wave</label>
    <nameField>
        <label>Wave Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Waves</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Test_update18PlusStatus.cls
/*
@ Name        : Test_update18PlusStatus (Test Class)
@ Description : Unit testing of 'update18PlusStatus' and 'update18PlusOnWaveSelection'
@ Developer   : Shaikh Saquib
@ Date        : 27-Oct-2014
*/
@isTest
public class Test_update18PlusStatus 
{
    static testmethod void testUpdate18PlusStatus()
    {                       
        // Create new Account record
        Account testAccount = new Account(Name = 'TestAccount');
        insert testAccount;
       
        // Create new Season record
        Season__c testSeason1 = new Season__c(Name = 'TestSeason1',
                                              Active_Season__c = '1');
        insert testSeason1;         
        
        List<Contact> listContact = new List<Contact>();
        for(integer count = 0; count < 50; count++)
        {              
            listContact.add(new Contact(Account = testAccount,
                                        LastName = 'TestContact',
                                        BirthDate = Date.valueOf('2014-10-05'),
                                        Email = 'testContact@test.com',
                                        Gender__c = 'Male',
                                        Parent_Email__c = 'testContact@test.com'));                
        }
        insert listContact;       
        
        Recordtype currentRecType = [SELECT id, Name, SobjectType 
                                    FROM Recordtype 
                                    WHERE 
                                        SObjectType = 'Inclusion_Details__c' 
                                    AND 
                                        Name = 'Current'];          
        
        // Create new Inclusion Detail Record
        List<Inclusion_Details__c> listInclusionDetails = new List<Inclusion_Details__c>();
        for(integer count = 0; count < 50; count++)
        {              
            listInclusionDetails.add(new Inclusion_Details__c(Contact__c = listContact[count].Id,
                                                              RecordTypeId = currentRecType.Id));                
        }
        insert listInclusionDetails;
        
        Season__c testSeason2 = new Season__c(Name = 'TestSeason2',
                                              Active_Season__c = '2',
                                              Oldest_Date_of_Birth_Possible_First_Wave__c = Date.valueOf('2014-10-10'));
        insert testSeason2; 
        
        // List of NCS Application
        List<NCS_Application__c> listNCSApplication = new List<NCS_Application__c>();       
        
        // Create NCS Application records and add to listNCSApplication for Insertion
        for(integer count = 0; count < 50; count++)
        {              
            listNCSApplication.add(new NCS_Application__c(YoungPerson__c = listContact[count].Id,
                                                          Season__c = testSeason2.Id));      
        }
        
        Test.startTest();       
        
        //Database.SaveResult[] srList = Database.insert(listNCSApplication, false);
        //System.debug('saveresult listNCSApplication ::: ' + srList);
            
        insert listNCSApplication;
            
        // Create new Cluster record
        Cluster__c testCluster = new Cluster__c(Name = 'testCluster');
        insert testCluster;
        System.debug('testCluster ::: ' + testCluster);
        
        // Create new Wave record
        Wave__c testWave = new Wave__c(Name = 'testWave',
                                       Wave_code__c = 'xyz',
                                       Oldest_date_of_birth_possible__c = Date.valueOf('2014-10-25'),
                                       Wave_Cluster__c = testCluster.Id);
        insert testWave;
        System.debug('testWave ::: ' + testWave);
        
        // list Wave Selection records
        Wave_Selection__c recWaveSelection = new Wave_Selection__c(Young_Person__c = listContact[0].Id,
                                                                    Wave__c = testWave.Id,
                                                                    Status__c = 'Waiting List',
                                                                    Inclusion_Detail__c = listInclusionDetails[0].Id,
                                                                    NCS_Application__c = listNCSApplication[0].Id);
        insert recWaveSelection;
        
        update listNCSApplication;        
        
        
        Test.stopTest();  
    }     
    
    static testmethod void testUpdate18PlusOnWaveSelectionHandler()
    {                       
        // Create new Account record
        Account testAccount = new Account(Name = 'TestAccount');
        insert testAccount;
       
        // Create new Season record
        Season__c testSeason1 = new Season__c(Name = 'TestSeason1',
                                              Active_Season__c = '1');
        insert testSeason1;  

        
        List<Contact> listContact = new List<Contact>();
        for(integer count = 0; count < 1; count++)
        {              
            listContact.add(new Contact(Account = testAccount,
                                        LastName = 'TestContact',
                                        BirthDate = Date.valueOf('2014-10-05'),
                                        Email = 'testContact@test.com',
                                        Gender__c = 'Male',
                                        Parent_Email__c = 'testContact@test.com'));                
        }
        insert listContact;       
        
        Recordtype currentRecType = [SELECT id, Name, SobjectType 
                                    FROM Recordtype 
                                    WHERE 
                                        SObjectType = 'Inclusion_Details__c' 
                                    AND 
                                        Name = 'Current'];  

        Recordtype archiveRecType = [SELECT id, Name, SobjectType 
                                    FROM Recordtype 
                                    WHERE 
                                        SObjectType = 'Inclusion_Details__c' 
                                    AND 
                                        Name = 'Archived'];                                     
        
        // Create new Inclusion Detail Record
        List<Inclusion_Details__c> listInclusionDetails = new List<Inclusion_Details__c>();
        listInclusionDetails.add(new Inclusion_Details__c(Contact__c = listContact[0].Id,
                                                          RecordTypeId = archiveRecType.Id));
        listInclusionDetails.add(new Inclusion_Details__c(Contact__c = listContact[0].Id,
                                                          RecordTypeId = currentRecType.Id));
        insert listInclusionDetails;
        
        Season__c testSeason2 = new Season__c(Name = 'TestSeason2',
                                              Active_Season__c = '2',
                                              Oldest_Date_of_Birth_Possible_First_Wave__c = Date.valueOf('2014-10-10'));
        insert testSeason2;     
        
        // List of NCS Application
        List<NCS_Application__c> listNCSApplication = new List<NCS_Application__c>();
        
        // Create NCS Application records and add to listNCSApplication for Insertion
        for(integer count = 0; count < 1; count++)
        {              
            listNCSApplication.add(new NCS_Application__c(YoungPerson__c = listContact[0].Id,
                                                          Season__c = testSeason2.Id));                
        }
        //Database.SaveResult[] srList = Database.insert(listNCSApplication, false);
        //System.debug('saveresult listNCSApplication ::: ' + srList);
            
        insert listNCSApplication;
        
        // Create new Cluster record
        Cluster__c testCluster = new Cluster__c(Name = 'testCluster');
        insert testCluster;
        System.debug('testCluster ::: ' + testCluster);
        
        // Create new Wave record
        Wave__c testWave = new Wave__c(Name = 'testWave',
                                       Wave_code__c = 'xyz',
                                       Oldest_date_of_birth_possible__c = Date.valueOf('2014-10-25'),
                                       Wave_Cluster__c = testCluster.Id);
        insert testWave;
        System.debug('testWave ::: ' + testWave);       
        
        Test.startTest(); 
        
        // list Wave Selection records
        List<Wave_Selection__c> listWaveSelection = new List<Wave_Selection__c>();
        for(integer count = 0; count < 210; count++)
        {              
            listWaveSelection.add(new Wave_Selection__c(Young_Person__c = listContact[0].Id,
                                                        Wave__c = testWave.Id,
                                                        Status__c = 'Waiting List',
                                                        Inclusion_Detail__c = listInclusionDetails[0].Id,
                                                        NCS_Application__c = listNCSApplication[0].Id));                
        }
        insert listWaveSelection;
        
        for(Wave_Selection__c recWaveSelection : listWaveSelection)
        {              
            recWaveSelection.Inclusion_Detail__c = listInclusionDetails[1].Id;
        }
        
        update listWaveSelection;          
        
        Test.stopTest();  
    }   
    
    static testmethod void testUpdate18PlusOnWaveSelectionHandler2()
    {                       
        // Create new Account record
        Account testAccount = new Account(Name = 'TestAccount');
        insert testAccount;
       
        // Create new Season record
        Season__c testSeason1 = new Season__c(Name = 'TestSeason1',
                                              Active_Season__c = '1',
                                              Oldest_Date_of_Birth_Possible_First_Wave__c = Date.valueOf('2014-10-10'));
        insert testSeason1;   
        
        List<Contact> listContact = new List<Contact>();
        for(integer count = 0; count < 1; count++)
        {              
            listContact.add(new Contact(Account = testAccount,
                                        LastName = 'TestContact',
                                        BirthDate = Date.valueOf('2014-10-05'),
                                        Email = 'testContact@test.com',
                                        Gender__c = 'Male',
                                        Parent_Email__c = 'testContact@test.com'));                
        }
        insert listContact;       
        
        Recordtype currentRecType = [SELECT id, Name, SobjectType 
                                    FROM Recordtype 
                                    WHERE 
                                        SObjectType = 'Inclusion_Details__c' 
                                    AND 
                                        Name = 'Current'];  

        Recordtype archiveRecType = [SELECT id, Name, SobjectType 
                                    FROM Recordtype 
                                    WHERE 
                                        SObjectType = 'Inclusion_Details__c' 
                                    AND 
                                        Name = 'Archived'];                                     
        
        // Create new Inclusion Detail Record
        List<Inclusion_Details__c> listInclusionDetails = new List<Inclusion_Details__c>();
        listInclusionDetails.add(new Inclusion_Details__c(Contact__c = listContact[0].Id,
                                                          RecordTypeId = archiveRecType.Id));
        listInclusionDetails.add(new Inclusion_Details__c(Contact__c = listContact[0].Id,
                                                          RecordTypeId = currentRecType.Id));
        insert listInclusionDetails;
        
        Season__c testSeason2 = new Season__c(Name = 'TestSeason2',
                                              Active_Season__c = '2',
                                              Oldest_Date_of_Birth_Possible_First_Wave__c = Date.valueOf('2014-10-10'));
        insert testSeason2;     
        
        // List of NCS Application
        List<NCS_Application__c> listNCSApplication = new List<NCS_Application__c>();
        
        // Create NCS Application records and add to listNCSApplication for Insertion
        for(integer count = 0; count < 1; count++)
        {              
            listNCSApplication.add(new NCS_Application__c(YoungPerson__c = listContact[0].Id,
                                                          Season__c = testSeason2.Id));                
        }
        //Database.SaveResult[] srList = Database.insert(listNCSApplication, false);
        //System.debug('saveresult listNCSApplication ::: ' + srList);
            
        insert listNCSApplication;
        
        // Create new Cluster record
        Cluster__c testCluster = new Cluster__c(Name = 'testCluster');
        insert testCluster;
        System.debug('testCluster ::: ' + testCluster);
        
        // Create new Wave record
        Wave__c testWave = new Wave__c(Name = 'testWave',
                                       Wave_code__c = 'xyz',
                                       Oldest_date_of_birth_possible__c = Date.valueOf('2014-10-25'),
                                       Wave_Cluster__c = testCluster.Id);
        insert testWave;
        System.debug('testWave ::: ' + testWave);       
        
        Test.startTest(); 
        
        // list Wave Selection records
        List<Wave_Selection__c> listWaveSelection = new List<Wave_Selection__c>();
        for(integer count = 0; count < 1; count++)
        {              
            listWaveSelection.add(new Wave_Selection__c(Young_Person__c = listContact[0].Id,
                                                        Wave__c = testWave.Id,
                                                        Status__c = 'Waiting List',
                                                        Inclusion_Detail__c = listInclusionDetails[0].Id,
                                                        NCS_Application__c = listNCSApplication[0].Id));                
        }
        insert listWaveSelection;
        
        for(Wave_Selection__c recWaveSelection : listWaveSelection)
        {              
            recWaveSelection.Inclusion_Detail__c = listInclusionDetails[1].Id;
        }
        
        update listWaveSelection;   
        
        listContact[0].BirthDate = Date.valueOf('2014-10-11');
        update listContact[0];         
        
        Test.stopTest();  
    }   
    
    static testmethod void testUpdate18PlusOnWaveSelectionHandler3()
    {                       
        // Create new Account record
        Account testAccount = new Account(Name = 'TestAccount');
        insert testAccount;
       
        // Create new Season record
        Season__c testSeason1 = new Season__c(Name = 'TestSeason1',
                                              Active_Season__c = '1',
                                              Oldest_Date_of_Birth_Possible_First_Wave__c = Date.valueOf('2014-10-01'),
                                              Oldest_date_of_birth__c = Date.valueOf('2014-10-10'));
        insert testSeason1;    
        
        List<Contact> listContact = new List<Contact>();
        for(integer count = 0; count < 1; count++)
        {              
            listContact.add(new Contact(Account = testAccount,
                                        LastName = 'TestContact',
                                        BirthDate = Date.valueOf('2014-10-05'),
                                        Email = 'testContact@test.com',
                                        Gender__c = 'Male',
                                        Parent_Email__c = 'testContact@test.com'));                
        }
        insert listContact;       
        
        Recordtype currentRecType = [SELECT id, Name, SobjectType 
                                    FROM Recordtype 
                                    WHERE 
                                        SObjectType = 'Inclusion_Details__c' 
                                    AND 
                                        Name = 'Current'];  

        Recordtype archiveRecType = [SELECT id, Name, SobjectType 
                                    FROM Recordtype 
                                    WHERE 
                                        SObjectType = 'Inclusion_Details__c' 
                                    AND 
                                        Name = 'Archived'];                                     
        
        // Create new Inclusion Detail Record
        List<Inclusion_Details__c> listInclusionDetails = new List<Inclusion_Details__c>();
        listInclusionDetails.add(new Inclusion_Details__c(Contact__c = listContact[0].Id,
                                                          RecordTypeId = archiveRecType.Id));
        listInclusionDetails.add(new Inclusion_Details__c(Contact__c = listContact[0].Id,
                                                          RecordTypeId = currentRecType.Id));
        insert listInclusionDetails;

        Season__c testSeason2 = new Season__c(Name = 'TestSeason2',
                                              Active_Season__c = '2',
                                              Oldest_Date_of_Birth_Possible_First_Wave__c = Date.valueOf('2014-10-10'));
        insert testSeason2;
        
        // List of NCS Application
        List<NCS_Application__c> listNCSApplication = new List<NCS_Application__c>();
        
        // Create NCS Application records and add to listNCSApplication for Insertion
        for(integer count = 0; count < 1; count++)
        {              
            listNCSApplication.add(new NCS_Application__c(YoungPerson__c = listContact[0].Id,
                                                          Season__c = testSeason2.Id));                
        }
        //Database.SaveResult[] srList = Database.insert(listNCSApplication, false);
        //System.debug('saveresult listNCSApplication ::: ' + srList);
            
        insert listNCSApplication;
        
        // Create new Cluster record
        Cluster__c testCluster = new Cluster__c(Name = 'testCluster');
        insert testCluster;
        System.debug('testCluster ::: ' + testCluster);
        
        // Create new Wave record
        Wave__c testWave = new Wave__c(Name = 'testWave',
                                       Wave_code__c = 'xyz',
                                       Oldest_date_of_birth_possible__c = Date.valueOf('2014-10-25'),
                                       Wave_Cluster__c = testCluster.Id);
        insert testWave;
        System.debug('testWave ::: ' + testWave);       
        
        Test.startTest(); 
        
        // list Wave Selection records
        List<Wave_Selection__c> listWaveSelection = new List<Wave_Selection__c>();
        for(integer count = 0; count < 1; count++)
        {              
            listWaveSelection.add(new Wave_Selection__c(Young_Person__c = listContact[0].Id,
                                                        Wave__c = testWave.Id,
                                                        Status__c = 'Waiting List',
                                                        Inclusion_Detail__c = listInclusionDetails[0].Id,
                                                        NCS_Application__c = listNCSApplication[0].Id));                
        }
        insert listWaveSelection;
        
        for(Wave_Selection__c recWaveSelection : listWaveSelection)
        {              
            recWaveSelection.Inclusion_Detail__c = listInclusionDetails[1].Id;
        }
        
        update listWaveSelection;        
        
        Test.stopTest();  
    }   
    
    static testmethod void testUpdate18PlusOnWaveSelectionHandler4()
    {                       
        // Create new Account record
        Account testAccount = new Account(Name = 'TestAccount');
        insert testAccount;
       
        // Create new Season record
        Season__c testSeason1 = new Season__c(Name = 'TestSeason1',
                                              Active_Season__c = '1',
                                              Oldest_Date_of_Birth_Possible_First_Wave__c = Date.valueOf('2014-10-01'),
                                              Oldest_date_of_birth__c = Date.valueOf('2014-10-10'),
                                              Youngest_date_of_birth__c = Date.valueOf('2014-10-01'));
        insert testSeason1; 
        
        List<Contact> listContact = new List<Contact>();
        for(integer count = 0; count < 1; count++)
        {              
            listContact.add(new Contact(Account = testAccount,
                                        LastName = 'TestContact',
                                        BirthDate = Date.valueOf('2014-10-05'),
                                        Email = 'testContact@test.com',
                                        Gender__c = 'Male',
                                        Parent_Email__c = 'testContact@test.com'));                
        }
        insert listContact;       
        
        Recordtype currentRecType = [SELECT id, Name, SobjectType 
                                    FROM Recordtype 
                                    WHERE 
                                        SObjectType = 'Inclusion_Details__c' 
                                    AND 
                                        Name = 'Current'];  

        Recordtype archiveRecType = [SELECT id, Name, SobjectType 
                                    FROM Recordtype 
                                    WHERE 
                                        SObjectType = 'Inclusion_Details__c' 
                                    AND 
                                        Name = 'Archived'];                                     
        
        // Create new Inclusion Detail Record
        List<Inclusion_Details__c> listInclusionDetails = new List<Inclusion_Details__c>();
        listInclusionDetails.add(new Inclusion_Details__c(Contact__c = listContact[0].Id,
                                                          RecordTypeId = archiveRecType.Id));
        listInclusionDetails.add(new Inclusion_Details__c(Contact__c = listContact[0].Id,
                                                          RecordTypeId = currentRecType.Id));
        insert listInclusionDetails;
        
        Season__c testSeason2 = new Season__c(Name = 'TestSeason2',
                                              Active_Season__c = '2',
                                              Oldest_Date_of_Birth_Possible_First_Wave__c = Date.valueOf('2014-10-10'));
        insert testSeason2;         
        
        // List of NCS Application
        List<NCS_Application__c> listNCSApplication = new List<NCS_Application__c>();
        
        // Create NCS Application records and add to listNCSApplication for Insertion
        for(integer count = 0; count < 1; count++)
        {              
            listNCSApplication.add(new NCS_Application__c(YoungPerson__c = listContact[0].Id,
                                                          Season__c = testSeason2.Id));                
        }
        //Database.SaveResult[] srList = Database.insert(listNCSApplication, false);
        //System.debug('saveresult listNCSApplication ::: ' + srList);
            
        insert listNCSApplication;
        
        // Create new Cluster record
        Cluster__c testCluster = new Cluster__c(Name = 'testCluster');
        insert testCluster;
        System.debug('testCluster ::: ' + testCluster);
        
        // Create new Wave record
        Wave__c testWave = new Wave__c(Name = 'testWave',
                                       Wave_code__c = 'xyz',
                                       Oldest_date_of_birth_possible__c = Date.valueOf('2014-10-25'),
                                       Wave_Cluster__c = testCluster.Id);
        insert testWave;
        System.debug('testWave ::: ' + testWave);       
        
        Test.startTest(); 
        
        // list Wave Selection records
        List<Wave_Selection__c> listWaveSelection = new List<Wave_Selection__c>();
        for(integer count = 0; count < 1; count++)
        {              
            listWaveSelection.add(new Wave_Selection__c(Young_Person__c = listContact[0].Id,
                                                        Wave__c = testWave.Id,
                                                        Status__c = 'Waiting List',
                                                        Inclusion_Detail__c = listInclusionDetails[0].Id,
                                                        NCS_Application__c = listNCSApplication[0].Id));                
        }
        insert listWaveSelection;
        
        for(Wave_Selection__c recWaveSelection : listWaveSelection)
        {              
            recWaveSelection.Inclusion_Detail__c = listInclusionDetails[1].Id;
        }
        
        update listWaveSelection;        
        
        Test.stopTest();  
    }       
    
    static testmethod void testUpdate18PlusOnWaveSelectionHandler5()
    {                       
        // Create new Account record
        Account testAccount = new Account(Name = 'TestAccount');
        insert testAccount;
       
        // Create new Season record
        Season__c testSeason1 = new Season__c(Name = 'TestSeason1',
                                              Active_Season__c = '1',
                                              Oldest_Date_of_Birth_Possible_First_Wave__c = Date.valueOf('2014-10-01'),
                                              Oldest_date_of_birth__c = Date.valueOf('2014-10-10'),
                                              Youngest_date_of_birth__c = Date.valueOf('2014-10-01'));
        insert testSeason1;   

        List<Contact> listContact = new List<Contact>();
        for(integer count = 0; count < 1; count++)
        {              
            listContact.add(new Contact(Account = testAccount,
                                        LastName = 'TestContact',
                                        BirthDate = Date.valueOf('2014-10-05'),
                                        Email = 'testContact@test.com',
                                        Gender__c = 'Male',
                                        Parent_Email__c = 'testContact@test.com'));                
        }
        insert listContact;       
        
        Recordtype currentRecType = [SELECT id, Name, SobjectType 
                                    FROM Recordtype 
                                    WHERE 
                                        SObjectType = 'Inclusion_Details__c' 
                                    AND 
                                        Name = 'Current'];  

        Recordtype archiveRecType = [SELECT id, Name, SobjectType 
                                    FROM Recordtype 
                                    WHERE 
                                        SObjectType = 'Inclusion_Details__c' 
                                    AND 
                                        Name = 'Archived'];                                     
        
        // Create new Inclusion Detail Record
        List<Inclusion_Details__c> listInclusionDetails = new List<Inclusion_Details__c>();
        listInclusionDetails.add(new Inclusion_Details__c(Contact__c = listContact[0].Id,
                                                          RecordTypeId = archiveRecType.Id));
        listInclusionDetails.add(new Inclusion_Details__c(Contact__c = listContact[0].Id,
                                                          RecordTypeId = currentRecType.Id));
        insert listInclusionDetails;
        
        Season__c testSeason2 = new Season__c(Name = 'TestSeason2',
                                              Active_Season__c = '2',
                                              Oldest_Date_of_Birth_Possible_First_Wave__c = Date.valueOf('2014-10-10'));
        insert testSeason2;         
        
        // List of NCS Application
        List<NCS_Application__c> listNCSApplication = new List<NCS_Application__c>();
        
        // Create NCS Application records and add to listNCSApplication for Insertion
        for(integer count = 0; count < 1; count++)
        {              
            listNCSApplication.add(new NCS_Application__c(YoungPerson__c = listContact[0].Id,
                                                          Season__c = testSeason2.Id));                
        }
        //Database.SaveResult[] srList = Database.insert(listNCSApplication, false);
        //System.debug('saveresult listNCSApplication ::: ' + srList);
            
        insert listNCSApplication;
        
        // Create new Cluster record
        Cluster__c testCluster = new Cluster__c(Name = 'testCluster');
        insert testCluster;
        System.debug('testCluster ::: ' + testCluster);
        
        // Create new Wave record
        Wave__c testWave = new Wave__c(Name = 'testWave',
                                       Wave_code__c = 'xyz',
                                       Oldest_date_of_birth_possible__c = Date.valueOf('2014-10-25'),
                                       Wave_Cluster__c = testCluster.Id);
        insert testWave;
        System.debug('testWave ::: ' + testWave);       
        
        Test.startTest(); 
        
        // list Wave Selection records
        List<Wave_Selection__c> listWaveSelection = new List<Wave_Selection__c>();
        for(integer count = 0; count < 1; count++)
        {              
            listWaveSelection.add(new Wave_Selection__c(Young_Person__c = listContact[0].Id,
                                                        Wave__c = testWave.Id,
                                                        Status__c = 'Waiting List',
                                                        Inclusion_Detail__c = listInclusionDetails[0].Id,
                                                        NCS_Application__c = listNCSApplication[0].Id));                
        }
        insert listWaveSelection;
        
        listNCSApplication[0].Date_of_Birth_Approval__c = Date.valueOf('2014-11-10');
        update listNCSApplication;
        
        Test.stopTest();  
    }       
    
    static testmethod void testUpdate18PlusOnWaveSelectionHandler6()
    {                       
        // Create new Account record
        Account testAccount = new Account(Name = 'TestAccount');
        insert testAccount;
       
        // Create new Season record
        Season__c testSeason1 = new Season__c(Name = 'TestSeason1',
                                              Active_Season__c = '1',
                                              Oldest_Date_of_Birth_Possible_First_Wave__c = Date.valueOf('2014-10-01'),
                                              Oldest_date_of_birth__c = Date.valueOf('2014-10-10'),
                                              Youngest_date_of_birth__c = Date.valueOf('2014-10-01'));
        insert testSeason1;  
        
        List<Contact> listContact = new List<Contact>();
        for(integer count = 0; count < 1; count++)
        {              
            listContact.add(new Contact(Account = testAccount,
                                        LastName = 'TestContact',
                                        BirthDate = Date.valueOf('2014-10-05'),
                                        Email = 'testContact@test.com',
                                        Gender__c = 'Male',
                                        Parent_Email__c = 'testContact@test.com'));                
        }
        insert listContact;       
        
        Recordtype currentRecType = [SELECT id, Name, SobjectType 
                                    FROM Recordtype 
                                    WHERE 
                                        SObjectType = 'Inclusion_Details__c' 
                                    AND 
                                        Name = 'Current'];  

        Recordtype archiveRecType = [SELECT id, Name, SobjectType 
                                    FROM Recordtype 
                                    WHERE 
                                        SObjectType = 'Inclusion_Details__c' 
                                    AND 
                                        Name = 'Archived'];                                     
        
        // Create new Inclusion Detail Record
        List<Inclusion_Details__c> listInclusionDetails = new List<Inclusion_Details__c>();
        listInclusionDetails.add(new Inclusion_Details__c(Contact__c = listContact[0].Id,
                                                          RecordTypeId = archiveRecType.Id));
        listInclusionDetails.add(new Inclusion_Details__c(Contact__c = listContact[0].Id,
                                                          RecordTypeId = currentRecType.Id));
        insert listInclusionDetails;
        
        Season__c testSeason2 = new Season__c(Name = 'TestSeason2',
                                              Active_Season__c = '2',
                                              Oldest_Date_of_Birth_Possible_First_Wave__c = Date.valueOf('2014-10-10'));
        insert testSeason2;         
        
        // List of NCS Application
        List<NCS_Application__c> listNCSApplication = new List<NCS_Application__c>();
        
        // Create NCS Application records and add to listNCSApplication for Insertion
        for(integer count = 0; count < 1; count++)
        {              
            listNCSApplication.add(new NCS_Application__c(YoungPerson__c = listContact[0].Id,
                                                          Season__c = testSeason2.Id));                
        }
        //Database.SaveResult[] srList = Database.insert(listNCSApplication, false);
        //System.debug('saveresult listNCSApplication ::: ' + srList);
            
        insert listNCSApplication;
        
        // Create new Cluster record
        Cluster__c testCluster = new Cluster__c(Name = 'testCluster');
        insert testCluster;
        System.debug('testCluster ::: ' + testCluster);
        
        // Create new Wave record
        Wave__c testWave = new Wave__c(Name = 'testWave',
                                       Wave_code__c = 'xyz',
                                       Oldest_date_of_birth_possible__c = Date.valueOf('2014-10-25'),
                                       Wave_Cluster__c = testCluster.Id);
        insert testWave;
        System.debug('testWave ::: ' + testWave);       
        
        Test.startTest(); 
        
        // list Wave Selection records
        List<Wave_Selection__c> listWaveSelection = new List<Wave_Selection__c>();
        for(integer count = 0; count < 1; count++)
        {              
            listWaveSelection.add(new Wave_Selection__c(Young_Person__c = listContact[0].Id,
                                                        Wave__c = testWave.Id,
                                                        Status__c = 'Waiting List',
                                                        Inclusion_Detail__c = listInclusionDetails[0].Id,
                                                        NCS_Application__c = listNCSApplication[0].Id));                
        }
        insert listWaveSelection;
        
        listInclusionDetails[0].OBS_P3_form_status__c = 'Completed';
        listInclusionDetails[0].MASI_Source__c = 'Other';
        update listInclusionDetails;
        
        Test.stopTest();  
    }  
    /*
    static testmethod void testContact()
    {                       
        // Create new Account record
        Account testAccount = new Account(Name = 'TestAccount');
        insert testAccount;
       
        // Create new Season record
        Season__c testSeason1 = new Season__c(Name = 'TestSeason1',
                                              Active_Season__c = '1',
                                              Oldest_Date_of_Birth_Possible_First_Wave__c = Date.valueOf('2014-10-01'),
                                              Oldest_date_of_birth__c = Date.valueOf('2014-10-10'),
                                              Youngest_date_of_birth__c = Date.valueOf('2014-10-01'));
        insert testSeason1;       
        
        Recordtype YPRecType = [SELECT id, Name, SobjectType 
                                FROM Recordtype 
                                WHERE 
                                    SObjectType = 'Contact' 
                                AND 
                                    Name = 'Young Person'] ;       
        
        List<Contact> listContact = new List<Contact>();
        for(integer count = 0; count < 5000; count++)
        {              
            listContact.add(new Contact(Account = testAccount,
                                        LastName = 'TestContact',
                                        BirthDate = Date.valueOf('2014-10-05'),
                                        Email = 'testContact@test.com',
                                        Gender__c = 'Male',
                                        RecordTypeId = YPRecType.Id,
                                        Parent_Email__c = 'testContact@test.com'));                
        }            
      
        
        Test.startTest(); 
            insert listContact;          
        Test.stopTest();  
    }      */
    
             
}