objects/Cluster__c.object
<CustomObject>
    <fields>
        <fullName>Zone__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Zone the cluster is part of</description>
        <inlineHelpText>The zone this cluster is part of</inlineHelpText>
        <label>Zone</label>
        <referenceTo>Zone__c</referenceTo>
        <relationshipLabel>Clusters</relationshipLabel>
        <relationshipName>Clusters</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Cluster</label>
    <nameField>
        <label>Cluster Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clusters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Job__c.object
<CustomObject>
    <description>Each individual job listed, including summer-long roles for each cluster, per wave roles for each wave and cluster</description>
    <fields>
        <fullName>Staffing_Zone__c</fullName>
        <label>Staffing Zone</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>West</fullName>
                </value>
                <value>
                    <fullName>North</fullName>
                </value>
                <value>
                    <fullName>East</fullName>
                </value>
                <value>
                    <fullName>Midlands</fullName>
                </value>
                <value>
                    <fullName>North West</fullName>
                </value>
                <value>
                    <fullName>South</fullName>
                </value>
                <value>
                    <fullName>SSH &amp; Black Country</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Wave_Number__c</fullName>
        <formula>Wave__r.Wave_number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Wave Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Wave__c</fullName>
        <label>Wave</label>
        <referenceTo>Wave__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Zone__c</fullName>
        <formula>Wave__r.Wave_Cluster__r.Zone__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Zone</label>
        <type>Text</type>
    </fields>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Job_Application__c.object
<CustomObject>
    <fields>
        <fullName>Assignment_end_date__c</fullName>
        <formula>today()</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Assignment end date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Cluster_selected__c</fullName>
        <formula>IF( RecordTypeId = &quot;012C0000000QBBE&quot;, TEXT( Training_location__c ), 
IF(RecordTypeId = &quot;012C0000000QCjZ&quot;,  Contact__r.School_s_cluster__c , 
IF(OR(RecordTypeId = &quot;012C0000000QFyh&quot;, RecordTypeId = &quot;012C0000000QO3L&quot;,RecordTypeId = &quot;012C0000000QFyc&quot;)

, &quot;2014 MRK&quot;, 

IF(OR(RecordTypeId = &quot;012C0000000QYFD&quot;, RecordTypeId = &quot;012C0000000QYFE&quot;,RecordTypeId = &quot;012C0000000QZxW&quot;)

,&quot;BlackCountry&quot;,

IF( App_form_page_3_complete__c  =TRUE,

IF(ISPICKVAL(Contact__r.Cluster_2012__c,&quot;&quot;),&quot;&quot;,
&quot;2016 &quot;&amp;TEXT(Contact__r.Cluster_2012__c))
,&quot;&quot;)

))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Cluster selected</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Job Applications</relationshipLabel>
        <relationshipName>Job_Applications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Staffing_Zone__c</fullName>
        <formula>TEXT(Contact__r.Staffing_Zone__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Staffing Zone</label>
        <type>Text</type>
    </fields>
    <label>Job Application</label>
    <nameField>
        <displayFormat>JA-2016-{0000}</displayFormat>
        <label>Job Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Job_placement__c.object
<CustomObject>
    <description>Used to assign an applicant to a Job</description>
    <fields>
        <fullName>Assignment_start_date__c</fullName>
        <description>2015 Formula can be found here:

https://drive.google.com/a/the-challenge.org/file/d/0B8U5IDmhTO3eb0l5TXJwSjdMQjg/view?usp=sharing</description>
        <formula>IF(
NOT(CONTAINS( RecordType.Name ,&quot;2016&quot;)),
Job__r.Wave__r.PC_KO_day__c,

IF( CONTAINS(RecordType.Name , &quot;Ad hoc&quot;), 
Ad_hoc_start_date__c , 

IF(RecordType.Name = &quot;(S)AM 2016&quot;, 
IF(ISPICKVAL ( Job__r.Wave__r.Wave_Model_Staffing__c , &quot;Pilot&quot;), 
  Job__r.Wave__r.TC_KO_day__c   , Job__r.Wave__r.RCD_start_date__c ), 


IF( CONTAINS(RecordType.Name , &quot;Grad&quot;), 
Job__r.Wave__r.Graduation_Date__c , 

IF(OR( 
ISPICKVAL( Role__c , &quot;Programme Leader&quot;), 
ISPICKVAL( Role__c , &quot;Assistant Programme Leader&quot;), 
ISPICKVAL( Role__c , &quot;Senior Mentor&quot;), 
ISPICKVAL( Role__c , &quot;Support Worker&quot;), 
ISPICKVAL( Role__c , &quot;Personal Coach&quot;)), 
Job__r.Wave__r.PC_KO_day__c, 

IF(ISPICKVAL( Role__c , &quot;Senior Community Facilitator&quot;), 
Job__r.Wave__r.RCD_start_date__c , 

IF(ISPICKVAL( Role__c , &quot;Residential Mentor&quot;), 
Job__r.Wave__r.TC_KO_day__c, 

IF(CONTAINS( TEXT(Role__c), &quot;Practitioner&quot;), 
IF( ISPICKVAL( Job__r.Wave__r.Wave_Model_Staffing__c , &quot;Pilot&quot;) , 
Job__r.Wave__r.TC_KO_day__c, Job__r.Wave__r.TC_KO_day__c+2), 

IF(ISBLANK( Ad_hoc_start_date__c) , 

IF(CONTAINS( RecordType.Name , &quot;RCA 1&quot;), 
IF(ISPICKVAL( Job__r.Wave__r.September_RCA_weekends__c , &quot;Saturday&quot;), 
Job__r.RCA_1_Sat__c , Job__r.RCA_1_Sun__c ), 

IF(CONTAINS( RecordType.Name , &quot;RCA 2&quot;), 
IF(ISPICKVAL( Job__r.Wave__r.September_RCA_weekends__c , &quot;Saturday&quot;), 
Job__r.RCA_2_Sat__c , Job__r.RCA_2_Sun__c ), 

IF(CONTAINS( RecordType.Name , &quot;RCA 3&quot;), 
IF(ISPICKVAL( Job__r.Wave__r.September_RCA_weekends__c , &quot;Saturday&quot;), 
Job__r.RCA_3_Sat__c , Job__r.RCA_3_Sun__c ), 

IF(CONTAINS( RecordType.Name , &quot;RCA 4&quot;), 
IF(ISPICKVAL( Job__r.Wave__r.September_RCA_weekends__c , &quot;Saturday&quot;), 
Job__r.RCA_4_Sat__c , Job__r.RCA_4_Sun__c ), 

NULL)))), 


Ad_hoc_start_date__c)))))))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Assignment start date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup relationship between Job Placement and Related Contact</description>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Summer staff, YP, YP2010, YP2012, YP2012A, TCS Mentor 2012, YP2013</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Job placements</relationshipLabel>
        <relationshipName>Job_placements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Job_Application__c</fullName>
        <label>Job Application</label>
        <referenceTo>Job_Application__c</referenceTo>
        <relationshipLabel>Job placements</relationshipLabel>
        <relationshipName>Job_placements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Job__c</fullName>
        <description>Role (including wave and cluster where necessary)</description>
        <label>Job</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Job__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>Wave-long roles 2014</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Job__c</referenceTo>
        <relationshipLabel>Job placements</relationshipLabel>
        <relationshipName>Job_placements</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Wave__c</fullName>
        <formula>Job__r.Wave__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Wave</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Wave_number__c</fullName>
        <formula>Job__r.Wave__r.Wave_number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Wave number</label>
        <type>Text</type>
    </fields>
    <label>Job placement</label>
    <nameField>
        <displayFormat>JP-2016-{00000}</displayFormat>
        <label>Job placement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job placements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Team__c.object
<CustomObject>
    <fields>
        <fullName>Wave_Number__c</fullName>
        <formula>Wave__r.Wave_number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Wave Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Wave__c</fullName>
        <label>Wave</label>
        <referenceTo>Wave__c</referenceTo>
        <relationshipLabel>Teams</relationshipLabel>
        <relationshipName>Teams</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Wave__c.object
<CustomObject>
    <fields>
        <fullName>All_Girl_Wave__c</fullName>
        <description>Tick when wave is an all girl wave</description>
        <label>All Girl Wave?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>No</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Yes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Wave_Cluster__c</fullName>
        <label>Cluster</label>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Waves</relationshipLabel>
        <relationshipName>Waves</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Wave_number__c</fullName>
        <label>Wave number</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zone__c</fullName>
        <description>Zone the wave is in</description>
        <formula>Wave_Cluster__r.Zone__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Zone the wave is in</inlineHelpText>
        <label>Zone</label>
        <type>Text</type>
    </fields>
    <label>Wave</label>
    <nameField>
        <label>Wave Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Waves</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/AVNDL_Job_Placement_DateClash_Handler.cls
public with sharing class AVNDL_Job_Placement_DateClash_Handler {
public static boolean working=false;  
public void checkDateClashes(List<Job_placement__c> confirmedJps){
  working=true;
    List<String> confirmedJpIDs=new List<String>(); 
    List<String> confirmedJpContactIDs=new List<String>(); 
    List<String> confirmedJpsWaveIds=new List<String> ();
    Map<Id,Job_placement__c> triggerListMap=new Map<Id,Job_placement__c>();
    system.debug('******confirmedJps********'+confirmedJps);
    for(Job_placement__c jp:confirmedJps){
      confirmedJpIDs.add(jp.Id);
      triggerListMap.put(jp.Id,jp);
    }
    
    List<Job_placement__c> confirmedJPwithAllFields=new List<Job_placement__c >( [Select Job__r.Wave__r.All_Girl_Wave__c,Job_Application__r.Cluster_selected__c,Job__r.Wave__r.Wave_Number__c,Job__r.Wave__r.Wave_Cluster__r.Zone__r.Name,Job__r.Wave__r.Wave_Cluster__r.Name ,Contact__r.Staffing_Zone__c,Id,Job__r.Wave__r.Name,Job__r.Wave__r.Id,Contact__r.Id,Contact__r.name,Assignment_start_date__c,Assignment_end_date__c,Contact__r.Gender__c,Name,Status__c,Role__c,Team_lookup__r.Name,Team_lookup__r.Team__c,Job__r.Wave__c From Job_placement__c Where Id IN : confirmedJpIDs] );
    system.debug('*******confirmedJPwithAllFields**********'+confirmedJPwithAllFields);
    
      for(Job_placement__c jp:confirmedJPwithAllFields){
      confirmedJpsWaveIds.add(jp.Job__r.Wave__c);
      confirmedJpContactIDs.add(jp.Contact__c);
    }
    
    
    system.debug('*****WaveIds'+confirmedJpsWaveIds); 
     List<Role__c> allRoles=[Select Id,Name,Min_number_of_rest_days__c From Role__c Where Freeze_Role__c!=true ];
    
    
    
    Map <String,Integer> roleMinRestDays=new Map <String,Integer>();
    
    Map<id,Job_placement__c> clashedJPsToUpdate=new Map<id,Job_placement__c>();
      
    for(Role__c role:allRoles){
            system.debug('*****Min_number_of_rest_days__c*****'+role.Min_number_of_rest_days__c+'******'+role.name);
            if(role.Min_number_of_rest_days__c != null){
                roleMinRestDays.put(role.name,Integer.valueof(role.Min_number_of_rest_days__c));
            }
            else{
                roleMinRestDays.put(role.name,0);
            }
     }
  
  
      
        List<Job_placement__c> temprelatedList=new List<Job_placement__c>();
        
        temprelatedList= new List<Job_placement__c>([Select Clashed_JPs__c,Job__r.Wave__r.All_Girl_Wave__c,Job_Application__r.Cluster_selected__c,Job__r.Wave__r.Wave_Number__c,Job__r.Wave__r.Wave_Cluster__r.Zone__r.Name,Job__r.Wave__r.Wave_Cluster__r.Name ,Contact__r.Staffing_Zone__c,Id,Job__r.Wave__r.Name,Job__r.Wave__r.Id,Contact__r.Id,Contact__r.name,Assignment_start_date__c,Assignment_end_date__c,Contact__r.Gender__c,Name,Status__c,Role__c,Team_lookup__r.Name,Team_lookup__r.Team__c,Job__r.Wave__c From Job_placement__c Where  (Contact__r.Id IN : confirmedJpContactIDs AND ID NOT IN:confirmedJpIDs ) OR (Job__r.Wave__c IN:confirmedJpsWaveIds AND ID NOT IN:confirmedJpIDs) ORDER BY Job__r.Wave__r.Wave_Number__c ]);
      
        Map<Id,Job_placement__c> tempRelatedMap=new Map<Id,Job_placement__c>();
        Map<Id,List<Job_placement__c>> tempRelatedListMap=new Map<Id,List<Job_placement__c>>();
          Map<Id,List<Job_placement__c>> tempSameWaveListMap=new Map<Id,List<Job_placement__c>>();
        
        for(Job_Placement__c tjp:temprelatedList){
                
                tempRelatedMap.put(tjp.Id,tjp);
                if(tempRelatedListMap.get(tjp.Contact__c)==null){
                List<Job_placement__c> tempList=new List<Job_placement__c>();
                tempList.add(tjp);  
                tempRelatedListMap.put(tjp.Contact__c,tempList);
                }
                else{
                tempRelatedListMap.get(tjp.Contact__c).add(tjp);
                }
                if(tempSameWaveListMap.get(tjp.Job__r.Wave__c)==null) {
                List<Job_placement__c> tempWaveList=new List<Job_placement__c>();
                tempWaveList.add(tjp);  
                tempSameWaveListMap.put(tjp.Job__r.Wave__c,tempWaveList);
                }
                else{
                   tempSameWaveListMap.get(tjp.Job__r.Wave__c).add(tjp);
                }
        }
  system.debug('*******SameWaveMap :'+tempSameWaveListMap);
    for(Job_placement__c confirmedJp:confirmedJPwithAllFields){
    String teamName;
    Boolean cannotAllocate=false;
          if(confirmedJp.Team_lookup__r.Name==null){
            teamName='';
              }
            else{
                teamName=confirmedJp.Team_lookup__r.Name;
    
            }
  
    if(tempRelatedListMap.get(confirmedJp.contact__c)!=null){
    for(Job_placement__c relatedJP:tempRelatedListMap.get(confirmedJp.contact__c)){
        if((triggerListMap.get(confirmedJp.Id).Status__c=='Confirmed' && (relatedJP.Status__c=='Selected as preference' ||   relatedJP.Status__c=='On back-up list')) || (triggerListMap.get(confirmedJp.Id).Status__c=='Selected as preference' && (relatedJP.Status__c=='Not available (date clash)'))){    
                                Boolean clash=false;
                                
                                system.debug('******confirmedJpEndDate:'+confirmedJp.Assignment_end_date__c);
                                system.debug('******confirmedJpStartDate:'+confirmedJp.Assignment_start_date__c);
                                system.debug('******confirmedJpStartDate:'+confirmedJp.Id);
                                system.debug('******relatedJPEndDate:'+relatedJP.Assignment_end_date__c);
                                system.debug('******relatedJPStartDate:'+relatedJP.Assignment_start_date__c);
                                system.debug('******relatedJPID:'+relatedJP.ID);
                                system.debug('******roleMinRestDays**********'+roleMinRestDays.get(relatedJP.Role__c));
                                if(confirmedJp.Assignment_end_date__c.daysBetween(relatedJP.Assignment_end_date__c)<0){//selected end date bigger than related 
                                    if(roleMinRestDays.get(relatedJP.Role__c) != null){
                                        if(relatedJP.Assignment_end_date__c.addDays(roleMinRestDays.get(relatedJP.Role__c))> confirmedJp.Assignment_start_date__c  ){
                                            clash=true;
                                        }
                                    }
                                    else{
                                        if(relatedJP.Assignment_end_date__c>confirmedJp.Assignment_start_date__c){
                                            clash=true;
                                        }
                                    }                                   
                                }
                                else if(confirmedJp.Assignment_end_date__c.daysBetween(relatedJP.Assignment_end_date__c)>0){//selected end date lesser than related 
                                                                        if(confirmedJp.Assignment_end_date__c.addDays(roleMinRestDays.get(confirmedJp.Role__c))> relatedJP.Assignment_start_date__c  ){
                                                                                                clash=true;
                                                                                        }       
                                }
                                else if(confirmedJp.Assignment_end_date__c==relatedJP.Assignment_end_date__c){//selected end date equals related 
                                        clash=true;
                                
                                }
                                else{
                                        clash=false;
                                }

                            if(clash){//date clash check
                              if(triggerListMap.get(confirmedJp.Id).Status__c=='Confirmed'){
                                        relatedJP.Status__c='Not available (date clash)';
                                        if(relatedJp.Clashed_JPs__c!=null && relatedJp.Clashed_JPs__c!='' && relatedJp.Clashed_JPs__c!='null'){
                                        relatedJp.Clashed_JPs__c=relatedJp.Clashed_JPs__c+confirmedJp.Id+',';
                                        }
                                        else{
                                        relatedJp.Clashed_JPs__c=confirmedJp.Id+',';
                                        }
                                        relatedJP.Team_lookup__c=null;
                                        clashedJPsToUpdate.put(relatedJP.id,relatedJP);
                              }
                              if(triggerListMap.get(confirmedJp.Id).Status__c=='Selected as preference'){
                                triggerListMap.get(confirmedJp.Id).Team_lookup__c=null;
                                List <String> clashedIds=new List<String>();
                                if(relatedJp.Clashed_JPs__c!=null && relatedJp.Clashed_JPs__c!='' ){
                                clashedIds=relatedJp.Clashed_JPs__c.split(',',0); 
                                }
                                   Integer clashCount=0; 
                                   String newClashedIds='';
                                   for(Integer i=0;i<clashedIds.size();i++){
                                     system.debug('*****clashedId'+clashedIds[i]);
                                     if(!(clashedIds[i]=='null' || clashedIds[i]==null ||  clashedIds[i]=='') ){
                                     if(clashedIds[i]!=confirmedJp.Id){
                                     newClashedIds=newClashedIds+clashedIds[i]+',';
                                     clashCount++;
                                     }
                                     }
                                   }
                                   
                                   triggerListMap.get(confirmedJp.ID).Team_lookup__c=null;
                                   if(clashCount==0){
                                   relatedJP.Status__c='Selected as preference';
                                   
                                        relatedJP.Team_lookup__c=null;
                                   }
                                   else{
                                   
                                   }
                                   relatedJp.Clashed_JPs__c=newClashedIds;
                                        clashedJPsToUpdate.put(relatedJP.id,relatedJP);
                                   
                              }

                                    }
      }

    }
    }
}

database.update( clashedJPsToUpdate.values(),false);
working=false; 
}


}