objects/Cluster__c.object
<CustomObject>
    <label>Cluster</label>
    <nameField>
        <label>Cluster Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clusters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/HR_Event__c.object
<CustomObject>
    <fields>
        <fullName>Cluster1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cluster</label>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>HR Events</relationshipLabel>
        <relationshipName>HR_Events</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Event_Date__c</fullName>
        <label>Event start date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MaxAttendee__c</fullName>
        <label>MaxAttendee</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Role_to_be_assessed1__c</fullName>
        <description>The field label has been changed for consistency. API name has remained the same. This field is used in booking form</description>
        <label>Roles to invite</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Programme Leader</fullName>
                </value>
                <value>
                    <fullName>Assistant Programme Leader</fullName>
                </value>
                <value>
                    <fullName>Senior Mentor</fullName>
                </value>
                <value>
                    <fullName>Community Facilitator</fullName>
                </value>
                <value>
                    <fullName>Support Worker</fullName>
                </value>
                <value>
                    <fullName>Residential Mentor</fullName>
                </value>
                <value>
                    <fullName>Practitioner Plus</fullName>
                </value>
                <value>
                    <fullName>Practitioner - Drama</fullName>
                </value>
                <value>
                    <fullName>Practitioner - Enterprise</fullName>
                </value>
                <value>
                    <fullName>Practitioner - Sport</fullName>
                </value>
                <value>
                    <fullName>Practitioner - Photography</fullName>
                </value>
                <value>
                    <fullName>Practitioner - Media</fullName>
                </value>
                <value>
                    <fullName>Project Volunteer</fullName>
                </value>
                <value>
                    <fullName>Senior Associate Mentor</fullName>
                </value>
                <value>
                    <fullName>Associate Mentor</fullName>
                </value>
                <value>
                    <fullName>Youth Board Member</fullName>
                </value>
                <value>
                    <fullName>TCS Mentor</fullName>
                </value>
                <value>
                    <fullName>The Challenge Academy</fullName>
                </value>
                <value>
                    <fullName>Personal Coach</fullName>
                </value>
                <value>
                    <fullName>Practitioner - Music</fullName>
                </value>
                <value>
                    <fullName>Logistics Officer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Roles_to_be_assessed__c</fullName>
        <description>Originally called &quot;Roles to be assessed&quot; but changed for consistency. API name is still the same as this field is used in the visual force booking form</description>
        <label>Roles to invite (OLD)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Programme Leader</fullName>
                </value>
                <value>
                    <fullName>Assistant Programme Leader</fullName>
                </value>
                <value>
                    <fullName>Senior Mentor</fullName>
                </value>
                <value>
                    <fullName>Community Mentor</fullName>
                </value>
                <value>
                    <fullName>Support Worker</fullName>
                </value>
                <value>
                    <fullName>Logs Officer</fullName>
                </value>
                <value>
                    <fullName>Residential Accommodation Manager</fullName>
                </value>
                <value>
                    <fullName>Practitioner Plus</fullName>
                </value>
                <value>
                    <fullName>Practitioner - Drama</fullName>
                </value>
                <value>
                    <fullName>Practitioner - Enterprise</fullName>
                </value>
                <value>
                    <fullName>Practitioner - Sport</fullName>
                </value>
                <value>
                    <fullName>Practitioner - Photography</fullName>
                </value>
                <value>
                    <fullName>Practitioner - Media</fullName>
                </value>
                <value>
                    <fullName>Senior Associate Mentor</fullName>
                </value>
                <value>
                    <fullName>Associate Mentor</fullName>
                </value>
                <value>
                    <fullName>Youth Board Member</fullName>
                </value>
                <value>
                    <fullName>TCS Mentor</fullName>
                </value>
                <value>
                    <fullName>The Challenge Academy</fullName>
                </value>
                <value>
                    <fullName>Personal Coach</fullName>
                </value>
                <value>
                    <fullName>Project Volunteer</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Staff_type__c</fullName>
        <label>Staff type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Core Staff</fullName>
                </value>
                <value>
                    <fullName>New Application</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Returner</fullName>
                </value>
                <value>
                    <fullName>Returner - different role</fullName>
                </value>
                <value>
                    <fullName>Returner - same role</fullName>
                </value>
                <value>
                    <fullName>Returner - lower role</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>HR Event</label>
    <nameField>
        <label>HR Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>HR Events</pluralLabel>
    <recordTypes>
        <fullName>Assessment</fullName>
        <active>true</active>
        <label>Assessment</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Job_Application__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Job Applications</relationshipLabel>
        <relationshipName>Job_Applications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Role_to_assess_for__c</fullName>
        <description>Previously called &quot;Role to assess for&quot;, this field label has been changed to make it more intuitive. This is the field that assessment and training booking emails use, so the value has to be changed depending on applicant&apos;s status</description>
        <label>Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Programme Leader</fullName>
                </value>
                <value>
                    <fullName>Assistant Programme Leader</fullName>
                </value>
                <value>
                    <fullName>Senior Mentor</fullName>
                </value>
                <value>
                    <fullName>Community Facilitator</fullName>
                </value>
                <value>
                    <fullName>Senior Community Facilitator</fullName>
                </value>
                <value>
                    <fullName>Residential Mentor</fullName>
                </value>
                <value>
                    <fullName>Support Worker</fullName>
                </value>
                <value>
                    <fullName>Personal Coach</fullName>
                </value>
                <value>
                    <fullName>Practitioner Plus</fullName>
                </value>
                <value>
                    <fullName>Practitioner - Drama</fullName>
                </value>
                <value>
                    <fullName>Practitioner - Enterprise</fullName>
                </value>
                <value>
                    <fullName>Practitioner - Sport</fullName>
                </value>
                <value>
                    <fullName>Practitioner - Photography</fullName>
                </value>
                <value>
                    <fullName>Practitioner - Media</fullName>
                </value>
                <value>
                    <fullName>Practitioner - Music</fullName>
                </value>
                <value>
                    <fullName>Practitioner - Art</fullName>
                </value>
                <value>
                    <fullName>Logistics Officer</fullName>
                </value>
                <value>
                    <fullName>Project Volunteer</fullName>
                </value>
                <value>
                    <fullName>Senior Associate Mentor</fullName>
                </value>
                <value>
                    <fullName>Associate Mentor</fullName>
                </value>
                <value>
                    <fullName>Youth Board Member</fullName>
                </value>
                <value>
                    <fullName>TCS Mentor</fullName>
                </value>
                <value>
                    <fullName>The Challenge Academy</fullName>
                </value>
                <value>
                    <fullName>Residential Accommodation Manager</fullName>
                </value>
                <value>
                    <fullName>Delivery Assistant Programme Manager</fullName>
                </value>
                <value>
                    <fullName>Programme Administrator</fullName>
                </value>
                <value>
                    <fullName>Practitioner</fullName>
                </value>
                <value>
                    <fullName>Learning and Behaviour Mentor</fullName>
                </value>
                <value>
                    <fullName>Social Inclusion Associate</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Staff_type__c</fullName>
        <inlineHelpText>Shows the staff type for this person. Default is &quot;New Application&quot;. More than 1 type is possible.</inlineHelpText>
        <label>Staff type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Agency staff</fullName>
                </value>
                <value>
                    <fullName>Core Staff</fullName>
                </value>
                <value>
                    <fullName>Franchise - London Youth</fullName>
                </value>
                <value>
                    <fullName>Limited Company</fullName>
                </value>
                <value>
                    <fullName>New Application</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Returner</fullName>
                </value>
                <value>
                    <fullName>Returner - different role</fullName>
                </value>
                <value>
                    <fullName>Returner - same role</fullName>
                </value>
                <value>
                    <fullName>Volunteer</fullName>
                </value>
                <value>
                    <fullName>Returner - lower role</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Job Application</label>
    <nameField>
        <displayFormat>JA-2016-{0000}</displayFormat>
        <label>Job Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TestAvailableDates.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class TestAvailableDates {

    static testMethod void unitTestAvailableDates() {
        
        Contact contact=new Contact();
        contact.Email='test@test.com';
      	contact.Cluster_2012__c='West London 2011';
        contact.LastName='testt';
        insert contact;
        system.assertNotEquals(null, contact.id);
            
        List<Cluster__c>clList=new List<Cluster__c>();
        Cluster__c cl1=new Cluster__c(Name='West London 2011');
        Cluster__c cl2=new Cluster__c(Name='Birmingham');
        clList.add(cl1);
        clList.add(cl2);
        insert clList;
        
        RecordType eventRT=[Select Id FROM RecordType 
                            WHERE SObjectType='HR_Event__c' 
                            AND Name='Assessment'];
                            
        List<HR_Event__c> eventList=new List<HR_Event__c>();
        HR_Event__c HRevent=new HR_Event__c();
        HRevent.Name='Event1';
        HRevent.Event_Date__c = System.today()+1;
        HRevent.RecordTypeId=eventRT.Id;
        HRevent.Cluster1__c=cl1.Id;
        HRevent.Roles_to_be_assessed__c='Programme Leader';
        HRevent.MaxAttendee__c=1;
        HRevent.Staff_type__c ='Returner';
        eventList.add(HRevent);
        
        HR_Event__c HRevent2=new HR_Event__c();
        HRevent2.Name='Event2';
        HRevent2.Event_Date__c = System.today()+1;
        HRevent2.RecordTypeId=eventRT.Id;
        HRevent2.Cluster1__c=cl1.Id;
        HRevent2.Role_to_be_assessed1__c='Programme Leader';
        HRevent2.MaxAttendee__c=5;
        HRevent2.Staff_type__c = 'Returner';
        eventList.add(HRevent2);
        
        insert eventList;
        
        
        Job_Application__c JobApplication=new Job_Application__c();
        JobApplication.Contact__c=contact.Id;
        //JobApplication.Cluster__c=cl1.Id;
        JobApplication.Role_to_assess_for__c='Programme Leader';
        JobApplication.Staff_type__c='test';
        insert JobApplication;
        
        PageReference DummyPage=new PageReference('/AvailableDates?key='+contact.Id+'&Type=1&JType='+JobApplication.Id);
        Test.setCurrentPage(DummyPage);
        
       
        AvailableDates ad=new AvailableDates();
        ad.SelectedId=HRevent2.Id;
        
        for(AvailableDates.EventWrapper ew:ad.eventWrapperList){
            ew.EventItem=HRevent2;
            ew.Selected=true;
            break;
        }
        ad.GrabSelected();
        ad.SaveChoice();
        ad.SaveChoice();
        ad.isAvailable=true;
        ad.SelectedId=null;
        ad.SaveChoice();
        
        ad.DisableRadiButton();
        ad.SaveChoice();
        
    }
   
}