objects/Cluster__c.object
<CustomObject>
    <label>Cluster</label>
    <nameField>
        <label>Cluster Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clusters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Metric__c.object
<CustomObject>
    <description>Keeps the Contact and some detailed metrics</description>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Metrics</relationshipLabel>
        <relationshipName>Metrics</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Total_SignPosting_Oppty_Meetings_Attend__c</fullName>
        <defaultValue>0</defaultValue>
        <label>#Total SignPosting Oppty Meetings Attend</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Metric</label>
    <nameField>
        <displayFormat>M-{0000}</displayFormat>
        <label>Metric Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Metrics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/TCS_Attendance_record__c.object
<CustomObject>
    <description>Links Volunteering Opportunity and Contact to track YP attendances</description>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>TCS Attendance records</relationshipLabel>
        <relationshipName>TCS_Attendance_records</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Meetings_attended_Dec__c</fullName>
        <inlineHelpText>Select the number of meetings attended to date in the months of November and December</inlineHelpText>
        <label>Meetings attended: Nov - Dec</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Volunteering_Opportunity__c</fullName>
        <label>Signposting Opportunity</label>
        <referenceTo>Volunteering_Opportunity__c</referenceTo>
        <relationshipLabel>TCS Attendance records</relationshipLabel>
        <relationshipName>TCS_Attendance_records</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>TCS Attendance record</label>
    <nameField>
        <displayFormat>TCS-{000000}</displayFormat>
        <label>TCS Attendance record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TCS Attendance records</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Volunteering_Opportunity__c.object
<CustomObject>
    <description>A custom object to use for signposting YPs into different types of opportunity.</description>
    <fields>
        <fullName>Approx_number_of_volunteering_places__c</fullName>
        <description>Field used to record the number of opportunities uploaded.  This will then be used as our end of year metric.</description>
        <inlineHelpText>Please give a rough number of how many young people could take up this opportunity.</inlineHelpText>
        <label>Approx number of volunteering places</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Borough_area_this_applies_to__c</fullName>
        <label>Borough/area this applies to</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Barking &amp; Dagenham</fullName>
                </value>
                <value>
                    <fullName>Barnet</fullName>
                </value>
                <value>
                    <fullName>Bexley</fullName>
                </value>
                <value>
                    <fullName>Birmingham</fullName>
                </value>
                <value>
                    <fullName>Blackburn</fullName>
                </value>
                <value>
                    <fullName>Brent</fullName>
                </value>
                <value>
                    <fullName>Bromley</fullName>
                </value>
                <value>
                    <fullName>Burnley</fullName>
                </value>
                <value>
                    <fullName>Bury</fullName>
                </value>
                <value>
                    <fullName>Camden</fullName>
                </value>
                <value>
                    <fullName>City of London</fullName>
                </value>
                <value>
                    <fullName>Coventry</fullName>
                </value>
                <value>
                    <fullName>Croydon</fullName>
                </value>
                <value>
                    <fullName>CSE Birmingham</fullName>
                </value>
                <value>
                    <fullName>CSW Birmingham</fullName>
                </value>
                <value>
                    <fullName>Dudley</fullName>
                </value>
                <value>
                    <fullName>Ealing</fullName>
                </value>
                <value>
                    <fullName>Enfield</fullName>
                </value>
                <value>
                    <fullName>Epsom</fullName>
                </value>
                <value>
                    <fullName>Godalming</fullName>
                </value>
                <value>
                    <fullName>Greenwich</fullName>
                </value>
                <value>
                    <fullName>Hackney</fullName>
                </value>
                <value>
                    <fullName>Hammersmith &amp; Fulham</fullName>
                </value>
                <value>
                    <fullName>Haringey</fullName>
                </value>
                <value>
                    <fullName>Harrow</fullName>
                </value>
                <value>
                    <fullName>Havering</fullName>
                </value>
                <value>
                    <fullName>Hillingdon</fullName>
                </value>
                <value>
                    <fullName>Hounslow</fullName>
                </value>
                <value>
                    <fullName>Islington</fullName>
                </value>
                <value>
                    <fullName>Kensington &amp; Chelsea</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Challenger_sign_up_action__c</fullName>
        <description>The action Challengers need to take in order to take up the opportunity</description>
        <inlineHelpText>he action Challengers need to take in order to take up the opportunity</inlineHelpText>
        <label>Young Person sign-up action</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to cluster the volunteering opportunity occurs in</description>
        <inlineHelpText>Select the cluster the volunteering opportunity occurs in</inlineHelpText>
        <label>Cluster</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Cluster__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>2012, 2013, 2014</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Signposting Opportunities</relationshipLabel>
        <relationshipName>Volunteering_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_s__c</fullName>
        <description>Date(s) of the volunteering opportunity</description>
        <inlineHelpText>Date(s) of the volunteering opportunity</inlineHelpText>
        <label>Date (s)</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_this_opportunity_expires__c</fullName>
        <description>Date on which this volunteering opportunity should no longer be offered to young people</description>
        <inlineHelpText>Date on which this volunteering opportunity should no longer be offered to young people</inlineHelpText>
        <label>Date this opportunity expires</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Full_description__c</fullName>
        <description>Full description of the opportunity</description>
        <inlineHelpText>Full description of the opportunity</inlineHelpText>
        <label>Full description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Opportunity_type__c</fullName>
        <description>Opportunity types/filters</description>
        <inlineHelpText>Select as many descriptions of the type of opportunity as possible</inlineHelpText>
        <label>Opportunity types/filters</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Animals &amp; Wildlife</fullName>
                </value>
                <value>
                    <fullName>Art</fullName>
                </value>
                <value>
                    <fullName>Befriending &amp; Buddying</fullName>
                </value>
                <value>
                    <fullName>Business Management &amp; Research</fullName>
                </value>
                <value>
                    <fullName>Campaigning &amp; lobbying</fullName>
                </value>
                <value>
                    <fullName>Career development &amp; work experience</fullName>
                </value>
                <value>
                    <fullName>Children</fullName>
                </value>
                <value>
                    <fullName>Communication &amp; public speaking</fullName>
                </value>
                <value>
                    <fullName>Design &amp; Technology</fullName>
                </value>
                <value>
                    <fullName>Disability</fullName>
                </value>
                <value>
                    <fullName>Elderly</fullName>
                </value>
                <value>
                    <fullName>Fundraising</fullName>
                </value>
                <value>
                    <fullName>Gardening</fullName>
                </value>
                <value>
                    <fullName>Human rights</fullName>
                </value>
                <value>
                    <fullName>Life Skills</fullName>
                </value>
                <value>
                    <fullName>Mentoring</fullName>
                </value>
                <value>
                    <fullName>Music &amp; Production</fullName>
                </value>
                <value>
                    <fullName>Practical work &amp; DIY</fullName>
                </value>
                <value>
                    <fullName>Project Management</fullName>
                </value>
                <value>
                    <fullName>Sports Development</fullName>
                </value>
                <value>
                    <fullName>Teaching training &amp; coaching</fullName>
                </value>
                <value>
                    <fullName>Technology &amp; Computers</fullName>
                </value>
                <value>
                    <fullName>Theatre &amp; Performance</fullName>
                </value>
                <value>
                    <fullName>Youth Work</fullName>
                </value>
                <value>
                    <fullName>Retail</fullName>
                </value>
                <value>
                    <fullName>Community development</fullName>
                </value>
                <value>
                    <fullName>Poverty Reduction</fullName>
                </value>
                <value>
                    <fullName>Events and festivals</fullName>
                </value>
                <value>
                    <fullName>Media</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Organisation__c</fullName>
        <description>The organisation the volunteering opportunity is with</description>
        <inlineHelpText>The organisation the volunteering opportunity is with</inlineHelpText>
        <label>Organisation</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>notEqual</operation>
                <value>Young Person, GPs, Core Staff, Summer Staff 2011, Grad2011</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipName>Volunteering_Opportunities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Summary_description__c</fullName>
        <description>Short summary description of the opportunity</description>
        <inlineHelpText>Short summary description of the opportunity</inlineHelpText>
        <label>Summary description</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Signposting Opportunity</label>
    <nameField>
        <label>Signposting Opportunities Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Signposting Opportunities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TestMetric_CalculateTCSEventAttendances.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class TestMetric_CalculateTCSEventAttendances {

    static testMethod void myUnitTest() {

			Contact c = new Contact( FirstName='Burak', LastName='test');
		
			insert c;
			
			Metric__c metric = new Metric__c ( Contact__c=c.Id);
			
			insert metric;
			
			RecordType rt = [SELECT Id FROM RecordType WHERE SObjectType='Cluster__c' AND Name='2012'];
			
			Cluster__c cluster = new Cluster__c(Name='testcluster', RecordTypeId = rt.Id);
			
			insert cluster;
			
			RecordType r = [SELECT Id FROM RecordType WHERE SObjectType='Account' AND (Name='Devt' OR Name='Family2012' OR Name='Family2012A' OR Name='Marketing not schools'
							OR Name='Personal Challenge' OR Name='Programmes' OR Name='Schools' OR Name='SeasonalStaff2012' OR Name='Sixth Form') LIMIT 1];
			
			Account acc = new Account (Name='testaccount', RecordTypeId = r.Id);
			
			insert acc;
			
			Volunteering_Opportunity__c volOp = new Volunteering_Opportunity__c(Name='test', Borough_area_this_applies_to__c='Barnet',Summary_description__c='testsum',
													 Opportunity_type__c='Art',Date_this_opportunity_expires__c=System.today(),Date_s__c='test',
													 Full_description__c='fulltest', Approx_number_of_volunteering_places__c=1,Challenger_sign_up_action__c='testaction',
													 Cluster__c=cluster.Id, Organisation__c=acc.Id);
													 
			insert volOp;
			
			TCS_Attendance_record__c TCS = new TCS_Attendance_record__c(Contact__c=c.Id, Volunteering_Opportunity__c=volOp.Id);
			
			insert TCS;
			
			Metric__c newmetric = [SELECT Total_SignPosting_Oppty_Meetings_Attend__c FROM Metric__c WHERE Contact__c =: c.Id];
						
			System.assertEquals(0, newmetric.Total_SignPosting_Oppty_Meetings_Attend__c);
			
			TCS.Meetings_attended_Dec__c='4';
			
			update TCS;
			
			newmetric = [SELECT Total_SignPosting_Oppty_Meetings_Attend__c FROM Metric__c WHERE Contact__c =: c.Id];
			
			System.assertEquals(4,newmetric.Total_SignPosting_Oppty_Meetings_Attend__c);
			
			delete TCS;
			
    }
}