objects/Disable_Button__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This object help to disable the schedule button for 5 after user clicks on it.</description>
    <fields>
        <fullName>Schedule_Count__c</fullName>
        <label>Schedule Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Schedule_Time__c</fullName>
        <label>Schedule Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>isDisabled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isDisabled</label>
        <type>Checkbox</type>
    </fields>
    <label>Schedule Button Disable</label>
</CustomObject>

objects/smagicinteract__SMS_SenderId__c.object
<CustomObject>
    <fields>
        <fullName>smagicinteract__senderId__c</fullName>
        <label>senderId</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>SMS SenderId</label>
    <nameField>
        <displayFormat>SS-{00000}</displayFormat>
        <label>SMS SenderIds Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SMS SenderIds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/smagicinteract__SMS_Template__c.object
<CustomObject>
    <description>SMS Template is similar to Email template, it gives way to add personalization to bulk sms&apos;ing.</description>
    <fields>
        <fullName>smagicinteract__Name__c</fullName>
        <description>Name of template</description>
        <label>Name</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>smagicinteract__ObjectName__c</fullName>
        <description>Objects for which templates to be created.</description>
        <label>ObjectName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>smagicinteract__Text__c</fullName>
        <description>Text in template</description>
        <label>Text</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <label>SMS Template</label>
    <nameField>
        <displayFormat>ST-{00000000}</displayFormat>
        <label>SMS Templates Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SMS Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ScheduleWaveSMSController.cls
public with sharing class ScheduleWaveSMSController {
	
	public String dateToSchedule {set;get;}
	public String waveTextContent;
	public String waveId = '';
	public String returnURL = '';
	public Date scheduleDate = null;
	public String senderId{get;set;}
	public String contactTemplateName {set;get;}
	public String waveName {set;get;}
	public boolean disableScheduleButton {set;get;}
	public String errorMsg = 'You have reached the maximum number of Wave SMS that you can schedule at one time. Please wait 3 minutes before you schedule SMS for the next Wave.';
	
	public ScheduleWaveSMSController(){
		
		system.debug(system.loggingLevel.INFO, 'ScheduleWaveSMSController constructor');
		disableScheduleButton = true;
		PageReference pageRef = ApexPages.currentPage();
		this.waveId = pageRef.getParameters().get('waveId');
		this.waveName = pageRef.getParameters().get('waveName');
		this.returnURL = pageRef.getParameters().get('retURL');
		if(this.returnURL == null)
			this.returnURL = this.waveId;
	}
	
	public void updateCustomSettings(){
		
		Disable_Button__c scheduleButtonDisableObj =  Disable_Button__c.getOrgDefaults();
		system.debug(Logginglevel.info, 'scheduleButtonDisableObj :'+scheduleButtonDisableObj);
		if(scheduleButtonDisableObj != null){
			
			Integer scheduleCount = 0;
			if(scheduleButtonDisableObj.Schedule_Count__c != null) 
				scheduleCount = scheduleButtonDisableObj.Schedule_Count__c.intValue();

			if(scheduleCount >= 5){

				DateTime currentDateTime = system.now();
				DateTime savedDateTime = scheduleButtonDisableObj.Schedule_Time__c;
				
				long savedMinutes = savedDateTime.getTime() / 1000 / 60;  //getTime gives us milliseconds, so divide by 1000 for seconds  
				long currentMinutes = currentDateTime.getTime() / 1000 / 60;
				system.debug(Logginglevel.info, 'currentMinutes :'+currentMinutes);
				system.debug(Logginglevel.info, 'savedMinutes :'+savedMinutes);
				Integer difference = Integer.valueOf(currentMinutes - savedMinutes);
				system.debug(Logginglevel.info, 'difference :'+difference);
	        	if(difference > 2){
	        		disableScheduleButton = false;
	        		scheduleButtonDisableObj.isDisabled__c = false;
	        		scheduleButtonDisableObj.Schedule_Time__c = null;
	        		scheduleButtonDisableObj.Schedule_Count__c = 0;
	        		update scheduleButtonDisableObj;
	        	}
	        	else{
	        		try{
		                if (ApexPages.currentPage() != null ){
		                    ApexPages.Message pMessage = new ApexPages.Message(ApexPages.Severity.INFO, errorMsg);
		                    ApexPages.addMessage(pMessage);
		                }
		            }catch(Exception e){
		                    //pass
		            }
	        	}
			}
			else {
				disableScheduleButton = false;	
			}
		}
		else{
			disableScheduleButton = false;
		}
	}
	
	public List<SelectOption> getTemplateDropDown(){
		
        List<smagicinteract__SMS_Template__c> templateList = [select Id, smagicinteract__Name__c, smagicinteract__Text__c, smagicinteract__ObjectName__c from smagicinteract__SMS_Template__c where smagicinteract__ObjectName__c = 'Wave_Selection__c'];
        List<SelectOption> tempList = new List<SelectOption>();
        if(templateList.size() > 0){
	        for(smagicinteract__SMS_Template__c templateName : templateList)
	                tempList.add(new SelectOption(String.valueOf(templateName.smagicinteract__Name__c),String.valueOf(templateName.smagicinteract__Name__c)));
        }
        
        return tempList;
    }
	
	public void setWaveTextContent(String txt){
        this.waveTextContent = txt;
    }
    
    public String getWaveTextContent(){
    	
        List<smagicinteract__SMS_Template__c> obj = null;
        string smsText='';
        if(contactTemplateName != null)
        {
            obj = [select smagicinteract__Text__c from smagicinteract__SMS_Template__c where smagicinteract__Name__c = :contactTemplateName];
            smsText = String.valueOf(obj[0].smagicinteract__Text__c);
        }
        else
        	smsText = '';
        
        system.debug(LoggingLevel.INFO,'smsText'+smsText);
        return smsText; 
    }
    
	public List<SelectOption> getSenderIds(){
		
		List<SelectOption> options = new List<SelectOption>();
		
		List<smagicinteract__SMS_SenderId__c> senderIdList = [select smagicinteract__senderId__c from smagicinteract__SMS_SenderId__c];
		for(smagicinteract__SMS_SenderId__c sender :senderIdList){
			options.add(new SelectOption(sender.smagicinteract__senderId__c, sender.smagicinteract__senderId__c));
		}
		if(options.size() == 0){
			options.add(new SelectOption('smsMagic', 'smsMagic'));
		}
		return options;
	}
	
	public void scheduleSMS(){
		
		Disable_Button__c scheduleButtonDisableObj =  Disable_Button__c.getOrgDefaults();
		if(scheduleButtonDisableObj != null){
			
			if(scheduleButtonDisableObj.isDisabled__c)
				return;
			system.debug(system.loggingLevel.INFO, 'In scheduleSMS');
			scheduleDate = Date.valueOf(dateToSchedule);
			system.debug(system.loggingLevel.INFO, 'Sender ID : '+senderId);
			system.debug(system.loggingLevel.INFO, 'Schedule Date : '+ scheduleDate);
			system.debug(system.loggingLevel.INFO, 'waveTextContent : '+ waveTextContent);
			WaveSMSBatch wavesmsbatch = new WaveSMSBatch(waveId, scheduleDate, waveTextContent, senderId);
			Database.executeBatch(wavesmsbatch);
			
			/*if(scheduleButtonDisableObj == null){
	        	scheduleButtonDisableObj = new Disable_Button__c();
	        	scheduleButtonDisableObj.isDisabled__c = true;
	        	scheduleButtonDisableObj.Schedule_Time__c = system.now();
				insert scheduleButtonDisableObj;
	        }else if(!scheduleButtonDisableObj.isDisabled__c){
	        	scheduleButtonDisableObj.isDisabled__c = true;
	        	scheduleButtonDisableObj.Schedule_Time__c = system.now();
				update scheduleButtonDisableObj;
	        }*/
	        //disableScheduleButton = true;
	        //scheduleButtonDisableObj.isDisabled__c = true;
	        Integer scheduleCount = 0;
	        if(scheduleButtonDisableObj.Schedule_Count__c != null){
	        	scheduleCount = scheduleButtonDisableObj.Schedule_Count__c.intValue();
	        }
	        scheduleCount += 1;
	        if(scheduleCount >= 5){
	        	disableScheduleButton = true;
	        	scheduleButtonDisableObj.isDisabled__c = true;
	        	scheduleButtonDisableObj.Schedule_Time__c = system.now();
	        }else{
	        	disableScheduleButton = false;
	        	scheduleButtonDisableObj.isDisabled__c = false;
	        	scheduleButtonDisableObj.Schedule_Time__c = null;
	        }
	        scheduleButtonDisableObj.Schedule_Count__c = scheduleCount; 
        	//scheduleButtonDisableObj.Schedule_Time__c = system.now();
			update scheduleButtonDisableObj;
			
			if(scheduleCount >= 5){
				try{
	                if (ApexPages.currentPage() != null ){
	                    ApexPages.Message pMessage = new ApexPages.Message(ApexPages.Severity.INFO, errorMsg);
	                    ApexPages.addMessage(pMessage);
	                }
	            }catch(Exception e){
	                    //pass
	            }
			}
		}
		else{
			disableScheduleButton = false;
			scheduleButtonDisableObj = new Disable_Button__c();
        	scheduleButtonDisableObj.isDisabled__c = false;
        	scheduleButtonDisableObj.Schedule_Time__c = null;
        	scheduleButtonDisableObj.Schedule_Count__c = 1; 
			insert scheduleButtonDisableObj;
		}
	}
	
	public Pagereference cancel(){
		
		system.debug(logginglevel.info,'returnURL : '+returnURL);
		returnURL = '/'+returnURL;
		PageReference pageRef = new PageReference(returnURL);
		return pageRef;
	}
}