objects/Feedback__c.object
<CustomObject>
    <description>Related object to Job Application for PM/APM feedback of summer staff</description>
    <fields>
        <fullName>How_many_days_did_they_attend__c</fullName>
        <label>No of attendances</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Job_Application__c</fullName>
        <label>Job Application</label>
        <referenceTo>Job_Application__c</referenceTo>
        <relationshipLabel>Feedback</relationshipLabel>
        <relationshipName>Feedback</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Feedback</label>
    <nameField>
        <displayFormat>Feedback-{DD}/{MM}/{YYYY}-{00000}</displayFormat>
        <label>Feedback Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Feedback</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/HR_Event__c.object
<CustomObject>
    <fields>
        <fullName>Staff_type__c</fullName>
        <label>Staff type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Core Staff</fullName>
                </value>
                <value>
                    <fullName>New Application</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Returner</fullName>
                </value>
                <value>
                    <fullName>Returner - different role</fullName>
                </value>
                <value>
                    <fullName>Returner - same role</fullName>
                </value>
                <value>
                    <fullName>Returner - lower role</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>HR Event</label>
    <nameField>
        <label>HR Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>HR Events</pluralLabel>
    <recordTypes>
        <fullName>Assessment</fullName>
        <active>true</active>
        <label>Assessment</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/HR_Event_Attendance__c.object
<CustomObject>
    <fields>
        <fullName>Contac__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>HR Event Attendance</relationshipLabel>
        <relationshipName>HR_Event_Attendance</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>HR_Event__c</fullName>
        <label>HR Event</label>
        <referenceTo>HR_Event__c</referenceTo>
        <relationshipLabel>HR Event Attendance</relationshipLabel>
        <relationshipName>HR_Event_Attendance</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Job_Application__c</fullName>
        <label>Job Application</label>
        <referenceTo>Job_Application__c</referenceTo>
        <relationshipLabel>HR Event Attendance</relationshipLabel>
        <relationshipName>Attendees</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>HR Event Attendance</label>
    <nameField>
        <displayFormat>Att-{0000}</displayFormat>
        <label>Attendee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HR Event Attendance</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Job_Application__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Job Applications</relationshipLabel>
        <relationshipName>Job_Applications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Staff_type__c</fullName>
        <inlineHelpText>Shows the staff type for this person. Default is &quot;New Application&quot;. More than 1 type is possible.</inlineHelpText>
        <label>Staff type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Agency staff</fullName>
                </value>
                <value>
                    <fullName>Core Staff</fullName>
                </value>
                <value>
                    <fullName>Franchise - London Youth</fullName>
                </value>
                <value>
                    <fullName>Limited Company</fullName>
                </value>
                <value>
                    <fullName>New Application</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Returner</fullName>
                </value>
                <value>
                    <fullName>Returner - different role</fullName>
                </value>
                <value>
                    <fullName>Returner - same role</fullName>
                </value>
                <value>
                    <fullName>Volunteer</fullName>
                </value>
                <value>
                    <fullName>Returner - lower role</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Job Application</label>
    <nameField>
        <displayFormat>JA-2016-{0000}</displayFormat>
        <label>Job Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Metric__c.object
<CustomObject>
    <description>Keeps the Contact and some detailed metrics</description>
    <fields>
        <fullName>AM_SAM_attendance_at_RCD__c</fullName>
        <defaultValue>0</defaultValue>
        <label>#AM &amp; SAM Attendance at RCD</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Metrics</relationshipLabel>
        <relationshipName>Metrics</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Metric</label>
    <nameField>
        <displayFormat>M-{0000}</displayFormat>
        <label>Metric Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Metrics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TestMetric_CalculateFeedback.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class TestMetric_CalculateFeedback {

    static testMethod void myUnitTest() {
    	
    		RecordType rt = [SELECT Id FROM RecordType WHERE Name='Assessment' AND sObjectType='HR_Event__c'];

			Contact c = new Contact(FirstName='Burak', LastName='test');
		
			insert c;
			
			Metric__c metric = new Metric__c(Contact__c = c.Id);
			
			insert metric;
			
						
			Job_Application__c ja = new Job_Application__c (Contact__c = c.Id);
			
			insert ja;
			
			HR_Event__c hrevent = new HR_Event__c (Name='testHRevent',Staff_type__c='Returner',RecordTypeId=rt.Id);
			
			insert hrevent;
			
			HR_Event_Attendance__c hreventatt = new HR_Event_Attendance__c (Contac__c = c.Id, HR_Event__c = hrevent.Id, Job_Application__c = ja.Id);
			
			insert hreventatt;
			
			Feedback__c feed = new Feedback__c (Job_Application__c = ja.Id);
			
			insert feed;
			
			Metric__c newmetric = [SELECT AM_SAM_attendance_at_RCD__c FROM Metric__c WHERE Contact__c =: c.Id];
			
			System.assertEquals(0,newmetric.AM_SAM_attendance_at_RCD__c);
			
			feed.How_many_days_did_they_attend__c = '1';
			
			update feed;
			
			newmetric = [SELECT AM_SAM_attendance_at_RCD__c FROM Metric__c WHERE Contact__c =: c.Id];
			
			System.assertEquals(1,newmetric.AM_SAM_attendance_at_RCD__c);
			 
			delete feed;
    }
}