objects/Feedback__c.object
<CustomObject>
    <description>Related object to Job Application for PM/APM feedback of summer staff</description>
    <fields>
        <fullName>How_many_days_did_they_attend__c</fullName>
        <label>No of attendances</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Job_Application__c</fullName>
        <label>Job Application</label>
        <referenceTo>Job_Application__c</referenceTo>
        <relationshipLabel>Feedback</relationshipLabel>
        <relationshipName>Feedback</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Feedback</label>
    <nameField>
        <displayFormat>Feedback-{DD}/{MM}/{YYYY}-{00000}</displayFormat>
        <label>Feedback Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Feedback</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Job_Application__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Job Applications</relationshipLabel>
        <relationshipName>Job_Applications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Job Application</label>
    <nameField>
        <displayFormat>JA-2016-{0000}</displayFormat>
        <label>Job Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Metric__c.object
<CustomObject>
    <description>Keeps the Contact and some detailed metrics</description>
    <fields>
        <fullName>AM_SAM_attendance_at_RCD__c</fullName>
        <defaultValue>0</defaultValue>
        <label>#AM &amp; SAM Attendance at RCD</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Metrics</relationshipLabel>
        <relationshipName>Metrics</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Metric</label>
    <nameField>
        <displayFormat>M-{0000}</displayFormat>
        <label>Metric Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Metrics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Metric_CalculateFeedback.cls
public class Metric_CalculateFeedback {

private list<id> ContactID = new list<Id>();
private list<id> FeedBackIDNotInclude = new list<Id>();
	public Metric_CalculateFeedback(List<Id> ContactID,List<Id> FeedBackIDNotInclude){
		
			this.ContactID=ContactID;
			this.FeedBackIDNotInclude=FeedBackIDNotInclude;
}

	
	public void DefineScope(){
	 
		List<Feedback__c> ListFeedback = new List<Feedback__c>();
			ListFeedback= [SELECT id, Job_Application__r.Contact__c, How_many_days_did_they_attend__c FROM Feedback__c
		 					WHERE Job_Application__r.Contact__c IN :this.ContactID
		 					AND Id NOT IN :this.FeedBackIDNotInclude];
		 					
	execute(ListFeedback);
	 }
	 
	 public void execute(List<Feedback__c> scope){
	       
	       List<Metric__c> ListMetrics = [SELECT id, Contact__c FROM Metric__c WHERE Contact__c IN :this.ContactID];
	       
	       for(Metric__c metric :ListMetrics){
	       	integer counter=0;
	       	
	       		for(Feedback__c feedItem : scope){
	       		
	       		if(feedItem.Job_Application__r.Contact__c == metric.Contact__c && feedItem.How_many_days_did_they_attend__c!=null){
	       			
	       			counter+=integer.valueOf(feedItem.How_many_days_did_they_attend__c);
	   			  	 }
	       		
	       		}
	       		metric.AM_SAM_attendance_at_RCD__c = counter;
	       	}
	   
	       update ListMetrics;
	   }
	
	}