objects/HR_Event__c.object
<CustomObject>
    <fields>
        <fullName>Staff_type__c</fullName>
        <label>Staff type</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Core Staff</fullName>
                </value>
                <value>
                    <fullName>New Application</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Returner</fullName>
                </value>
                <value>
                    <fullName>Returner - different role</fullName>
                </value>
                <value>
                    <fullName>Returner - same role</fullName>
                </value>
                <value>
                    <fullName>Returner - lower role</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>HR Event</label>
    <nameField>
        <label>HR Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>HR Events</pluralLabel>
    <recordTypes>
        <fullName>Assessment</fullName>
        <active>true</active>
        <label>Assessment</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/HR_Event_Attendance_YP__c.object
<CustomObject>
    <description>Is used to capture Graduates working as Assessors for Staffing assessment events</description>
    <fields>
        <fullName>Attendance_status__c</fullName>
        <inlineHelpText>Update this field after the event</inlineHelpText>
        <label>Attendance status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Planning to attend</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Attended</fullName>
                </value>
                <value>
                    <fullName>Did not attend</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>This record is the wrong record type. Only YP, YP2010, YP2012 and YP2012A can be added here.</errorMessage>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>YP, YP2012, YP2012A, YP2010</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>HR Event Attendance YPs</relationshipLabel>
        <relationshipName>HR_Event_Attendance_YPs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>HR_Event__c</fullName>
        <label>HR Event</label>
        <referenceTo>HR_Event__c</referenceTo>
        <relationshipLabel>HR Event Attendance YPs</relationshipLabel>
        <relationshipName>HR_Event_Attendance_YPs</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>HR Event Attendance YP</label>
    <nameField>
        <displayFormat>HRYP-{000000}</displayFormat>
        <label>HR Event Attendance YP Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HR Event Attendance YPs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Metric__c.object
<CustomObject>
    <description>Keeps the Contact and some detailed metrics</description>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Metrics</relationshipLabel>
        <relationshipName>Metrics</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Staffing_Ambassador__c</fullName>
        <defaultValue>0</defaultValue>
        <label>#Staffing Ambassador Events Attended</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Metric</label>
    <nameField>
        <displayFormat>M-{0000}</displayFormat>
        <label>Metric Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Metrics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TestMetric_CalculateHREventsAttYP.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class TestMetric_CalculateHREventsAttYP {

    static testMethod void myUnitTest() { 

			RecordType rt = [SELECT Id FROM RecordType WHERE SObjectType='Contact' AND (Name='YP' OR Name='Grad2012') LIMIT 1];
			RecordType rtass = [SELECT Id FROM RecordType WHERE Name='Assessment' AND sObjectType='HR_Event__c'];
			
			Contact c = new Contact( FirstName='Burak', LastName='test', RecordTypeId = rt.Id );
		
			insert c;
			
			Metric__c metric = new Metric__c ( Contact__c = c.Id);
			
			insert metric;
			
			HR_Event__c hrevent = new HR_Event__c (Name='testHRevent',Staff_type__c='Returner',RecordTypeId=rtass.Id);
			
			insert hrevent;
			
			HR_Event_Attendance_YP__c hreventattyp = new HR_Event_Attendance_YP__c (Contact__c = c.Id, HR_Event__c = hrevent.Id);
			
			insert hreventattyp;
			
			Metric__c newmetric = [SELECT Staffing_Ambassador__c FROM Metric__c WHERE Contact__c =: c.Id];
			
			System.assertEquals(0,newmetric.Staffing_Ambassador__c);
			
			hreventattyp.Attendance_status__c = 'Attended';
			
			update hreventattyp;
			
			newmetric = [SELECT Staffing_Ambassador__c FROM Metric__c WHERE Contact__c =: c.Id];
			
			System.assertEquals(1,newmetric.Staffing_Ambassador__c);
    		
    		delete hreventattyp;
    }
}