objects/HR_Event_Attendance_YP__c.object
<CustomObject>
    <description>Is used to capture Graduates working as Assessors for Staffing assessment events</description>
    <fields>
        <fullName>Attendance_status__c</fullName>
        <inlineHelpText>Update this field after the event</inlineHelpText>
        <label>Attendance status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Planning to attend</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Attended</fullName>
                </value>
                <value>
                    <fullName>Did not attend</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>This record is the wrong record type. Only YP, YP2010, YP2012 and YP2012A can be added here.</errorMessage>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>YP, YP2012, YP2012A, YP2010</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>HR Event Attendance YPs</relationshipLabel>
        <relationshipName>HR_Event_Attendance_YPs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>HR Event Attendance YP</label>
    <nameField>
        <displayFormat>HRYP-{000000}</displayFormat>
        <label>HR Event Attendance YP Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>HR Event Attendance YPs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Metric__c.object
<CustomObject>
    <description>Keeps the Contact and some detailed metrics</description>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Metrics</relationshipLabel>
        <relationshipName>Metrics</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Staffing_Ambassador__c</fullName>
        <defaultValue>0</defaultValue>
        <label>#Staffing Ambassador Events Attended</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Metric</label>
    <nameField>
        <displayFormat>M-{0000}</displayFormat>
        <label>Metric Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Metrics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Metric_CalculateHREventsAttYP.cls
public class Metric_CalculateHREventsAttYP {

List<Id> CATId = new List<Id>();
	public Metric_CalculateHREventsAttYP(List<Id> CATId){
		this.CATId=CATId;
	}

	
	 public void DefineScope(){
	 	
	 	List<HR_Event_Attendance_YP__c> ListHREventYP = new List<HR_Event_Attendance_YP__c>();
	 	ListHREventYP = [SELECT id, Contact__c,Contact__r.Account.Attended_Assembly_2__c, 
 							Contact__r.Account.Attended_Assembly_1__c 
	 								FROM HR_Event_Attendance_YP__c WHERE Attendance_Status__c='Attended' AND
	 								Contact__c IN :this.CATId];
		
	 execute(ListHREventYP);
	 }
	 
	public void execute(List<HR_Event_Attendance_YP__c> scope){
	   
	       
	       List<Metric__c> ListMetrics = [SELECT id, Contact__c FROM Metric__c WHERE Contact__c IN :this.CATId];
	       
	       
	       for(Metric__c metric :ListMetrics){
	       	integer counter=0;

	       		for(HR_Event_Attendance_YP__c HReventItem : scope){
	       		
	       		if(HReventItem.Contact__c == metric.Contact__c){
	       			
	       				counter++;
	       		}
	       	}
	       	metric.Staffing_Ambassador__c = counter;
	   }
	       update ListMetrics;
   }
	   
}