objects/Inclusion_Details__c.object
<CustomObject>
    <fields>
        <fullName>details_of_other_info__c</fullName>
        <label>Details of other info</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Inclusion Detail</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Inclusion Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inclusion Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/NCS_Data_Entry_Staging__c.object
<CustomObject>
    <description>Staging object for transforming Captricity data into Account, Contact, NCS Application, Inclusion Details, Relationship records.</description>
    <fields>
        <fullName>details_of_other_info__c</fullName>
        <label>details of other info</label>
        <type>TextArea</type>
    </fields>
    <label>NCS Data Entry Staging</label>
    <nameField>
        <displayFormat>NCSDES-{000000}</displayFormat>
        <label>NCS Data Entry Staging Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NCS Data Entry Staging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/NCS_Data_Entry_Staging_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Source_Field__c</fullName>
        <description>NCS Data Entry Staging Field (Mapping from)</description>
        <inlineHelpText>This is the API name of the field on the NCS Data Entry Staging Object ie; yp_first_name__c</inlineHelpText>
        <label>Source Field</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Target_Field__c</fullName>
        <description>Target field, this is the field the Source Field maps to on the related Salesforce object</description>
        <inlineHelpText>Target Field on Target Object, uses the Salesforce API name ie, firstName, ap_recieved__c</inlineHelpText>
        <label>Target Field</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Target_Object__c</fullName>
        <inlineHelpText>Salesforce Object API name ie, Contact, Inclusion_Details__c</inlineHelpText>
        <label>Target Object</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Target_Type__c</fullName>
        <inlineHelpText>Target type is used to specify the target object for use within the APEX classes bg_NCSDataEntry

ENSURE ALL CAPITALS

Values are;
INC
NCS
YPCON
PGCON
YP&amp;PGCON</inlineHelpText>
        <label>Target Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>NCS Data Entry Staging Settings</label>
</CustomObject>

classes/bg_InclusionDetailUtils_Test.cls
/********************************************************************
 * bg_InclusionDetailUtils_Test
 *
 * Test class for bg_InclusionDetailUtils
 * 
 * Author: Antony Daley
 * Created: 07-04-2015
 * Changes: 
 *
 ********************************************************************/

@isTest
private class bg_InclusionDetailUtils_Test 
{

    static testMethod void testPopulateINCDetail()
    {
    	//Disable the data creation triggers
    	bg_NCSDataEntryStagingUtils.DISABLE_TRIGGER_PROCESS = true;
    	
    	//Setup a custom setting - Source Fields are derived from the NCS Data Entry Staging object
        NCS_Data_Entry_Staging_Settings__c cstSetting = new NCS_Data_Entry_Staging_Settings__c();
        
        cstSetting.Name = 'INC Test';
        cstSetting.Target_Field__c = 'details_of_other_info__c';
        cstSetting.Target_Object__c = 'inclusion_details__c';
        cstSetting.Source_Field__c = 'details_of_other_info__c';
        cstSetting.Target_Type__c = bg_NCSDataEntryStagingUtils.TARGET_TYPE_INC;
        
        insert cstSetting;
        
        NCS_Data_Entry_Staging__c stagingRecord = bg_UnitTestHelper.getStagingObj('myemail@waterspout.com', null); 
        stagingRecord.details_of_other_info__c = 'test';
        
        insert stagingRecord;
        
        map<String, List<bg_NCSDataEntryFieldMappingUtils.fieldMappingValidation>> fieldSourceToWrapperMap = bg_NCSDataEntryFieldMappingUtils.validateFieldMappings();
        
        Inclusion_Details__c incRecord = new Inclusion_Details__c();
        incRecord = bg_InclusionDetailUtils.PopulateINCDetail(incRecord, stagingRecord, fieldSourceToWrapperMap.get(bg_NCSDataEntryStagingUtils.TARGET_TYPE_INC), null);
    	
    	system.assertEquals(incRecord.details_of_other_info__c, 'test');
    }
    
    static testMethod void testPopulateNCSApplicationNullValue()
    {
    	//Disable the data creation triggers
    	bg_NCSDataEntryStagingUtils.DISABLE_TRIGGER_PROCESS = true;
    	
    	//Setup a custom setting - Source Fields are derived from the NCS Data Entry Staging object
        NCS_Data_Entry_Staging_Settings__c cstSetting = new NCS_Data_Entry_Staging_Settings__c();
        
        cstSetting.Name = 'INC Test';
        cstSetting.Target_Field__c = 'details_of_other_info__c';
        cstSetting.Target_Object__c = 'Inclusion_Details__c';
        cstSetting.Source_Field__c = 'details_of_other_info__c';
        cstSetting.Target_Type__c = bg_NCSDataEntryStagingUtils.TARGET_TYPE_INC;
        
        insert cstSetting;
        
        NCS_Data_Entry_Staging__c stagingRecord = bg_UnitTestHelper.getStagingObj('myemail@waterspout.com', null); 
        stagingRecord.details_of_other_info__c = '';
        
        insert stagingRecord;
        
        map<String, List<bg_NCSDataEntryFieldMappingUtils.fieldMappingValidation>> fieldSourceToWrapperMap = bg_NCSDataEntryFieldMappingUtils.validateFieldMappings();
        
        Inclusion_Details__c incRecord = new Inclusion_Details__c();
        incRecord.details_of_other_info__c = 'test';
        incRecord = bg_InclusionDetailUtils.PopulateINCDetail(incRecord, stagingRecord, fieldSourceToWrapperMap.get(bg_NCSDataEntryStagingUtils.TARGET_TYPE_INC), null);
    	
    	system.assertEquals(incRecord.details_of_other_info__c, 'test');
    }
}