objects/Inclusion_Details__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Inclusion Details</relationshipLabel>
        <relationshipName>Inclusion_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>HTR__c</fullName>
        <defaultValue>false</defaultValue>
        <label>HTR?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>OBS_P3_form_status__c</fullName>
        <label>OBS MASI form status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Started but not completed</fullName>
                </value>
                <value>
                    <fullName>Completed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Season__c</fullName>
        <formula>Contact__r.NCS_Application_Primary_Season__c</formula>
        <label>Season</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Support_Level__c</fullName>
        <label>Support Level</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1 - no extra support</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>2 - medical conditions</fullName>
                </value>
                <value>
                    <fullName>3a - extra mentor support for learning difficulties</fullName>
                </value>
                <value>
                    <fullName>3b - extra mentor support for challenging behaviour or mental health conditions</fullName>
                </value>
                <value>
                    <fullName>4a – Extra APL support for YPs with restricted mobility, language barrier or learning difficulties</fullName>
                </value>
                <value>
                    <fullName>4b - extra APL support for challenging behaviour or mental health conditions</fullName>
                </value>
                <value>
                    <fullName>5.05 - support worker required, can share with another YP</fullName>
                </value>
                <value>
                    <fullName>5.1 - full-time support worker required</fullName>
                </value>
                <value>
                    <fullName>5.2 - requires 2 full time support workers</fullName>
                </value>
                <value>
                    <fullName>6 - case-by-case, potential non-accept</fullName>
                </value>
                <value>
                    <fullName>5b - personal coach required</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Inclusion Detail</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Inclusion Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inclusion Details</pluralLabel>
    <recordTypes>
        <fullName>Archived</fullName>
        <active>true</active>
        <description>Archived Inclusion Detail Information</description>
        <label>Archived</label>
    </recordTypes>
    <recordTypes>
        <fullName>Current</fullName>
        <active>true</active>
        <label>Current</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/NCS_Application__c.object
<CustomObject>
    <fields>
        <fullName>Active_season__c</fullName>
        <description>Pulls through the value of Active Season from the Season object</description>
        <formula>TEXT( Season__r.Active_season__c )</formula>
        <inlineHelpText>Pulls through the value of Active Season from the Season object</inlineHelpText>
        <label>Active season</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Season__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Season</label>
        <referenceTo>Season__c</referenceTo>
        <relationshipLabel>NCS Applications</relationshipLabel>
        <relationshipName>NCS_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>NCS Application</label>
    <nameField>
        <displayFormat>NCSA{000000}</displayFormat>
        <label>NCS Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NCS Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Season__c.object
<CustomObject>
    <description>NCS season</description>
    <fields>
        <fullName>Active_season__c</fullName>
        <label>Active season</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Season</label>
    <nameField>
        <label>Season Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Seasons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/updateSupportLevelAndHTRHandler.cls
/*
@ Name        : updateSupportLevelAndHTRHandler (Class Handler)
@ Description : Update 'Support Level' and 'HTR?' field of Wave Selection,
@               and 'Support Level' field of Contact same as value of 'Support Level' 
@               field of Inclusion Details.
@ Developer   : Shaikh Saquib
@ Date        : 27-Oct-2014
*/

public class updateSupportLevelAndHTRHandler 
{
    /**
    @ Description : Assign Inclusion Detail lookup on Wave Selection having lookup field 
    value empty or Inclusion Detail record with 'Archived' record type.
    */
    public void afterInsert(Map<Id, Inclusion_Details__c> mapNewInclusionDetail)
    {
        Set<Id> setContactId = new Set<Id>();
        // List of Wave Selection records to be updated
        List<Wave_Selection__c> listWaveSelectionForUpdate = new List<Wave_Selection__c>();
        
        List<Contact> listContactForUpdate = new List<Contact>();
        
        try
        {
            for(Inclusion_Details__c inclusionDetailRecord : mapNewInclusionDetail.values())
            {
                setContactId.add(inclusionDetailRecord.Contact__c);
            }   
            
            System.debug('setContactId ::: ' + setContactId);
            
            // Map of new contact Records and their related NCS Application and Inclusion Detail record.
            Map<Id, Contact> mapNewContact;
            mapNewContact = new Map<Id, Contact>([SELECT Count_of_Inclusion_detail__c,
                                                  
                                                  (SELECT Id, Season__r.Active_season__c                                   
                                                   FROM NCS_Applications__r
                                                   WHERE Season__r.Active_season__c != '' ),
                                                  
                                                  (SELECT Id, Support_Level__c, OBS_P3_form_status__c 
                                                   FROM Inclusion_Details__r
                                                   WHERE RecordType.Name = 'Current')
                                                  
                                                  FROM Contact
                                                  WHERE 
                                                  Id IN :setContactId
                                                  //AND 
                                                  //Count_of_Inclusion_detail__c = 1
                                                 ]);     
            
            System.debug('mapNewContact ::: ' + mapNewContact);
            
            // Set of NCS Application Id
            Set<Id> setNCSApplication = new Set<Id>();
            
            // Assign value to set of Id of NCS Application
            for(Contact contactRecord : mapNewContact.values())
            {               
                for(NCS_Application__c ncsApplication : contactRecord.NCS_Applications__r)
                {
                    if(!setNCSApplication.contains(ncsApplication.Id))
                    {
                        setNCSApplication.add(ncsApplication.Id);
                    }
                }                        
                
            }
            System.debug('setNCSApplication ::: ' + setNCSApplication);
            
            // Map of NSC Application related to new Contact records
            Map<Id, NCS_Application__c> mapNCSApplication;
            mapNCSApplication = new Map<Id, NCS_Application__c>([SELECT Id,                                                                    
                                                                 (SELECT Inclusion_Detail__c, Inclusion_Detail__r.RecordType.Name, 
                                                                  Access_category_filter__c, HTR_Filter__c, HTR__c
                                                                  FROM Wave_Selections__r)
                                                                 
                                                                 FROM NCS_Application__c
                                                                 WHERE
                                                                 Id IN :setNCSApplication
                                                                ]);     
            
            System.debug('mapNCSApplication ::: ' + mapNCSApplication);
            
            // List of Wave Selection records to be updated
            listWaveSelectionForUpdate = new List<Wave_Selection__c>();            
            listContactForUpdate = new List<Contact>();
            
            /**
            @ Description : Assign Inclusion Detail lookup field of Wave Selection.
            */
            Boolean flag = false;
            for(Contact contactRecord : mapNewContact.values())
            {
                if(contactRecord.Inclusion_Details__r.size() == 1)
                {
                    flag = false;
                    
                    // Assign Support Level of Contact with value of Inclusion Detail - Support Level
                    for(Inclusion_Details__c inclusionDetailRecord : contactRecord.Inclusion_Details__r)
                    {         
                        System.debug('contactRecord.Inclusion_Details__r ::: ' + contactRecord.Inclusion_Details__r);       
                        if(mapNewInclusionDetail.containsKey(inclusionDetailRecord.Id) && 
                           inclusionDetailRecord.OBS_P3_form_status__c == 'Completed')
                        {
                            contactRecord.Access_category_2_6__c = inclusionDetailRecord.Support_Level__c;
                            listContactForUpdate.add(contactRecord);
                            flag = true;                    
                            break;
                        }                
                    }
                    
                    if(flag == false && contactRecord.Inclusion_Details__r.size() > 0 && 
                           contactRecord.Inclusion_Details__r[0].OBS_P3_form_status__c == 'Completed')
                    {
                        contactRecord.Access_category_2_6__c = contactRecord.Inclusion_Details__r[0].Support_Level__c;
                        listContactForUpdate.add(contactRecord);
                    }        
                    
                    for(NCS_Application__c ncsAppication : contactRecord.NCS_Applications__r)
                    {                
                        ncsAppication = mapNCSApplication.get(ncsAppication.Id);
                        System.debug('before ncsAppication.Wave_Selections__r ::: ' + ncsAppication.Wave_Selections__r);
                        
                        for(Wave_Selection__c waveSelection : ncsAppication.Wave_Selections__r)
                        {
                            if(contactRecord.Inclusion_Details__r.size() > 0)
                            {                           
                                if(waveSelection.Inclusion_Detail__c == null 
                                   || waveSelection.Inclusion_Detail__r.RecordType.Name == 'Archived')
                                {
                                    waveSelection.Inclusion_Detail__c = contactRecord.Inclusion_Details__r[0].Id;
                                    waveSelection.Access_category_filter__c = contactRecord.Inclusion_Details__r[0].Support_Level__c;
                                    waveSelection.HTR_Filter__c = waveSelection.HTR__c;
                                }
                                else if(mapNewInclusionDetail.containsKey(waveSelection.Inclusion_Detail__c))
                                {
                                    waveSelection.Access_category_filter__c = mapNewInclusionDetail.get(waveSelection.Inclusion_Detail__c).Support_Level__c;
                                    waveSelection.HTR_Filter__c = waveSelection.HTR__c;
                                }
                                
                                listWaveSelectionForUpdate.add(waveSelection);  
                            }                             
                            
                        }  
                        System.debug('after ncsAppication.Wave_Selections__r ::: ' + ncsAppication.Wave_Selections__r);
                    }
                }
            }                     
        }
        catch(Exception e)
        {
            System.debug('Exception : Line Number - ' + e.getLineNumber() + ',\nError Message: ' + e.getMessage());
        }    
        
        if(!listContactForUpdate.isEmpty())
        {
            update listContactForUpdate;
        }
        System.debug('Before update ::: ' + listWaveSelectionForUpdate);
        
        // Update list of Wave Selection with new Inclusion Detail lookup field value.
        if(!listWaveSelectionForUpdate.isEmpty())
        {
            update listWaveSelectionForUpdate;
        }
        System.debug('After update ::: ' + listWaveSelectionForUpdate);         
    }
    
    
    
   /**
    @ Description : Update the related Wave Selection and Contact Records
    */
    public void afterUpdate(Map<Id, Inclusion_Details__c> mapNewInclusionDetails,
                            Map<Id, Inclusion_Details__c> mapOldInclusionDetails)
    {
        
        List<Inclusion_Details__c> listInclusionDetails = new List<Inclusion_Details__c>();
        String oldSupportLevel;
        Boolean oldHTR;
        
        for(Inclusion_Details__c recordInclusionDetail : mapNewInclusionDetails.values())
        {
            oldSupportLevel = mapOldInclusionDetails.get(recordInclusionDetail.Id).Support_Level__c;
            oldHTR = mapOldInclusionDetails.get(recordInclusionDetail.Id).HTR__c;
            if(recordInclusionDetail.Support_Level__c != oldSupportLevel ||
               recordInclusionDetail.HTR__c != oldHTR) 
            {            
                listInclusionDetails .add(recordInclusionDetail);            
            }
        }
        
        if(listInclusionDetails!= null && !listInclusionDetails.isEmpty())
        {
            afterInsert(new Map<Id, Inclusion_Details__c>(listInclusionDetails));        
        }
                               
    }
}