objects/Inclusion_Details__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Inclusion Details</relationshipLabel>
        <relationshipName>Inclusion_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>School_Code__c</fullName>
        <formula>Contact__r.School_s_code_display__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>School Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>School_Type__c</fullName>
        <formula>TEXT(Contact__r.School__r.School_type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>School Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Season__c</fullName>
        <formula>Contact__r.NCS_Application_Primary_Season__c</formula>
        <label>Season</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Support_Level__c</fullName>
        <label>Support Level</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1 - no extra support</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>2 - medical conditions</fullName>
                </value>
                <value>
                    <fullName>3a - extra mentor support for learning difficulties</fullName>
                </value>
                <value>
                    <fullName>3b - extra mentor support for challenging behaviour or mental health conditions</fullName>
                </value>
                <value>
                    <fullName>4a – Extra APL support for YPs with restricted mobility, language barrier or learning difficulties</fullName>
                </value>
                <value>
                    <fullName>4b - extra APL support for challenging behaviour or mental health conditions</fullName>
                </value>
                <value>
                    <fullName>5.05 - support worker required, can share with another YP</fullName>
                </value>
                <value>
                    <fullName>5.1 - full-time support worker required</fullName>
                </value>
                <value>
                    <fullName>5.2 - requires 2 full time support workers</fullName>
                </value>
                <value>
                    <fullName>6 - case-by-case, potential non-accept</fullName>
                </value>
                <value>
                    <fullName>5b - personal coach required</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Inclusion Detail</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Inclusion Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inclusion Details</pluralLabel>
    <recordTypes>
        <fullName>Archived</fullName>
        <active>true</active>
        <description>Archived Inclusion Detail Information</description>
        <label>Archived</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/NCS_Application__c.object
<CustomObject>
    <fields>
        <fullName>AP_received__c</fullName>
        <label>AP received</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Active_season__c</fullName>
        <description>Pulls through the value of Active Season from the Season object</description>
        <formula>TEXT( Season__r.Active_season__c )</formula>
        <inlineHelpText>Pulls through the value of Active Season from the Season object</inlineHelpText>
        <label>Active season</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>School</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Schools</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>NCS Applications</relationshipLabel>
        <relationshipName>NCS_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Season__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Season</label>
        <referenceTo>Season__c</referenceTo>
        <relationshipLabel>NCS Applications</relationshipLabel>
        <relationshipName>NCS_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Wave__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Wave</label>
        <referenceTo>Wave__c</referenceTo>
        <relationshipLabel>NCS Applications</relationshipLabel>
        <relationshipName>NCS_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>YoungPerson__c</fullName>
        <label>Young Person</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>NCS Applications</relationshipLabel>
        <relationshipName>NCS_Applications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>NCS Application</label>
    <nameField>
        <displayFormat>NCSA{000000}</displayFormat>
        <label>NCS Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NCS Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Payment_method__c</fullName>
        <label>Payment method</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Cheque</fullName>
                </value>
                <value>
                    <fullName>Cash</fullName>
                </value>
                <value>
                    <fullName>Postal order</fullName>
                </value>
                <value>
                    <fullName>Credit or debit card Worldpay</fullName>
                </value>
                <value>
                    <fullName>Credit or debit card PayPal</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
                <value>
                    <fullName>NCS Campaign Call Centre</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Season__c.object
<CustomObject>
    <description>NCS season</description>
    <fields>
        <fullName>Active_season__c</fullName>
        <label>Active season</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Payment_validity_beyond_current_Season__c</fullName>
        <label>Payment validity beyond current Season</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>February 2015</fullName>
                </value>
                <value>
                    <fullName>Summer 2015</fullName>
                </value>
                <value>
                    <fullName>Autumn 2015</fullName>
                </value>
                <value>
                    <fullName>February 2016</fullName>
                </value>
                <value>
                    <fullName>Summer 2016</fullName>
                </value>
                <value>
                    <fullName>Autumn 2016</fullName>
                </value>
                <value>
                    <fullName>February 2017</fullName>
                </value>
                <value>
                    <fullName>Summer 2017</fullName>
                </value>
                <value>
                    <fullName>Autumn 2017</fullName>
                </value>
                <value>
                    <fullName>February 2018</fullName>
                </value>
                <value>
                    <fullName>Summer 2018</fullName>
                </value>
                <value>
                    <fullName>Autumn 2018</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>RCA_weekend_picklist__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Tick this if the Weekend RCA picklist is required on the OBS (generally only required for Summer)</description>
        <inlineHelpText>Tick this if the Weekend RCA picklist is required on the OBS (generally only required for Summer)</inlineHelpText>
        <label>RCA weekend picklist</label>
        <type>Checkbox</type>
    </fields>
    <label>Season</label>
    <nameField>
        <label>Season Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Seasons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Wave__c.object
<CustomObject>
    <fields>
        <fullName>Champion_school_place_limit_percentage__c</fullName>
        <description>Percentage of YP on the wave who can attend from the same champion school</description>
        <inlineHelpText>Percentage of YP on the wave who can attend from the same champion school</inlineHelpText>
        <label>Champion school place limit percentage</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Ind_school_type_place_limit_percentage__c</fullName>
        <description>Percentage of YP on the wave who can attend an independent school</description>
        <inlineHelpText>Percentage of YP on the wave who can attend an independent school</inlineHelpText>
        <label>Ind school type place limit percentage</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Season__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Which season the wave is part of.  A look up to the Season object</description>
        <label>Season</label>
        <referenceTo>Season__c</referenceTo>
        <relationshipLabel>Waves</relationshipLabel>
        <relationshipName>Waves</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Single_school_place_limit_percentage__c</fullName>
        <description>Percentage of YP on the wave who can attend the same school</description>
        <inlineHelpText>Percentage of YP on the wave who can attend the same school</inlineHelpText>
        <label>Single school place limit percentage</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>TC_Res_Venue__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>TC Res Venue</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Waves (TC Res Venue)</relationshipLabel>
        <relationshipName>TCWaves</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Wave_code__c</fullName>
        <description>Unique wave code</description>
        <inlineHelpText>Unique wave code</inlineHelpText>
        <label>Wave code</label>
        <length>25</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Wave_number__c</fullName>
        <label>Wave number</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>YP_female_place_limit_percentage__c</fullName>
        <description>Percentage of the wave that can be female</description>
        <inlineHelpText>Percentage of the wave that can be female</inlineHelpText>
        <label>YP female place limit percentage</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>YP_male_place_limit_percentage__c</fullName>
        <description>Percentage of the wave that can be male</description>
        <inlineHelpText>Percentage of the wave that can be male</inlineHelpText>
        <label>YP male place limit percentage</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>YP_place_capacity_absolute_maximum__c</fullName>
        <description>Absolute maximum of YP who can actually come on the wave - the real size of the wave</description>
        <inlineHelpText>Absolute maximum of YP who can actually come on the wave - the real size of the wave</inlineHelpText>
        <label>YP place capacity absolute maximum</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>YP_place_overbooking_capacity_percentage__c</fullName>
        <description>The additional percentage of YP who can be booked onto a wave, above the maximum wave capacity of 100%</description>
        <inlineHelpText>The additional percentage of YP who can be booked onto a wave, above the maximum wave capacity of 100%</inlineHelpText>
        <label>YP place overbooking capacity percentage</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>Wave</label>
    <nameField>
        <label>Wave Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Waves</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Test_TCN_Wave_AutoAssignHandler.cls
@isTest
public with sharing class Test_TCN_Wave_AutoAssignHandler {

    static testMethod void myUnitTest()
    {
    
        RecordType a=[Select id,Name From RecordType Where sObjectType='Account' and Name Like 'Schools' limit 1 ];
        RecordType i=[Select id,Name From RecordType Where sObjectType='Inclusion_Details__c' and Name Like 'Archived' limit 1 ];
        RecordType rc=[Select id,Name From RecordType Where sObjectType='Contact' and Name Like '%YP20%' Order By Name  limit 1 ];
        RecordType c = [SELECT Id FROM RecordType WHERE SObjectType='Cluster__c' AND Name='2012'];
        List<Contact> cntList=new List<Contact>();
        List<Wave__c> waveList=new List<Wave__c>();
        List<Wave_Selection__c> WaveSelList=new List<Wave_Selection__c>();
        
        Cluster__c cluster = new Cluster__c(Name='TestCluster4Metric',RecordTypeId = c.Id);
        insert cluster;
        Account school1 = new Account(
                          Name = 'Test Account',
                          School_Type__c = 'Independent Selective',
                          School_Code__c = 'AIS1',
                          RecordTypeId = a.id,
                          Champion_school__c = true,
                          Unique_ID_for_School__c = 'TestST'
        );
        insert school1;
        Opportunity op = new Opportunity(
                         Name = 'Test Opp',
                         StageName = 'Received',
                         CloseDate =system.today(),
                         Amount = 100,
                         Payment_Method__c = 'Cheque',
                         accountid = school1.id     
        );
        insert op;
        Contact c1 = new Contact (
                     Firstname='test',
                     Lastname='LN',
                     school__c = school1.id,
                     accountid = school1.id,
                     Date_P2_data_form_received_by_CO__c = system.today(),
                     P3_completion_date__c = system.today().adddays(1),
                     Gender__c = 'Female'
        );
        Contact c2 = new Contact (
                     Firstname='test2',
                     Lastname='LN2',
                     school__c = school1.id,
                     accountid = school1.id,
                     Date_P2_data_form_received_by_CO__c = system.today().adddays(1),
                     P3_completion_date__c =system.today().adddays(2),
                     Gender__c = 'Male'
        );
        cntList.add(c1);
        cntList.add(c2);
        insert cntList;
        
        Season__c sea = new Season__c(Name = 'TestSeason',
                                      RCA_weekend_picklist__c = true,
                                      Payment_validity_beyond_current_Season__c = 'February 2015',
                                      Active_season__c = '1'     
        );
        insert sea;

        NCS_Application__c ncs = new NCS_Application__c(YoungPerson__c = cntlist[0].Id,
                                                        AP_received__c = system.today().addDays(-3),
                                                        School__c = school1.id,
                                                        Season__c = sea.id
        );
        insert ncs;

        Inclusion_Details__c inc = new Inclusion_Details__c(RecordTypeId = i.id,
                                                            Contact__c = cntlist[0].id,
                                                            Support_Level__c = '4b - extra APL support for challenging behaviour or mental health conditions'
        );
        insert inc;

        Wave__c wv=new Wave__c();
          wv.Name='Wave Test';
          wv.Wave_number__c='1';
          wv.Wave_code__c='Wa45';
          wv.TC_Res_Venue__c = school1.id;
          wv.Season__c = sea.id;
          wv.YP_place_capacity_absolute_maximum__c = 40;
          wv.YP_place_overbooking_capacity_percentage__c = 100;
          wv.YP_female_place_limit_percentage__c = 50;
          wv.YP_male_place_limit_percentage__c = 50;
          wv.Ind_school_type_place_limit_percentage__c = 25;
          wv.Single_school_place_limit_percentage__c = 50;
          wv.Champion_school_place_limit_percentage__c = 25;
          wv.Wave_Cluster__c = cluster.id;
          wv.Enable_Autofill__c = true;
          wv.iscalculate__c = true;
          wv.Max_Number_of_SL_4b_allowed__c = 3;
          wv.Max_Number_of_SL_4a_allowed__c = 2;
        insert wv;

        Test.startTest();

        Wave_Selection__c ws1 = new Wave_Selection__c(
                                Young_Person__c = cntlist[0].id,
                                Wave__c = wv.id,
                                Inclusion_Detail__c = inc.id,
                                NCS_Application__c = ncs.id,
                                Status__c = 'Assigned',
                                Date_put_on_waiting_list__c = system.today().addDays(-3),
                                Access_category_filter__c = '4b - extra APL support for challenging behaviour or mental health conditions'
        );
        Wave_Selection__c ws2 = new Wave_Selection__c(
                                Young_Person__c = cntlist[1].id,
                                Wave__c = wv.id,
                                Inclusion_Detail__c = inc.id,
                                Status__c = 'Reserved',
                                NCS_Application__c = ncs.id,
                                Date_put_on_waiting_list__c = system.today().addDays(-3),
                                Access_category_filter__c = '4a – Extra APL support for YPs with restricted mobility, language barrier or learning difficulties'                
        );
        Wave_Selection__c ws3 = new Wave_Selection__c(
                                Young_Person__c = cntlist[0].id,
                                Wave__c = wv.id,
                                Inclusion_Detail__c = inc.id,
                                Status__c = 'Waiting List',
                                NCS_Application__c = ncs.id,
                                Date_put_on_waiting_list__c = system.today().addDays(-2),
                                Access_category_filter__c = '4a – Extra APL support for YPs with restricted mobility, language barrier or learning difficulties'                
        );
        Wave_Selection__c ws4 = new Wave_Selection__c(
                                Young_Person__c = cntlist[1].id,
                                Wave__c = wv.id,
                                Inclusion_Detail__c = inc.id,
                                Status__c = 'Waiting List',
                                NCS_Application__c = ncs.id,
                                Date_put_on_waiting_list__c = system.today().addDays(-1),
                                Access_category_filter__c = '4b - extra APL support for challenging behaviour or mental health conditions'                
        );
        Wave_Selection__c ws6 = new Wave_Selection__c(
                                Young_Person__c = cntlist[1].id,
                                Wave__c = wv.id,
                                Inclusion_Detail__c = inc.id,
                                Status__c = 'Waiting List',
                                NCS_Application__c = ncs.id,
                                Date_put_on_waiting_list__c = system.today().addDays(-1),
                                Access_category_filter__c = '4b - extra APL support for challenging behaviour or mental health conditions'                
        );
        Wave_Selection__c ws7 = new Wave_Selection__c(
                                Young_Person__c = cntlist[1].id,
                                Wave__c = wv.id,
                                Inclusion_Detail__c = inc.id,
                                Status__c = 'Waiting List',
                                NCS_Application__c = ncs.id,
                                Date_put_on_waiting_list__c = system.today().addDays(-2),
                                Access_category_filter__c = '4a – Extra APL support for YPs with restricted mobility, language barrier or learning difficulties'                
        );

        WaveSelList.add(ws1);
        WaveSelList.add(ws2);
        WaveSelList.add(ws3);
        WaveSelList.add(ws4);
        WaveSelList.add(ws6);
        WaveSelList.add(ws7);

        insert WaveSelList;

        List<Wave_Selection__c> wwlist = new List<Wave_Selection__c>();
        List<Wave_Selection__c> wwlist2 = new List<Wave_Selection__c>();

        wwlist = [SELECT id, Access_category_filter__c, Status__c FROM Wave_Selection__c WHERE Id IN: WaveSelList AND Status__c =: 'Reserved'];
        wwlist[0].Access_category_filter__c = '4b - extra APL support for challenging behaviour or mental health conditions';     
        
        update wwlist[0];

        Test.stopTest();
    }

    static testMethod void myUnitTest2()
    {
    
        RecordType a=[Select id,Name From RecordType Where sObjectType='Account' and Name Like 'Schools' limit 1 ];
        RecordType i=[Select id,Name From RecordType Where sObjectType='Inclusion_Details__c' and Name Like 'Archived' limit 1 ];
        RecordType rc=[Select id,Name From RecordType Where sObjectType='Contact' and Name Like '%YP20%' Order By Name  limit 1 ];
        RecordType c = [SELECT Id FROM RecordType WHERE SObjectType='Cluster__c' AND Name='2012'];
        List<Contact> cntList=new List<Contact>();
        List<Wave__c> waveList=new List<Wave__c>();
        List<Wave_Selection__c> WaveSelList=new List<Wave_Selection__c>();
        
        Cluster__c cluster = new Cluster__c(Name='TestCluster4Metric',RecordTypeId = c.Id);
        insert cluster;
        Account school1 = new Account(
                          Name = 'Test Account',
                          School_Type__c = 'Independent Selective',
                          School_Code__c = 'AIS1',
                          RecordTypeId = a.id,
                          Champion_school__c = true,
                          Unique_ID_for_School__c = 'TestST'
        );
        insert school1;
        Opportunity op = new Opportunity(
                         Name = 'Test Opp',
                         StageName = 'Received',
                         CloseDate =system.today(),
                         Amount = 100,
                         Payment_Method__c = 'Cheque',
                         accountid = school1.id     
        );
        insert op;
        Contact c1 = new Contact (
                     Firstname='test',
                     Lastname='LN',
                     school__c = school1.id,
                     accountid = school1.id,
                     Date_P2_data_form_received_by_CO__c = system.today(),
                     P3_completion_date__c = system.today().adddays(1),
                     Gender__c = 'Female'
        );
        Contact c2 = new Contact (
                     Firstname='test2',
                     Lastname='LN2',
                     school__c = school1.id,
                     accountid = school1.id,
                     Date_P2_data_form_received_by_CO__c = system.today().adddays(1),
                     P3_completion_date__c =system.today().adddays(2),
                     Gender__c = 'Male'
        );
        cntList.add(c1);
        cntList.add(c2);
        insert cntList;
        
        Season__c sea = new Season__c(Name = 'TestSeason',
                                      RCA_weekend_picklist__c = true,
                                      Payment_validity_beyond_current_Season__c = 'February 2015',
                                      Active_season__c = '1'     
        );
        insert sea;

        NCS_Application__c ncs = new NCS_Application__c(YoungPerson__c = cntlist[0].Id,
                                                        AP_received__c = system.today().addDays(-3),
                                                        School__c = school1.id,
                                                        Season__c = sea.id
        );
        insert ncs;

        Inclusion_Details__c inc = new Inclusion_Details__c(RecordTypeId = i.id,
                                                            Contact__c = cntlist[0].id,
                                                            Support_Level__c = '4b - extra APL support for challenging behaviour or mental health conditions'
        );
        insert inc;

        Wave__c wv=new Wave__c();
          wv.Name='Wave Test';
          wv.Wave_number__c='1';
          wv.Wave_code__c='Wa45';
          wv.TC_Res_Venue__c = school1.id;
          wv.Season__c = sea.id;
          wv.YP_place_capacity_absolute_maximum__c = 40;
          wv.YP_place_overbooking_capacity_percentage__c = 100;
          wv.YP_female_place_limit_percentage__c = 50;
          wv.YP_male_place_limit_percentage__c = 50;
          wv.Ind_school_type_place_limit_percentage__c = 25;
          wv.Single_school_place_limit_percentage__c = 50;
          wv.Champion_school_place_limit_percentage__c = 25;
          wv.Wave_Cluster__c = cluster.id;
          wv.Enable_Autofill__c = true;
          wv.iscalculate__c = true;
          wv.Max_Number_of_SL_4b_allowed__c = 3;
          wv.Max_Number_of_SL_4a_allowed__c = 2;
        insert wv;

        Test.startTest();

        Wave_Selection__c ws1 = new Wave_Selection__c(
                                Young_Person__c = cntlist[0].id,
                                Wave__c = wv.id,
                                Inclusion_Detail__c = inc.id,
                                NCS_Application__c = ncs.id,
                                Status__c = 'Assigned',
                                Date_put_on_waiting_list__c = system.today().addDays(-3),
                                Access_category_filter__c = '4b - extra APL support for challenging behaviour or mental health conditions'
        );
        Wave_Selection__c ws2 = new Wave_Selection__c(
                                Young_Person__c = cntlist[1].id,
                                Wave__c = wv.id,
                                Inclusion_Detail__c = inc.id,
                                Status__c = 'Reserved',
                                NCS_Application__c = ncs.id,
                                Date_put_on_waiting_list__c = system.today().addDays(-3),
                                Access_category_filter__c = '4a – Extra APL support for YPs with restricted mobility, language barrier or learning difficulties'                
        );
        Wave_Selection__c ws3 = new Wave_Selection__c(
                                Young_Person__c = cntlist[0].id,
                                Wave__c = wv.id,
                                Inclusion_Detail__c = inc.id,
                                Status__c = 'Waiting List',
                                NCS_Application__c = ncs.id,
                                Date_put_on_waiting_list__c = system.today().addDays(-2),
                                Access_category_filter__c = '4a – Extra APL support for YPs with restricted mobility, language barrier or learning difficulties'                
        );
        Wave_Selection__c ws4 = new Wave_Selection__c(
                                Young_Person__c = cntlist[1].id,
                                Wave__c = wv.id,
                                Inclusion_Detail__c = inc.id,
                                Status__c = 'Waiting List',
                                NCS_Application__c = ncs.id,
                                Date_put_on_waiting_list__c = system.today().addDays(-1),
                                Access_category_filter__c = '4b - extra APL support for challenging behaviour or mental health conditions'                
        );
        Wave_Selection__c ws6 = new Wave_Selection__c(
                                Young_Person__c = cntlist[1].id,
                                Wave__c = wv.id,
                                Inclusion_Detail__c = inc.id,
                                Status__c = 'Waiting List',
                                NCS_Application__c = ncs.id,
                                Date_put_on_waiting_list__c = system.today().addDays(-1),
                                Access_category_filter__c = '4b - extra APL support for challenging behaviour or mental health conditions'                
        );
        Wave_Selection__c ws7 = new Wave_Selection__c(
                                Young_Person__c = cntlist[1].id,
                                Wave__c = wv.id,
                                Inclusion_Detail__c = inc.id,
                                Status__c = 'Waiting List',
                                NCS_Application__c = ncs.id,
                                Date_put_on_waiting_list__c = system.today().addDays(-2),
                                Access_category_filter__c = '4a – Extra APL support for YPs with restricted mobility, language barrier or learning difficulties'                
        );

        WaveSelList.add(ws1);
        WaveSelList.add(ws2);
        WaveSelList.add(ws3);
        WaveSelList.add(ws4);
        WaveSelList.add(ws6);
        WaveSelList.add(ws7);

        insert WaveSelList;

        List<Wave_Selection__c> wwlist = new List<Wave_Selection__c>();
        List<Wave_Selection__c> wwlist2 = new List<Wave_Selection__c>();

        wwlist = [SELECT id, Access_category_filter__c, Status__c FROM Wave_Selection__c WHERE Id IN: WaveSelList AND Status__c =: 'Assigned'];
        wwlist[0].Status__c = 'Withdrawn';     
        
        update wwlist[0];

        Test.stopTest();
    }

    static testMethod void myUnitTest3()
    {
    
        RecordType a=[Select id,Name From RecordType Where sObjectType='Account' and Name Like 'Schools' limit 1 ];
        RecordType i=[Select id,Name From RecordType Where sObjectType='Inclusion_Details__c' and Name Like 'Archived' limit 1 ];
        RecordType rc=[Select id,Name From RecordType Where sObjectType='Contact' and Name Like '%YP20%' Order By Name  limit 1 ];
        RecordType c = [SELECT Id FROM RecordType WHERE SObjectType='Cluster__c' AND Name='2012'];
        List<Contact> cntList=new List<Contact>();
        List<Wave__c> waveList=new List<Wave__c>();
        List<Wave_Selection__c> WaveSelList=new List<Wave_Selection__c>();
        
        Cluster__c cluster = new Cluster__c(Name='TestCluster4Metric',RecordTypeId = c.Id);
        insert cluster;
        Account school1 = new Account(
                          Name = 'Test Account',
                          School_Type__c = 'Independent Selective',
                          School_Code__c = 'AIS1',
                          RecordTypeId = a.id,
                          Champion_school__c = true,
                          Unique_ID_for_School__c = 'TestST'
        );
        insert school1;
        Opportunity op = new Opportunity(
                         Name = 'Test Opp',
                         StageName = 'Received',
                         CloseDate =system.today(),
                         Amount = 100,
                         Payment_Method__c = 'Cheque',
                         accountid = school1.id     
        );
        insert op;
        Contact c1 = new Contact (
                     Firstname='test',
                     Lastname='LN',
                     school__c = school1.id,
                     accountid = school1.id,
                     Date_P2_data_form_received_by_CO__c = system.today(),
                     P3_completion_date__c = system.today().adddays(1),
                     Gender__c = 'Female'
        );
        Contact c2 = new Contact (
                     Firstname='test2',
                     Lastname='LN2',
                     school__c = school1.id,
                     accountid = school1.id,
                     Date_P2_data_form_received_by_CO__c = system.today().adddays(1),
                     P3_completion_date__c =system.today().adddays(2),
                     Gender__c = 'Male'
        );
        cntList.add(c1);
        cntList.add(c2);
        insert cntList;
        
        Season__c sea = new Season__c(Name = 'TestSeason',
                                      RCA_weekend_picklist__c = true,
                                      Payment_validity_beyond_current_Season__c = 'February 2015',
                                      Active_season__c = '1'     
        );
        insert sea;

        NCS_Application__c ncs = new NCS_Application__c(YoungPerson__c = cntlist[0].Id,
                                                        AP_received__c = system.today().addDays(-3),
                                                        School__c = school1.id,
                                                        Season__c = sea.id
        );
        insert ncs;

        Inclusion_Details__c inc = new Inclusion_Details__c(RecordTypeId = i.id,
                                                            Contact__c = cntlist[0].id,
                                                            Support_Level__c = '4b - extra APL support for challenging behaviour or mental health conditions'
        );
        insert inc;

        Wave__c wv=new Wave__c();
          wv.Name='Wave Test';
          wv.Wave_number__c='1';
          wv.Wave_code__c='Wa45';
          wv.TC_Res_Venue__c = school1.id;
          wv.Season__c = sea.id;
          wv.YP_place_capacity_absolute_maximum__c = 40;
          wv.YP_place_overbooking_capacity_percentage__c = 100;
          wv.YP_female_place_limit_percentage__c = 50;
          wv.YP_male_place_limit_percentage__c = 50;
          wv.Ind_school_type_place_limit_percentage__c = 25;
          wv.Single_school_place_limit_percentage__c = 50;
          wv.Champion_school_place_limit_percentage__c = 25;
          wv.Wave_Cluster__c = cluster.id;
          wv.Enable_Autofill__c = true;
          wv.iscalculate__c = true;
          wv.Max_Number_of_SL_4b_allowed__c = 3;
          wv.Max_Number_of_SL_4a_allowed__c = 2;
        insert wv;

        Test.startTest();

        Wave_Selection__c ws1 = new Wave_Selection__c(
                                Young_Person__c = cntlist[0].id,
                                Wave__c = wv.id,
                                Inclusion_Detail__c = inc.id,
                                NCS_Application__c = ncs.id,
                                Status__c = 'Assigned',
                                Date_put_on_waiting_list__c = system.today().addDays(-3),
                                Access_category_filter__c = '4b - extra APL support for challenging behaviour or mental health conditions'
        );
        Wave_Selection__c ws2 = new Wave_Selection__c(
                                Young_Person__c = cntlist[1].id,
                                Wave__c = wv.id,
                                Inclusion_Detail__c = inc.id,
                                Status__c = 'Reserved',
                                NCS_Application__c = ncs.id,
                                Date_put_on_waiting_list__c = system.today().addDays(-3),
                                Access_category_filter__c = '4a – Extra APL support for YPs with restricted mobility, language barrier or learning difficulties'                
        );
        Wave_Selection__c ws3 = new Wave_Selection__c(
                                Young_Person__c = cntlist[0].id,
                                Wave__c = wv.id,
                                Inclusion_Detail__c = inc.id,
                                Status__c = 'Waiting List',
                                NCS_Application__c = ncs.id,
                                Date_put_on_waiting_list__c = system.today().addDays(-2),
                                Access_category_filter__c = '4a – Extra APL support for YPs with restricted mobility, language barrier or learning difficulties'                
        );
        Wave_Selection__c ws4 = new Wave_Selection__c(
                                Young_Person__c = cntlist[1].id,
                                Wave__c = wv.id,
                                Inclusion_Detail__c = inc.id,
                                Status__c = 'Waiting List',
                                NCS_Application__c = ncs.id,
                                Date_put_on_waiting_list__c = system.today().addDays(-1),
                                Access_category_filter__c = '4b - extra APL support for challenging behaviour or mental health conditions'                
        );
        Wave_Selection__c ws6 = new Wave_Selection__c(
                                Young_Person__c = cntlist[1].id,
                                Wave__c = wv.id,
                                Inclusion_Detail__c = inc.id,
                                Status__c = 'Waiting List',
                                NCS_Application__c = ncs.id,
                                Date_put_on_waiting_list__c = system.today().addDays(-1),
                                Access_category_filter__c = '4b - extra APL support for challenging behaviour or mental health conditions'                
        );
        Wave_Selection__c ws7 = new Wave_Selection__c(
                                Young_Person__c = cntlist[1].id,
                                Wave__c = wv.id,
                                Inclusion_Detail__c = inc.id,
                                Status__c = 'Waiting List',
                                NCS_Application__c = ncs.id,
                                Date_put_on_waiting_list__c = system.today().addDays(-2),
                                Access_category_filter__c = '4a – Extra APL support for YPs with restricted mobility, language barrier or learning difficulties'                
        );

        WaveSelList.add(ws1);
        WaveSelList.add(ws2);
        WaveSelList.add(ws3);
        WaveSelList.add(ws4);
        WaveSelList.add(ws6);
        WaveSelList.add(ws7);

        insert WaveSelList;

        List<Wave_Selection__c> wwlist = new List<Wave_Selection__c>();
        List<Wave_Selection__c> wwlist2 = new List<Wave_Selection__c>();

        wwlist = [SELECT id, Access_category_filter__c, Status__c FROM Wave_Selection__c WHERE Id IN: WaveSelList AND Status__c ='Reserved'];
        wwlist[0].Status__c = 'Withdrawn';     
        
        update wwlist[0];
        
        Test.stopTest();
    }

}