objects/Inclusion_Details__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Inclusion Details</relationshipLabel>
        <relationshipName>Inclusion_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Sales_Tracker_Identifier__c</fullName>
        <description>This is an indexed field that is used by the Sales Tracker flow to query the inclusion detail records. it concatenates the 18 digit school ID and the 18 digit Contact ID</description>
        <externalId>true</externalId>
        <label>Sales Tracker Identifier</label>
        <length>36</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>School_Code__c</fullName>
        <formula>Contact__r.School_s_code_display__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>School Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Season__c</fullName>
        <formula>Contact__r.NCS_Application_Primary_Season__c</formula>
        <label>Season</label>
        <type>Text</type>
    </fields>
    <label>Inclusion Detail</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Inclusion Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inclusion Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/NCS_Application__c.object
<CustomObject>
    <fields>
        <fullName>School__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>School</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Schools</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>NCS Applications</relationshipLabel>
        <relationshipName>NCS_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Season__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Season</label>
        <referenceTo>Season__c</referenceTo>
        <relationshipLabel>NCS Applications</relationshipLabel>
        <relationshipName>NCS_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>YoungPerson__c</fullName>
        <label>Young Person</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>NCS Applications</relationshipLabel>
        <relationshipName>NCS_Applications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>NCS Application</label>
    <nameField>
        <displayFormat>NCSA{000000}</displayFormat>
        <label>NCS Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NCS Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Sales_Tracker__c.object
<CustomObject>
    <fields>
        <fullName>EOIs__c</fullName>
        <label>EOIs</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Paid__c</fullName>
        <label>Paid</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SU__c</fullName>
        <label>SU</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Sales Tracker</label>
    <nameField>
        <label>Sales Tracker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Trackers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/School_Activities__c.object
<CustomObject>
    <description>School notes and information by Programme year and season</description>
    <fields>
        <fullName>Sales_Tracker_Pendulum__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sales Tracker Pendulum</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>School_Code__c</fullName>
        <formula>School__r.School_s_code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>School Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>School__c</fullName>
        <description>Master-detail link to the school record</description>
        <label>School</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>School Activities</relationshipLabel>
        <relationshipName>Past_School_Activities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Season__c</fullName>
        <formula>IF(CONTAINS( RecordType.Name ,&quot;Summer&quot;),&quot;Summer&quot;,

IF(CONTAINS( RecordType.Name ,&quot;Autumn&quot;),&quot;Autumn&quot;,&quot;Spring&quot;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Season</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Season_lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Season</label>
        <referenceTo>Season__c</referenceTo>
        <relationshipLabel>School Activities</relationshipLabel>
        <relationshipName>School_Activities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>School Activity</label>
    <nameField>
        <displayFormat>S-{000000}</displayFormat>
        <label>Past School Activities ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>School Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Season__c.object
<CustomObject>
    <description>NCS season</description>
    <fields>
        <fullName>Date_Sales_season_commences__c</fullName>
        <description>This is the date from which an EOI is considered. This is referenced from the Sales Target Tracking system</description>
        <inlineHelpText>This is the date from which an EOI is considered</inlineHelpText>
        <label>Date Sales season commences</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_Sales_tracker_finishes__c</fullName>
        <label>Date Sales tracker finishes</label>
        <type>Date</type>
    </fields>
    <label>Season</label>
    <nameField>
        <label>Season Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Seasons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/test_SalesTracker.cls
/**
  * @Modified By : Prajakta
  * @Description : Batch class to get inclusion details and insert Sales Tracker records accordingly
  * @Created Date: 16 April 2016
 */
@isTest
// this will test the sales tracker code that calculates the metrics on a daily basis
public class test_SalesTracker {
    @TestSetup
    static void createTestData() {
        
        Season__c Season = new Season__c();                     // create season record and insert
        Season.Name = 'Summer 2016';
        Season.Date_Sales_tracker_finishes__c = System.today() + 365;
        Season.Date_Sales_season_commences__c = System.today()-365;
        Insert Season;
        
        Account School = new Account();                         // create school account record and insert
        School.RecordTypeId = '01280000000PxZO';
        School.School_code__c = 'AAAA';
        School.Name = 'School';
        Insert School;
         
        Date Yesterday = System.today() -1;
        List<School_Activities__c> schoolActivities = new List<School_Activities__c>();
        for( Integer i = 0; i < 1; i++ ) {
            
            schoolActivities.add(new School_Activities__c( School__c = School.id,
                                                           Season_lookup__c = Season.id ));
        }
        
        insert schoolActivities;
        
        List<RecordType> contactRecordType = [ SELECT Name, Id 
                                               FROM RecordType 
                                               WHERE sObjectType = 'Contact' AND DeveloperName = 'Young_Person' ];
        
        Contact YP = new Contact();
        
        YP.AccountID = School.Id;
        YP.FirstName = 'YP1';
        YP.LastName = 'YP';
        YP.RecordTypeId = contactRecordType[0].id;
        YP.School__c = School.Id;
        YP.NCS_Application_Primary_Season__c = 'Summer 2016';
        YP.LeadSource = 'School paper form (Marketing)';
        YP.Date_P2_data_form_received_by_CO__c = System.today();
        YP.Dupe_exclude_from_processes__c = FALSE;
        
        Insert YP;
        
        List<Inclusion_Details__c> inclusionDetailsLst = new List<Inclusion_Details__c>();
        for( Integer i = 0; i < 1; i++ ) {
            
            inclusionDetailsLst.add(new Inclusion_Details__c( Contact__c = YP.ID,
                                                              Sales_Tracker_Identifier__c= School.Id ));
        }
        
        insert inclusionDetailsLst;
        
        NCS_Application__c NCS = New NCS_Application__c();
        NCS.YoungPerson__c = YP.Id;
        NCS.Season__c = Season.Id;
        Insert NCS;
        
                
        YP.Update_NCS_Application_Primary_Season__c = 'Summer 2016';    // Ensure that Summer 2016 is the main season
        Update YP;
        
        
    }
    
     /**
      * @purpose : test school activity trigger
     */
    public static testMethod void testGetSalesTrackerMethod(){
        
        List<School_Activities__c> schoolActivities = [ SELECT Id,
                                                               Sales_Tracker_Pendulum__c
                                                        FROM School_Activities__c ];
        Test.startTest();
        System.debug('schoolActivities record in test clas : ' + schoolActivities);
        for( School_Activities__c schoolActivity : schoolActivities ) {
            schoolActivity.Sales_Tracker_Pendulum__c = TRUE;
        }
        
        update schoolActivities;
        
        
        Test.stopTest();
        
        List<Sales_Tracker__c> salesTrackerList = [ SELECT EOIs__c, SU__c, Paid__c 
                                                    FROM Sales_Tracker__c ];
                                                    
        System.debug('salesTrackerList : ' + salesTrackerList );
        
        System.assertEquals( schoolActivities.size(),salesTrackerList.size());
        
        System.assert( salesTrackerList[0].EOIs__c != 0);
        
    }
}