objects/Inclusion_Details__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Inclusion Details</relationshipLabel>
        <relationshipName>Inclusion_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Season__c</fullName>
        <formula>Contact__r.NCS_Application_Primary_Season__c</formula>
        <label>Season</label>
        <type>Text</type>
    </fields>
    <label>Inclusion Detail</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Inclusion Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inclusion Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/NCS_Application__c.object
<CustomObject>
    <fields>
        <fullName>Parent_Email__c</fullName>
        <inlineHelpText>Updated via a workflow before sending out Telesales emails</inlineHelpText>
        <label>PG Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Season__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Season</label>
        <referenceTo>Season__c</referenceTo>
        <relationshipLabel>NCS Applications</relationshipLabel>
        <relationshipName>NCS_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>YoungPerson__c</fullName>
        <label>Young Person</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>NCS Applications</relationshipLabel>
        <relationshipName>NCS_Applications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>NCS Application</label>
    <nameField>
        <displayFormat>NCSA{000000}</displayFormat>
        <label>NCS Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NCS Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/NCS_Data_Entry_Staging__c.object
<CustomObject>
    <description>Staging object for transforming Captricity data into Account, Contact, NCS Application, Inclusion Details, Relationship records.</description>
    <fields>
        <fullName>Parent_Email__c</fullName>
        <label>Parent Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Season__c</fullName>
        <label>Season</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>YP_Email_address__c</fullName>
        <label>YP Email address</label>
        <type>Email</type>
    </fields>
    <label>NCS Data Entry Staging</label>
    <nameField>
        <displayFormat>NCSDES-{000000}</displayFormat>
        <label>NCS Data Entry Staging Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NCS Data Entry Staging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/NCS_Data_Entry_Staging_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Source_Field__c</fullName>
        <description>NCS Data Entry Staging Field (Mapping from)</description>
        <inlineHelpText>This is the API name of the field on the NCS Data Entry Staging Object ie; yp_first_name__c</inlineHelpText>
        <label>Source Field</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Target_Field__c</fullName>
        <description>Target field, this is the field the Source Field maps to on the related Salesforce object</description>
        <inlineHelpText>Target Field on Target Object, uses the Salesforce API name ie, firstName, ap_recieved__c</inlineHelpText>
        <label>Target Field</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Target_Object__c</fullName>
        <inlineHelpText>Salesforce Object API name ie, Contact, Inclusion_Details__c</inlineHelpText>
        <label>Target Object</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Target_Type__c</fullName>
        <inlineHelpText>Target type is used to specify the target object for use within the APEX classes bg_NCSDataEntry

ENSURE ALL CAPITALS

Values are;
INC
NCS
YPCON
PGCON
YP&amp;PGCON</inlineHelpText>
        <label>Target Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>NCS Data Entry Staging Settings</label>
</CustomObject>

objects/NCS_Data_Entry_Template_Type_Rules__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Contains the rules for each Template - IE, If &apos;EOI&apos; Template then Create Contacts only. (This isn&apos;t the OVERWRITE check)</description>
    <fields>
        <fullName>Upsert_Guardian_Contact__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>For the template type - Do we create a new Guardian Contact</inlineHelpText>
        <label>Upsert Guardian Contact</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Upsert_Inclusion_Detail__c</fullName>
        <defaultValue>false</defaultValue>
        <description>For the template type - Do we create a new Inclusion Details record</description>
        <inlineHelpText>For the template type - Do we create a new Inclusion Details record</inlineHelpText>
        <label>Upsert Inclusion Detail</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Upsert_NCS_Application__c</fullName>
        <defaultValue>false</defaultValue>
        <description>For the template type - Do we create a new NCS Application</description>
        <inlineHelpText>For the template type - Do we create a new NCS Application</inlineHelpText>
        <label>Upsert NCS Application</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Upsert_Young_Contact__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>For the template type - Do we create a new Young Contact?</inlineHelpText>
        <label>Upsert Young Contact</label>
        <type>Checkbox</type>
    </fields>
    <label>NCS Data Entry Template Type Rules</label>
</CustomObject>

objects/Relationship__c.object
<CustomObject>
    <description>Relationship records for relationship widget.Keeps relationships  between contact account,account contact,account account,contact contact.</description>
    <fields>
        <fullName>From_Individual__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Pick only ONE &quot;From&quot;, either Institution or Individual</inlineHelpText>
        <label>From Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Relationships (From Individual)</relationshipLabel>
        <relationshipName>Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>To_Individual__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>To Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Relationships (To Individual)</relationshipLabel>
        <relationshipName>Affiliations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Relationship</label>
    <nameField>
        <label>Relationship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Season__c.object
<CustomObject>
    <description>NCS season</description>
    <label>Season</label>
    <nameField>
        <label>Season Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Seasons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/bg_UnitTestHelper.cls
/********************************************************************
 * bg_UnitTestHelper
 *
 * Utility class that contains methods to create test data for all bg_ Classes
 * 
 * Author: Antony Daley
 * Created: 19-03-2015
 * Changes: 
 *
 ********************************************************************/
@isTest
public class bg_UnitTestHelper
{
	
	public static Account GetAccount(String name)
	{
		Account a = new Account();
		a.Name = name;
		
		a.BillingCity = 'Never Gonna';
        a.BillingCountry = 'Give You Up';
        a.BillingPostalCode = 'NE1 1NE';
        a.BillingState = 'Never Gonna';
        a.BillingStreet = 'Let You Down';
		
		return a;
	}
	
	public static Account CreateAccount(String name)
	{
		Account a = getAccount(name);
		
		insert a;
		return a;
	}
	
	
	
	public static Contact GetContact(String firstName, String lastName, Id accountId, Id recordTypeId, String emailAddress)
	{
		Contact c = new Contact();
		c.FirstName = firstName;
		c.LastName = lastName;
		c.AccountId = accountId;
		c.RecordTypeId = recordTypeId;
		c.Email = emailAddress;
		
		return c;
	}
	
	public static Contact CreateContact(String firstName, String lastName, Id accountId, Id recordTypeId, String emailAddress)
	{
		Contact c = getContact(firstName, lastName, accountId, recordTypeId, emailAddress);
		
		insert c;
		return c;
	}
	
	
	
	public static NCS_Application__c GetNCSApplication(Id contactId, Id seasonId)
	{
		NCS_Application__c ncs = new NCS_Application__c();
		ncs.YoungPerson__c = contactId;
		ncs.Season__c = seasonId;
		
		return ncs;
	}
	
	public static NCS_Application__c CreateNCSApplication(Id contactId, Id seasonId)
	{
		NCS_Application__c ncs = getNCSApplication(contactId, seasonId);
		
		insert ncs;
		return ncs;
	}
	
	
	
	public static Season__c GetSeason(String name)
	{
		Season__c s = new Season__c();
		s.Name = name;
		
		return s;
	}
	
	public static Season__c CreateSeason(String name)
	{
		Season__c s = getSeason(name);
		
		insert s;
		return s;
	}
	
	
	
	public static Inclusion_Details__c GetInclusion(Id contactId, Id recordTypeId)
	{
		
		Inclusion_Details__c i = new Inclusion_Details__c();
		i.Contact__c = contactId;
		i.RecordTypeId = recordTypeId;
		
		return i;
	}
	
	public static Inclusion_Details__c CreateInclusion(Id contactId, Id recordTypeId)
	{
		Inclusion_Details__c i = getInclusion(contactId, recordTypeId);
		
		insert i;
		return i;
	}
	
	
	
	public static NCS_Data_Entry_Staging__c GetStagingObj(String youngPersonEmailAddress, String oldPersonEmailAddress)
	{
		NCS_Data_Entry_Staging__c stagingObj = new NCS_Data_Entry_Staging__c();
		stagingObj.YP_Email_address__c = youngPersonEmailAddress;
		stagingObj.parent_email__c = oldPersonEmailAddress;
		
		return stagingObj;
	}
	
	public static NCS_Data_Entry_Staging__c CreateStagingObj(String youngPersonEmailAddress, String oldPersonEmailAddress)
	{
		NCS_Data_Entry_Staging__c stagingObj = getStagingObj(youngPersonEmailAddress, oldPersonEmailAddress);
		
		insert stagingObj;
		return stagingObj;
	}
	
	
	
	public static Relationship__c GetRelationship(String name, Id fromContactId, Id toContactId)
	{
		Relationship__c relationship = new Relationship__c();
		relationship.Name = name;
		relationship.From_Individual__c = fromContactId;
		relationship.To_Individual__c = toContactId;
		
		return relationship;
	}
	
	public static Relationship__c CreateRelationship(String name, Id fromContactId, Id toContactId)
	{
		Relationship__c relationship = getRelationship(name, fromContactId, toContactId);
		
		insert relationship;
		return relationship;
	}
	
	public static NCS_Data_Entry_Staging_Settings__c GetFieldMappingCustomSetting(String settingName, String target_Field, String target_Object, String source_Field, String target_Type)
	{
		NCS_Data_Entry_Staging_Settings__c cstSetting = new NCS_Data_Entry_Staging_Settings__c();
        
        cstSetting.Name = settingName;
        cstSetting.Target_Field__c = target_Field;
        cstSetting.Target_Object__c = target_Object;
        cstSetting.Source_Field__c = source_Field;
        cstSetting.Target_Type__c = target_Type;
		
		return cstSetting;
	}
	
	public static NCS_Data_Entry_Staging_Settings__c CreateFieldMappingCustomSetting(String settingName, String target_Field, String target_Object, String source_Field, String target_Type)
	{
		NCS_Data_Entry_Staging_Settings__c cstSetting = GetFieldMappingCustomSetting(settingName, target_Field, target_Object, source_Field, target_Type);
		
		insert cstSetting;
		return cstSetting;
	}
	
	public static NCS_Data_Entry_Template_Type_Rules__c GetTemplateTypeCustomSetting(String settingName, Boolean ypUpsert, Boolean pgUpsert, Boolean ncsUpsert, Boolean incUpsert)
	{
		NCS_Data_Entry_Template_Type_Rules__c cstSetting = new NCS_Data_Entry_Template_Type_Rules__c();
        
        cstSetting.Name = settingName;
        cstSetting.Upsert_Young_Contact__c = ypUpsert;
        cstSetting.Upsert_Guardian_Contact__c = pgUpsert;
        cstSetting.Upsert_NCS_Application__c = ncsUpsert;
        cstSetting.Upsert_Inclusion_Detail__c = incUpsert;
		
		return cstSetting;
	}
	
	public static NCS_Data_Entry_Template_Type_Rules__c CreateTemplateTypeCustomSetting(String settingName, Boolean ypUpsert, Boolean pgUpsert, Boolean ncsUpsert, Boolean incUpsert)
	{
		NCS_Data_Entry_Template_Type_Rules__c cstSetting = GetTemplateTypeCustomSetting(settingName, ypUpsert, pgUpsert, ncsUpsert, incUpsert);
		
		insert cstSetting;
		return cstSetting;
	}
}