objects/Inclusion_Details__c.object
<CustomObject>
    <fields>
        <fullName>Season__c</fullName>
        <formula>Contact__r.NCS_Application_Primary_Season__c</formula>
        <label>Season</label>
        <type>Text</type>
    </fields>
    <label>Inclusion Detail</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Inclusion Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inclusion Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/NCS_Application__c.object
<CustomObject>
    <fields>
        <fullName>Home_Phone__c</fullName>
        <formula>YoungPerson__r.HomePhone</formula>
        <label>Home Phone</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_Email__c</fullName>
        <inlineHelpText>Updated via a workflow before sending out Telesales emails</inlineHelpText>
        <label>PG Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Season__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Season</label>
        <referenceTo>Season__c</referenceTo>
        <relationshipLabel>NCS Applications</relationshipLabel>
        <relationshipName>NCS_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>NCS Application</label>
    <nameField>
        <displayFormat>NCSA{000000}</displayFormat>
        <label>NCS Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NCS Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/NCS_Data_Entry_Staging__c.object
<CustomObject>
    <description>Staging object for transforming Captricity data into Account, Contact, NCS Application, Inclusion Details, Relationship records.</description>
    <fields>
        <fullName>Home_Phone__c</fullName>
        <label>Home Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Parent_Email__c</fullName>
        <label>Parent Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Season__c</fullName>
        <label>Season</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>NCS Data Entry Staging</label>
    <nameField>
        <displayFormat>NCSDES-{000000}</displayFormat>
        <label>NCS Data Entry Staging Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NCS Data Entry Staging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/NCS_Data_Entry_Staging_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Source_Field__c</fullName>
        <description>NCS Data Entry Staging Field (Mapping from)</description>
        <inlineHelpText>This is the API name of the field on the NCS Data Entry Staging Object ie; yp_first_name__c</inlineHelpText>
        <label>Source Field</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Target_Field__c</fullName>
        <description>Target field, this is the field the Source Field maps to on the related Salesforce object</description>
        <inlineHelpText>Target Field on Target Object, uses the Salesforce API name ie, firstName, ap_recieved__c</inlineHelpText>
        <label>Target Field</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Target_Object__c</fullName>
        <inlineHelpText>Salesforce Object API name ie, Contact, Inclusion_Details__c</inlineHelpText>
        <label>Target Object</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Target_Type__c</fullName>
        <inlineHelpText>Target type is used to specify the target object for use within the APEX classes bg_NCSDataEntry

ENSURE ALL CAPITALS

Values are;
INC
NCS
YPCON
PGCON
YP&amp;PGCON</inlineHelpText>
        <label>Target Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>NCS Data Entry Staging Settings</label>
</CustomObject>

objects/Relationship__c.object
<CustomObject>
    <description>Relationship records for relationship widget.Keeps relationships  between contact account,account contact,account account,contact contact.</description>
    <fields>
        <fullName>Key_Relationship__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Is this a KEY relationship? Used in reports.</inlineHelpText>
        <label>Key Relationship</label>
        <type>Checkbox</type>
    </fields>
    <label>Relationship</label>
    <nameField>
        <label>Relationship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Season__c.object
<CustomObject>
    <description>NCS season</description>
    <label>Season</label>
    <nameField>
        <label>Season Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Seasons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/bg_ContactUtils_Test.cls
/********************************************************************
 * bg_ContactUtils_Test
 *
 * Test class for bg_ContactUtils
 * 
 * Author: Antony Daley
 * Created: 31-03-2015
 * Changes: 
 *
 ********************************************************************/

@isTest
private class bg_ContactUtils_Test 
{

   	static testMethod void testGetYoungPersonContactsForStagingRecords() 
    {
    	//
    	// Test the Get Younger Persons method, this should return a contact and its child NCS and Inclusion records
    	//
    	
    	//SET UP TEST DATA - Setup a young person, with an NCS Application and Inclusion Details record
        //Disable the data creation triggers
    	CreateNCSnIncDetailRecrdOnContactHandler.DISABLE_CREATE_NCS_AND_INC = true;
    	KeyRelHandler.DISABLE_CREATE_NRELATIONSHIPS = true;
    	bg_NCSDataEntryStagingUtils.DISABLE_TRIGGER_PROCESS = true;
        
        Account testAccount = bg_UnitTestHelper.createAccount('The Web Family');
        RecordType youngPersonRecordType = bg_RecordTypeUtils.getRecordType('Contact', bg_RecordTypeUtils.RECORD_TYPE_NAME_CONTACT_YOUNG_PERSON);
	    Contact youngPerson = bg_UnitTestHelper.createContact('Wincey', 'Spider', testAccount.Id, youngPersonRecordType.Id, 'myemail@waterspout.com');
        Season__c season = bg_UnitTestHelper.createSeason('Rainy');
        RecordType inclusionDetaiLRecordType = bg_RecordTypeUtils.getRecordType('Inclusion_Details__c', bg_RecordTypeUtils.RECORD_TYPE_NAME_INCLUSION_CURRENT);
        NCS_Application__c ncs = bg_UnitTestHelper.createNCSApplication(youngPerson.Id, season.Id);
        Inclusion_Details__c inclusionDetail = bg_UnitTestHelper.createInclusion(youngPerson.Id, inclusionDetaiLRecordType.Id);
        
        NCS_Data_Entry_Staging__c stagingObj = bg_UnitTestHelper.createStagingObj('myemail@waterspout.com', null);
        List<NCS_Data_Entry_Staging__c> stagingObjects = new List<NCS_Data_Entry_Staging__c>();
        stagingObjects.add(stagingObj);
        
        //START TEST
        test.StartTest();
        	List<Contact> relatedContacts = new List<Contact>();
        	relatedContacts = bg_ContactUtils.getYoungPersonContactsForStagingRecords(stagingObjects);
        test.StopTest();
        
        //DO ASSERTS - Related contacts should return 1 along with 1 ncs and 1 inclusion detail record that should match the above created test data
        system.assertEquals(1, relatedContacts.size());
        system.assertEquals(1, relatedContacts[0].NCS_Applications__r.size());
        system.assertEquals(1, relatedContacts[0].Inclusion_Details__r.size());
        
        system.assertEquals(ncs.Id, relatedContacts[0].NCS_Applications__r[0].Id);
        system.assertEquals(inclusionDetail.Id, relatedContacts[0].Inclusion_Details__r[0].Id);
    }

    static testMethod void testGetGuardianContactsForStagingRecords() 
    {
    	//
    	// Test the get guardian contacts method, this should return the parent guardian contact
    	//
    	
        //SETUP TEST DATA - Setup a young person and a parent
        
       	//Disable the data creation triggers
    	CreateNCSnIncDetailRecrdOnContactHandler.DISABLE_CREATE_NCS_AND_INC = true;
    	KeyRelHandler.DISABLE_CREATE_NRELATIONSHIPS = true;
    	bg_NCSDataEntryStagingUtils.DISABLE_TRIGGER_PROCESS = true;
        
        Account testAccount = bg_UnitTestHelper.createAccount('The Web Family');
        RecordType youngPersonRecordType = bg_RecordTypeUtils.getRecordType('Contact', bg_RecordTypeUtils.RECORD_TYPE_NAME_CONTACT_YOUNG_PERSON);
        RecordType parentGuardianRecordType = bg_RecordTypeUtils.getRecordType('Contact', bg_RecordTypeUtils.RECORD_TYPE_NAME_CONTACT_PARENT_GUARDIAN);
	        
	    Contact youngPerson = bg_UnitTestHelper.createContact('Spider', 'Pig', testAccount.Id, youngPersonRecordType.Id, 'myemail@waterspout.com');
        Contact parentGuardian = bg_UnitTestHelper.createContact('Spider', 'Man', testAccount.Id, parentGuardianRecordType.Id, 'parentEmail@waterspout.com');
        
        Relationship__c youngPersonToParentGuardianRelationship = bg_UnitTestHelper.getRelationship('ypTOpg', youngPerson.Id, parentGuardian.Id);
        youngPersonToParentGuardianRelationship.Key_Relationship__c = true;
        insert youngPersonToParentGuardianRelationship;
        
        NCS_Data_Entry_Staging__c stagingObj = bg_UnitTestHelper.createStagingObj(null, 'parentEmail@waterspout.com');
        List<NCS_Data_Entry_Staging__c> stagingObjects = new List<NCS_Data_Entry_Staging__c>();
        stagingObjects.add(stagingObj);
        
        //RUN TEST
        test.StartTest();
        	List<Contact> youngPersons = new List<Contact>();
        	youngPersons.add(youngPerson);
        	List<Contact> relatedContacts = new List<Contact>();
        	relatedContacts = bg_ContactUtils.getGuardianContactsForStagingRecords(stagingObjects, youngPersons);
        test.StopTest();
        
        //ASERT THE CONTACT RETURNED IS THE PARENT GUARDIAN
        system.assertEquals(1, relatedContacts.size());
        system.assertEquals(parentGuardian.Id, relatedContacts[0].Id);
        
    }
    
    static testMethod void testPopulateContact()
    {
    	//Disable the data creation triggers
    	bg_NCSDataEntryStagingUtils.DISABLE_TRIGGER_PROCESS = true;
    	
    	//Setup a custom setting - Source Fields are derived from the NCS Data Entry Staging object
        NCS_Data_Entry_Staging_Settings__c cstSetting = new NCS_Data_Entry_Staging_Settings__c();
        
        //Doesnt Exist
        cstSetting.Name = 'YP Contact Test';
        cstSetting.Target_Field__c = 'homephone';
        cstSetting.Target_Object__c = 'Contact';
        cstSetting.Source_Field__c = 'home_phone__c';
        cstSetting.Target_Type__c = bg_NCSDataEntryStagingUtils.TARGET_TYPE_YP_PGCON;
        
        insert cstSetting;
        
        NCS_Data_Entry_Staging__c stagingRecord = bg_UnitTestHelper.getStagingObj('myemail@waterspout.com', null); 
        stagingRecord.home_phone__c = '01234567890';
        
        insert stagingRecord;
        
        Account familyAccount = bg_UnitTestHelper.createAccount('Pikachu');
        
        map<String, List<bg_NCSDataEntryFieldMappingUtils.fieldMappingValidation>> fieldSourceToWrapperMap = bg_NCSDataEntryFieldMappingUtils.validateFieldMappings();
                
    	Contact ypContact = new Contact();
    	ypContact.AccountId = familyAccount.Id;
    	ypContact = bg_ContactUtils.populateContact(ypContact, stagingRecord, fieldSourceToWrapperMap.get(bg_NCSDataEntryStagingUtils.TARGET_TYPE_YP_PGCON), familyAccount.Id);
    	
    	system.assertEquals(ypContact.homephone, '01234567890');
    	system.assertEquals(ypContact.AccountId, familyAccount.Id);
    }
    
    static testMethod void testPopulateContactNullValue()
    {
    	//Disable the data creation triggers
    	bg_NCSDataEntryStagingUtils.DISABLE_TRIGGER_PROCESS = true;
    	
    	//Setup a custom setting - Source Fields are derived from the NCS Data Entry Staging object
        NCS_Data_Entry_Staging_Settings__c cstSetting = new NCS_Data_Entry_Staging_Settings__c();
        
        //Doesnt Exist
        cstSetting.Name = 'YP Contact Test';
        cstSetting.Target_Field__c = 'homephone';
        cstSetting.Target_Object__c = 'Contact';
        cstSetting.Source_Field__c = 'home_phone__c';
        cstSetting.Target_Type__c = bg_NCSDataEntryStagingUtils.TARGET_TYPE_YP_PGCON;
        
        insert cstSetting;
        
        NCS_Data_Entry_Staging__c stagingRecord = bg_UnitTestHelper.getStagingObj('myemail@waterspout.com', null); 
        stagingRecord.home_phone__c = '';
        
        insert stagingRecord;
        
        Account familyAccount = bg_UnitTestHelper.createAccount('Pikachu');
        
        map<String, List<bg_NCSDataEntryFieldMappingUtils.fieldMappingValidation>> fieldSourceToWrapperMap = bg_NCSDataEntryFieldMappingUtils.validateFieldMappings();
                
    	Contact ypContact = new Contact();
    	ypContact.AccountId = familyAccount.Id;
    	ypContact.homephone = '01234567890';
    	ypContact = bg_ContactUtils.populateContact(ypContact, stagingRecord, fieldSourceToWrapperMap.get(bg_NCSDataEntryStagingUtils.TARGET_TYPE_YP_PGCON), ypContact.AccountId);
    	
    	system.assertEquals(ypContact.homephone, '01234567890');
    	system.assertEquals(ypContact.AccountId, familyAccount.Id);
    }
    
    static testMethod void testPopulateContact_LastNameIsEmpty()
    {
    	//Disable the data creation triggers
    	bg_NCSDataEntryStagingUtils.DISABLE_TRIGGER_PROCESS = true;
    	
    	//Setup a custom setting - Source Fields are derived from the NCS Data Entry Staging object
        NCS_Data_Entry_Staging_Settings__c cstSetting = new NCS_Data_Entry_Staging_Settings__c();
        
        //Doesnt Exist
        cstSetting.Name = 'YP Contact Test';
        cstSetting.Target_Field__c = 'homephone';
        cstSetting.Target_Object__c = 'Contact';
        cstSetting.Source_Field__c = 'home_phone__c';
        cstSetting.Target_Type__c = bg_NCSDataEntryStagingUtils.TARGET_TYPE_YP_PGCON;
        
        insert cstSetting;
        
        NCS_Data_Entry_Staging__c stagingRecord = bg_UnitTestHelper.getStagingObj('myemail@waterspout.com', null); 
        stagingRecord.home_phone__c = '01234567890';
        
        insert stagingRecord;
        
        Account familyAccount = bg_UnitTestHelper.createAccount('Pikachu');
        
        map<String, List<bg_NCSDataEntryFieldMappingUtils.fieldMappingValidation>> fieldSourceToWrapperMap = bg_NCSDataEntryFieldMappingUtils.validateFieldMappings();
                
    	Contact ypContact = new Contact();
    	ypContact.AccountId = familyAccount.Id;
    	ypContact = bg_ContactUtils.populateContact(ypContact, stagingRecord, fieldSourceToWrapperMap.get(bg_NCSDataEntryStagingUtils.TARGET_TYPE_YP_PGCON), familyAccount.Id);
    	
    	system.assertEquals(ypContact.lastName, '.');
    }
    
    static testMethod void testGetYoungPersonContactsForStagingRecordsByParentEmail() 
    {
    	//
    	// Test the Get Younger Persons method, this should return a contact and its child NCS and Inclusion records
    	//
    	
    	//SET UP TEST DATA - Setup a young person, with an NCS Application and Inclusion Details record
        //Disable the data creation triggers
    	CreateNCSnIncDetailRecrdOnContactHandler.DISABLE_CREATE_NCS_AND_INC = true;
    	KeyRelHandler.DISABLE_CREATE_NRELATIONSHIPS = true;
    	bg_NCSDataEntryStagingUtils.DISABLE_TRIGGER_PROCESS = true;
        
        Account testAccount = bg_UnitTestHelper.createAccount('The Web Family');
        RecordType youngPersonRecordType = bg_RecordTypeUtils.getRecordType('Contact', bg_RecordTypeUtils.RECORD_TYPE_NAME_CONTACT_YOUNG_PERSON);
	    Contact youngPerson = bg_UnitTestHelper.getContact('Wincey', 'Spider', testAccount.Id, youngPersonRecordType.Id, 'myemail@waterspout.com');
        youngPerson.Parent_Email__c = 'somefairytailsarescary@mymail.com';
        insert youngPerson;
        Season__c season = bg_UnitTestHelper.createSeason('Rainy');
        RecordType inclusionDetaiLRecordType = bg_RecordTypeUtils.getRecordType('Inclusion_Details__c', bg_RecordTypeUtils.RECORD_TYPE_NAME_INCLUSION_CURRENT);
        NCS_Application__c ncs = bg_UnitTestHelper.createNCSApplication(youngPerson.Id, season.Id);
        Inclusion_Details__c inclusionDetail = bg_UnitTestHelper.createInclusion(youngPerson.Id, inclusionDetaiLRecordType.Id);
        
        NCS_Data_Entry_Staging__c stagingObj = bg_UnitTestHelper.createStagingObj(null, 'somefairytailsarescary@mymail.com');
        List<NCS_Data_Entry_Staging__c> stagingObjects = new List<NCS_Data_Entry_Staging__c>();
        stagingObjects.add(stagingObj);
        
        //START TEST
        test.StartTest();
        	List<Contact> relatedContacts = new List<Contact>();
        	relatedContacts = bg_ContactUtils.getYoungPersonContactsForStagingRecords(stagingObjects);
        test.StopTest();
        
        //DO ASSERTS - Related contacts should return 1 along with 1 ncs and 1 inclusion detail record that should match the above created test data
        system.assertEquals(1, relatedContacts.size());
        system.assertEquals(1, relatedContacts[0].NCS_Applications__r.size());
        system.assertEquals(1, relatedContacts[0].Inclusion_Details__r.size());
        
        system.assertEquals(ncs.Id, relatedContacts[0].NCS_Applications__r[0].Id);
        system.assertEquals(inclusionDetail.Id, relatedContacts[0].Inclusion_Details__r[0].Id);
    }
}