objects/Inclusion_Details__c.object
<CustomObject>
    <fields>
        <fullName>HTR__c</fullName>
        <defaultValue>false</defaultValue>
        <label>HTR?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Season__c</fullName>
        <formula>Contact__r.NCS_Application_Primary_Season__c</formula>
        <label>Season</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Support_Level__c</fullName>
        <label>Support Level</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1 - no extra support</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>2 - medical conditions</fullName>
                </value>
                <value>
                    <fullName>3a - extra mentor support for learning difficulties</fullName>
                </value>
                <value>
                    <fullName>3b - extra mentor support for challenging behaviour or mental health conditions</fullName>
                </value>
                <value>
                    <fullName>4a – Extra APL support for YPs with restricted mobility, language barrier or learning difficulties</fullName>
                </value>
                <value>
                    <fullName>4b - extra APL support for challenging behaviour or mental health conditions</fullName>
                </value>
                <value>
                    <fullName>5.05 - support worker required, can share with another YP</fullName>
                </value>
                <value>
                    <fullName>5.1 - full-time support worker required</fullName>
                </value>
                <value>
                    <fullName>5.2 - requires 2 full time support workers</fullName>
                </value>
                <value>
                    <fullName>6 - case-by-case, potential non-accept</fullName>
                </value>
                <value>
                    <fullName>5b - personal coach required</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Inclusion Detail</label>
    <nameField>
        <displayFormat>{000000}</displayFormat>
        <label>Inclusion Details Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Inclusion Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/NCS_Application__c.object
<CustomObject>
    <fields>
        <fullName>Active_season__c</fullName>
        <description>Pulls through the value of Active Season from the Season object</description>
        <formula>TEXT( Season__r.Active_season__c )</formula>
        <inlineHelpText>Pulls through the value of Active Season from the Season object</inlineHelpText>
        <label>Active season</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_of_Birth_Approval__c</fullName>
        <label>Date of Birth Approval?</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Season__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Season</label>
        <referenceTo>Season__c</referenceTo>
        <relationshipLabel>NCS Applications</relationshipLabel>
        <relationshipName>NCS_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Wave__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Wave</label>
        <referenceTo>Wave__c</referenceTo>
        <relationshipLabel>NCS Applications</relationshipLabel>
        <relationshipName>NCS_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>X18_Status__c</fullName>
        <label>18+ Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>18+ for entire season</fullName>
                </value>
                <value>
                    <fullName>Turns 18+ During Season</fullName>
                </value>
                <value>
                    <fullName>DOB OK</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>YoungPerson__c</fullName>
        <label>Young Person</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>NCS Applications</relationshipLabel>
        <relationshipName>NCS_Applications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>NCS Application</label>
    <nameField>
        <displayFormat>NCSA{000000}</displayFormat>
        <label>NCS Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NCS Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Season__c.object
<CustomObject>
    <description>NCS season</description>
    <fields>
        <fullName>Active_season__c</fullName>
        <label>Active season</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Oldest_Date_of_Birth_Possible_First_Wave__c</fullName>
        <label>Oldest Date of Birth Possible:FirstWave</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Youngest_date_of_birth__c</fullName>
        <label>Youngest date of birth</label>
        <type>Date</type>
    </fields>
    <label>Season</label>
    <nameField>
        <label>Season Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Seasons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Wave__c.object
<CustomObject>
    <fields>
        <fullName>HTR__c</fullName>
        <label>HTR?</label>
        <summaryFilterItems>
            <field>Wave_Selection__c.HTR_Filter__c</field>
            <operation>equals</operation>
            <value>HTR YP</value>
        </summaryFilterItems>
        <summaryFilterItems>
            <field>Wave_Selection__c.Status_equals_assigned_or_reserved__c</field>
            <operation>equals</operation>
            <value>TRUE</value>
        </summaryFilterItems>
        <summaryForeignKey>Wave_Selection__c.Wave__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Oldest_date_of_birth_possible__c</fullName>
        <description>Oldest DOB of YP to be able to go on this wave.</description>
        <label>Oldest date of birth possible</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Season__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Which season the wave is part of.  A look up to the Season object</description>
        <label>Season</label>
        <referenceTo>Season__c</referenceTo>
        <relationshipLabel>Waves</relationshipLabel>
        <relationshipName>Waves</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Wave</label>
    <nameField>
        <label>Wave Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Waves</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/update18PlusOnWaveSelectionHandler.cls
/*
@ Name        : update18PlusOnWaveSelectionHandler (Trigger Class Handler)
@ Description : Update '18+?' field on 'Wave Selection'
@ Developer   : Shaikh Saquib
@ Date        : 27-Oct-2014
*/

public class update18PlusOnWaveSelectionHandler 
{
    // Imp : This method, we are also calling from "NCSApp18PlusStatus" class. 
    // If in future any one has added a new field WaveSelection related fields, then it should also
    // add in this "NCSApp18PlusStatus" class SOQL query.
    public void update18Plus(List<Wave_Selection__c> newWaveSelectionList,
                            Map<Id, Wave_Selection__c> mapOldWaveSelection)
    {
        // Set of NCS Application Id related to 'Wave Selection' records
        Set<Id> ncsAppicationIdSet = new Set<Id>();       

        // Set of Young Person Id related to 'Wave Selection' records
        Set<Id> contactIdSet = new Set<Id>();
 
        // Set of Wave Id related to 'Wave Selection' records
        Set<Id> waveIdSet = new Set<Id>(); 
                       
        // Add NCS Application and Young Person Lookup field value on Wave Selection to their Set of Id
        for(Wave_Selection__c waveSelectionRecord : newWaveSelectionList)
        {
            System.debug('waveSelectionRecord : ' + waveSelectionRecord);
            if(waveSelectionRecord.NCS_Application__c != null)
            {
                ncsAppicationIdSet.add(waveSelectionRecord.NCS_Application__c);     
            }
            
            if(waveSelectionRecord.Young_Person__c != null)
            {
                contactIdSet.add(waveSelectionRecord.Young_Person__c);     
            } 
            
            if(waveSelectionRecord.Wave__c != null)
            {
                waveIdSet.add(waveSelectionRecord.Wave__c);     
            }             
        }    
        
        // Mapping of NCS Application Id with its record
        Map<Id, NCS_Application__c> ncsApplicationMap; 
        
      
        if(!ncsAppicationIdSet.isEmpty())
        {
            // Map of NCS Application records
            ncsApplicationMap = new Map<Id, NCS_Application__c>([SELECT Id, Date_of_Birth_Approval__c,
                                                                 X18_Status__c, YoungPerson__c,
                                                                 Season__r.Youngest_date_of_birth__c,
                                                                 Season__r.Oldest_Date_of_Birth_Possible_First_Wave__c,
                                                                 Season__r.Active_Season__c                                                                 
                                                                 FROM NCS_Application__c 
                                                                 WHERE Id In :ncsAppicationIdSet]);
            System.debug('ncsApplicationMap >>> ' + ncsApplicationMap);
        }

        // Mapping of Contact Id with its record 
        Map<Id, Contact> contactMap;
        
        if(!contactIdSet.isEmpty())
        {
            // Map of Contact records
            contactMap = new Map<Id, Contact>([SELECT Id, Birthdate                                         
                                               FROM Contact 
                                               WHERE Id In :contactIdSet]);  
            System.debug('contactMap >>> ' + contactMap);
        }        
                
        // Mapping of Wave Id with its record 
        Map<Id, Wave__c> waveMap;        
        
        if(!waveIdSet.isEmpty())
        {
            // Map of Wave records
            waveMap = new Map<Id, Wave__c>([SELECT Id, Oldest_date_of_birth_possible__c
                                            FROM Wave__c 
                                            WHERE Id In :waveIdSet]);      
            System.debug('waveMap >>> ' + waveMap);
        }        
        
        NCS_Application__c ncsApplicationRecord = new NCS_Application__c();
        Wave__c waveRecord = new Wave__c();        
        Contact contactRecord = new Contact();
        
        Date contactBirthDate, waveOldestDOBPossible;
        String strNCSApplication18plusStatus;
        
        try
        {
            // Moidfy or assign '18+?'(X18__c) field of Wave Selection
            for(Wave_Selection__c waveSelectionRecord : newWaveSelectionList)
            {   
                if(waveSelectionRecord.NCS_Application__c != null)
                {
                    ncsApplicationRecord = ncsApplicationMap.get(waveSelectionRecord.NCS_Application__c);
                }
                
                if(waveSelectionRecord.Wave__c != null)
                {
                    waveRecord = waveMap.get(waveSelectionRecord.Wave__c);
                }
                
                if(waveSelectionRecord.Young_Person__c != null)
                {
                    contactRecord = contactMap.get(waveSelectionRecord.Young_Person__c); 
                }                
                  
                
                if(ncsApplicationRecord != null && ncsApplicationRecord.X18_Status__c != null)
                {                    
                    strNCSApplication18plusStatus = ncsApplicationRecord.X18_Status__c;               
                }
                else
                {
                    strNCSApplication18plusStatus = '';
                }                
            
                if(ncsApplicationRecord.X18_Status__c == 'DOB OK' ||
                        ncsApplicationRecord.X18_Status__c == 'Too Young')
                {
                    waveSelectionRecord.X18__c = null;
                    System.debug('waveSelectionRecord.X18__c >>>> ' + waveSelectionRecord.X18__c);
                }
                
                // Check  '18+ Status'(X18_Status__c) field of 'NCS Application'
                else if(strNCSApplication18plusStatus.equals('18+ for entire season') 
                        && ncsApplicationRecord.Date_of_Birth_Approval__c == null)
                {
                    waveSelectionRecord.X18__c = '18+ for entire season';
                    System.debug('waveSelectionRecord.X18__c >>>> ' + waveSelectionRecord.X18__c);
                }
                
                else if(strNCSApplication18plusStatus.equals('Turns 18+ During Season') &&
                        contactRecord.BirthDate <= waveRecord.Oldest_date_of_birth_possible__c &&
                        ncsApplicationRecord.Date_of_Birth_Approval__c == null)
                {         
                    waveSelectionRecord.X18__c = 'Will be 18+ for the residential part of this wave';
                    System.debug('waveSelectionRecord.X18__c >>>> ' + waveSelectionRecord.X18__c);
                }
                
                else if(strNCSApplication18plusStatus.equals('Turns 18+ During Season') &&
                        contactRecord.BirthDate > waveRecord.Oldest_date_of_birth_possible__c &&
                        ncsApplicationRecord.Date_of_Birth_Approval__c == null)
                {         
                    waveSelectionRecord.X18__c = null;
                    System.debug('waveSelectionRecord.X18__c >>>> ' + waveSelectionRecord.X18__c);
                }
                
                /*else if(ncsApplicationRecord.Date_of_Birth_Approval__c != null)
                {
                    if(mapOldWaveSelection != null &&
                       mapOldWaveSelection.containsKey(waveSelectionRecord.Id) &&
                       mapOldWaveSelection.get(waveSelectionRecord.Id).X18__c == null)
                    {
                      waveSelectionRecord.X18__c = null;
                    }
                    else
                    {
                        waveSelectionRecord.X18__c = 'Yes';
                    }
                    
                    System.debug('waveSelectionRecord.X18__c >>>> ' + waveSelectionRecord.X18__c);
                } */               
                else if(ncsApplicationRecord.Date_of_Birth_Approval__c != null) {
                    waveSelectionRecord.X18__c = 'Yes';
                }
                else
                {
                    waveSelectionRecord.X18__c = 'Will Turn 18+';
                    System.debug('waveSelectionRecord.X18__c >>>> ' + waveSelectionRecord.X18__c);
                }
            } 
            
            System.debug('newWaveSelectionList ::: ' + newWaveSelectionList);
        }    
        catch(Exception e)
        {
            System.debug('Exception : line number ' + e.getLineNumber() + ' - ' + e.getMessage());
        } 
    }     
    
    /**
    @ Description : Update value of X18__c On wave selection when related NCS_Application.Date_of_Birth_Approval__c != null then check if old value of Wave_Selection__c.X18__c == null then keep X18__c = null otherwise X18__c = 'Yes';
    */
    public void onChangeOfWaveSelection18Plus(List<Wave_Selection__c> newWaveSelectionList, Map<Id, Wave_Selection__c> oldMapWaveSelection){
        
        Set<Id> waveSelectionIds = new Set<Id>();
        for(Wave_Selection__c waveSelectionRec: newWaveSelectionList) {
            if(oldMapWaveSelection.get(waveSelectionRec.id).X18__c != waveSelectionRec.X18__c)
                waveSelectionIds.add(waveSelectionRec.id);
        }
        
        if(waveSelectionIds.size() > 0) {
            List<Wave_Selection__c>  waveSelectionList = [select id,X18__c,NCS_Application__r.Date_of_Birth_Approval__c 
                                                          FROM Wave_Selection__c 
                                                          WHERE NCS_Application__r.Date_of_Birth_Approval__c !=null AND ID IN: waveSelectionIds];

            if(waveSelectionList.size() > 0) {
                for(Wave_Selection__c waveSelectionRec: waveSelectionList) {
                    if(oldMapWaveSelection.get(waveSelectionRec.id).X18__c == null)
                        waveSelectionRec.X18__c = null;
                }
                if(waveSelectionList.size() > 0)
                    UPDATE waveSelectionList;
            }
        }
        
        
    }
    
    /**
    @ Description : Assign Support Level of Inclusion Detail and HTR of Wave Selection to 
    Support Level Filter and HTR Filter of Wave Selection
    */
    public void updateHTRAndSupportLevel(Map<Id, Wave_Selection__c> newWaveSelectionMap, 
                                         Map<Id, Wave_Selection__c> oldWaveSelectionMap)
    {                     
        Set<Id> waveSelectionIdSet = new Set<Id>();
        // Set of Inclusion Detail Id related to 'Wave Selection' records
        Set<Id> inclusionDetailIdSet = new Set<Id>();  
        
        //update18Plus(newWaveSelectionMap.values());
 
        if(oldWaveSelectionMap != null)
        {
            for(Wave_Selection__c waveSelectionRecord : newWaveSelectionMap.values())
            {
                System.debug('condition ::: ' + (oldWaveSelectionMap.get(waveSelectionRecord.Id).Inclusion_Detail__c 
                                                 != waveSelectionRecord.Inclusion_Detail__c));
                
                if(oldWaveSelectionMap.get(waveSelectionRecord.Id).Inclusion_Detail__c == null ||
                   (oldWaveSelectionMap.get(waveSelectionRecord.Id).Inclusion_Detail__c 
                   != waveSelectionRecord.Inclusion_Detail__c) )
                {
                    inclusionDetailIdSet.add(waveSelectionRecord.Inclusion_Detail__c);
                    waveSelectionIdSet.add(waveSelectionRecord.Id);
                }
            }
        }
        else
        {
            for(Wave_Selection__c waveSelectionRecord : newWaveSelectionMap.values())
            {
                inclusionDetailIdSet.add(waveSelectionRecord.Inclusion_Detail__c);
                waveSelectionIdSet.add(waveSelectionRecord.Id);                
            }
        }
        
        system.debug('waveSelectionIdSet ::: ' + waveSelectionIdSet);
        
        // Map of Inclusion Detail realted to Wave Selection
        Map<Id, Inclusion_Details__c> inclusionDetailMap = new Map<Id, Inclusion_Details__c>([SELECT Support_Level__c, HTR__c
                                                                                              FROM Inclusion_Details__c
                                                                                              WHERE Id IN :inclusionDetailIdSet
                                                                                             ]);        
        
        System.debug('inclusionDetailMap ::: ' + inclusionDetailMap);
        System.debug('newWaveSelectionMap.values() ::: ' + newWaveSelectionMap.values());
        
        Wave_Selection__c waveSelection;
        Inclusion_Details__c inclusionDetailRecord = new Inclusion_Details__c();
        
        for(Wave_Selection__c waveSelectionRecord : newWaveSelectionMap.values())
        {
            if(waveSelectionIdSet.contains(waveSelectionRecord.Id))
            {
                if(waveSelectionRecord.Inclusion_Detail__c == null)
                {
                    waveSelectionRecord.Access_category_filter__c = null;
                    waveSelectionRecord.HTR_Filter__c = null;  
                }
                else
                {
                    inclusionDetailRecord = inclusionDetailMap.get(waveSelectionRecord.Inclusion_Detail__c);
                    waveSelectionRecord.Access_category_filter__c = inclusionDetailRecord.Support_Level__c;
                    waveSelectionRecord.HTR_Filter__c = waveSelectionRecord.HTR__c;    
                }
                System.debug('Access_category_filter__c ::: ' + waveSelectionRecord.Access_category_filter__c);
                System.debug('HTR_Filter__c ::: ' + waveSelectionRecord.HTR_Filter__c);
            }            
        }    
        
      
        System.debug('newWaveSelectionMap ::: ' + newWaveSelectionMap.values());
    }    
}