objects/Job_Application__c.object
<CustomObject>
    <fields>
        <fullName>Activities_not_able_to_do__c</fullName>
        <inlineHelpText>Are there any activities in which you should not participate? (Some of the activities undertaken on the Personal Challenge are abseiling, kayaking and canoeing, hiking, raft building)</inlineHelpText>
        <label>Activities not able to do</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Allergies__c</fullName>
        <inlineHelpText>You must provide an answer – if no allergies, please state NA. If you do have an allergy please give specific details and any additional information we need to be aware of – i.e. allergy to nuts, and severity of the allergy.</inlineHelpText>
        <label>HSI1A.Allergies</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Date_time_HS_I_form_submitted__c</fullName>
        <label>Date/time HS &amp; I form submitted</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Disabilty__c</fullName>
        <inlineHelpText>If you do have a disability, please give details in relation to what reasonable adjustments may be required to help you best fulfil this position.
You must provide an answer – If no disability, state &quot;NA&quot;.</inlineHelpText>
        <label>HSI52A.Disability Detail</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Emergency_contact_address__c</fullName>
        <label>Emergency contact address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Emergency_contact_mobile__c</fullName>
        <label>Emergency contact mobile</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Emergency_contact_name__c</fullName>
        <label>Emergency contact name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Emergency_contact_phone__c</fullName>
        <label>Emergency contact phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Epi_pen_carrier__c</fullName>
        <label>HSI2A.Epi Pen Carrier</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>First_Aid_certificate_expiry_date__c</fullName>
        <inlineHelpText>Please provide the expiry date of the certificate.</inlineHelpText>
        <label>HSI11.3A: First Aid Cert Expiry Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>First_Aid_certificate_no__c</fullName>
        <inlineHelpText>Please provide the type of certificate and the certificate number</inlineHelpText>
        <label>HSI11.2A: First Aid Type and Cert No.</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Other_disclosed_conditions__c</fullName>
        <inlineHelpText>If you ticked any health condition, or ‘other’ please give further details specifically in relation to what reasonable adjustments may be required to help you best fulfil this position.
If you have ticked ‘None’ please enter in &quot;NA&quot;.</inlineHelpText>
        <label>HSI4A. Health Condition Detail</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Pregnant__c</fullName>
        <label>HSI8A.Pregnant?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not relevant</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
                <value>
                    <fullName>Yes - 1st trimester</fullName>
                </value>
                <value>
                    <fullName>Yes - 2nd trimester</fullName>
                </value>
                <value>
                    <fullName>Yes - 3rd trimester</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Relationship_to_emergency_contact__c</fullName>
        <label>Relationship to emergency contact</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Special_dietary_requirements__c</fullName>
        <inlineHelpText>If you have no special dietary requirements please state NA. Some examples of special dietary requiremens could be (Vegetarian,Halal, Celiac etc)</inlineHelpText>
        <label>HSI7A. Special Dietary Requirements</label>
        <length>10000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Up_to_date_tetanus_vaccination__c</fullName>
        <inlineHelpText>Do you have an up-to-date Tetanus injection (within 10 years)</inlineHelpText>
        <label>HSI9A.Tetanus In Date?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Valid_First_Aid_certificate__c</fullName>
        <inlineHelpText>Do you have a valid and up to date First Aid certificate?</inlineHelpText>
        <label>HSI11A: Valid First Aid Certificate</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Job Application</label>
    <nameField>
        <displayFormat>JA-2016-{0000}</displayFormat>
        <label>Job Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/OnlineHealthSafetyQuestionaireExtension.cls
global with sharing class OnlineHealthSafetyQuestionaireExtension {
    ApexPages.StandardController controller;
    public DateTime appDateTime                                    {get;set;}
    public Job_Application__c    jobApp                            {get;set;}
    public OnlineHealthSafetyQuestionaireExtension(ApexPages.StandardController controller) {
        this.Controller=controller;
        jobApp=(Job_Application__c)controller.getRecord();
    }
    public PageReference SaveThis(){
      try{
           jobApp.Date_time_HS_I_form_submitted__c=System.now();
           
           Boolean RequiredFieldsCompleted=jobApp.Allergies__c !=null && jobApp.Epi_pen_carrier__c!=null 
                                        && jobApp.Other_disclosed_conditions__c !=null && jobApp.Disabilty__c!=null 
                                        && jobApp.Special_dietary_requirements__c !=null && jobApp.Activities_not_able_to_do__c !=null
                                        && jobApp.Up_to_date_tetanus_vaccination__c!=null && jobApp.Pregnant__c!=null
                                        && jobApp.Valid_First_Aid_certificate__c!=null
                                        && (jobApp.Valid_First_Aid_certificate__c!='YES' || (jobApp.Valid_First_Aid_certificate__c=='YES'&& jobApp.First_Aid_certificate_no__c!=null && jobApp.First_Aid_certificate_expiry_date__c !=null ))
                                        && jobApp.Emergency_contact_name__c !=  null && jobApp.Relationship_to_emergency_contact__c !=null
                                        && jobApp.Emergency_contact_phone__c != null && jobApp.Emergency_contact_mobile__c != null
                                        && jobApp.Emergency_contact_address__c != null ;
           if(RequiredFieldsCompleted){
                controller.save();
                boolean errCount=ApexPages.hasMessages(ApexPages.Severity.Error);
               if(errCount==true){
                   return null;
               }
               else{
                   ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'Information has been saved successfully!'));
                                    PageReference page = new PageReference('/apex/JobApplicationUpdateSubmission');
                                    return page.setRedirect(true);
               }
           }
           else{
              ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO,'Please fill in all of the fields before you submit the form'));
              return null;
           }
           
           
          
      }
      catch(Exception ex){
                 ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, ex.getDmlMessage(0)));
                 return null;
      }
    }
    public void empty(){}
    @RemoteAction
    global static DateTime getDate(){
     System.debug('***************'+System.now());
        return System.now();
        
    }
}