objects/Job__c.object
<CustomObject>
    <description>Each individual job listed, including summer-long roles for each cluster, per wave roles for each wave and cluster</description>
    <fields>
        <fullName>Cluster__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Cluster</label>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Wave__c</fullName>
        <label>Wave</label>
        <referenceTo>Wave__c</referenceTo>
        <relationshipLabel>Jobs</relationshipLabel>
        <relationshipName>Jobs</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Job</label>
    <nameField>
        <label>Job Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Job_Application__c.object
<CustomObject>
    <fields>
        <fullName>Assignment_end_date__c</fullName>
        <formula>today()</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Assignment end date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Job Applications</relationshipLabel>
        <relationshipName>Job_Applications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date_dismissed__c</fullName>
        <label>Date dismissed</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date_of_withdrawal_notification__c</fullName>
        <label>Date of withdrawal notification</label>
        <type>Date</type>
    </fields>
    <label>Job Application</label>
    <nameField>
        <displayFormat>JA-2016-{0000}</displayFormat>
        <label>Job Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Job_placement__c.object
<CustomObject>
    <description>Used to assign an applicant to a Job</description>
    <fields>
        <fullName>Assignment_end_date__c</fullName>
        <description>2015 Formula can be found here: 

https://drive.google.com/a/the-challenge.org/file/d/0B8U5IDmhTO3eOU0zc3ZSaFZ5YkE/view?usp=sharing</description>
        <formula>IF(
NOT(CONTAINS( RecordType.Name ,&quot;2016&quot;)),
Job__r.Wave__r.PC_Return_day__c ,

IF( CONTAINS(RecordType.Name , &quot;Ad hoc&quot;), 
Ad_hoc_end_date__c , 

IF(RecordType.Name = &quot;(S)AM 2016&quot;, 
Job__r.Wave__r.RCD_end_date__c , 

IF( CONTAINS(RecordType.Name , &quot;Grad&quot;), 
Job__r.Wave__r.Graduation_Date__c , 

IF(OR( 
ISPICKVAL( Role__c , &quot;Programme Leader&quot;), 
ISPICKVAL( Role__c , &quot;Senior Community Facilitator&quot;)), 
Job__r.Wave__r.RCD_end_date__c , 

IF(OR( 
ISPICKVAL( Role__c , &quot;Assistant Programme Leader&quot;), 
ISPICKVAL( Role__c , &quot;Residential Mentor&quot;)), 
IF( ISPICKVAL(Job__r.Wave__r.Wave_Model_Staffing__c , &quot;Pilot&quot;), 
Job__r.Wave__r.RCD_end_date__c, Job__r.Wave__r.TC_end_day__c ), 

IF(OR( 
ISPICKVAL( Role__c , &quot;Senior Mentor&quot;), 
ISPICKVAL( Role__c , &quot;Support Worker&quot;), 
ISPICKVAL( Role__c , &quot;Personal Coach&quot;)), 
Job__r.Wave__r.RCA_End_Date__c, 


IF(OR( 
ISPICKVAL( Role__c , &quot;Programme Leader&quot;), 
ISPICKVAL( Role__c , &quot;Assistant Programme Leader&quot;), 
ISPICKVAL( Role__c , &quot;Senior Mentor&quot;), 
ISPICKVAL( Role__c , &quot;Support Worker&quot;), 
ISPICKVAL( Role__c , &quot;Personal Coach&quot;)), 
Job__r.Wave__r.PC_KO_day__c, 

IF(CONTAINS( TEXT(Role__c), &quot;Practitioner&quot;), 
Job__r.Wave__r.TC_end_day__c , 

IF(ISBLANK( Ad_hoc_end_date__c) , 

IF(CONTAINS( RecordType.Name , &quot;RCA 1&quot;), 
IF(ISPICKVAL( Job__r.Wave__r.September_RCA_weekends__c , &quot;Saturday&quot;), 
Job__r.RCA_1_Sat__c , Job__r.RCA_1_Sun__c ), 

IF(CONTAINS( RecordType.Name , &quot;RCA 2&quot;), 
IF(ISPICKVAL( Job__r.Wave__r.September_RCA_weekends__c , &quot;Saturday&quot;), 
Job__r.RCA_2_Sat__c , Job__r.RCA_2_Sun__c ), 

IF(CONTAINS( RecordType.Name , &quot;RCA 3&quot;), 
IF(ISPICKVAL( Job__r.Wave__r.September_RCA_weekends__c , &quot;Saturday&quot;), 
Job__r.RCA_3_Sat__c , Job__r.RCA_3_Sun__c ), 

IF(CONTAINS( RecordType.Name , &quot;RCA 4&quot;), 
IF(ISPICKVAL( Job__r.Wave__r.September_RCA_weekends__c , &quot;Saturday&quot;), 
Job__r.RCA_4_Sat__c , Job__r.RCA_4_Sun__c ), 

NULL)))), 

Ad_hoc_end_date__c))))))))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Assignment end date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Assignment_start_date__c</fullName>
        <description>2015 Formula can be found here:

https://drive.google.com/a/the-challenge.org/file/d/0B8U5IDmhTO3eb0l5TXJwSjdMQjg/view?usp=sharing</description>
        <formula>IF(
NOT(CONTAINS( RecordType.Name ,&quot;2016&quot;)),
Job__r.Wave__r.PC_KO_day__c,

IF( CONTAINS(RecordType.Name , &quot;Ad hoc&quot;), 
Ad_hoc_start_date__c , 

IF(RecordType.Name = &quot;(S)AM 2016&quot;, 
IF(ISPICKVAL ( Job__r.Wave__r.Wave_Model_Staffing__c , &quot;Pilot&quot;), 
  Job__r.Wave__r.TC_KO_day__c   , Job__r.Wave__r.RCD_start_date__c ), 


IF( CONTAINS(RecordType.Name , &quot;Grad&quot;), 
Job__r.Wave__r.Graduation_Date__c , 

IF(OR( 
ISPICKVAL( Role__c , &quot;Programme Leader&quot;), 
ISPICKVAL( Role__c , &quot;Assistant Programme Leader&quot;), 
ISPICKVAL( Role__c , &quot;Senior Mentor&quot;), 
ISPICKVAL( Role__c , &quot;Support Worker&quot;), 
ISPICKVAL( Role__c , &quot;Personal Coach&quot;)), 
Job__r.Wave__r.PC_KO_day__c, 

IF(ISPICKVAL( Role__c , &quot;Senior Community Facilitator&quot;), 
Job__r.Wave__r.RCD_start_date__c , 

IF(ISPICKVAL( Role__c , &quot;Residential Mentor&quot;), 
Job__r.Wave__r.TC_KO_day__c, 

IF(CONTAINS( TEXT(Role__c), &quot;Practitioner&quot;), 
IF( ISPICKVAL( Job__r.Wave__r.Wave_Model_Staffing__c , &quot;Pilot&quot;) , 
Job__r.Wave__r.TC_KO_day__c, Job__r.Wave__r.TC_KO_day__c+2), 

IF(ISBLANK( Ad_hoc_start_date__c) , 

IF(CONTAINS( RecordType.Name , &quot;RCA 1&quot;), 
IF(ISPICKVAL( Job__r.Wave__r.September_RCA_weekends__c , &quot;Saturday&quot;), 
Job__r.RCA_1_Sat__c , Job__r.RCA_1_Sun__c ), 

IF(CONTAINS( RecordType.Name , &quot;RCA 2&quot;), 
IF(ISPICKVAL( Job__r.Wave__r.September_RCA_weekends__c , &quot;Saturday&quot;), 
Job__r.RCA_2_Sat__c , Job__r.RCA_2_Sun__c ), 

IF(CONTAINS( RecordType.Name , &quot;RCA 3&quot;), 
IF(ISPICKVAL( Job__r.Wave__r.September_RCA_weekends__c , &quot;Saturday&quot;), 
Job__r.RCA_3_Sat__c , Job__r.RCA_3_Sun__c ), 

IF(CONTAINS( RecordType.Name , &quot;RCA 4&quot;), 
IF(ISPICKVAL( Job__r.Wave__r.September_RCA_weekends__c , &quot;Saturday&quot;), 
Job__r.RCA_4_Sat__c , Job__r.RCA_4_Sun__c ), 

NULL)))), 


Ad_hoc_start_date__c)))))))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Assignment start date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Cluster__c</fullName>
        <formula>Job__r.Wave__r.Wave_Cluster__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Cluster</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup relationship between Job Placement and Related Contact</description>
        <label>Contact</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.RecordTypeId</field>
                <operation>equals</operation>
                <value>Summer staff, YP, YP2010, YP2012, YP2012A, TCS Mentor 2012, YP2013</value>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Job placements</relationshipLabel>
        <relationshipName>Job_placements</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Job_Application__c</fullName>
        <label>Job Application</label>
        <referenceTo>Job_Application__c</referenceTo>
        <relationshipLabel>Job placements</relationshipLabel>
        <relationshipName>Job_placements</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PC_KO_Date__c</fullName>
        <formula>Job__r.PCKO_Date__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>PC KO Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Certain Status values are updated by apex trigger from Job Application.

Please therefore do not delete or amend the following status values:
Not available (date clash)
Withdrew from TCN (pre-programme)
Withdrew from wave (pre-programme)
Withdrew from wave (during programme) - available for ad hoc days
Withdrew from TCN (during programme) - see withdrawal date
Withdrew from TCN (post-programme)
Dismissed - see dismissal date

It is possible to add new values, however, without affecting the code</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Selected as preference</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Confirmed</fullName>
                </value>
                <value>
                    <fullName>On back-up list</fullName>
                </value>
                <value>
                    <fullName>Withdrew from wave (pre-programme)</fullName>
                </value>
                <value>
                    <fullName>Withdrew from wave (during programme) - available for ad hoc days</fullName>
                </value>
                <value>
                    <fullName>Not available (date clash)</fullName>
                </value>
                <value>
                    <fullName>Withdrew from TCN (pre-programme)</fullName>
                </value>
                <value>
                    <fullName>Withdrew from TCN (during programme) - see withdrawal date</fullName>
                </value>
                <value>
                    <fullName>Withdrew from TCN (post-programme)</fullName>
                </value>
                <value>
                    <fullName>Dismissed - see dismissal date</fullName>
                </value>
                <value>
                    <fullName>Role finished</fullName>
                </value>
                <value>
                    <fullName>Withdrawn</fullName>
                </value>
                <value>
                    <fullName>Started during wave - see ad hoc start date</fullName>
                </value>
                <value>
                    <fullName>AM - High probability of attending</fullName>
                </value>
                <value>
                    <fullName>AM - Low probability of attending</fullName>
                </value>
                <value>
                    <fullName>SAM - High probability of attending</fullName>
                </value>
                <value>
                    <fullName>SAM - Low probability of attending</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Wave__c</fullName>
        <formula>Job__r.Wave__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Wave</label>
        <type>Text</type>
    </fields>
    <label>Job placement</label>
    <nameField>
        <displayFormat>JP-2016-{00000}</displayFormat>
        <label>Job placement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job placements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Wave__c.object
<CustomObject>
    <fields>
        <fullName>PC_KO_day__c</fullName>
        <description>Personal Challenge Kick Off Day</description>
        <inlineHelpText>Personal Challenge Kick Off Day</inlineHelpText>
        <label>PC KO day</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Wave_Cluster__c</fullName>
        <label>Cluster</label>
        <referenceTo>Cluster__c</referenceTo>
        <relationshipLabel>Waves</relationshipLabel>
        <relationshipName>Waves</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Wave_code__c</fullName>
        <description>Unique wave code</description>
        <inlineHelpText>Unique wave code</inlineHelpText>
        <label>Wave code</label>
        <length>25</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Wave</label>
    <nameField>
        <label>Wave Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Waves</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TCSJobPlacementUpdaterTriggerHandler.cls
public class TCSJobPlacementUpdaterTriggerHandler {
    
    public static boolean PreventUpdateTrigger=false;
    
   
    public void OnBeforeUpdate(List<Job_Application__c> jobapps){
        System.debug('****PreventUpdateTrigger******'+PreventUpdateTrigger);
        if(PreventUpdateTrigger==false){
            List<Job_Placement__c> jobplacementstoupdate = new List<Job_Placement__c>();
            Map<Id,List<Job_Placement__c>> jobplacementMap=new Map<Id,List<Job_Placement__c>>();
            
            for(Job_Placement__c jobplacement : [SELECT PC_KO_Date__c,Assignment_start_date__c,Assignment_end_date__c,Job_Application__c,Status__c FROM Job_Placement__c WHERE Job_Application__c IN:jobapps]){
                System.debug('**********'+jobplacement);
                if(jobplacementMap.containsKey(jobplacement.Job_Application__c) == false){
                     List<Job_Placement__c> JobPlaceList=new List<Job_Placement__c>();
                     JobPlaceList.add(jobplacement);
                     jobplacementMap.put(jobplacement.Job_Application__c,JobPlaceList);
                }
                else{
                     jobplacementMap.get(jobplacement.Job_Application__c).add(jobplacement); 
                }
            }
            for(Job_Application__c jobapp:jobapps){
                if(jobplacementMap.containsKey(jobapp.Id)){
                    for(Job_Placement__c jobplacement: jobplacementMap.get(jobapp.Id)){
                        
                        if(jobapp.Date_dismissed__c!=null) {
                            if(jobplacement.Status__c != 'Dismissed - see dismissal date'){
                                jobplacement.Status__c='Dismissed - see dismissal date';
                                jobplacementstoupdate.add(jobplacement);
                            }
                        }
                        else if(jobapp.Date_of_withdrawal_notification__c != null && jobapp.Date_of_withdrawal_notification__c > jobplacement.Assignment_start_date__c && jobapp.Date_of_withdrawal_notification__c < jobplacement.Assignment_end_date__c && (jobplacement.Status__c!='Selected as preference' && jobplacement.Status__c != 'Not available (date clash)')){
                            if(jobplacement.Status__c!='Withdrew from TCN (during programme) - see withdrawal date'){
                                jobplacement.Status__c='Withdrew from TCN (during programme) - see withdrawal date';
                                jobplacementstoupdate.add(jobplacement);
                            }
                        }
                        else if(jobapp.Date_of_withdrawal_notification__c != null && jobapp.Date_of_withdrawal_notification__c <= jobplacement.Assignment_start_date__c){
                            if( jobplacement.Status__c!='Withdrew from TCN (pre-programme)'){
                                jobplacement.Status__c='Withdrew from TCN (pre-programme)';
                                jobplacementstoupdate.add(jobplacement);
                            }
                        }
                        else if(jobapp.Date_of_withdrawal_notification__c != null && jobapp.Date_of_withdrawal_notification__c > jobplacement.Assignment_end_date__c && (jobplacement.Status__c!='Selected as preference' && jobplacement.Status__c != 'Not available (date clash)')){
                            jobplacement.Status__c ='Withdrew from TCN (post-programme)';
                            jobplacementstoupdate.add(jobplacement);
                        }
                    }
                }
            }
        
        /*Modified at 7/18/2013 by Ozlem Sabirli
       List<Job_Placement__c> jobplacements = new List<Job_Placement__c>();
       jobplacements = [SELECT PC_KO_Date__c,Assignment_start_date__c,Job_Application__c,Status__c FROM Job_Placement__c WHERE Job_Application__c IN:jobapps];
        
       for(Job_Application__c jobapp:jobapps){
            for(Job_Placement__c jobplacement:jobplacements){
                if(jobplacement.Job_Application__c==jobapp.Id){
                    if(jobapp.Date_dismissed__c!=null){
                      jobplacement.Status__c='Dismissed - see dismissal date';
                      jobplacementstoupdate.add(jobplacement);
                    }else if(jobplacement.Assignment_start_date__c<System.today() && jobapp.Date_of_withdrawal_notification__c!=null){
                        jobplacement.Status__c='Withdrew from TCN (during programme) - see withdrawal date';
                        jobplacementstoupdate.add(jobplacement);
                    }else if((jobplacement.Assignment_start_date__c>System.today() || jobplacement.Assignment_start_date__c==System.today()) && jobapp.Date_of_withdrawal_notification__c!=null){
                        jobplacement.Status__c='Withdrew from TCN (pre-programme)';
                        jobplacementstoupdate.add(jobplacement);
                    }
                }
            }
        }*/
        if(jobplacementstoupdate.size()!=0){
          PreventUpdateTrigger=true;
          System.debug('*****jobplacementstoupdate******'+jobplacementstoupdate);
         
          update jobplacementstoupdate;
          
        
        }
      }
    }
    
    static testmethod void TCSJobPlacementUpdaterTriggerHandler(){
    
        Account account = new Account(Name='testaccount');
        
        insert account;
                    
        Contact con = new Contact(FirstName='testname',LastName='lasttest',AccountId=account.Id);
            
        insert con;
        
        Cluster__c cluster = new Cluster__c(Name='testcluster');
            
        insert cluster;
            
        Wave__c wave = new Wave__c(Name='Wave 1',Wave_Cluster__c=cluster.Id,Wave_Code__c='K1',PC_KO_day__c=System.Today().AddDays(-1));
            
        insert wave;
        
        Job_Application__c jobapp = new Job_Application__c(Contact__c=con.Id,Date_of_withdrawal_notification__c=System.today(),Reason_for_withdrawal__c='Other',Withdrawal_details__c='test');
        
        insert jobapp;
        
        Job__c job = new Job__c(Wave__c=wave.Id,Cluster__c=cluster.Id);
        
        insert job;
        
        Wave__c wave2 = new Wave__c(Name='Wave 2',Wave_Cluster__c=cluster.Id,Wave_Code__c='K2',PC_KO_day__c=System.Today().AddDays(1));
            
        insert wave2;
        
        Job__c job2 = new Job__c(Wave__c=wave2.Id,Cluster__c=cluster.Id);
        
        insert job2;
        
        Job_Placement__c jobplace = new Job_Placement__c(Job__c=job.Id,Job_Application__c=jobapp.Id);
        
        insert jobplace;
        
        update jobapp;
        
        Job_Placement__c jobplace2 = new Job_Placement__c(Job__c=job2.Id,Job_Application__c=jobapp.Id);
        
        insert jobplace2;
        
        update jobapp;
    }
}