objects/Metric__c.object
<CustomObject>
    <description>Keeps the Contact and some detailed metrics</description>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Metrics</relationshipLabel>
        <relationshipName>Metrics</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PC_Meetings_Attended__c</fullName>
        <defaultValue>0</defaultValue>
        <label>#PC Meetings Attended</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Metric</label>
    <nameField>
        <displayFormat>M-{0000}</displayFormat>
        <label>Metric Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Metrics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Personal_Coach__c.object
<CustomObject>
    <description>TCS Personal Coaching</description>
    <fields>
        <fullName>Young_person__c</fullName>
        <description>Master-detail link to YP being coached</description>
        <inlineHelpText>Link to the young person being coached</inlineHelpText>
        <label>Young person</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Personal Coaching</relationshipLabel>
        <relationshipName>Personal_Coaching</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Personal Coach</label>
    <nameField>
        <displayFormat>P#{000000}</displayFormat>
        <label>Personal Coach Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Personal Coaching</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Personal_Coach_Meetings__c.object
<CustomObject>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location of Meeting</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Meeting_attendance__c</fullName>
        <description>Picklist with YP attendance options</description>
        <inlineHelpText>Please specify whether or not the YP attended the scheduled meeting</inlineHelpText>
        <label>Did the YP attend the meeting?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Attended</fullName>
                </value>
                <value>
                    <fullName>Did not attend</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Meeting_date__c</fullName>
        <description>Date field for capturing date of scheduled meeting with YP</description>
        <inlineHelpText>Date of the scheduled meeting with the YP</inlineHelpText>
        <label>Date of meeting</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Meeting_successful__c</fullName>
        <label>Meeting successful?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Meeting_summary__c</fullName>
        <description>Long text area for capturing notes of the meeting</description>
        <inlineHelpText>Please provide a summary or outline of the meeting</inlineHelpText>
        <label>Meeting summary</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Personal_Coaching__c</fullName>
        <description>Master-detail link to the main Personal Coaching record</description>
        <inlineHelpText>Link to the main Personal Coaching record</inlineHelpText>
        <label>Personal Coaching</label>
        <referenceTo>Personal_Coach__c</referenceTo>
        <relationshipLabel>Personal Coach Meetings</relationshipLabel>
        <relationshipName>Personal_Coach_Meetings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Time_of_meeting__c</fullName>
        <label>Time of meeting</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Personal Coach Meeting</label>
    <nameField>
        <displayFormat>PCM#{000000}</displayFormat>
        <label>Personal Coach Meetings Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Personal Coach Meetings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TestMetric_CalculatePCMeetings.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class TestMetric_CalculatePCMeetings {

    static testMethod void myUnitTest() {
            
            Contact c = new Contact( FirstName='Burak', LastName='test' );
        
            insert c;
            
            Metric__c metric = new Metric__c ( Contact__c = c.Id);
            
            insert metric;
            
            Personal_Coach__c pc = new Personal_Coach__c(Young_person__c = c.Id );
            
            insert pc;
            
            Personal_Coach_Meetings__c pcme = new Personal_Coach_Meetings__c( Personal_Coaching__c = pc.Id , 
                                                                                Meeting_summary__c='test desc',
                                                                                Meeting_date__c=date.today(),
                                                                                Location__c='test',
                                                                                Time_of_meeting__c='test',
                                                                                Meeting_successful__c = 'Yes'); //new fields added 
        
            insert pcme;
            
            Metric__c newmetric = [SELECT PC_Meetings_Attended__c FROM Metric__c WHERE Contact__c =: c.Id];
            
            System.assertNotEquals(1,newmetric.PC_Meetings_Attended__c);
            
            pcme.Meeting_attendance__c = 'Attended';
            
            update pcme;
            
            newmetric = [SELECT PC_Meetings_Attended__c FROM Metric__c WHERE Contact__c =: c.Id];
                        
            System.assertEquals(1,newmetric.PC_Meetings_Attended__c);
            
            delete pcme;
            
            
    }
    
    
}