objects/Metric__c.object
<CustomObject>
    <description>Keeps the Contact and some detailed metrics</description>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                    <default>true</default>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>CAT_Meetings_Attended__c</fullName>
        <defaultValue>0</defaultValue>
        <label>#CAT Meetings Attended</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Metrics</relationshipLabel>
        <relationshipName>Metrics</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Meetings_attended_on_one_TCS_Attendance__c</fullName>
        <defaultValue>0</defaultValue>
        <label>#Meetings attended on one TCS Attendance</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Nearly_Active__c</fullName>
        <label>Nearly Active</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                    <default>true</default>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Total_SignPosting_Oppty_Meetings_Attend__c</fullName>
        <defaultValue>0</defaultValue>
        <label>#Total SignPosting Oppty Meetings Attend</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>YB_Meetings_Attended__c</fullName>
        <defaultValue>0</defaultValue>
        <label>#YB Meetings Attended</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Metric</label>
    <nameField>
        <displayFormat>M-{0000}</displayFormat>
        <label>Metric Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Metrics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/TCS_Attendance_record__c.object
<CustomObject>
    <description>Links Volunteering Opportunity and Contact to track YP attendances</description>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>TCS Attendance records</relationshipLabel>
        <relationshipName>TCS_Attendance_records</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Total_Attendance_in_a_year__c</fullName>
        <formula>IF( VALUE(TEXT(Meetings_attended_Nov_Dec__c))&gt;0, VALUE(TEXT(Meetings_attended_Nov_Dec__c)), 0 ) + 
IF( VALUE(TEXT(Meetings_attended_May_Jun__c))&gt;0, VALUE(TEXT(Meetings_attended_May_Jun__c)), 0)+ 
IF( VALUE(TEXT(Meetings_attended_Mar_Apr__c))&gt;0, VALUE( TEXT(Meetings_attended_Mar_Apr__c)), 0) + 
IF( VALUE(TEXT(Meetings_attended_Jul_Aug__c))&gt;0, VALUE(TEXT(Meetings_attended_Jul_Aug__c)), 0)+ 
IF( VALUE(TEXT( Meetings_attended_Dec__c ))&gt;0, VALUE(TEXT( Meetings_attended_Dec__c )), 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total # Attendance in a year</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>TCS Attendance record</label>
    <nameField>
        <displayFormat>TCS-{000000}</displayFormat>
        <label>TCS Attendance record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TCS Attendance records</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Metric_CalculateTCSEventAttendances.cls
public class Metric_CalculateTCSEventAttendances {//implements Database.Batchable<sObject>{

public List<Id> TCSId = new List<Id>();

	public Metric_CalculateTCSEventAttendances(List<Id> TCSId){
		this.TCSId=TCSId;
	}
 public void DefineScope(){
 	
 	List<TCS_Attendance_record__c> ListTCS = new List<TCS_Attendance_record__c>();
 	ListTCS = [SELECT id, Contact__c, Total_Attendance_in_a_year__c 
 			   FROM TCS_Attendance_record__c WHERE Contact__c IN :this.TCSId];
 	
 	
 	execute(ListTCS);
 }
 
  public void execute(List<TCS_Attendance_record__c> scope){
  	
	       List<Metric__c> ListMetrics = new List<Metric__c>();
	       
	       ListMetrics = [SELECT id, Contact__c, Total_SignPosting_Oppty_Meetings_Attend__c, 
	       				  Meetings_attended_on_one_TCS_Attendance__c, CAT_Meetings_Attended__c,
	       				  YB_Meetings_Attended__c, Active__c, Nearly_Active__c  
	       				  FROM Metric__c WHERE Contact__c IN :this.TCSId];
	       
	       for(Metric__c metric :ListMetrics){
	       	integer counter=0;
			integer maxTCSAttendance=0;
	       		for(TCS_Attendance_record__c TCSEventItem : scope){
	       		
	       		if(TCSEventItem.Contact__c == metric.Contact__c){
	       			
	       			 if(TCSEventItem.Total_Attendance_in_a_year__c!=null){
	       				counter+=integer.valueof(TCSEventItem.Total_Attendance_in_a_year__c);
	       			 }
	       			 if(integer.valueof(TCSEventItem.Total_Attendance_in_a_year__c)>maxTCSAttendance){
	       			 	
	       			 	maxTCSAttendance=integer.valueof(TCSEventItem.Total_Attendance_in_a_year__c);
	       			 }
	       		}
	       	}
	       	metric.Total_SignPosting_Oppty_Meetings_Attend__c = counter;
	       	metric.Meetings_attended_on_one_TCS_Attendance__c = maxTCSAttendance;
	       	
	       	//deciding Active Status
	       	if(metric.YB_Meetings_Attended__c>=4 || metric.CAT_Meetings_Attended__c>=4 || 
	       	   maxTCSAttendance>=4){
	       	   	metric.Active__c = 'Yes';
	       	   	metric.Nearly_Active__c = 'No';
	       	   }
	       	 //deciding Nearly Active Status
	       	 else if(metric.YB_Meetings_Attended__c>=3 || metric.CAT_Meetings_Attended__c>=3 || 
	       	  	  maxTCSAttendance>=3){
	       	   	metric.Nearly_Active__c = 'Yes';
	       	   	metric.Active__c = 'No';
	       	   }
       	   else{
       	   	metric.Active__c='No';
       			metric.Nearly_Active__c='No';
       	   }
	       	
	   }
	       update ListMetrics;
   }

}