objects/Metric__c.object
<CustomObject>
    <description>Keeps the Contact and some detailed metrics</description>
    <fields>
        <fullName>AM_SAM_attendance_at_RCD__c</fullName>
        <defaultValue>0</defaultValue>
        <label>#AM &amp; SAM Attendance at RCD</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>AM_SAM_attendance_at_training__c</fullName>
        <description>TO DELETE</description>
        <formula>0</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>AM &amp; SAM attendance at training</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                    <default>true</default>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Big_Challenge_Day_Event_Attended__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Big Challenge Day</inlineHelpText>
        <label>#BC Day Event Attended</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CAT_Meetings_Attended__c</fullName>
        <defaultValue>0</defaultValue>
        <label>#CAT Meetings Attended</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Metrics</relationshipLabel>
        <relationshipName>Metrics</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Involved__c</fullName>
        <formula>IF(Big_Challenge_Day_Event_Attended__c +  CAT_Meetings_Attended__c +  YB_Meetings_Attended__c +  Local_Events_Attended__c +  Skill_Workshop_Attended__c +  Marketing_Ambassador_Events_Attended1__c +  Media_Ambassador_Events_Attended__c +  Staffing_Ambassador__c +  PC_Meetings_Attended__c +  Total_AM_SAM_Attendances__c +  Total_SignPosting_Oppty_Meetings_Attend__c &gt;= 1, &apos;Yes&apos;, &apos;No&apos; )</formula>
        <label>Involved</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Local_Events_Attended__c</fullName>
        <defaultValue>0</defaultValue>
        <label>#Local Events Attended</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Marketing_Ambassador_Events_Attended1__c</fullName>
        <description>[DS[ I have filtered out YP records from here, as their metrics from last year should not be included here. This is a workaround while I think of something better</description>
        <formula>IF(OR( Contact__r.RecordTypeId = &quot;012C0000000Q2H0&quot;,Contact__r.RecordTypeId = &quot;012C0000000QBZg&quot;), 0,
IF(AND(ISPICKVAL(Contact__r.Account.Attended_Assembly_1__c,&apos;Yes&apos;),ISPICKVAL(Contact__r.Account.Attended_Assembly_2__c,&apos;Yes&apos;)),2,
IF(OR(ISPICKVAL(Contact__r.Account.Attended_Assembly_1__c,&apos;Yes&apos;),ISPICKVAL(Contact__r.Account.Attended_Assembly_2__c,&apos;Yes&apos;)),1,0)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>#Marketing Ambassador Events Attended</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Media_Ambassador_Events_Attended__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Where the Campaign RT is Development/Advocacy Event</inlineHelpText>
        <label>#Media Ambassador Events Attended</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Meetings_attended_on_one_TCS_Attendance__c</fullName>
        <defaultValue>0</defaultValue>
        <label>#Meetings attended on one TCS Attendance</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PC_Meetings_Attended__c</fullName>
        <defaultValue>0</defaultValue>
        <label>#PC Meetings Attended</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Skill_Workshop_Attended__c</fullName>
        <defaultValue>0</defaultValue>
        <label>#Skill Workshop Attended</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Staffing_Ambassador__c</fullName>
        <defaultValue>0</defaultValue>
        <label>#Staffing Ambassador Events Attended</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_AM_SAM_Attendances__c</fullName>
        <formula>AM_SAM_attendance_at_RCD__c +  AM_SAM_attendance_at_training__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Total # AM &amp; SAM Attendances</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_SignPosting_Oppty_Meetings_Attend__c</fullName>
        <defaultValue>0</defaultValue>
        <label>#Total SignPosting Oppty Meetings Attend</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_TCS_Events_Attended__c</fullName>
        <formula>Big_Challenge_Day_Event_Attended__c +  CAT_Meetings_Attended__c +  Local_Events_Attended__c +  Media_Ambassador_Events_Attended__c +  Skill_Workshop_Attended__c +  YB_Meetings_Attended__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>#Total TCS Events Attended</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>YB_Meetings_Attended__c</fullName>
        <defaultValue>0</defaultValue>
        <label>#YB Meetings Attended</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>YP_Want_to_Stay_Involved__c</fullName>
        <defaultValue>0</defaultValue>
        <label>% YP Want to Stay Involved</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>Metric</label>
    <nameField>
        <displayFormat>M-{0000}</displayFormat>
        <label>Metric Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Metrics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Summary_Metric__c.object
<CustomObject>
    <fields>
        <fullName>Asian__c</fullName>
        <label>Asian</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Black__c</fullName>
        <label>Black</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Buddhist__c</fullName>
        <label>Buddhist</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Chinese__c</fullName>
        <label>Chinese</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Christian__c</fullName>
        <label>Christian</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Disability__c</fullName>
        <label>Disability</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Female__c</fullName>
        <label>Female</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FreeSchoolMeals__c</fullName>
        <label>FreeSchoolMeals</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Hindu__c</fullName>
        <label>Hindu</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Independent__c</fullName>
        <label>Independent</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Intraining__c</fullName>
        <label>Intraining</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Jewish__c</fullName>
        <label>Jewish</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LookedAfterChild__c</fullName>
        <label>LookedAfterChild</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Male__c</fullName>
        <label>Male</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Mixed__c</fullName>
        <label>Mixed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Muslim__c</fullName>
        <label>Muslim</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>None__c</fullName>
        <label>None</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OtherSchoolType__c</fullName>
        <label>OtherSchoolType</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Other_Ethnicity__c</fullName>
        <label>Other Ethnicity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PRU__c</fullName>
        <label>PRU</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SEN__c</fullName>
        <label>SEN</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sikh__c</fullName>
        <label>Sikh</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Studyingschool_collegene__c</fullName>
        <label>Studyingschool_collegene</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SupportLevel__c</fullName>
        <label>SupportLevel</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total__c</fullName>
        <label>Total</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unemployed__c</fullName>
        <label>Unemployed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unknown__c</fullName>
        <label>Unknown</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>VolunteeringInvolvement__c</fullName>
        <label>VolunteeringInvolvement</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>White__c</fullName>
        <label>White</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Working__c</fullName>
        <label>Working</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Summary Metric</label>
    <nameField>
        <displayFormat>Summary-{0000}</displayFormat>
        <label>Summary Metric Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Summary Metrics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestBatch.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest(seealldata = true)
private class TestBatch {

   
         static testMethod void myUnitTest() {
       
     // insert accns;
        Test.StartTest();  
        String MainQuery = '';
          MainQuery ='SELECT id, Big_Challenge_Day_Event_Attended__c, CAT_Meetings_Attended__c, AM_SAM_attendance_at_RCD__c,'+
			   'Local_Events_Attended__c, Marketing_Ambassador_Events_Attended1__c, Media_Ambassador_Events_Attended__c,' +
			   'Meetings_attended_on_one_TCS_Attendance__c, PC_Meetings_Attended__c, Skill_Workshop_Attended__c,' +
			   'Staffing_Ambassador__c, Total_SignPosting_Oppty_Meetings_Attend__c, Total_TCS_Events_Attended__c,'+
			   'YB_Meetings_Attended__c, YP_Want_to_Stay_Involved__c, Active__c, AM_SAM_attendance_at_training__c,' +
			   'Involved__c, Total_AM_SAM_Attendances__c,Contact__r.Name, Contact__r.Religion__c,'+
			   'Contact__r.Gender__c, Contact__r.Ethnicity__c, Contact__r.Calculation_of_total_hours__c,'+
			   'Contact__r.Status__c, Contact__r.Free_school_meals__c, Contact__r.Looked_after_child_in_care__c,'+
			   'Contact__r.Disability_summary__c, Contact__r.Access_category_2_6__c, Contact__r.Volunteering_involvement_summary__c,'+ 
			   'Contact__r.YP_occupation__c, Contact__r.School_category__c '+
			   'FROM Metric__c limit 200';
			   List<Summary_Metric__c> ListSummMetrics = new List<Summary_Metric__c>();
			   for(integer i = 0 ; i<18; i++){
			   	Summary_Metric__c sm = new Summary_Metric__c();
			   	sm.Female__c= 0;
			   	sm.Male__c= 0;
			   	sm.Asian__c = 0;
			   	sm.Black__c= 0;
			   	sm.Buddhist__c= 0;
				sm.Chinese__c= 0;
				sm.White__c= 0;
				sm.Mixed__c= 0;
				sm.Disability__c= 0;
				sm.Other_Ethnicity__c= 0;
				sm.FreeSchoolMeals__c= 0;
				sm.LookedAfterChild__c= 0;
				sm.SupportLevel__c= 0;
				sm.VolunteeringInvolvement__c= 0;
				sm.Christian__c= 0;
				sm.Hindu__c= 0;
				sm.Sikh__c= 0;
				sm.Jewish__c= 0;
				sm.Muslim__c= 0;
				sm.None__c= 0;
				sm.Studyingschool_collegene__c= 0;
				sm.Intraining__c= 0;
				sm.Working__c= 0;
				sm.Unemployed__c= 0;
				sm.Unknown__c= 0;
				sm.State__c= 0;
				sm.Independent__c= 0;
				sm.PRU__c= 0;
				sm.SEN__c= 0;
				sm.OtherSchoolType__c= 0;
				sm.Total__c= 0;
			   	ListSummMetrics.add(sm);
			   } 
			   insert ListSummMetrics;
           BatchableMetrics Batch = new BatchableMetrics(MainQuery);
           ID batchprocessid = Database.executeBatch(Batch,200);
          
           Test.StopTest();

        }
    
}