objects/Metric__c.object
<CustomObject>
    <description>Keeps the Contact and some detailed metrics</description>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                    <default>true</default>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Involved__c</fullName>
        <formula>IF(Big_Challenge_Day_Event_Attended__c +  CAT_Meetings_Attended__c +  YB_Meetings_Attended__c +  Local_Events_Attended__c +  Skill_Workshop_Attended__c +  Marketing_Ambassador_Events_Attended1__c +  Media_Ambassador_Events_Attended__c +  Staffing_Ambassador__c +  PC_Meetings_Attended__c +  Total_AM_SAM_Attendances__c +  Total_SignPosting_Oppty_Meetings_Attend__c &gt;= 1, &apos;Yes&apos;, &apos;No&apos; )</formula>
        <label>Involved</label>
        <type>Text</type>
    </fields>
    <label>Metric</label>
    <nameField>
        <displayFormat>M-{0000}</displayFormat>
        <label>Metric Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Metrics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Region__c.object
<CustomObject>
    <description>TCN Region (geographical area)</description>
    <label>Regions</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Survey__c.object
<CustomObject>
    <description>Hold Survey data</description>
    <fields>
        <fullName>Desire_to_remain_involved_0_10__c</fullName>
        <inlineHelpText>Survey Question: Would you want to get involved in a day like this again? (10 = yes definitely! 0 = no thanks)</inlineHelpText>
        <label>Desire to remain involved (0-10)</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Event_rating_0_10__c</fullName>
        <inlineHelpText>Survey Question: On a scale of 0 to 10 please rate the day</inlineHelpText>
        <label>Event rating (0-10)</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Zone__c</fullName>
        <formula>IF( ISBLANK( Wave__c),  Zone_Wave_Not_Entered__c ,Zone_Wave_Entered__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Zone</label>
        <type>Text</type>
    </fields>
    <label>Survey</label>
    <nameField>
        <displayFormat>S-{YYYY}{MM}{00000}</displayFormat>
        <label>Survey Reference No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <recordTypes>
        <fullName>YP</fullName>
        <active>true</active>
        <label>YP</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Zone__c.object
<CustomObject>
    <description>TCN Zone (geographical area)</description>
    <fields>
        <fullName>Region__c</fullName>
        <description>Region the zone is part of</description>
        <inlineHelpText>The region this zones is part of</inlineHelpText>
        <label>Region</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Zones</relationshipLabel>
        <relationshipName>Zones</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Zone</label>
    <nameField>
        <label>Zone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Zones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/RegionController.cls
public class RegionController {
        
        public String title {get; set;}
        public String regionid {get; set;}
        public List<Zone__c> zones {get; set;}
        public List<Metric__c> involvedReports {get; set;}
        public List<Metric__c> activeReports {get; set;}
        public List<Survey__c> wantToRemains {get; set;} 
        public List<Survey__c> eventRatings {get; set;} 
        public Integer noInvolvedReports {get; set;}
        public Integer noActiveReports {get; set;}
        public Decimal percentageOfRemainings {get; set;}
        public Decimal averageRating {get; set;}
        
        public RegionController(){
            
            regionid = ApexPages.currentPage().getParameters().get('id');
            percentageOfRemainings = 0;
            averageRating = 0;
            getZones();
            getInvolvedReports();
            getRatios();
                        
        }       
                
        public List<Zone__c> getZones(){
                
            Region__c region = new Region__c();
            zones = [SELECT Name FROM Zone__c ORDER BY Name];
                        
        	return zones;
        }
        public List<Metric__c> getInvolvedReports(){
        
                        involvedReports = [SELECT Involved__c FROM Metric__c WHERE Involved__c = 'Yes'];
                        activeReports = [SELECT Active__c FROM Metric__c WHERE Active__c = 'Yes'];

                        noInvolvedReports = involvedReports.size();
                        noActiveReports = activeReports.size();
        
       return activeReports;
        }
        
        public List<Survey__c> getRatios(){
        
        List<Survey__c> remains = new List<Survey__c>();
        Decimal totalRatings=0;

        List<RecordType> r = [SELECT Id FROM RecordType WHERE SObjectType='Survey__c' AND Name='TCS event YP'];
                
        wantToRemains = [SELECT Desire_to_remain_involved_0_10__c, Event_rating_0_10__c 
        				 FROM Survey__c WHERE RecordTypeId =: r[0].id];
    
        if(wantToRemains.size()!=0){
                for(Integer i=0; i<wantToRemains.size(); i++)
                {
                        if(wantToRemains[i].Desire_to_remain_involved_0_10__c != null && 
                           wantToRemains[i].Desire_to_remain_involved_0_10__c>=7){
                                remains.add(wantToRemains[i]);
                        }
                        if(wantToRemains[i].Event_rating_0_10__c != null){
                    		totalRatings += wantToRemains[i].Event_rating_0_10__c;
                        }
                }
                Decimal a = remains.size();
                Decimal b = wantToRemains.size();
                percentageOfRemainings = ((a/b)*100).setScale(1);
                averageRating = (totalRatings/Decimal.valueOf(wantToRemains.size())).setScale(1);
        }
                                        
     /*
    eventRatings = [SELECT Event_rating_0_10__c FROM Survey__c WHERE RecordTypeId =: r];
            
    if(eventRatings.size()!=0){
        for(Integer i=0; i<eventRatings.size(); i++){
                totalRatings += eventRatings[i].Event_rating_0_10__c;
        }
        averageRating = (totalRatings/Decimal.valueOf(eventRatings.size())).setScale(1);
    }
    */
                        
        return wantToRemains;
        }
}