objects/Metric__c.object
<CustomObject>
    <description>Keeps the Contact and some detailed metrics</description>
    <fields>
        <fullName>Active__c</fullName>
        <label>Active</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                    <default>true</default>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Big_Challenge_Day_Event_Attended__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Big Challenge Day</inlineHelpText>
        <label>#BC Day Event Attended</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CAT_Meetings_Attended__c</fullName>
        <defaultValue>0</defaultValue>
        <label>#CAT Meetings Attended</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Metrics</relationshipLabel>
        <relationshipName>Metrics</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Involved__c</fullName>
        <formula>IF(Big_Challenge_Day_Event_Attended__c +  CAT_Meetings_Attended__c +  YB_Meetings_Attended__c +  Local_Events_Attended__c +  Skill_Workshop_Attended__c +  Marketing_Ambassador_Events_Attended1__c +  Media_Ambassador_Events_Attended__c +  Staffing_Ambassador__c +  PC_Meetings_Attended__c +  Total_AM_SAM_Attendances__c +  Total_SignPosting_Oppty_Meetings_Attend__c &gt;= 1, &apos;Yes&apos;, &apos;No&apos; )</formula>
        <label>Involved</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Local_Events_Attended__c</fullName>
        <defaultValue>0</defaultValue>
        <label>#Local Events Attended</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Marketing_Ambassador_Events_Attended1__c</fullName>
        <description>[DS[ I have filtered out YP records from here, as their metrics from last year should not be included here. This is a workaround while I think of something better</description>
        <formula>IF(OR( Contact__r.RecordTypeId = &quot;012C0000000Q2H0&quot;,Contact__r.RecordTypeId = &quot;012C0000000QBZg&quot;), 0,
IF(AND(ISPICKVAL(Contact__r.Account.Attended_Assembly_1__c,&apos;Yes&apos;),ISPICKVAL(Contact__r.Account.Attended_Assembly_2__c,&apos;Yes&apos;)),2,
IF(OR(ISPICKVAL(Contact__r.Account.Attended_Assembly_1__c,&apos;Yes&apos;),ISPICKVAL(Contact__r.Account.Attended_Assembly_2__c,&apos;Yes&apos;)),1,0)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>#Marketing Ambassador Events Attended</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Media_Ambassador_Events_Attended__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Where the Campaign RT is Development/Advocacy Event</inlineHelpText>
        <label>#Media Ambassador Events Attended</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PC_Meetings_Attended__c</fullName>
        <defaultValue>0</defaultValue>
        <label>#PC Meetings Attended</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Staffing_Ambassador__c</fullName>
        <defaultValue>0</defaultValue>
        <label>#Staffing Ambassador Events Attended</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_SignPosting_Oppty_Meetings_Attend__c</fullName>
        <defaultValue>0</defaultValue>
        <label>#Total SignPosting Oppty Meetings Attend</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>YB_Meetings_Attended__c</fullName>
        <defaultValue>0</defaultValue>
        <label>#YB Meetings Attended</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Metric</label>
    <nameField>
        <displayFormat>M-{0000}</displayFormat>
        <label>Metric Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Metrics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/IndividulMetricController.cls
public with sharing class IndividulMetricController {

public List<Metric__c> ListMetrics {get;set;}

public IndividulMetricController(ApexPages.StandardController cont){
	
	ListMetrics = new List<Metric__c>();
	String Contactid = cont.getId();
	ListMetrics = [SELECT id, YB_Meetings_Attended__c, CAT_Meetings_Attended__c,
				 Marketing_Ambassador_Events_Attended1__c, Media_Ambassador_Events_Attended__c, 
				 Staffing_Ambassador__c, PC_Meetings_Attended__c, Total_SignPosting_Oppty_Meetings_Attend__c, 
				 Big_Challenge_Day_Event_Attended__c, Local_Events_Attended__c, Involved__c, Active__c
				 FROM Metric__c WHERE Contact__c = :Contactid];
}
}