objects/Metric__c.object
<CustomObject>
    <description>Keeps the Contact and some detailed metrics</description>
    <fields>
        <fullName>Contact__c</fullName>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Metrics</relationshipLabel>
        <relationshipName>Metrics</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>PC_Meetings_Attended__c</fullName>
        <defaultValue>0</defaultValue>
        <label>#PC Meetings Attended</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Metric</label>
    <nameField>
        <displayFormat>M-{0000}</displayFormat>
        <label>Metric Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Metrics</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Personal_Coach__c.object
<CustomObject>
    <description>TCS Personal Coaching</description>
    <fields>
        <fullName>Young_person__c</fullName>
        <description>Master-detail link to YP being coached</description>
        <inlineHelpText>Link to the young person being coached</inlineHelpText>
        <label>Young person</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Personal Coaching</relationshipLabel>
        <relationshipName>Personal_Coaching</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Personal Coach</label>
    <nameField>
        <displayFormat>P#{000000}</displayFormat>
        <label>Personal Coach Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Personal Coaching</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Personal_Coach_Meetings__c.object
<CustomObject>
    <fields>
        <fullName>Meeting_attendance__c</fullName>
        <description>Picklist with YP attendance options</description>
        <inlineHelpText>Please specify whether or not the YP attended the scheduled meeting</inlineHelpText>
        <label>Did the YP attend the meeting?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Attended</fullName>
                </value>
                <value>
                    <fullName>Did not attend</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Personal_Coaching__c</fullName>
        <description>Master-detail link to the main Personal Coaching record</description>
        <inlineHelpText>Link to the main Personal Coaching record</inlineHelpText>
        <label>Personal Coaching</label>
        <referenceTo>Personal_Coach__c</referenceTo>
        <relationshipLabel>Personal Coach Meetings</relationshipLabel>
        <relationshipName>Personal_Coach_Meetings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Personal Coach Meeting</label>
    <nameField>
        <displayFormat>PCM#{000000}</displayFormat>
        <label>Personal Coach Meetings Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Personal Coach Meetings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Metric_CalculatePCMeetings.cls
public class Metric_CalculatePCMeetings {
	
private list<id> ContactIDs = new list<Id>();
private list<id> PCMeetingNotInclude = new list<Id>();
	public Metric_CalculatePCMeetings(list<Id> ContactIDs, list<Id> PCMeetingNotInclude){
		this.ContactIDs=ContactIDs;	
		this.PCMeetingNotInclude = PCMeetingNotInclude;
	}
	
	 public void DefineScope(){
	 
		List<Personal_Coach_Meetings__c> ListPCMeetings = new List<Personal_Coach_Meetings__c>();
		
		ListPCMeetings = [SELECT id, Personal_Coaching__c, Personal_Coaching__r.Young_person__c, Personal_Coaching__r.Young_person__r.Account.Attended_Assembly_1__c, 
			 	Personal_Coaching__r.Young_person__r.Account.Attended_Assembly_2__c FROM Personal_Coach_Meetings__c
			 	WHERE Meeting_attendance__c = 'Attended' AND Personal_Coaching__r.Young_person__c IN :this.ContactIDs 
			 	AND Id NOT IN :this.PCMeetingNotInclude];
			 	
		execute(ListPCMeetings);
	 }
	 
	  public void execute(List<Personal_Coach_Meetings__c> scope){
	       
	       List<Metric__c> ListMetrics = [SELECT id, Contact__c FROM Metric__c WHERE Contact__c IN :this.ContactIDs];
	       
	       for(Metric__c metric :ListMetrics){
	       	integer counter=0;
	       		for(Personal_Coach_Meetings__c pcm : scope){
	       		
	       		if(pcm.Personal_Coaching__r.Young_person__c == metric.Contact__c){
	       			counter++;
	       		}
	       	}
	       		metric.PC_Meetings_Attended__c = counter;
	       }
	       update ListMetrics;
	  }
}