objects/NCS_Application__c.object
<CustomObject>
    <fields>
        <fullName>Friend_requests__c</fullName>
        <label>Friend requests</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Season__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Season</label>
        <referenceTo>Season__c</referenceTo>
        <relationshipLabel>NCS Applications</relationshipLabel>
        <relationshipName>NCS_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>NCS Application</label>
    <nameField>
        <displayFormat>NCSA{000000}</displayFormat>
        <label>NCS Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NCS Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/NCS_Data_Entry_Staging__c.object
<CustomObject>
    <description>Staging object for transforming Captricity data into Account, Contact, NCS Application, Inclusion Details, Relationship records.</description>
    <fields>
        <fullName>Season__c</fullName>
        <label>Season</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>NCS Data Entry Staging</label>
    <nameField>
        <displayFormat>NCSDES-{000000}</displayFormat>
        <label>NCS Data Entry Staging Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NCS Data Entry Staging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/NCS_Data_Entry_Staging_Settings__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Source_Field__c</fullName>
        <description>NCS Data Entry Staging Field (Mapping from)</description>
        <inlineHelpText>This is the API name of the field on the NCS Data Entry Staging Object ie; yp_first_name__c</inlineHelpText>
        <label>Source Field</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Target_Field__c</fullName>
        <description>Target field, this is the field the Source Field maps to on the related Salesforce object</description>
        <inlineHelpText>Target Field on Target Object, uses the Salesforce API name ie, firstName, ap_recieved__c</inlineHelpText>
        <label>Target Field</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Target_Object__c</fullName>
        <inlineHelpText>Salesforce Object API name ie, Contact, Inclusion_Details__c</inlineHelpText>
        <label>Target Object</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Target_Type__c</fullName>
        <inlineHelpText>Target type is used to specify the target object for use within the APEX classes bg_NCSDataEntry

ENSURE ALL CAPITALS

Values are;
INC
NCS
YPCON
PGCON
YP&amp;PGCON</inlineHelpText>
        <label>Target Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>NCS Data Entry Staging Settings</label>
</CustomObject>

objects/Season__c.object
<CustomObject>
    <description>NCS season</description>
    <label>Season</label>
    <nameField>
        <label>Season Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Seasons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/bg_NCSApplicationUtils_Test.cls
/********************************************************************
 * bg_NCSApplicationUtils_Test
 *
 * Test class for bg_NCSApplicationUtils
 * 
 * Author: Antony Daley
 * Created: 05-04-2015
 * Changes: 
 *
 ********************************************************************/

@isTest
private class bg_NCSApplicationUtils_Test 
{

    static testMethod void testPopulateNCSApplication()
    {
    	//Disable the data creation triggers
    	bg_NCSDataEntryStagingUtils.DISABLE_TRIGGER_PROCESS = true;
    	
    	//Setup a custom setting - Source Fields are derived from the NCS Data Entry Staging object
        NCS_Data_Entry_Staging_Settings__c cstSetting = new NCS_Data_Entry_Staging_Settings__c();
        
        cstSetting.Name = 'NCS Test';
        cstSetting.Target_Field__c = 'Friend_requests__c';
        cstSetting.Target_Object__c = 'NCS_Application__c';
        cstSetting.Source_Field__c = 'Season__c';
        cstSetting.Target_Type__c = bg_NCSDataEntryStagingUtils.TARGET_TYPE_NCS;
        
        insert cstSetting;
        
        NCS_Data_Entry_Staging__c stagingRecord = bg_UnitTestHelper.getStagingObj('myemail@waterspout.com', null); 
        stagingRecord.Season__c = 'test';
        
        insert stagingRecord;
        
        map<String, List<bg_NCSDataEntryFieldMappingUtils.fieldMappingValidation>> fieldSourceToWrapperMap = bg_NCSDataEntryFieldMappingUtils.validateFieldMappings();
        
        NCS_Application__c ncsRecord = new NCS_Application__c();
        ncsRecord = bg_NCSApplicationUtils.populateNCSApplication(ncsRecord, stagingRecord, fieldSourceToWrapperMap.get(bg_NCSDataEntryStagingUtils.TARGET_TYPE_NCS), null);
    	
    	system.assertEquals(ncsRecord.Friend_requests__c, 'test');
    }
    
    static testMethod void testPopulateNCSApplicationNullValue()
    {
    	//Disable the data creation triggers
    	bg_NCSDataEntryStagingUtils.DISABLE_TRIGGER_PROCESS = true;
    	
    	//Setup a custom setting - Source Fields are derived from the NCS Data Entry Staging object
        NCS_Data_Entry_Staging_Settings__c cstSetting = new NCS_Data_Entry_Staging_Settings__c();
        
        cstSetting.Name = 'NCS Test';
        cstSetting.Target_Field__c = 'Friend_requests__c';
        cstSetting.Target_Object__c = 'NCS_Application__c';
        cstSetting.Source_Field__c = 'Season__c';
        cstSetting.Target_Type__c = bg_NCSDataEntryStagingUtils.TARGET_TYPE_NCS;
        
        insert cstSetting;
        
        NCS_Data_Entry_Staging__c stagingRecord = bg_UnitTestHelper.getStagingObj('myemail@waterspout.com', null); 
        stagingRecord.Season__c = '';
        
        insert stagingRecord;
        
        map<String, List<bg_NCSDataEntryFieldMappingUtils.fieldMappingValidation>> fieldSourceToWrapperMap = bg_NCSDataEntryFieldMappingUtils.validateFieldMappings();
        
        NCS_Application__c ncsRecord = new NCS_Application__c();
        ncsRecord.Friend_requests__c = 'test';
        ncsRecord = bg_NCSApplicationUtils.populateNCSApplication(ncsRecord, stagingRecord, fieldSourceToWrapperMap.get(bg_NCSDataEntryStagingUtils.TARGET_TYPE_NCS), null);
    	
    	system.assertEquals(ncsRecord.Friend_requests__c, 'test');
    }
}