objects/NCS_Application__c.object
<CustomObject>
    <fields>
        <fullName>Date_of_Birth_Approval__c</fullName>
        <label>Date of Birth Approval?</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Season__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Season</label>
        <referenceTo>Season__c</referenceTo>
        <relationshipLabel>NCS Applications</relationshipLabel>
        <relationshipName>NCS_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Wave__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Wave</label>
        <referenceTo>Wave__c</referenceTo>
        <relationshipLabel>NCS Applications</relationshipLabel>
        <relationshipName>NCS_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>X18_Status__c</fullName>
        <label>18+ Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>18+ for entire season</fullName>
                </value>
                <value>
                    <fullName>Turns 18+ During Season</fullName>
                </value>
                <value>
                    <fullName>DOB OK</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>YoungPerson__c</fullName>
        <label>Young Person</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>NCS Applications</relationshipLabel>
        <relationshipName>NCS_Applications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>NCS Application</label>
    <nameField>
        <displayFormat>NCSA{000000}</displayFormat>
        <label>NCS Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NCS Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Season__c.object
<CustomObject>
    <description>NCS season</description>
    <fields>
        <fullName>Oldest_Date_of_Birth_Possible_First_Wave__c</fullName>
        <label>Oldest Date of Birth Possible:FirstWave</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Oldest_date_of_birth__c</fullName>
        <label>Oldest date of birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Youngest_date_of_birth__c</fullName>
        <label>Youngest date of birth</label>
        <type>Date</type>
    </fields>
    <label>Season</label>
    <nameField>
        <label>Season Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Seasons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Wave__c.object
<CustomObject>
    <fields>
        <fullName>Season__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Which season the wave is part of.  A look up to the Season object</description>
        <label>Season</label>
        <referenceTo>Season__c</referenceTo>
        <relationshipLabel>Waves</relationshipLabel>
        <relationshipName>Waves</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Wave</label>
    <nameField>
        <label>Wave Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Waves</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/NCSApp18PlusStatus.cls
/*
@ Description : Update '18+ Status' field on 'NCS Application'
@ Called From : update18PlusStatus (Trigger)
@ Developer : Shaikh Saquib
@ Date : 27-Oct-2014
*/
public class NCSApp18PlusStatus {

    public static void update18PlusStatus(List<NCS_Application__c> ncsApplicationList) {
    
        set<id> setOfNCSApplicationIds = new set<id>();
        for(NCS_Application__c ncsApplicationRec : ncsApplicationList) {
           setOfNCSApplicationIds.add(ncsApplicationRec.id);
        }
        
        if(setOfNCSApplicationIds.size() > 0) {
            List<NCS_Application__c> ncsAppList = [SELECT id, YoungPerson__r.Birthdate,YoungPerson__c, 
                                                           Season__c, Season__r.Oldest_date_of_birth__c,
                                                           Season__r.Youngest_date_of_birth__c, 
                                                           Season__r.Oldest_Date_of_Birth_Possible_First_Wave__c
                                                    FROM NCS_Application__c
                                                    WHERE ID IN:setOfNCSApplicationIds ];
            // NCS Application related Season 'oldest date of birth possible' and 'oldest date of birth' field values
            Date oldestDOBPossible, oldestDOB, youngestDOB;
            // NCS Application related Young Person(Contact) 'Birthdate' field value
            Date youngPersonDOB;

            for(NCS_Application__c ncsApplicationRec : ncsAppList) {
            
                if(ncsApplicationRec.YoungPerson__c != null && ncsApplicationRec.Season__c != null) {
                    oldestDOBPossible = ncsApplicationRec.Season__r.Oldest_Date_of_Birth_Possible_First_Wave__c;
                    oldestDOB = ncsApplicationRec.Season__r.Oldest_date_of_birth__c;
                    youngestDOB = ncsApplicationRec.Season__r.Youngest_date_of_birth__c;
                    youngPersonDOB = ncsApplicationRec.YoungPerson__r.Birthdate;
                    
                    if(youngestDOB != null && youngPersonDOB != null && youngPersonDOB > youngestDOB) {
                    
                        ncsApplicationRec.X18_Status__c = 'Too Young';
                        
                    } else if((oldestDOBPossible != null && oldestDOB != null) && 
                            (oldestDOB > youngPersonDOB && oldestDOBPossible <= youngPersonDOB)) {
                            
                        ncsApplicationRec.X18_Status__c = 'Turns 18+ During Season';
                        
                    }else if((youngPersonDOB != null && oldestDOBPossible != null) && 
                            (youngPersonDOB < oldestDOBPossible)) {
                            
                        ncsApplicationRec.X18_Status__c = '18+ for entire season';
                        
                    } else {
                    
                        ncsApplicationRec.X18_Status__c = 'DOB OK';
                        
                    }
                }
            }
            
            if(ncsAppList.size() > 0) {
                UPDATE ncsAppList;
                // If NCS application is changed then update Wave_Selection__c
                updateWaveSelection(setOfNCSApplicationIds);
            }
        }
            
    }
    
    public static void onNCSAppUpdate(List<NCS_Application__c> newNCSAppList, Map<Id, NCS_Application__c> oldMapNCSApp) {
        
        NCS_Application__c oldNCSAppRec = new NCS_Application__c();
        Set<Id> nscAppIds = new Set<Id>(); 
        for(NCS_Application__c ncsAppRec: newNCSAppList) {
            oldNCSAppRec = oldMapNCSApp.get(ncsAppRec.id);
            if(((ncsAppRec.Date_of_Birth_Approval__c != oldNCSAppRec.Date_of_Birth_Approval__c) && (ncsAppRec.Date_of_Birth_Approval__c == null || oldNCSAppRec.Date_of_Birth_Approval__c == null )) || (ncsAppRec.Season__c != oldNCSAppRec.Season__c))
                nscAppIds.add(ncsAppRec.id);
        }
        system.debug('nscAppIds size=='+nscAppIds.size());
        if(nscAppIds.size() > 0) 
            updateWaveSelection(nscAppIds);
        
    }
    
    private static void updateWaveSelection(Set<Id> nscAppIds) {
        
        List<Wave_Selection__c> waveSelectionList = new List<Wave_Selection__c>([SELECT Id,NCS_Application__c, Young_Person__c,
                                                                                        Wave__c, X18__c
                                                                                 FROM Wave_Selection__c
                                                                                 WHERE NCS_Application__c IN :nscAppIds ]);
        if(waveSelectionList.size() > 0){
            update18PlusOnWaveSelectionHandler update18PlusOnWave = new update18PlusOnWaveSelectionHandler();
            update18PlusOnWave.update18Plus(waveSelectionList,null);
            UPDATE waveSelectionList;
        }
    }
}