objects/NCS_Application__c.object
<CustomObject>
    <fields>
        <fullName>YoungPerson__c</fullName>
        <label>Young Person</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>NCS Applications</relationshipLabel>
        <relationshipName>NCS_Applications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>NCS Application</label>
    <nameField>
        <displayFormat>NCSA{000000}</displayFormat>
        <label>NCS Application Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NCS Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/NCS_Data_Entry_Staging__c.object
<CustomObject>
    <description>Staging object for transforming Captricity data into Account, Contact, NCS Application, Inclusion Details, Relationship records.</description>
    <label>NCS Data Entry Staging</label>
    <nameField>
        <displayFormat>NCSDES-{000000}</displayFormat>
        <label>NCS Data Entry Staging Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NCS Data Entry Staging</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/bg_NCSApplicationUtils.cls
/********************************************************************
 * bg_NCSApplicationUtils
 *
 * Utility class for NCS_Application__c's
 * 
 * Test Class: bg_NCSApplicationUtils_Test
 * Author: Antony Daley
 * Created: 03-04-2015
 * Changes: 
 *
 ********************************************************************/

public class bg_NCSApplicationUtils 
{

	/*
		Takes in a Contact Record, a NCS Data Entry Wizzard Staging Object and a list of validated fields for the Contact, loops through the field mapping an populates the Contact with the mapped fields in the Staging object.
	*/
	public static NCS_Application__c populateNCSApplication(NCS_Application__c ncsRecord, NCS_Data_Entry_Staging__c stagingRecord, List<bg_NCSDataEntryFieldMappingUtils.fieldMappingValidation> validatedFields, Id parentId)
	{
		if(ncsRecord.YoungPerson__c == null)
		{
			ncsRecord.YoungPerson__c = parentId;
		}
		if(validatedFields != null)
		{
			for(bg_NCSDataEntryFieldMappingUtils.fieldMappingValidation wrapper : validatedFields)
			{
				if(!bg_NCSDataEntryFieldMappingUtils.isFieldBlank(stagingRecord, wrapper.SourceField, wrapper.SourceDisplayType))
				{
					ncsRecord.put(wrapper.TargetField, stagingRecord.get(wrapper.SourceField));
				}
			}
		}
		
		return ncsRecord;
	}
}