objects/PAYBASE2__Payment__c.object
<CustomObject>
    <description>Represents payments from you to your customers</description>
    <fields>
        <fullName>PAYBASE2__Amount__c</fullName>
        <description>Payment amount</description>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PAYBASE2__Pay_Date__c</fullName>
        <label>Pay Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PAYBASE2__Status__c</fullName>
        <description>Payment status</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PAYCP2__Authorisation_Code__c</fullName>
        <description>Transaction authorisation code returned by payment gateway</description>
        <label>Authorisation Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PAYCP2__Name_On_Card__c</fullName>
        <description>Card holder&apos;s name</description>
        <label>Name On Card</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Payonomy Payment</label>
    <nameField>
        <label>Payonomy Payment Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payonomy Payments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PAYBASE2__Refund__c.object
<CustomObject>
    <description>Represents payments from you to your customers</description>
    <fields>
        <fullName>PAYBASE2__Amount__c</fullName>
        <description>The refund amount</description>
        <label>Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>PAYBASE2__Pay_Date__c</fullName>
        <description>Date that the refund is to happen</description>
        <label>Pay Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>PAYBASE2__Payment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Payment</label>
        <referenceTo>PAYBASE2__Payment__c</referenceTo>
        <relationshipName>Refunds</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PAYBASE2__Status__c</fullName>
        <description>Status of the refund transaction</description>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Error</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PAYCP2__Authorisation_Code__c</fullName>
        <description>Transaction authorisation code returned by payment gateway</description>
        <label>Authorisation Code</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PAYCP2__Reason__c</fullName>
        <description>Reason for the refund</description>
        <label>Reason</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Payonomy Refund</label>
    <nameField>
        <label>Payonomy Refund Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Payonomy Refunds</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/PMTestOpportunityPB2.cls
@isTest
public with sharing class PMTestOpportunityPB2 {

	public static testMethod void testOpportunityTrigger(){
		// the above does check the opportunity trigger to well over 60%.  add the following to get past 75%
		List<PAYBASE2__Payment__c> p= new list<Paybase2__Payment__c>{
										new PayBase2__payment__c(PAYBASE2__Amount__c=3, PAYCP2__Name_On_Card__c='test3quid'),
										new PayBase2__payment__c(PAYBASE2__Amount__c=4, PAYCP2__Name_On_Card__c='test4q',PAYBASE2__Status__c = 'AUTHORISED') 
										};
		insert p;
		
		//p[0].
		
		System.debug('Done insert, will now delete');
		
		PAYBASE2__Refund__c [] refs = new PAYBASE2__Refund__c [] {
			new PAYBASE2__Refund__c(PAYBASE2__Payment__c = p.get(1).id, 
						PAYBASE2__pay_date__c = Date.today(), PAYCP2__Reason__c = 'TEST', 
						PAYBASE2__Amount__c = 3, PAYCP2__Authorisation_Code__c = 'TEST')
		};
	
		
		// test delete trigger
		delete p;		
	}

}