objects/Personal_Coach__c.object
<CustomObject>
    <description>TCS Personal Coaching</description>
    <fields>
        <fullName>Coach__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup relationship to the YP&apos;s coach</description>
        <inlineHelpText>Link to the YP&apos;s coach</inlineHelpText>
        <label>Coach</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Personal_Coaching</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Young_person__c</fullName>
        <description>Master-detail link to YP being coached</description>
        <inlineHelpText>Link to the young person being coached</inlineHelpText>
        <label>Young person</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Personal Coaching</relationshipLabel>
        <relationshipName>Personal_Coaching</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Personal Coach</label>
    <nameField>
        <displayFormat>P#{000000}</displayFormat>
        <label>Personal Coach Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Personal Coaching</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Personal_Coach_Meetings__c.object
<CustomObject>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location of Meeting</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Meeting_date__c</fullName>
        <description>Date field for capturing date of scheduled meeting with YP</description>
        <inlineHelpText>Date of the scheduled meeting with the YP</inlineHelpText>
        <label>Date of meeting</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Meeting_successful__c</fullName>
        <label>Meeting successful?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Meeting_summary__c</fullName>
        <description>Long text area for capturing notes of the meeting</description>
        <inlineHelpText>Please provide a summary or outline of the meeting</inlineHelpText>
        <label>Meeting summary</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Personal_Coaching__c</fullName>
        <description>Master-detail link to the main Personal Coaching record</description>
        <inlineHelpText>Link to the main Personal Coaching record</inlineHelpText>
        <label>Personal Coaching</label>
        <referenceTo>Personal_Coach__c</referenceTo>
        <relationshipLabel>Personal Coach Meetings</relationshipLabel>
        <relationshipName>Personal_Coach_Meetings</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Time_of_meeting__c</fullName>
        <label>Time of meeting</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Personal Coach Meeting</label>
    <nameField>
        <displayFormat>PCM#{000000}</displayFormat>
        <label>Personal Coach Meetings Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Personal Coach Meetings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TCSPortal_ContactHomeController.cls
public with sharing class TCSPortal_ContactHomeController {

public Integer hasPC {get;set;}
public String PCid {get;set;}
public boolean isPCProfile {get;set;}
public TCSPortal_ContactHomeController(ApexPages.StandardController stdController){
    hasPC = 0;
    String ConId = stdController.getId();
    User u = [select id, Profile.Name from User where id = :Userinfo.getUserId()];
    if(u.Profile.Name.contains('PC')){
        isPCProfile = true;
    }else{  
        isPCProfile = false;
    }
    Contact c = [select id, (select id from Personal_Coaching__r) from Contact where id=:ConId];
    if(c.Personal_Coaching__r.size()>0){
        hasPC = 1;
        PCid = c.Personal_Coaching__r[0].id;
    }
} 

@IsTest
  static void testContatHomeController () {
      Contact c = new Contact();
      c.LastName = 'Test Contact';
      insert c;
       
       Personal_Coach__c pc = new personal_Coach__c();
       pc.Young_person__c = c.id;
       insert pc;
       
       Personal_Coach_Meetings__c pcm = new Personal_Coach_Meetings__c(Meeting_summary__c='test desc',
                                                                                Meeting_date__c=date.today(),
                                                                                Location__c='test',
                                                                                Time_of_meeting__c='test',
                                                                                Meeting_successful__c = 'Yes');// new Fields added
       pcm.Personal_Coaching__c = pc.id;
       insert pcm;
       
        ApexPages.StandardController stdController=new ApexPages.StandardController(c);
        PageReference DummyPage=new PageReference('/TCNPortal_ContactHome?id='+c.Id);
        Test.setCurrentPage(DummyPage);
        TCSPortal_ContactHomeController controller = new TCSPortal_ContactHomeController(stdController);                        
    }    
}