objects/Relationship__c.object
<CustomObject>
    <description>Relationship records for relationship widget.Keeps relationships  between contact account,account contact,account account,contact contact.</description>
    <fields>
        <fullName>First_Relationship_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>First Relationship Type</label>
        <referenceTo>Relationship_Type__c</referenceTo>
        <relationshipLabel>Relationships (First Relationship Type)</relationshipLabel>
        <relationshipName>First_Relationship_Type</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>From_Individual__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Pick only ONE &quot;From&quot;, either Institution or Individual</inlineHelpText>
        <label>From Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Relationships (From Individual)</relationshipLabel>
        <relationshipName>Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Key_Relationship__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Is this a KEY relationship? Used in reports.</inlineHelpText>
        <label>Key Relationship</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Second_Relationship_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Second Relationship Type</label>
        <referenceTo>Relationship_Type__c</referenceTo>
        <relationshipLabel>Second Relationship Type</relationshipLabel>
        <relationshipName>Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>To_Individual__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>To Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Relationships (To Individual)</relationshipLabel>
        <relationshipName>Affiliations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Relationship</label>
    <nameField>
        <label>Relationship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Relationship_Type__c.object
<CustomObject>
    <label>Relationship Type</label>
    <nameField>
        <label>Relationship Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relationship Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/bg_RelationshipUtils.cls
/********************************************************************
 * bg_RelationshipUtils
 *
 * Utility class for Relationship__c's
 * 
 * Test Class : bg_RelationshipUtils_Test
 * Author: Antony Daley
 * Created: 03-04-2015
 * Changes: 
 *
 ********************************************************************/

public class bg_RelationshipUtils 
{
	/*
		Create a relationship for the passed in individuals and what type of relationship they have
	*/
	public static Relationship__c CreateRelationship(Id fromPersonId, Id toPersonId, ID relationshipTypeFromId, ID relationshipTypeToId)
	{
		Relationship__c relationshipToCreate = new Relationship__c();
		relationshipToCreate.From_Individual__c = fromPersonId;
		relationshipToCreate.To_Individual__c = toPersonId;
		relationshipToCreate.First_Relationship_Type__c = relationshipTypeToId;
		relationshipToCreate.Second_Relationship_Type__c = relationshipTypeFromId;
		relationshipToCreate.Key_Relationship__c = true;
		
		return relationshipToCreate;
	}
	
	/*  
		Return a Map of the relationship types name to the records id to be used when creating a relationship
	*/
	public static map<String, Id> GetMapOfRelationshipTypeNameToId()
	{
		map<String, Id> relationshipTypeNameToIdMap = new map<String, Id>();
		for(Relationship_Type__c relationship : [SELECT Name, ID FROM Relationship_Type__c])
		{
			relationshipTypeNameToIdMap.put(relationship.Name, relationship.Id);
		}
		
		return relationshipTypeNameToIdMap;
	}
}