objects/Relationship__c.object
<CustomObject>
    <description>Relationship records for relationship widget.Keeps relationships  between contact account,account contact,account account,contact contact.</description>
    <fields>
        <fullName>End_Date__c</fullName>
        <inlineHelpText>Leave blank if no end.</inlineHelpText>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>First_Relationship_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>First Relationship Type</label>
        <referenceTo>Relationship_Type__c</referenceTo>
        <relationshipLabel>Relationships (First Relationship Type)</relationshipLabel>
        <relationshipName>First_Relationship_Type</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>From_Individual__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Pick only ONE &quot;From&quot;, either Institution or Individual</inlineHelpText>
        <label>From Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Relationships (From Individual)</relationshipLabel>
        <relationshipName>Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>From_Institution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Pick only ONE &quot;From&quot;, either Institution OR Individual.</inlineHelpText>
        <label>From Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Relationships (From Institution)</relationshipLabel>
        <relationshipName>Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>From_Relationship_Entity__c</fullName>
        <label>From Relationship Entity</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Institution</fullName>
                </value>
                <value>
                    <fullName>Individual</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Key_Relationship__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Is this a KEY relationship? Used in reports.</inlineHelpText>
        <label>Key Relationship</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Second_Relationship_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Second Relationship Type</label>
        <referenceTo>Relationship_Type__c</referenceTo>
        <relationshipLabel>Second Relationship Type</relationshipLabel>
        <relationshipName>Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Start_Date__c</fullName>
        <defaultValue>today()</defaultValue>
        <inlineHelpText>When did this relationship start?</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>To_Individual__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>To Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Relationships (To Individual)</relationshipLabel>
        <relationshipName>Affiliations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>To_Institution__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Pick only ONE To, either Institution OR Individual.</inlineHelpText>
        <label>To Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Relationships (To Institution)</relationshipLabel>
        <relationshipName>Affiliations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>To_Relationship_Entity__c</fullName>
        <label>To Relationship Entity</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Individual</fullName>
                </value>
                <value>
                    <fullName>Institution</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Relationship</label>
    <nameField>
        <label>Relationship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Relationship_Type__c.object
<CustomObject>
    <label>Relationship Type</label>
    <nameField>
        <label>Relationship Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relationship Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/extEditRel.cls
public class extEditRel 
{
/***** VARIABLE *****/ 
 
  sObject sObj;  
  public ID objId;
  private String strAccKeyPrefix = Schema.SObjectType.Account.getKeyPrefix();
  private String strConKeyPrefix = Schema.SObjectType.Contact.getKeyPrefix();

  public Relationship__c rel = new Relationship__c();
  
  private String strRId = '';
  private String strEdt = '';
  private String na = '';
  private String ob = '';
  private String cr = '';
  private String cr2 = '';
  private String cr3 = '';
  private String cb = '';  
  



  public Relationship__c propRelationship { get {return rel;} set {rel = value;} }
  
  public List<SelectOption> getPropRelationshipType() 
  {
    List<Relationship_Type__c> lstRT = [SELECT id, name FROM Relationship_Type__c ORDER BY name];
    
    List<SelectOption> lstOpt = new List<SelectOption>();
    lstOpt.add(new selectOption('', '--None--'));
    
    if(!lstRT.isEmpty())
      for(Relationship_Type__c oRT : lstRT)
        lstOpt.add(new SelectOption(oRT.Id, oRT.Name));

    return lstOpt;
  }//End Prop getPropRelationshipType
  
  public Boolean propIsEdit
  {
    get { return (strEdt == 'T') ? true : false; }
    set;
  }//End Prop propIsEdit
  
  public String propParentId { get; set; }
  public String propFromIndInsName { get; set; }
  public String propToIndInsName { get; set; }
  
  public String propSelVal { get; set; }//Selected value of Entity type dropdown
  public String propSelValE1toE2 { get; set; }//Selected value of Entity 1 to Entity 2 dropdown
/*** END PROPERTY ***/

/***** CONSTRUCTOR *****/

  public extEditRel(ApexPages.StandardController controller)
  {
    sObj = controller.getRecord(); 
    objId = sObj.ID;
    objId = (Id)ApexPages.currentPage().getParameters().get('Id');
    propParentId = objId;
    
    strRId = ApexPages.currentPage().getParameters().get('rId');
    strEdt = ApexPages.currentPage().getParameters().get('edt');
    na = ApexPages.CurrentPage().getParameters().get('na');  
    ob = ApexPages.CurrentPage().getParameters().get('ob');  
    cr = ApexPages.CurrentPage().getParameters().get('cr');
    cr2 = ApexPages.CurrentPage().getParameters().get('cr2');
    cr3 = ApexPages.CurrentPage().getParameters().get('cr3');
    cb = ApexPages.CurrentPage().getParameters().get('cb');
 
    
    strRId = (ApexPages.currentPage().getParameters().get('rId') != null) ? ApexPages.currentPage().getParameters().get('rId') : '';
    strEdt = (ApexPages.currentPage().getParameters().get('edt') != null) ? ApexPages.currentPage().getParameters().get('edt') : '';
    na = (ApexPages.CurrentPage().getParameters().get('na') != null) ? ApexPages.CurrentPage().getParameters().get('na') : '';  
    ob = (ApexPages.CurrentPage().getParameters().get('ob') != null) ? ApexPages.CurrentPage().getParameters().get('ob') : '';  
    cr = (ApexPages.CurrentPage().getParameters().get('cr') != null) ? ApexPages.CurrentPage().getParameters().get('cr') : '';
    cr2 = (ApexPages.CurrentPage().getParameters().get('cr2') != null) ? ApexPages.CurrentPage().getParameters().get('cr2') : '';
    cr3 = (ApexPages.CurrentPage().getParameters().get('cr3') != null) ? ApexPages.CurrentPage().getParameters().get('cr3') : '';
    cb = (ApexPages.CurrentPage().getParameters().get('cb') != null) ? ApexPages.CurrentPage().getParameters().get('cb') : '';
    
    
    AfterConstructor();
  }
/*** END CONSTRUCTOR ***/

/***** FUNCTION *****/

  private void AfterConstructor()
  {
    if(objId != null && strRId == '' && strEdt == 'F')//New relationship creation request
    {
      if(String.valueOf(objId).startsWith(strAccKeyPrefix))//Account record
      {
        rel.From_Relationship_Entity__c = 'Institution';
        rel.From_Institution__c = String.valueOf(objId);
        rel.To_Relationship_Entity__c = 'Individual';
        rel.Start_Date__c = Date.Today();
      }
      else if(String.valueOf(objId).startsWith(strConKeyPrefix))//Contact record
      {
        rel.From_Relationship_Entity__c = 'Individual';
        rel.From_Individual__c = String.valueOf(objId);
        rel.To_Relationship_Entity__c = 'Institution';
        rel.Start_Date__c = Date.Today();
      }
    }
    else if(objId != null && strRId != '' && strEdt == 'T')//Edit relationship request
    {   
      rel = [SELECT r.From_Relationship_Entity__c, r.From_Institution__c, r.From_Institution__r.Id, r.From_Institution__r.Name, r.From_Individual__c, r.From_Individual__r.id, r.From_Individual__r.Name, r.To_Relationship_Entity__c, r.To_Institution__c, r.To_Institution__r.Id, r.To_Institution__r.Name, r.To_Individual__c, r.To_Individual__r.Id, r.To_Individual__r.Name, r.First_Relationship_Type__c, r.Second_Relationship_Type__c, r.Start_Date__c, r.End_Date__c, r.Key_Relationship__c  FROM Relationship__c r WHERE r.Id =: strRId];
      if(String.valueOf(objId).startsWith(strAccKeyPrefix))//Account record
      {
        if(rel.From_Institution__r.Id == String.valueOf(objId))
          propFromIndInsName = rel.From_Institution__r.Name;
        else if(rel.To_Institution__r.Id == String.valueOf(objId))
          propToIndInsName = rel.To_Institution__r.Name;
      }
      else if(String.valueOf(objId).startsWith(strConKeyPrefix))//Contact record
      {
        if(rel.From_Individual__r.Id == String.valueOf(objId))
          propFromIndInsName = rel.From_Individual__r.Name;
        else if(rel.To_Individual__r.Id == String.valueOf(objId))
          propToIndInsName = rel.To_Individual__r.Name;   
      }
    }
  }//End Func AfterConstructor
  
  public PageReference CancelPage()
  {
    PageReference pr;
    if(String.valueOf(objId).startsWith(strAccKeyPrefix))//Account record
      pr = new PageReference('/apex/treeDLoading');//pr = new PageReference('/apex/tree');
    else if(String.valueOf(objId).startsWith(strConKeyPrefix))//Contact record
      pr = new PageReference('/apex/treeCDLoading');//pr = new PageReference('/apex/treeC');

    pr.getParameters().put('id', String.valueOf(objId));
    pr.getParameters().put('na', na);
    pr.getParameters().put('ob', ob);
    pr.getParameters().put('cr', cr);
    pr.getParameters().put('cr2', cr2);
    pr.getParameters().put('cr3', cr3);
    pr.getParameters().put('cb', cb);      

    pr.setRedirect(true);
    return pr;
  }//End Func CancelPage
  
  public PageReference SavePage()
  {
    Pagereference pr;
    Database.UpsertResult up = Database.Upsert(rel);
    if(up.isSuccess())
    {
      if(String.valueOf(objId).startsWith(strAccKeyPrefix))//Account record
        pr = new PageReference('/apex/treeDLoading');//pr = new PageReference('/apex/tree');
      else if(String.valueOf(objId).startsWith(strConKeyPrefix))//Contact record
        pr = new PageReference('/apex/treeCDLoading');//pr = new PageReference('/apex/treeC');

      pr.getParameters().put('id', String.valueOf(objId));
      pr.getParameters().put('na', na);
      pr.getParameters().put('ob', ob);
      pr.getParameters().put('cr', cr);
      pr.getParameters().put('cr2', cr2);
      pr.getParameters().put('cr3', cr3);
      pr.getParameters().put('cb', cb);             
      pr.SetRedirect(true);
    }
    else
      pr = null;
    return pr;
  }//End Func SavePage
  
  public void FlipFromLookupType()
  {
    if(propSelVal == 'Institution')
    {
      rel.From_Individual__c = null;
      rel.From_Relationship_Entity__c = 'Institution';
    }
    else if(propSelVal == 'Individual')
    {        
      rel.From_Institution__c = null;
      rel.From_Relationship_Entity__c = 'Individual';
    }
  }//End Func FlipFromLookupType
  
  public void FlipToLookupType()
  {
    if(propSelVal == 'Institution')
    {
      rel.To_Individual__c = null;
      rel.To_Relationship_Entity__c = 'Institution';
    }
    else if(propSelVal == 'Individual')
    {
      rel.To_Institution__c = null;
      rel.To_Relationship_Entity__c = 'Individual';
    }
  }//End Func FlipToLookupType
  
  public void ChangeE2toE1()
  {
    if(propSelValE1toE2 != null)
      rel.Second_Relationship_Type__c = propSelValE1toE2;
  }//End Func ChangeE2toE1
/*** END FUNCTION ***/

/***** TEST METHOD *****/
/*** END TEST METHOD ***/
}//End Class extEditRel