objects/Relationship__c.object
<CustomObject>
    <description>Relationship records for relationship widget.Keeps relationships  between contact account,account contact,account account,contact contact.</description>
    <fields>
        <fullName>From_Individual__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Pick only ONE &quot;From&quot;, either Institution or Individual</inlineHelpText>
        <label>From Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Relationships (From Individual)</relationshipLabel>
        <relationshipName>Relationships</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>To_Individual__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>To Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Relationships (To Individual)</relationshipLabel>
        <relationshipName>Affiliations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Relationship</label>
    <nameField>
        <label>Relationship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/bg_SObjectUtils_Test.cls
/********************************************************************
 * bg_SObjectUtils_Test
 *
 * Test class for bg_SObjectUtils
 * 
 * Author: Antony Daley
 * Created: 15-04-2015
 * Changes: 
 *
 ********************************************************************/

@isTest
private class bg_SObjectUtils_Test 
{

	static testMethod void testGetStringFieldListForAPIName() 
    {
        String contactFieldString = bg_SObjectUtils.getStringFieldListForAPIName('Contact');
        system.debug(contactFieldString);
        system.assertEquals(true, contactFieldString.contains('firstname'));
        system.assertEquals(true, contactFieldString.contains('lastname'));
        
        system.assertEquals(false, contactFieldString.contains('randomfieldname__z'));
        
        String relationshipFieldString = bg_SObjectUtils.getStringFieldListForAPIName('Relationship__c');
        system.debug(relationshipFieldString);
        system.assertEquals(true, relationshipFieldString.contains('from_individual__c'));
        system.assertEquals(true, relationshipFieldString.contains('to_individual__c'));
        
        system.assertEquals(false, relationshipFieldString.contains('randomfieldname__z'));
        
        
    }
}