objects/Relationship__c.object
<CustomObject>
    <description>Relationship records for relationship widget.Keeps relationships  between contact account,account contact,account account,contact contact.</description>
    <fields>
        <fullName>Key_Relationship__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Is this a KEY relationship? Used in reports.</inlineHelpText>
        <label>Key Relationship</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>To_Individual__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>To Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Relationships (To Individual)</relationshipLabel>
        <relationshipName>Affiliations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Relationship</label>
    <nameField>
        <label>Relationship Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Relationship_Type__c.object
<CustomObject>
    <label>Relationship Type</label>
    <nameField>
        <label>Relationship Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Relationship Types</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/bg_RelationshipUtils_Test.cls
/********************************************************************
 * bg_RelationshipUtils_Test
 *
 * Test class for bg_RelationshipUtils
 * 
 * Author: Antony Daley
 * Created: 31-03-2015
 * Changes: 
 *
 ********************************************************************/

@isTest
private class bg_RelationshipUtils_Test 
{
	static testMethod void testCreateRelationship()
	{
		//Disable the data creation triggers
    	CreateNCSnIncDetailRecrdOnContactHandler.DISABLE_CREATE_NCS_AND_INC = true;
    	KeyRelHandler.DISABLE_CREATE_NRELATIONSHIPS = true;
    	bg_NCSDataEntryStagingUtils.DISABLE_TRIGGER_PROCESS = true;
        
        Account testAccount = bg_UnitTestHelper.createAccount('The Web Family');
        RecordType youngPersonRecordType = bg_RecordTypeUtils.getRecordType('Contact', bg_RecordTypeUtils.RECORD_TYPE_NAME_CONTACT_YOUNG_PERSON);
        RecordType parentGuardianRecordType = bg_RecordTypeUtils.getRecordType('Contact', bg_RecordTypeUtils.RECORD_TYPE_NAME_CONTACT_PARENT_GUARDIAN);
	        
	    Contact youngPerson = bg_UnitTestHelper.createContact('Spider', 'Pig', testAccount.Id, youngPersonRecordType.Id, 'myemail@waterspout.com');
        Contact parentGuardian = bg_UnitTestHelper.createContact('Spider', 'Man', testAccount.Id, parentGuardianRecordType.Id, 'parentEmail@waterspout.com');
        
        Relationship_Type__c testType = new Relationship_Type__c();
        testType.Name = 'bgTestType';
        insert testType;
        
        Relationship__c relationship = bg_RelationshipUtils.CreateRelationship(youngPerson.Id, parentGuardian.Id, testType.Id, testType.Id);
		system.assertEquals(relationship.To_Individual__c, parentGuardian.Id);
		system.assertEquals(relationship.Key_Relationship__c, true);
	}
	
	static testMethod void testGetMapOfRelationshipTypeNameToId()
	{
		//Disable the data creation triggers
    	CreateNCSnIncDetailRecrdOnContactHandler.DISABLE_CREATE_NCS_AND_INC = true;
    	KeyRelHandler.DISABLE_CREATE_NRELATIONSHIPS = true;
    	bg_NCSDataEntryStagingUtils.DISABLE_TRIGGER_PROCESS = true;
        
        Relationship_Type__c testType = new Relationship_Type__c();
        testType.Name = 'bgTestType';
        insert testType;
        
        map<String, Id> relationshipTypeNameToIdMap = bg_RelationshipUtils.GetMapOfRelationshipTypeNameToId();
        system.assertEquals(relationshipTypeNameToIdMap.containsKey('bgTestType'), true);
        system.assertEquals(relationshipTypeNameToIdMap.size(), 1);
	}
}