objects/smagicinteract__Scheduled_SMS__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Scheduled SMSs</relationshipLabel>
        <relationshipName>Scheduled_SMSs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SenderId__c</fullName>
        <label>SenderId</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>smagicinteract__MobilePhone__c</fullName>
        <label>MobilePhone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>smagicinteract__ObjectId__c</fullName>
        <label>ObjectId</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>smagicinteract__Object_Type__c</fullName>
        <label>Object Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>smagicinteract__Scheduled_Date__c</fullName>
        <label>Scheduled Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>smagicinteract__jobId__c</fullName>
        <label>jobId</label>
        <length>200</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>smagicinteract__smsText__c</fullName>
        <label>smsText</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>smagicinteract__status__c</fullName>
        <defaultValue>&quot;active&quot;</defaultValue>
        <label>status</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Scheduled SMS</label>
    <nameField>
        <displayFormat>SS-{0000000}</displayFormat>
        <label>Scheduled SMS Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scheduled SMSs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Wave__c.object
<CustomObject>
    <label>Wave</label>
    <nameField>
        <label>Wave Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Waves</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/WaveSMSBatch.cls
global class WaveSMSBatch implements Database.Batchable<sObject>, Database.AllowsCallouts{
	
	global String waveId = '';
	global Date scheduleDate = null;
	global String smsText = '';
	global String senderId = '';
	global List<smagicinteract__Scheduled_SMS__c> scheduleSMSList = new List<smagicinteract__Scheduled_SMS__c>();
	global WaveSMSBatch(String idOfWave, Date dateToSchedule, String waveSMSText)
	{
		this.waveId = idOfWave;
		this.scheduleDate = dateToSchedule;
		this.smsText = waveSMSText;
	}
	
	global WaveSMSBatch(String idOfWave, Date dateToSchedule, String waveSMSText, String senderIdName)
	{
		this.waveId = idOfWave;
		this.scheduleDate = dateToSchedule;
		this.smsText = waveSMSText;
		this.senderId = senderIdName;
		system.debug(system.loggingLevel.INFO, 'Sender ID : '+senderId);
	}

	global Database.QueryLocator start(Database.BatchableContext BC){
		
		 List<String> recordTypeNameList = new List<String>();
		 recordTypeNameList.add('YP');
		 recordTypeNameList.add('YP2012');
		 recordTypeNameList.add('YP2013');
		 recordTypeNameList.add('YP2014');
		 recordTypeNameList.add('Young Person');
		 List <RecordType> rtList = [select Id, Name, Description  from RecordType where Name in :recordTypeNameList];
		 system.debug(system.logginglevel.INFO, rtList);
		 List<Id> recordTypeIdList = new List<Id>();
		 for(RecordType recordTypeId :rtList){
		 	recordTypeIdList.add(recordTypeId.Id);
		 }
		 String statusString = 'Assigned';
   	  	 String query = 'select Id, YP_Mobile__c, YPContactID__c, Wave__c from Wave_Selection__c where Young_Person__r.RecordTypeId in :recordTypeIdList and Wave__c= :waveId and Status__c = :statusString';
		 return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<sObject> scope){
    	system.debug(system.logginglevel.INFO, 'Scope List : '+scope);
    	map<Id,string> WaveSelectionIdTempTextMap = new map<Id,string>();
	
    	WaveBatchTemplateRenderingHelper WaveBatchRenderingHelper = new WaveBatchTemplateRenderingHelper();
    	WaveSelectionIdTempTextMap = WaveBatchRenderingHelper.evalTplForAllObject(scope, smsText, waveId, senderId);
    	
    	for(sObject obj : scope)
    	{
    		smagicinteract__Scheduled_SMS__c scheduleSMSObject = new smagicinteract__Scheduled_SMS__c();
    		Wave_Selection__c waveSelectionObj = (Wave_Selection__c) obj;
    		
    		if(waveSelectionObj.YP_Mobile__c != null)
    		{
    			scheduleSMSObject.smagicinteract__MobilePhone__c = waveSelectionObj.YP_Mobile__c;
	    		scheduleSMSObject.smagicinteract__smsText__c = WaveSelectionIdTempTextMap.get(waveSelectionObj.Id);
	    		scheduleSMSObject.smagicinteract__Scheduled_Date__c = scheduleDate;
	    		scheduleSMSObject.smagicinteract__jobId__c = waveSelectionObj.Id;
	    		scheduleSMSObject.smagicinteract__status__c = 'Schedule';
	    		scheduleSMSObject.Contact__c = waveSelectionObj.YPContactID__c;
	    		scheduleSMSObject.smagicinteract__Object_Type__c = 'Contact';
	    		scheduleSMSObject.smagicinteract__ObjectId__c = waveSelectionObj.YPContactID__c; 
	    		scheduleSMSObject.SenderId__c = senderId; 
	    		scheduleSMSList.add(scheduleSMSObject);
    		}
    	}
    	system.debug(system.logginglevel.INFO, 'scheduleSMSList : '+scheduleSMSList);
    	insert scheduleSMSList;
    }
    
    global void finish(Database.BatchableContext BC){
		// send batch execution email;		
   }
   
}