objects/Summary_Metric__c.object
<CustomObject>
    <fields>
        <fullName>Asian__c</fullName>
        <label>Asian</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Black__c</fullName>
        <label>Black</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Buddhist__c</fullName>
        <label>Buddhist</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Chinese__c</fullName>
        <label>Chinese</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Christian__c</fullName>
        <label>Christian</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Disability__c</fullName>
        <label>Disability</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Female__c</fullName>
        <label>Female</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FreeSchoolMeals__c</fullName>
        <label>FreeSchoolMeals</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Hindu__c</fullName>
        <label>Hindu</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Independent__c</fullName>
        <label>Independent</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Intraining__c</fullName>
        <label>Intraining</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Jewish__c</fullName>
        <label>Jewish</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>LookedAfterChild__c</fullName>
        <label>LookedAfterChild</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Male__c</fullName>
        <label>Male</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Mixed__c</fullName>
        <label>Mixed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Muslim__c</fullName>
        <label>Muslim</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>None__c</fullName>
        <label>None</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>OtherSchoolType__c</fullName>
        <label>OtherSchoolType</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Other_Ethnicity__c</fullName>
        <label>Other Ethnicity</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PRU__c</fullName>
        <label>PRU</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SEN__c</fullName>
        <label>SEN</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sikh__c</fullName>
        <label>Sikh</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Studyingschool_collegene__c</fullName>
        <label>Studyingschool_collegene</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SupportLevel__c</fullName>
        <label>SupportLevel</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total__c</fullName>
        <label>Total</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unemployed__c</fullName>
        <label>Unemployed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unknown__c</fullName>
        <label>Unknown</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>VolunteeringInvolvement__c</fullName>
        <label>VolunteeringInvolvement</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>White__c</fullName>
        <label>White</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Working__c</fullName>
        <label>Working</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Summary Metric</label>
    <nameField>
        <displayFormat>Summary-{0000}</displayFormat>
        <label>Summary Metric Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Summary Metrics</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/SummaryMetricController.cls
public with sharing class SummaryMetricController {
	
	public List<Summary_Metric__c> getSummaryMetircList(){
			List<Summary_Metric__c> ListSummMetric = [SELECT s.Working__c, s.White__c, s.VolunteeringInvolvement__c, s.Unknown__c, 
										s.Unemployed__c, s.Total__c, s.SupportLevel__c, s.Studyingschool_collegene__c, 
										s.State__c, s.Sikh__c, s.SEN__c, s.PRU__c, s.Other_Ethnicity__c, 
										s.OtherSchoolType__c, s.None__c, s.Name, s.Muslim__c, s.Mixed__c, s.Male__c, 
										s.LookedAfterChild__c, s.Jewish__c, s.Intraining__c, s.Independent__c, s.Hindu__c, 
										s.FreeSchoolMeals__c, s.Female__c, s.Disability__c, s.Christian__c, s.Chinese__c, 
										s.Buddhist__c, s.Black__c, s.Asian__c FROM Summary_Metric__c s where CreatedById=:UserInfo.getUserId()];
			 return ListSummMetric;
	}

	public List<String> getMetrics(){
	List<String> ListMetric = new List<String>();
	 
	 ListMetric.add('Total of TCS involvement');
	 ListMetric.add('Total# involved YP');
	 ListMetric.add('Total# active YP');
	 ListMetric.add('#YP not involved');
	 ListMetric.add('#YP with a Personal Coach');
	 ListMetric.add('#YP who have attended a Challenge Day');
	 ListMetric.add('#YP who have attended a Local Event');
	 ListMetric.add('#YP who have attended a Skills Workshop');
	 ListMetric.add('Total hours logged');
	 ListMetric.add('#YP  within 5 hrs of CwD');
	 ListMetric.add('#YP have Challenge with Distinction');
	 ListMetric.add('Total non-Challengers');
	 ListMetric.add('#active Youth Board Members');
	 ListMetric.add('#YP who are active Action Team members');
	 ListMetric.add('#Associate Mentors');
	 ListMetric.add('#Marketing Ambassadors');
	 ListMetric.add('#Staffing Ambassadors');
	 ListMetric.add('#Development Ambassadors');
	 
	 return ListMetric;
	}
}