objects/Survey__c.object
<CustomObject>
    <description>Hold Survey data</description>
    <fields>
        <fullName>Contact_lookup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Surveys</relationshipLabel>
        <relationshipName>Surveys</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_s_TCN_Id_code__c</fullName>
        <label>Contact&apos;s TCN Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Wave_Summary__c</fullName>
        <label>Wave Summary</label>
        <referenceTo>Wave_Summary__c</referenceTo>
        <relationshipLabel>Surveys</relationshipLabel>
        <relationshipName>Surveys</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Survey</label>
    <nameField>
        <displayFormat>S-{YYYY}{MM}{00000}</displayFormat>
        <label>Survey Reference No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Surveys</pluralLabel>
    <recordTypes>
        <fullName>YP</fullName>
        <active>true</active>
        <label>YP</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Wave_Summary__c.object
<CustomObject>
    <description>Summarised Survey results for field.</description>
    <fields>
        <fullName>WaveSum_TCN_Id__c</fullName>
        <description>Unique external id of the Wave Summary record</description>
        <externalId>true</externalId>
        <inlineHelpText>Unique external id of the Wave Summary record</inlineHelpText>
        <label>WaveSum TCN Id</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Survey Summary</label>
    <nameField>
        <label>Survey Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Survey Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Test_Survey_Contact_Relation.cls
@isTest
private class Test_Survey_Contact_Relation {

    static testMethod void myUnitTest() {
        RecordType ConRecYP = [SELECT Id FROM RecordType WHERE (Name LIKE 'YP%' AND Name !='YP') AND SobjectType = 'Contact' LIMIT 1];
        RecordType AccRecFam= [SELECT Id FROM RecordType WHERE Name LIKE 'Family%' AND SobjectType = 'Account' LIMIT 1];
                 
        Account FamilyAcc= new Account(
                                    Name='Test Name2' ,
                                    BillingState='Test State2', 
                                    BillingCountry='Test Country', 
                                    BillingCity='Test City', 
                                    BillingStreet='Test Street', 
                                    BillingPostalCode='Test PostalCode'                                      
                                    );      
        FamilyAcc.RecordTypeId= AccRecFam.Id;                          
        insert FamilyAcc;
        
        List<Contact> NewContacts=new List<Contact>();
        for(integer i=0; i<50; i++){
            Contact TestCont = new  Contact(FirstName='TestName',LastName='TestName', HomePhone='00000'+i, Email='test@gmail.com'  );
            TestCont.RecordTypeId=ConRecYP.Id;
            TestCont.AccountId=FamilyAcc.Id;
            NewContacts.add(TestCont);
        }              
        database.insert(NewContacts);

        Wave_Summary__c WS=new Wave_Summary__c(Name='Test',WaveSum_TCN_Id__c='TestId112233');
        database.insert(WS);
        
        List<Survey__c> Surveys=new List<Survey__c>(); 
        for(Contact c:[Select Id,Name, TCNContactId__c from Contact Where Name like '%Test%']){
            Survey__c S=new Survey__c(Wave_Summary__c=WS.id,Contact_s_TCN_Id_code__c=c.TCNContactId__c);
            Surveys.add(S);
        }
        database.insert(Surveys);
        Surveys[5].Contact_s_TCN_Id_code__c=NewContacts[10].TCNContactId__c;
        database.update(Surveys[5]);
        
      //  system.debug([Select Name,Contact_lookup__c ,Contact_s_TCN_Id_code__c from  Survey__c]);
        
        
    }
}