objects/Transport_order__c.object
<CustomObject>
    <description>This object tracks the transport needed to carry YPs from one booking to another</description>
    <fields>
        <fullName>Date_Optimised__c</fullName>
        <label>Date Optimised</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <formula>DATEVALUE( Earliest_departure_time__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Date of travel</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>De_optimise__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Reset order</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Method_of_Transport__c</fullName>
        <label>Method of Transport</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Walking</fullName>
                </value>
                <value>
                    <fullName>Public transport</fullName>
                </value>
                <value>
                    <fullName>Private Transport</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PM_Approval__c</fullName>
        <label>PM Approval</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Resubmit_rejected_journey__c</fullName>
        <label>Date Journey Submitted</label>
        <type>Date</type>
    </fields>
    <label>Transport order</label>
    <nameField>
        <displayFormat>{0000}{DD}{MM}</displayFormat>
        <label>Transport Order ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transport orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Vehicle__c.object
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <label>vehicle Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Waypoint__c.object
<CustomObject>
    <fields>
        <fullName>Arrival_Time__c</fullName>
        <label>Arrival TimeOld</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <formula>DATEVALUE(  Transport__r.Earliest_departure_time__c  )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Departure_time__c</fullName>
        <label>Departure timeOld</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Transport__c</fullName>
        <label>Transport</label>
        <referenceTo>Transport_order__c</referenceTo>
        <relationshipLabel>Waypoints</relationshipLabel>
        <relationshipName>Transport_Stops</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>transport_method__c</fullName>
        <formula>TEXT( Transport__r.Method_of_Transport__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>transport method</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>vehicle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipName>Transport_Stops</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Waypoint</label>
    <nameField>
        <label>Points Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Waypoints</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TransportOrdersTriggerHandler.cls
public with sharing class TransportOrdersTriggerHandler{
  
   List<Waypoint__c> waypointList;
   List<Vehicle__c> vehiclesList;
   List<Transport_order__c>tosList;
   public TransportOrdersTriggerHandler(){
       tosList=new List<Transport_order__c>();
       waypointList=new List<Waypoint__c>();
       vehiclesList=new List<Vehicle__c>();
   }
      
   public void onAfterUpdateTransportOrders(List<Transport_order__c> toList){
   
       set<id> toId=new set<id>();
       for(Transport_order__c to:toList){
       toId.add(to.Id);
       }
      
       waypointList=[Select id,Transport__c,vehicle__c,Arrival_Time__c,Date__c,Departure_time__c,transport_method__c From Waypoint__c where Transport__c=:toId];
       
       set<id> vehicleId=new set<id>();
       for(Waypoint__c wa:waypointList){
       vehicleId.add(wa.vehicle__c);
       }
       vehiclesList=[Select id From Vehicle__c where id=:vehicleId];
       
       for(Transport_order__c tos:toList){
           for(integer i=0; i<waypointList.size();i++){
              
               if(tos.De_optimise__c == TRUE){
                waypointList[i].vehicle__c = null;
                tos.Date_Optimised__c= null;
                tos.PM_Approval__c= null;

                // Start By Amol
                tos.Method_of_Transport__c = null;
                tos.Resubmit_rejected_journey__c = null;
                // End By Amol
               
               }
               
           }
           tos.De_optimise__c = FALSE;
               tosList.add(tos);
       }
       update waypointList;
   }

}