objects/Transport_order__c.object
<CustomObject>
    <description>This object tracks the transport needed to carry YPs from one booking to another</description>
    <fields>
        <fullName>De_optimise__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Reset order</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Method_of_Transport__c</fullName>
        <label>Method of Transport</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Walking</fullName>
                </value>
                <value>
                    <fullName>Public transport</fullName>
                </value>
                <value>
                    <fullName>Private Transport</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>PM_Approval__c</fullName>
        <label>PM Approval</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Resubmit_rejected_journey__c</fullName>
        <label>Date Journey Submitted</label>
        <type>Date</type>
    </fields>
    <label>Transport order</label>
    <nameField>
        <displayFormat>{0000}{DD}{MM}</displayFormat>
        <label>Transport Order ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transport orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Waypoint__c.object
<CustomObject>
    <fields>
        <fullName>Transport__c</fullName>
        <label>Transport</label>
        <referenceTo>Transport_order__c</referenceTo>
        <relationshipLabel>Waypoints</relationshipLabel>
        <relationshipName>Transport_Stops</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Waypoint</label>
    <nameField>
        <label>Points Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Waypoints</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/Test_TransportOrdersTriggerHandler.cls
/*Modified by :- Dreamwares [Amol Kulthe]
*/
@isTest
private class Test_TransportOrdersTriggerHandler{

   static testMethod void myUnitTestInsert(){
   
   List<Transport_order__c> toList=new List<Transport_order__c>();
   
   Transport_order__c to=new Transport_order__c(
   De_optimise__c = FALSE);
    insert to;
   
   List<Waypoint__c> wayList=new List<Waypoint__c>();
   Waypoint__c way=new Waypoint__c(
   Name='test',
   Transport__c=to.Id
   );
   insert way;     
   to.De_optimise__c = TRUE;
   update to; 

   // Start by Amol K
   System.assertEquals(to.Method_of_Transport__c,null);
   System.assertEquals(to.Resubmit_rejected_journey__c,null);
   System.assertEquals(to.PM_Approval__c,null);   
   // End by  Amol K
   }
}